"""Module 3: what your organisation must do. Original teaching text; Sunfield Bakery is fictional."""

from lesson_builder import assessment

ILLUSTRATION = {"type": "callout", "tone": "note", "text": "These Sunfield examples are **illustrations**. A real assessment depends on all the facts."}

LESSONS = {
    "O01": {
        "summary": "Scale your measures to the risk, and keep a record of processing activities, including when small businesses must too.",
        "sources": [("GDPR", "Articles 24, 30")],
        "screens": [
            [
                "Article 24(1) turns accountability into action. Taking into account the nature, scope, context and purposes of processing, and the **risks** of varying likelihood and severity, the controller must implement **appropriate technical and organisational measures**.",
                "Those measures must ensure, and enable it to demonstrate, that processing complies with the GDPR. They must be reviewed and updated where necessary.",
            ],
            [
                "Where proportionate, the measures include **data protection policies** (Article 24(2)).",
                "Following an approved code of conduct or certification can be used as one element to demonstrate compliance (Article 24(3)).",
                "The key word is **appropriate**: a hospital and a bakery do not need the same measures.",
            ],
            [
                "The main tool for demonstrating compliance is the **record of processing activities** (Article 30(1)). The controller's record contains:",
                {"type": "list", "items": [
                    "(a) the name and contact details of the controller, and of any joint controller, representative or data protection officer;",
                    "(b) the purposes of the processing;",
                    "(c) the categories of data subjects and of personal data;",
                    "(d) the categories of recipients, including any outside the EU;",
                    "(e) transfers to countries outside the EU, where applicable;",
                    "(f) where possible, the time limits for erasure;",
                    "(g) where possible, a general description of the security measures.",
                ]},
            ],
            [
                "Processors keep their own record of the processing they do for each controller (Article 30(2)).",
                "Records must be in writing, which includes electronic form (Article 30(3)). They must be made available to the **supervisory authority on request** (Article 30(4)).",
            ],
            [
                "**The under-250 exemption** (Article 30(5)): an organisation with **fewer than 250 employees** does not have to keep the record, **unless** its processing:",
                {"type": "list", "items": [
                    "is likely to result in a risk to people's rights and freedoms; or",
                    "is **not occasional**; or",
                    "includes special-category data or criminal-offence data.",
                ]},
                "Because any one of these defeats the exemption, it is narrower than it first looks.",
            ],
            [
                "Sunfield has about 40 staff, but it processes pre-orders and payroll every week, which is not occasional. It also handles sick notes, which are health data. So the exemption does not apply, and Sunfield keeps a record.",
                "A sample entry: *Pre-orders. Purpose: fulfil orders. Data subjects: customers. Data: name, phone, order. Recipients: app hosting provider. Erasure: a set period after the last order. Security: access by role, encrypted backups.*",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1, 2], "How should a controller choose its data protection measures under Article 24?", "Under Article 24, how are a controller's measures matched to its situation?",
                       ("By nature, scope, context, purposes and risk", "Article 24(1)."),
                       ("Identically for every business, whatever its size", "Article 24 requires appropriate measures, so they vary."),
                       ("Only once a regulator demands them", "Article 24 applies from the start.")),
            assessment([1], [3], "Which of these belongs in a controller's record of processing activities?", "What does Article 30(1) require the record to contain?",
                       ("The purposes of the processing", "Article 30(1)(b)."),
                       ("The name of every individual customer", "The record lists categories, not each person."),
                       ("The administrator passwords", "Passwords are not record content. They must be kept secret.")),
            assessment([1], [5, 6], "Sunfield has 40 staff, processes orders every week and handles staff sick notes. Can it skip the record?", "Does the under-250 exemption help a small business that processes regularly and handles health data?",
                       ("No, the processing is not occasional and includes health data", "Article 30(5): either condition defeats the exemption."),
                       ("Yes, fewer than 250 staff is always exempt", "The exemption has three exceptions."),
                       ("Yes, if it has never had a breach", "A clean history is not a condition in Article 30(5).")),
            assessment([1], [4], "Who can require Sunfield to show its record of processing?", "To whom must the Article 30 record be made available on request?",
                       ("The supervisory authority", "Article 30(4)."),
                       ("Any customer who asks", "Customers have access rights, but Article 30(4) concerns the authority."),
                       ("No one; the record is purely internal", "Article 30(4) requires availability to the authority.")),
        ],
    },
    "O02": {
        "summary": "Build the principles into systems from the start, and choose privacy-friendly default settings.",
        "sources": [("GDPR", "Article 25")],
        "screens": [
            [
                "**Data protection by design** (Article 25(1)): the controller must implement appropriate technical and organisational measures that are designed to implement the data protection principles effectively, and must integrate the necessary safeguards.",
                "Article 25(1) names **pseudonymisation** as an example measure and **data minimisation** as an example principle.",
            ],
            [
                "This applies **both** at the time the means of processing are decided **and** at the time of the processing itself (Article 25(1)).",
                "It is about planning before you build or buy, not fixing things afterwards.",
                "What is appropriate depends on the state of the art, the cost of implementation, the nature, scope, context and purposes of processing, and the risks.",
            ],
            [
                "**Data protection by default** (Article 25(2)): by default, only the personal data **necessary for each specific purpose** may be processed. This covers four dimensions:",
                {"type": "list", "items": ["the amount of data collected;", "the extent of processing;", "the period of storage;", "who can access it."]},
            ],
            [
                "In particular, by default personal data must not be made accessible to an **indefinite number of people** without the individual's own intervention (Article 25(2)).",
                "An approved certification can be used as one element to demonstrate compliance with Article 25 (Article 25(3)).",
            ],
            [
                "Sunfield's app redesign:",
                {"type": "list", "items": [
                    "The date-of-birth field is removed. That is design, implementing minimisation.",
                    "Optional fields start empty, and marketing is unticked. These are defaults.",
                    "Order data is deleted automatically after a set period, which handles storage by default.",
                    "A new \"top customers\" leaderboard is **off** unless a customer switches it on, which limits accessibility by default.",
                    "Shop staff see only the orders for their own shop, which limits access.",
                ]},
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [2], "When must a controller think about data protection by design?", "At which stages does Article 25(1) apply?",
                       ("When deciding the means, and during processing", "Article 25(1) names both times."),
                       ("Only after the system is launched", "Design measures start when the means are decided."),
                       ("Only after a data breach", "Article 25 is preventive.")),
            assessment([0], [1], "Which measure does Article 25(1) name as an example?", "Which example measure appears in the text of Article 25(1)?",
                       ("Pseudonymisation", "Named in Article 25(1)."),
                       ("A larger marketing budget", "Not a data protection measure."),
                       ("Keeping data for longer", "That works against the principles.")),
            assessment([1], [4, 5], "Sunfield adds a public leaderboard of top customers by name. What must the default be?", "How should a feature that would publish customers' names be set by default?",
                       ("Off, until a customer chooses to join", "Article 25(2): not accessible to an indefinite number without the person's intervention."),
                       ("On, with an option to opt out", "Opt-out exposes people without their intervention."),
                       ("On, as long as the notice mentions it", "A notice does not replace a privacy-friendly default.")),
            assessment([1], [3], "Which dimensions does the by-default rule in Article 25(2) cover?", "Article 25(2) limits defaults in which respects?",
                       ("Amount, extent of processing, storage period and accessibility", "Article 25(2) lists all four."),
                       ("Only the amount of data collected", "Article 25(2) covers four dimensions."),
                       ("Only the security of the data", "Security is Article 32. Article 25(2) concerns necessity.")),
        ],
    },
    "O03": {
        "summary": "Choose processors with guarantees, put the mandatory terms in writing, and control sub-processors.",
        "sources": [("GDPR", "Article 28")],
        "screens": [
            [
                "A controller may use only processors that provide **sufficient guarantees** to implement appropriate measures, so that the processing meets the GDPR and protects people's rights (Article 28(1)).",
                "Choosing a provider is therefore a data protection decision, not just a purchasing decision.",
            ],
            [
                "Processing by a processor must be governed by a **contract** or other binding legal act (Article 28(3)). It must set out the subject matter and duration, the nature and purpose, the type of personal data, the categories of data subjects, and the controller's obligations and rights.",
                "It must be **in writing**, which includes electronic form (Article 28(9)).",
            ],
            [
                "The contract must require the processor in particular to (Article 28(3)(a)-(h)):",
                {"type": "list", "items": [
                    "process only on the controller's **documented instructions**, including on transfers outside the EU;",
                    "ensure its staff are bound by **confidentiality**;",
                    "take the **security** measures required by Article 32;",
                    "follow the rules on engaging **sub-processors**;",
                    "**assist** the controller with requests from people exercising their rights, and with security, breaches and impact assessments;",
                    "**delete or return** all data at the end, at the controller's choice;",
                    "provide information and allow **audits**.",
                ]},
                "The processor must immediately tell the controller if, in its opinion, an instruction infringes data protection law.",
            ],
            [
                "**Sub-processors** (Article 28(2)): a processor may not engage another processor without the controller's prior **specific or general written authorisation**.",
                "Under a general authorisation, the processor must inform the controller of intended changes, giving it the opportunity to **object**.",
            ],
            [
                "The same data protection obligations must be passed down to the sub-processor by contract. If the sub-processor fails, the **initial processor remains fully liable** to the controller (Article 28(4)).",
            ],
            [
                "The contract may be based on **standard contractual clauses** adopted by the Commission or by a supervisory authority (Article 28(6)-(8)).",
                "Sunfield checks the terms of its newsletter service, app host and payroll firm. Each must contain the Article 28(3) items. Many providers publish such terms, and Sunfield keeps a copy of each.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [3], "Which term must a controller-processor contract contain?", "Which clause does Article 28(3) make mandatory?",
                       ("Process only on the controller's documented instructions", "Article 28(3)(a)."),
                       ("The processor may use the data for its own marketing", "That would make it a controller for that use."),
                       ("The processor decides how long data is kept", "Purposes and essential means belong to the controller.")),
            assessment([0], [2], "What form must the processor contract take?", "In what form does Article 28(9) require the processor contract?",
                       ("In writing, which may be electronic", "Article 28(9)."),
                       ("An oral agreement is enough", "Article 28(9) requires writing."),
                       ("It must be notarised", "Article 28 has no notary requirement.")),
            assessment([1], [4], "Under a general authorisation, Sunfield's newsletter service wants to add a new sub-processor. What must happen?", "Sunfield gave its newsletter service a general written authorisation. What must happen when the service changes sub-processors?",
                       ("It informs Sunfield, which may object", "Article 28(2)."),
                       ("It may add sub-processors freely", "Changes must be notified so the controller can object."),
                       ("A supervisory authority must approve it", "Article 28(2) involves the controller, not the authority.")),
            assessment([1], [5], "A sub-processor fails its data protection duties. Who is liable to Sunfield for that failure?", "A sub-processor engaged by Sunfield's processor fails its duties. Under Article 28(4), who answers to Sunfield?",
                       ("The initial processor, fully", "Article 28(4)."),
                       ("No one, because Sunfield never signed with it", "The initial processor remains liable."),
                       ("Only the sub-processor", "Article 28(4) keeps the initial processor fully liable.")),
        ],
    },
    "O04": {
        "summary": "Choose security measures appropriate to the risk, and test that they work.",
        "sources": [("GDPR", "Article 32")],
        "screens": [
            [
                "Article 32(1): taking into account the state of the art, the costs, the nature, scope, context and purposes of processing, and the risks, the **controller and the processor** must implement measures to ensure a level of security **appropriate to the risk**.",
                "So security is neither \"maximum regardless of cost\" nor \"cheapest possible\". It is matched to the risk.",
            ],
            [
                "Article 32(1) lists measures to use as appropriate:",
                {"type": "list", "items": [
                    "(a) **pseudonymisation and encryption**;",
                    "(b) ensuring ongoing **confidentiality, integrity, availability and resilience** of systems;",
                    "(c) the ability to **restore** availability and access in a timely manner after an incident;",
                    "(d) a process for **regularly testing, assessing and evaluating** the measures.",
                ]},
            ],
            [
                "When assessing the risk, consider in particular accidental or unlawful **destruction, loss, alteration, unauthorised disclosure of, or access to** personal data (Article 32(2)).",
            ],
            [
                "Organisations must take steps so that anyone acting under their authority with access to personal data processes it **only on instructions** (Article 32(4)).",
                "Following an approved code of conduct or certification can help demonstrate compliance (Article 32(3)).",
            ],
            [
                "Sunfield's measures, scaled to its risks:",
                {"type": "list", "items": [
                    "encrypted laptops and phones;",
                    "access to staff files only for the manager and payroll;",
                    "daily backups of the order system, with a restore that is actually tested;",
                    "written staff instructions;",
                    "a yearly review of whether the measures still work.",
                ]},
                "Buying a firewall once and never checking it does not meet point (d).",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "What level of security does Article 32 require?", "How does Article 32 set the required security level?",
                       ("A level appropriate to the risk", "Article 32(1)."),
                       ("The maximum possible, whatever the cost", "Cost and state of the art are factors."),
                       ("Whatever is cheapest", "The level must be appropriate to the risk.")),
            assessment([0], [2], "Which of these is listed in Article 32(1)?", "Which capability does Article 32(1) name?",
                       ("Restoring access to data in a timely manner after an incident", "Article 32(1)(c)."),
                       ("Publishing annual turnover", "Not a security measure."),
                       ("Appointing a data protection officer", "That is Article 37, not an Article 32 measure.")),
            assessment([0], [2, 5], "Sunfield installed security software three years ago and has never checked it. Which point is it missing?", "What does Article 32(1)(d) add beyond installing measures?",
                       ("Regularly testing and evaluating the measures", "Article 32(1)(d)."),
                       ("Nothing; installing once is enough", "Point (d) requires regular testing."),
                       ("Testing only after a breach", "Point (d) says regularly, not after the event.")),
            assessment([0], [1], "Does Article 32 apply to Sunfield's payroll processor?", "Must processors, as well as controllers, implement Article 32 security measures?",
                       ("Yes, controllers and processors alike", "Article 32(1) names both."),
                       ("No, only the controller", "Processors are named too."),
                       ("No, only if the contract says so", "Article 32 applies directly.")),
        ],
    },
    "O05": {
        "summary": "Recognise a personal data breach, notify the authority within 72 hours when required, and tell affected people when the risk is high.",
        "sources": [("GDPR", "Articles 4(12), 33, 34"), ("GDPR-REC", "recital 85")],
        "screens": [
            [
                "A **personal data breach** is a breach of security leading to the accidental or unlawful **destruction, loss, alteration, unauthorised disclosure of, or access to** personal data (Article 4(12)).",
                "It is not only hacking. An email sent to the wrong person, a lost laptop and ransomware that destroys files are all breaches.",
            ],
            [
                "**Notify the supervisory authority** without undue delay and, where feasible, **within 72 hours of becoming aware** of the breach, **unless** it is unlikely to result in a risk to people's rights and freedoms (Article 33(1)).",
                "If notification comes later than 72 hours, give the reasons for the delay.",
            ],
            [
                "A **processor** must notify the controller without undue delay after becoming aware of a breach (Article 33(2)).",
                "The notification must at least describe the nature of the breach and the approximate numbers of people and records, give a contact point, and describe the likely consequences and the measures taken (Article 33(3)). If not everything is known, information may be given **in phases** (Article 33(4)).",
            ],
            [
                "**Document every breach**, including those you do not notify: the facts, the effects and the remedial action (Article 33(5)).",
                "This record lets the authority check your decisions.",
            ],
            [
                "**Tell the affected people** without undue delay when the breach is **likely to result in a high risk** to their rights and freedoms (Article 34(1)).",
                "Use clear, plain language, and include the contact point, the likely consequences and the measures taken (Article 34(2)).",
                "Recital 85 lists possible harms, such as identity theft, fraud, financial loss, discrimination and damage to reputation.",
            ],
            [
                "You do not need to tell people if (Article 34(3)):",
                {"type": "list", "items": [
                    "(a) protective measures, such as **encryption**, were applied to the affected data and make it unintelligible to anyone unauthorised;",
                    "(b) later measures mean the high risk is no longer likely to materialise; or",
                    "(c) it would involve disproportionate effort. A public communication is then used instead.",
                ]},
                "The authority can still require you to tell people (Article 34(4)).",
            ],
            [
                "Sunfield's cases:",
                {"type": "list", "items": [
                    "An unencrypted laptop holding staff sick notes is stolen. Health data is exposed, so Sunfield notifies the authority within 72 hours and tells the staff.",
                    "A strongly encrypted laptop is stolen, and the key is safe. The encryption exception in Article 34(3)(a) is likely to apply. Sunfield still documents the breach and assesses whether to notify the authority.",
                ]},
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "Which of these is a personal data breach?", "Which event fits the Article 4(12) definition?",
                       ("A staff member emails the customer list to the wrong supplier", "Unauthorised disclosure (Article 4(12))."),
                       ("A customer updates her email address", "A normal, authorised change."),
                       ("Sunfield deletes old data under its policy", "Authorised erasure is not a security breach.")),
            assessment([1], [2], "When must a notifiable breach be reported to the supervisory authority?", "What is the Article 33(1) time limit?",
                       ("Without undue delay and, where feasible, within 72 hours of becoming aware", "Article 33(1)."),
                       ("Within 72 hours of the breach happening", "The clock runs from awareness."),
                       ("Within one month", "One month is the rights-request deadline.")),
            assessment([1], [4], "Sunfield decides a small breach is unlikely to result in any risk and does not notify. Must it still record it?", "Are breaches that are not notified still documented?",
                       ("Yes, all breaches must be documented", "Article 33(5)."),
                       ("No, only notified breaches are recorded", "Article 33(5) covers any breach."),
                       ("No, but it must notify anyway", "If risk is unlikely, notification is not required. Documentation is.")),
            assessment([2], [6, 7], "A stolen laptop's data was strongly encrypted, and the key is safe. Must the staff be told?", "Must affected people always be told about a breach of strongly encrypted data?",
                       ("Not necessarily: Article 34(3)(a) is an exception", "Encryption that makes the data unintelligible is a listed exception."),
                       ("Yes, always, whatever the protection", "Article 34(3) lists exceptions."),
                       ("Only if the authority fines Sunfield", "Fines are not the trigger. High risk is.")),
            assessment([2], [5], "When must affected people be told about a breach?", "When does a breach trigger the Article 34 duty to inform data subjects?",
                       ("When it is likely to result in a high risk to them", "Article 34(1)."),
                       ("After every breach, however small", "The trigger is a likely high risk."),
                       ("Never; only the authority is told", "Article 34 requires telling people in high-risk cases.")),
        ],
    },
    "O06": {
        "summary": "Decide when a data protection impact assessment is required, and what it must contain.",
        "sources": [("GDPR", "Article 35")],
        "screens": [
            [
                "Where processing, especially using new technologies, is **likely to result in a high risk** to people's rights and freedoms, the controller must carry out a **data protection impact assessment** (DPIA) **before** the processing starts (Article 35(1)).",
                "One assessment may cover a set of similar operations with similar high risks.",
            ],
            [
                "Article 35(3) lists cases where a DPIA is required in particular:",
                {"type": "list", "items": [
                    "(a) systematic and extensive **evaluation** of personal aspects based on automated processing, including profiling, with decisions that have legal or similarly significant effects;",
                    "(b) **large-scale** processing of special-category data or criminal-offence data;",
                    "(c) systematic **monitoring of a publicly accessible area** on a large scale.",
                ]},
            ],
            [
                "Each supervisory authority publishes a **list** of processing types that require a DPIA (Article 35(4)). It may also publish a list of types that do not (Article 35(5)).",
                "Check your authority's list. It is the practical way to find cases beyond Article 35(3).",
            ],
            [
                "A DPIA must contain at least (Article 35(7)):",
                {"type": "list", "items": [
                    "(a) a systematic description of the processing and its purposes;",
                    "(b) an assessment of **necessity and proportionality**;",
                    "(c) an assessment of the **risks** to people's rights and freedoms;",
                    "(d) the **measures** to address those risks.",
                ]},
            ],
            [
                "Seek the advice of the data protection officer, if there is one (Article 35(2)). Where appropriate, seek the views of the people affected or their representatives (Article 35(9)).",
                "Review the DPIA at least when the risk changes (Article 35(11)).",
            ],
            [
                "Sunfield plans software that scores job applicants and automatically rejects low scores. That is systematic, automated evaluation with significant effects, matching Article 35(3)(a), so a DPIA is needed first.",
                "Whether its shop cameras need one depends on scale and on the authority's list. Sunfield checks that list rather than guessing.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "When must a DPIA be carried out?", "At what point does Article 35(1) require an impact assessment?",
                       ("Before processing that is likely to be high risk", "Article 35(1)."),
                       ("After a breach occurs", "A DPIA is done prior to processing."),
                       ("Every year for all processing", "Article 35 targets likely high-risk processing.")),
            assessment([0], [2, 6], "Which case does Article 35(3) list as requiring a DPIA?", "Which processing is named in Article 35(3)?",
                       ("Large-scale processing of special-category data", "Article 35(3)(b)."),
                       ("Sending a monthly newsletter", "Not a listed case, and not normally high risk."),
                       ("Keeping a customer contact list", "Not a listed case.")),
            assessment([0], [4], "Which element must every DPIA include?", "What does Article 35(7) require a DPIA to contain?",
                       ("An assessment of necessity and proportionality", "Article 35(7)(b)."),
                       ("The company's marketing plan", "Not required by Article 35(7)."),
                       ("Prior approval from the regulator", "Article 35 does not require approval.")),
            assessment([0], [3], "Where can Sunfield find further processing types that need a DPIA?", "Where should Sunfield look for DPIA cases beyond those named in Article 35(3)?",
                       ("Its supervisory authority's published list", "Article 35(4)."),
                       ("Nowhere; Article 35(3) is the complete list", "Article 35(3) says \"in particular\". It is not exhaustive."),
                       ("The Commission's annual report", "Article 35(4) gives the lists to supervisory authorities.")),
        ],
    },
    "O07": {
        "summary": "Decide whether a data protection officer is mandatory, and protect the role's independence.",
        "sources": [("GDPR", "Articles 37, 38, 39")],
        "screens": [
            [
                "A **data protection officer** (DPO) must be designated where (Article 37(1)):",
                {"type": "list", "items": [
                    "(a) processing is carried out by a **public authority** or body, except courts acting in their judicial capacity;",
                    "(b) the **core activities** consist of processing that requires **regular and systematic monitoring** of people on a **large scale**; or",
                    "(c) the **core activities** consist of **large-scale** processing of special-category or criminal-offence data.",
                ]},
            ],
            [
                "In other cases, appointing a DPO is voluntary, **unless EU or national law requires it** (Article 37(4)).",
                "Some countries add their own requirements. This course does not cover national law, so check yours.",
            ],
            [
                "The DPO must have **expert knowledge** of data protection law and practice (Article 37(5)). The DPO may be a staff member or work under a service contract (Article 37(6)). A group of companies may share one DPO if the DPO is easily accessible from each establishment (Article 37(2)).",
                "The DPO's contact details must be published and given to the supervisory authority (Article 37(7)).",
            ],
            [
                "**Independence** (Article 38):",
                {"type": "list", "items": [
                    "involved properly and in good time in all data protection issues;",
                    "given the necessary resources;",
                    "receives **no instructions** about how to perform their tasks;",
                    "**not dismissed or penalised** for performing them;",
                    "reports directly to the **highest management level**;",
                    "may hold other roles only if there is no conflict of interests.",
                ]},
            ],
            [
                "**Tasks** (Article 39(1)): to inform and advise the organisation and its staff; to **monitor compliance**, including training and audits; to advise on data protection impact assessments (DPIAs); to **cooperate with the supervisory authority** and act as its contact point.",
                "People may contact the DPO about their data and rights (Article 38(4)).",
            ],
            [
                "Sunfield's core activity is baking and selling bread. Its staff and customer processing supports that, but it is not obviously large-scale monitoring or large-scale sensitive-data processing.",
                "So a DPO may not be mandatory under Article 37(1). National law may still require one under Article 37(4), and Sunfield must check.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1, 2], "Which organisation must appoint a DPO under Article 37(1)?", "Which case makes a DPO mandatory under the GDPR text itself?",
                       ("A public authority", "Article 37(1)(a)."),
                       ("Any business with a website", "Not an Article 37(1) case."),
                       ("Any business with over ten employees", "The GDPR text sets no headcount. National law may add rules (Article 37(4)).")),
            assessment([0], [4], "To whom does the DPO report?", "Under Article 38(3), which level does the DPO report to?",
                       ("The highest management level", "Article 38(3)."),
                       ("The IT department", "Article 38(3) requires the highest management level."),
                       ("The supervisory authority", "The DPO cooperates with the authority but reports internally to top management.")),
            assessment([0], [4], "Sunfield's DPO reports a compliance problem. May Sunfield dismiss the DPO for that?", "Can a DPO be penalised for performing their tasks, such as reporting a problem?",
                       ("No, Article 38(3) forbids it", "A DPO must not be dismissed or penalised for performing their tasks."),
                       ("Yes, if the DPO is an employee", "The protection applies to staff DPOs too."),
                       ("Yes, if the report caused costs", "Costs do not lift the protection.")),
            assessment([0], [5], "Which is a task of the DPO?", "What does Article 39(1) assign to the DPO?",
                       ("Monitoring compliance with the GDPR", "Article 39(1)(b)."),
                       ("Deciding the purposes of processing", "That is the controller's role."),
                       ("Imposing fines on the organisation", "Fines are for supervisory authorities.")),
        ],
    },
    "O08": {
        "summary": "Apply the core duties together to Sunfield Bakery, and find what is missing.",
        "sources": [("GDPR", "Articles 5, 6, 13, 22, 28, 30, 33, 34, 35")],
        "screens": [
            [
                "This capstone applies the first four modules to one fictional business. Read each step and check it against what you have learned.",
                {"type": "callout", "tone": "note", "text": "**Sunfield Bakery is invented** for this course. The scenario is an illustration, not a template for a real review."},
            ],
            [
                "**Step 1, the record** (Article 30): Sunfield's processing is regular and includes health data, so it keeps a record. It lists six activities: pre-orders, loyalty, newsletter, cameras, payroll and recruitment, each with purposes, data categories, recipients, erasure limits and security.",
            ],
            [
                "**Step 2, legal bases and notices** (Articles 6 and 13):",
                {"type": "list", "items": [
                    "pre-orders: contract;",
                    "newsletter: consent;",
                    "cameras on the sales floor: legitimate interests, after the balancing test;",
                    "payroll: legal obligation, with the contract for the rest.",
                ]},
                "Each activity appears in a privacy notice given at collection.",
            ],
            [
                "**Step 3, processors** (Article 28): the app host, the newsletter service and the payroll firm each process data for Sunfield.",
                "The review finds that the newsletter service has no written processor terms on file. That is a gap: a contract with the Article 28(3) content is required.",
            ],
            [
                "**Step 4, a breach drill** (Articles 33 and 34): the payroll firm reports ransomware that has destroyed salary files. Sunfield becomes aware on **Friday at 18:00**.",
                "Unless the breach is unlikely to result in a risk, Sunfield notifies the authority where feasible by **Monday at 18:00**, which is 72 hours later. Details may follow in phases. Sunfield documents the breach either way and considers whether staff face a high risk.",
            ],
            [
                "**Step 5, a new project** (Articles 22 and 35): Sunfield wants software that automatically rejects low-scoring job applicants.",
                "That is a DPIA case under Article 35(3)(a), and a solely automated decision under Article 22. Sunfield must complete the DPIA first. It must also either keep meaningful human review, or meet an Article 22(2) exception with the Article 22(3) safeguards.",
            ],
        ],
        "questions": [
            assessment([0], [5], "Sunfield becomes aware of the payroll breach on Friday at 18:00. If notification is required, by when should the authority be notified, where feasible?", "Sunfield learned of a notifiable breach on Friday at 18:00. By when should it notify the authority, where feasible?",
                       ("Monday at 18:00", "72 hours after becoming aware (Article 33(1))."),
                       ("One month later", "One month is the rights-request deadline."),
                       ("Only once every detail is known", "Information may be given in phases (Article 33(4)).")),
            assessment([0], [4], "Sunfield's review finds no written processor terms on file for its newsletter service. What is missing?", "Which document does the review find absent for the newsletter service?",
                       ("A contract with the Article 28(3) content", "Required for every processor."),
                       ("Nothing, because the provider is well known", "Reputation does not replace a contract."),
                       ("A DPIA for the newsletter", "The gap found is the contract, not a DPIA.")),
            assessment([0], [2], "Which fact defeats Sunfield's under-250 exemption from keeping a record?", "Why must 40-staff Sunfield still keep an Article 30 record?",
                       ("Its processing is not occasional and includes health data", "Article 30(5)."),
                       ("It uses a mobile app", "Using an app is not an Article 30(5) condition."),
                       ("It has three shops", "The number of shops is not a condition.")),
            assessment([0], [6], "Before automatically rejecting applicants by software, what must Sunfield do?", "What does the review require before the automatic-rejection project starts?",
                       ("Carry out a DPIA, and meet Article 22", "Articles 35(3)(a) and 22."),
                       ("Nothing, because hiring is an internal matter", "Applicants are data subjects with rights."),
                       ("Only update the privacy notice", "A notice alone does not meet Articles 22 and 35.")),
        ],
    },
}
