"""Modul 3 (deutsche Ausgabe): was Ihr Unternehmen tun muss. Übersetzung von lesson_content_m3.py; die Bäckerei Sonnenfeld ist erfunden."""

from lesson_builder import assessment

ILLUSTRATION = {"type": "callout", "tone": "note", "text": "Diese Beispiele mit der Bäckerei Sonnenfeld sind **Veranschaulichungen**. Eine echte Beurteilung hängt von allen Umständen ab."}

LESSONS = {
    "O01": {
        "title": "Rechenschaftspflicht in der Praxis: das Verzeichnis von Verarbeitungstätigkeiten",
        "summary": "Die Maßnahmen am Risiko ausrichten, ein Verzeichnis von Verarbeitungstätigkeiten führen und erkennen, wann auch kleine Unternehmen eines führen müssen.",
        "prerequisites": {
            "P01": "Jeder Eintrag im Verzeichnis nennt die Zwecke der Verarbeitung.",
            "P03": "Artikel 24 setzt die Rechenschaftspflicht in Maßnahmen und Datenschutzvorkehrungen um.",
            "P08": "Die Ausnahme für weniger als 250 Beschäftigte gilt nicht für besondere Kategorien personenbezogener Daten.",
        },
        "sources": [("GDPR", "Art. 24, 30")],
        "screens": [
            [
                "Artikel 24 Abs. 1 macht aus der Rechenschaftspflicht konkretes Handeln. Unter Berücksichtigung der Art, des Umfangs, der Umstände und der Zwecke der Verarbeitung sowie der unterschiedlichen Eintrittswahrscheinlichkeit und Schwere der **Risiken** muss der Verantwortliche **geeignete technische und organisatorische Maßnahmen** umsetzen.",
                "Diese Maßnahmen müssen sicherstellen, dass die Verarbeitung gemäß der DSGVO erfolgt, und es dem Verantwortlichen ermöglichen, das nachzuweisen. Sie werden erforderlichenfalls überprüft und aktualisiert.",
            ],
            [
                "Sofern dies in einem angemessenen Verhältnis zu den Verarbeitungstätigkeiten steht, umfassen die Maßnahmen geeignete **Datenschutzvorkehrungen** (Art. 24 Abs. 2).",
                "Die Einhaltung genehmigter Verhaltensregeln oder eines genehmigten Zertifizierungsverfahrens kann als ein Gesichtspunkt herangezogen werden, um die Einhaltung nachzuweisen (Art. 24 Abs. 3).",
                "Das entscheidende Wort ist **geeignet**: Ein Krankenhaus und eine Bäckerei brauchen nicht dieselben Maßnahmen.",
            ],
            [
                "Das wichtigste Werkzeug für diesen Nachweis ist das **Verzeichnis von Verarbeitungstätigkeiten** (Art. 30 Abs. 1). Das Verzeichnis des Verantwortlichen enthält:",
                {"type": "list", "items": [
                    "a) den Namen und die Kontaktdaten des Verantwortlichen und gegebenenfalls des gemeinsam mit ihm Verantwortlichen, des Vertreters sowie eines etwaigen Datenschutzbeauftragten;",
                    "b) die Zwecke der Verarbeitung;",
                    "c) die Kategorien betroffener Personen und die Kategorien personenbezogener Daten;",
                    "d) die Kategorien von Empfängern, auch Empfänger außerhalb der EU;",
                    "e) gegebenenfalls Übermittlungen in Länder außerhalb der EU;",
                    "f) wenn möglich, die vorgesehenen Fristen für die Löschung;",
                    "g) wenn möglich, eine allgemeine Beschreibung der technischen und organisatorischen Sicherheitsmaßnahmen.",
                ]},
            ],
            [
                "Auftragsverarbeiter führen ein eigenes Verzeichnis der Verarbeitungen, die sie im Auftrag jedes Verantwortlichen durchführen (Art. 30 Abs. 2).",
                "Das Verzeichnis ist schriftlich zu führen, was auch in einem elektronischen Format erfolgen kann (Art. 30 Abs. 3). Es ist der **Aufsichtsbehörde auf Anfrage** zur Verfügung zu stellen (Art. 30 Abs. 4).",
            ],
            [
                "**Die Ausnahme für weniger als 250 Beschäftigte** (Art. 30 Abs. 5): Unternehmen oder Einrichtungen, die **„weniger als 250 Mitarbeiter beschäftigen“**, müssen kein Verzeichnis führen, **es sei denn**, ihre Verarbeitung",
                {"type": "list", "items": [
                    "birgt ein Risiko für die Rechte und Freiheiten der betroffenen Personen,",
                    "erfolgt **„nicht nur gelegentlich“** oder",
                    "umfasst besondere Kategorien personenbezogener Daten oder Daten über strafrechtliche Verurteilungen und Straftaten.",
                ]},
                "Schon eine dieser Bedingungen lässt die Ausnahme entfallen. Deshalb ist sie enger, als sie zunächst aussieht.",
            ],
            [
                "Die Bäckerei Sonnenfeld hat rund 40 Beschäftigte. Sie bearbeitet aber jede Woche Vorbestellungen und die Lohnabrechnung, und das geschieht nicht nur gelegentlich. Außerdem verarbeitet sie Krankmeldungen, also Gesundheitsdaten. Die Ausnahme greift daher nicht, und die Bäckerei führt ein Verzeichnis.",
                "Ein Beispieleintrag: *Vorbestellungen. Zweck: Bestellungen abwickeln. Betroffene Personen: Kundinnen und Kunden. Daten: Name, Telefonnummer, Bestellung. Empfänger: Hosting-Anbieter der App. Löschung: eine festgelegte Frist nach der letzten Bestellung. Sicherheit: Zugriff nach Rollen, verschlüsselte Sicherungskopien.*",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1, 2], "Wie soll ein Verantwortlicher nach Art. 24 seine Datenschutzmaßnahmen auswählen?", "Wie werden die Maßnahmen eines Verantwortlichen nach Art. 24 auf seine Lage abgestimmt?",
                       ("Nach Art, Umfang, Umständen und Zwecken der Verarbeitung sowie nach dem Risiko", "Art. 24 Abs. 1."),
                       ("Für jedes Unternehmen gleich, unabhängig von seiner Größe", "Artikel 24 verlangt geeignete Maßnahmen, also fallen sie unterschiedlich aus."),
                       ("Erst wenn eine Behörde sie verlangt", "Artikel 24 gilt von Anfang an.")),
            assessment([1], [3], "Was davon gehört in das Verzeichnis von Verarbeitungstätigkeiten eines Verantwortlichen?", "Welche dieser Angaben muss das Verzeichnis nach Art. 30 Abs. 1 enthalten?",
                       ("Die Zwecke der Verarbeitung", "Art. 30 Abs. 1 Buchst. b."),
                       ("Den Namen jeder einzelnen Kundin und jedes einzelnen Kunden", "Das Verzeichnis nennt Kategorien, nicht jede einzelne Person."),
                       ("Die Administratorpasswörter", "Passwörter gehören nicht in das Verzeichnis. Sie müssen geheim bleiben.")),
            assessment([1], [5, 6], "Die Bäckerei Sonnenfeld hat 40 Beschäftigte, bearbeitet jede Woche Bestellungen und verarbeitet Krankmeldungen ihrer Beschäftigten. Darf sie auf das Verzeichnis verzichten?", "Hilft die Ausnahme für weniger als 250 Beschäftigte einem kleinen Unternehmen, das regelmäßig Daten verarbeitet, darunter Gesundheitsdaten?",
                       ("Nein, die Verarbeitung erfolgt nicht nur gelegentlich und umfasst Gesundheitsdaten", "Art. 30 Abs. 5: Jede der beiden Bedingungen lässt die Ausnahme entfallen."),
                       ("Ja, mit weniger als 250 Beschäftigten gilt die Ausnahme immer", "Die Ausnahme hat selbst drei Ausnahmen."),
                       ("Ja, wenn es noch nie eine Datenpanne gab", "Eine Vorgeschichte ohne Vorfälle ist keine Bedingung in Art. 30 Abs. 5.")),
            assessment([1], [4], "Wer kann von der Bäckerei Sonnenfeld verlangen, ihr Verzeichnis von Verarbeitungstätigkeiten vorzulegen?", "Wer kann nach Art. 30 verlangen, dass ihm das Verzeichnis von Verarbeitungstätigkeiten zur Verfügung gestellt wird?",
                       ("Die Aufsichtsbehörde", "Art. 30 Abs. 4."),
                       ("Jede Kundin und jeder Kunde, die danach fragen", "Kundinnen und Kunden haben ein Auskunftsrecht, aber Art. 30 Abs. 4 betrifft die Aufsichtsbehörde."),
                       ("Niemand, das Verzeichnis ist rein intern", "Nach Art. 30 Abs. 4 ist es der Aufsichtsbehörde zur Verfügung zu stellen.")),
        ],
    },
    "O02": {
        "title": "Datenschutz durch Technikgestaltung und durch datenschutzfreundliche Voreinstellungen",
        "summary": "Die Grundsätze von Anfang an in Systeme einbauen und datenschutzfreundliche Voreinstellungen wählen.",
        "prerequisites": {
            "G03": "Die Pseudonymisierung ist die Beispielmaßnahme, die Art. 25 nennt.",
            "G05": "Artikel 25 ist eine Pflicht des Verantwortlichen, die schon greift, wenn er die Mittel der Verarbeitung festlegt.",
            "P02": "Maßnahmen der Technikgestaltung setzen Grundsätze wie die Datenminimierung um.",
        },
        "sources": [("GDPR", "Art. 25")],
        "screens": [
            [
                "**Datenschutz durch Technikgestaltung** (Art. 25 Abs. 1): Der Verantwortliche muss geeignete technische und organisatorische Maßnahmen treffen, die dafür ausgelegt sind, die Datenschutzgrundsätze wirksam umzusetzen, und er muss die notwendigen Garantien in die Verarbeitung aufnehmen.",
                "Artikel 25 Abs. 1 nennt die **Pseudonymisierung** als Beispiel für eine Maßnahme und die **Datenminimierung** als Beispiel für einen Grundsatz.",
            ],
            [
                "Das gilt **sowohl** zum Zeitpunkt der Festlegung der Mittel für die Verarbeitung **als auch** zum Zeitpunkt der eigentlichen Verarbeitung (Art. 25 Abs. 1).",
                "Es geht darum, vorauszuplanen, bevor Sie ein System entwickeln oder kaufen, und nicht darum, hinterher nachzubessern.",
                "Was geeignet ist, hängt vom Stand der Technik, von den Implementierungskosten, von Art, Umfang, Umständen und Zwecken der Verarbeitung sowie von den Risiken ab.",
            ],
            [
                "**Datenschutzfreundliche Voreinstellungen** (Art. 25 Abs. 2): Durch Voreinstellung dürfen nur personenbezogene Daten verarbeitet werden, deren Verarbeitung **für den jeweiligen bestimmten Verarbeitungszweck erforderlich** ist. Diese Pflicht gilt für vier Dimensionen:",
                {"type": "list", "items": ["die Menge der erhobenen Daten;", "den Umfang ihrer Verarbeitung;", "ihre Speicherfrist;", "ihre Zugänglichkeit, also wer auf sie zugreifen kann."]},
            ],
            [
                "Insbesondere dürfen personenbezogene Daten durch Voreinstellungen „nicht ohne Eingreifen der Person einer **unbestimmten Zahl von natürlichen Personen** zugänglich gemacht werden“ (Art. 25 Abs. 2).",
                "Ein genehmigtes Zertifizierungsverfahren kann als ein Faktor herangezogen werden, um die Einhaltung von Art. 25 nachzuweisen (Art. 25 Abs. 3).",
            ],
            [
                "Die Bäckerei Sonnenfeld gestaltet ihre App neu:",
                {"type": "list", "items": [
                    "Das Feld für das Geburtsdatum entfällt. Das ist Technikgestaltung, die die Datenminimierung umsetzt.",
                    "Freiwillige Felder sind anfangs leer, und das Häkchen für Werbung ist nicht gesetzt. Das sind Voreinstellungen.",
                    "Bestelldaten werden nach einer festgelegten Frist automatisch gelöscht. Damit ist die Speicherfrist durch Voreinstellung geregelt.",
                    "Eine neue Bestenliste der »Top-Kundschaft« ist **ausgeschaltet**, solange eine Kundin oder ein Kunde sie nicht selbst einschaltet. Das begrenzt die Zugänglichkeit durch Voreinstellung.",
                    "Die Beschäftigten einer Filiale sehen nur die Bestellungen ihrer eigenen Filiale. Das begrenzt den Zugriff.",
                ]},
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [2], "Wann muss ein Verantwortlicher an Datenschutz durch Technikgestaltung denken?", "Zu welchen Zeitpunkten gilt die Pflicht aus Art. 25 Abs. 1?",
                       ("Bei der Festlegung der Mittel und während der Verarbeitung", "Artikel 25 Abs. 1 nennt beide Zeitpunkte."),
                       ("Erst nachdem das System in Betrieb gegangen ist", "Die Technikgestaltung beginnt, wenn die Mittel festgelegt werden."),
                       ("Erst nach einer Datenpanne", "Artikel 25 wirkt vorbeugend.")),
            assessment([0], [1], "Welche Maßnahme nennt Art. 25 Abs. 1 als Beispiel?", "Welche Beispielmaßnahme steht im Text von Art. 25 Abs. 1?",
                       ("Pseudonymisierung", "In Art. 25 Abs. 1 genannt."),
                       ("Ein höheres Marketingbudget", "Keine Datenschutzmaßnahme."),
                       ("Daten länger speichern", "Das läuft den Grundsätzen zuwider.")),
            assessment([1], [4, 5], "Die Bäckerei Sonnenfeld führt eine öffentliche Bestenliste ihrer besten Kundinnen und Kunden mit Namen ein. Wie muss die Voreinstellung sein?", "Wie sollte eine Funktion voreingestellt sein, die die Namen von Kundinnen und Kunden veröffentlichen würde?",
                       ("Ausgeschaltet, bis eine Kundin oder ein Kunde selbst mitmachen will", "Art. 25 Abs. 2: nicht ohne Eingreifen der Person einer unbestimmten Zahl von Personen zugänglich."),
                       ("Eingeschaltet, mit der Möglichkeit, sich abzumelden", "Wer sich erst abmelden muss, wird ohne eigenes Eingreifen sichtbar."),
                       ("Eingeschaltet, solange die Datenschutzhinweise es erwähnen", "Ein Hinweis ersetzt keine datenschutzfreundliche Voreinstellung.")),
            assessment([1], [3], "Welche Dimensionen erfasst die Regel zu Voreinstellungen in Art. 25 Abs. 2?", "In welcher Hinsicht begrenzt Art. 25 Abs. 2 die Voreinstellungen?",
                       ("Menge, Umfang der Verarbeitung, Speicherfrist und Zugänglichkeit", "Artikel 25 Abs. 2 nennt alle vier."),
                       ("Nur die Menge der erhobenen Daten", "Artikel 25 Abs. 2 erfasst vier Dimensionen."),
                       ("Nur die Sicherheit der Daten", "Die Sicherheit regelt Art. 32. Bei Art. 25 Abs. 2 geht es um die Erforderlichkeit.")),
        ],
    },
    "O03": {
        "title": "Zusammenarbeit mit Auftragsverarbeitern",
        "summary": "Auftragsverarbeiter mit hinreichenden Garantien auswählen, die Pflichtinhalte schriftlich festhalten und weitere Auftragsverarbeiter kontrollieren.",
        "prerequisites": {"G05": "Der Vertrag regelt die Verarbeitung durch einen Auftragsverarbeiter."},
        "sources": [("GDPR", "Art. 28")],
        "screens": [
            [
                "Ein Verantwortlicher darf nur mit Auftragsverarbeitern arbeiten, die **hinreichend Garantien** dafür bieten, dass geeignete Maßnahmen so durchgeführt werden, dass die Verarbeitung den Anforderungen der DSGVO entspricht und die Rechte der betroffenen Personen schützt (Art. 28 Abs. 1).",
                "Die Wahl eines Dienstleisters ist deshalb eine Entscheidung über Datenschutz und nicht nur eine Einkaufsentscheidung.",
            ],
            [
                "Die Verarbeitung durch einen Auftragsverarbeiter erfolgt auf der Grundlage eines **Vertrags** oder eines anderen Rechtsinstruments, das den Auftragsverarbeiter bindet (Art. 28 Abs. 3). Darin sind Gegenstand und Dauer der Verarbeitung, Art und Zweck der Verarbeitung, die Art der personenbezogenen Daten, die Kategorien betroffener Personen sowie die Pflichten und Rechte des Verantwortlichen festgelegt.",
                "Der Vertrag ist **schriftlich** abzufassen, was auch in einem elektronischen Format erfolgen kann (Art. 28 Abs. 9).",
            ],
            [
                "Der Vertrag muss insbesondere vorsehen, dass der Auftragsverarbeiter (Art. 28 Abs. 3 Buchst. a bis h):",
                {"type": "list", "items": [
                    "die Daten nur auf **dokumentierte Weisung** des Verantwortlichen verarbeitet, auch in Bezug auf Übermittlungen außerhalb der EU;",
                    "gewährleistet, dass die zur Verarbeitung befugten Personen zur **Vertraulichkeit** verpflichtet sind;",
                    "alle nach Art. 32 erforderlichen **Sicherheitsmaßnahmen** ergreift;",
                    "die Bedingungen für die Inanspruchnahme **weiterer Auftragsverarbeiter** einhält;",
                    "den Verantwortlichen **unterstützt**: bei Anträgen von Menschen, die ihre Rechte wahrnehmen, sowie bei Sicherheit, Datenpannen und Folgenabschätzungen;",
                    "nach Abschluss der Leistungen alle Daten nach Wahl des Verantwortlichen **löscht oder zurückgibt**;",
                    "alle erforderlichen Informationen zur Verfügung stellt und **Überprüfungen** einschließlich Inspektionen ermöglicht.",
                ]},
                "Der Auftragsverarbeiter muss den Verantwortlichen unverzüglich informieren, wenn er der Auffassung ist, dass eine Weisung gegen Datenschutzrecht verstößt.",
            ],
            [
                "**Weitere Auftragsverarbeiter** (Art. 28 Abs. 2): Ein Auftragsverarbeiter darf keinen weiteren Auftragsverarbeiter ohne vorherige **gesonderte oder allgemeine schriftliche Genehmigung** des Verantwortlichen in Anspruch nehmen.",
                "Bei einer allgemeinen Genehmigung muss der Auftragsverarbeiter den Verantwortlichen über jede beabsichtigte Änderung informieren. So erhält der Verantwortliche die Möglichkeit, **Einspruch** zu erheben.",
            ],
            [
                "Dem weiteren Auftragsverarbeiter müssen per Vertrag dieselben Datenschutzpflichten auferlegt werden. „Kommt der weitere Auftragsverarbeiter seinen Datenschutzpflichten nicht nach, so **haftet der erste Auftragsverarbeiter** gegenüber dem Verantwortlichen für die Einhaltung der Pflichten jenes anderen Auftragsverarbeiters.“ (Art. 28 Abs. 4)",
            ],
            [
                "Der Vertrag kann auf **Standardvertragsklauseln** beruhen, die die Kommission oder eine Aufsichtsbehörde festgelegt hat (Art. 28 Abs. 6 bis 8).",
                "Die Bäckerei Sonnenfeld prüft die Bedingungen ihres Newsletter-Dienstes, ihres App-Hosters und ihres Lohnabrechnungsdienstleisters. Jeder dieser Verträge muss die Punkte aus Art. 28 Abs. 3 enthalten. Viele Anbieter veröffentlichen solche Bedingungen, und die Bäckerei bewahrt von jedem eine Kopie auf.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [3], "Welche Regelung muss ein Vertrag zwischen einem Verantwortlichen und einem Auftragsverarbeiter enthalten?", "Welche Klausel schreibt Art. 28 Abs. 3 für den Vertrag mit einem Auftragsverarbeiter zwingend vor?",
                       ("Verarbeitung nur auf dokumentierte Weisung des Verantwortlichen", "Art. 28 Abs. 3 Buchst. a."),
                       ("Der Auftragsverarbeiter darf die Daten für eigene Werbung nutzen", "Damit würde er für diese Nutzung selbst zum Verantwortlichen."),
                       ("Der Auftragsverarbeiter entscheidet, wie lange Daten gespeichert werden", "Über die Zwecke und die wesentlichen Mittel entscheidet der Verantwortliche.")),
            assessment([0], [2], "Welche Form muss der Vertrag mit einem Auftragsverarbeiter haben?", "In welcher Form verlangt Art. 28 Abs. 9 den Vertrag mit einem Auftragsverarbeiter?",
                       ("Schriftlich, was auch elektronisch möglich ist", "Art. 28 Abs. 9."),
                       ("Eine mündliche Vereinbarung genügt", "Artikel 28 Abs. 9 verlangt, dass der Vertrag schriftlich abgefasst wird."),
                       ("Er muss notariell beurkundet werden", "Artikel 28 verlangt keine notarielle Beurkundung.")),
            assessment([1], [4], "Die Bäckerei Sonnenfeld hat eine allgemeine Genehmigung erteilt, und ihr Newsletter-Dienst will einen neuen weiteren Auftragsverarbeiter hinzuziehen. Was muss geschehen?", "Die Bäckerei Sonnenfeld hat ihrem Newsletter-Dienst eine allgemeine schriftliche Genehmigung erteilt. Was muss geschehen, wenn der Dienst seine weiteren Auftragsverarbeiter ändert?",
                       ("Er informiert die Bäckerei, die Einspruch erheben kann", "Art. 28 Abs. 2."),
                       ("Er darf beliebig weitere Auftragsverarbeiter hinzuziehen", "Änderungen sind mitzuteilen, damit der Verantwortliche Einspruch erheben kann."),
                       ("Eine Aufsichtsbehörde muss zustimmen", "Artikel 28 Abs. 2 bezieht den Verantwortlichen ein, nicht die Behörde.")),
            assessment([1], [5], "Ein weiterer Auftragsverarbeiter kommt seinen Datenschutzpflichten nicht nach. Wer haftet gegenüber der Bäckerei Sonnenfeld für dieses Versäumnis?", "Ein weiterer Auftragsverarbeiter, den der Auftragsverarbeiter der Bäckerei Sonnenfeld hinzugezogen hat, verletzt seine Pflichten. Wer haftet nach Art. 28 Abs. 4 gegenüber der Bäckerei dafür?",
                       ("Der erste Auftragsverarbeiter", "Art. 28 Abs. 4: Er haftet für die Einhaltung der Pflichten des weiteren Auftragsverarbeiters."),
                       ("Niemand, weil die Bäckerei keinen Vertrag mit ihm geschlossen hat", "Der erste Auftragsverarbeiter haftet weiterhin."),
                       ("Nur der weitere Auftragsverarbeiter", "Nach Art. 28 Abs. 4 haftet der erste Auftragsverarbeiter gegenüber dem Verantwortlichen.")),
        ],
    },
    "O04": {
        "title": "Sicherheit der Verarbeitung",
        "summary": "Dem Risiko angemessene Sicherheitsmaßnahmen wählen und prüfen, ob sie wirken.",
        "prerequisites": {
            "G03": "Die Pseudonymisierung ist eine der genannten Sicherheitsmaßnahmen.",
            "G05": "Artikel 32 ist eine Pflicht des Verantwortlichen, deshalb müssen Lernende diese Rolle kennen.",
            "P03": "Artikel 32 setzt den Grundsatz der Integrität und Vertraulichkeit um.",
        },
        "sources": [("GDPR", "Art. 32")],
        "screens": [
            [
                "Artikel 32 Abs. 1: Unter Berücksichtigung des Stands der Technik, der Implementierungskosten, der Art, des Umfangs, der Umstände und der Zwecke der Verarbeitung sowie der Risiken treffen **der Verantwortliche und der Auftragsverarbeiter** Maßnahmen, um ein **„dem Risiko angemessenes Schutzniveau“** zu gewährleisten.",
                "Sicherheit heißt also weder »das Maximum, koste es, was es wolle« noch »so billig wie möglich«. Sie richtet sich nach dem Risiko.",
            ],
            [
                "Artikel 32 Abs. 1 nennt Maßnahmen, die gegebenenfalls einzusetzen sind:",
                {"type": "list", "items": [
                    "a) die **Pseudonymisierung und Verschlüsselung**;",
                    "b) die Fähigkeit, die **Vertraulichkeit, Integrität, Verfügbarkeit und Belastbarkeit** der Systeme auf Dauer sicherzustellen;",
                    "c) die Fähigkeit, die Verfügbarkeit der Daten und den Zugang zu ihnen nach einem Zwischenfall rasch **wiederherzustellen**;",
                    "d) ein Verfahren zur **regelmäßigen Überprüfung, Bewertung und Evaluierung** der Maßnahmen.",
                ]},
            ],
            [
                "Bei der Beurteilung des Risikos sind insbesondere die Risiken zu berücksichtigen, die, ob unbeabsichtigt oder unrechtmäßig, durch **Vernichtung, Verlust, Veränderung oder unbefugte Offenlegung** personenbezogener Daten oder durch **unbefugten Zugang** zu ihnen entstehen (Art. 32 Abs. 2).",
            ],
            [
                "Unternehmen müssen Schritte unternehmen, damit Personen, die ihnen unterstellt sind und Zugang zu personenbezogenen Daten haben, diese **nur auf Anweisung** verarbeiten (Art. 32 Abs. 4).",
                "Die Einhaltung genehmigter Verhaltensregeln oder eines genehmigten Zertifizierungsverfahrens kann helfen, die Einhaltung nachzuweisen (Art. 32 Abs. 3).",
            ],
            [
                "Die Maßnahmen der Bäckerei Sonnenfeld, abgestimmt auf ihre Risiken:",
                {"type": "list", "items": [
                    "verschlüsselte Laptops und Mobiltelefone;",
                    "Zugriff auf Personalakten nur für die Geschäftsführung und die Lohnabrechnung;",
                    "tägliche Sicherungen des Bestellsystems, deren Wiederherstellung tatsächlich getestet wird;",
                    "schriftliche Anweisungen für die Beschäftigten;",
                    "eine jährliche Prüfung, ob die Maßnahmen noch wirken.",
                ]},
                "Einmal eine Firewall zu kaufen und sie nie zu überprüfen, erfüllt Buchst. d nicht.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "Welches Schutzniveau verlangt Art. 32?", "Wie hoch muss das Schutzniveau der Verarbeitung nach Art. 32 sein?",
                       ("Es muss dem Risiko angemessen sein", "Art. 32 Abs. 1."),
                       ("Es muss so hoch wie möglich sein, gleich, was es kostet", "Kosten und Stand der Technik sind zu berücksichtigen."),
                       ("Das billigste genügt", "Das Schutzniveau muss dem Risiko angemessen sein.")),
            assessment([0], [2], "Was davon nennt Art. 32 Abs. 1?", "Was gehört zu den Maßnahmen, die Art. 32 Abs. 1 aufzählt?",
                       ("Die Fähigkeit, den Zugang zu Daten nach einem Zwischenfall rasch wiederherzustellen", "Art. 32 Abs. 1 Buchst. c."),
                       ("Die Veröffentlichung des Jahresumsatzes", "Keine Sicherheitsmaßnahme."),
                       ("Die Benennung eines Datenschutzbeauftragten", "Das regelt Art. 37. Es ist keine Maßnahme nach Art. 32.")),
            assessment([0], [2, 5], "Die Bäckerei Sonnenfeld hat vor drei Jahren Sicherheitssoftware installiert und sie nie überprüft. Was fehlt ihr nach Art. 32 Abs. 1?", "Was verlangt Art. 32 Abs. 1 Buchst. d über das Installieren von Sicherheitsmaßnahmen hinaus?",
                       ("Die regelmäßige Überprüfung und Bewertung der Maßnahmen", "Art. 32 Abs. 1 Buchst. d."),
                       ("Nichts, einmal installieren genügt", "Buchst. d verlangt eine regelmäßige Überprüfung."),
                       ("Eine Prüfung, aber erst nach einer Datenpanne", "Buchst. d sagt regelmäßig, nicht erst nach einem Vorfall.")),
            assessment([0], [1], "Gilt Art. 32 für den Auftragsverarbeiter, der für die Bäckerei Sonnenfeld die Lohnabrechnung erledigt?", "Müssen neben Verantwortlichen auch Auftragsverarbeiter Sicherheitsmaßnahmen nach Art. 32 treffen?",
                       ("Ja, Verantwortliche und Auftragsverarbeiter gleichermaßen", "Artikel 32 Abs. 1 nennt beide."),
                       ("Nein, nur der Verantwortliche", "Auftragsverarbeiter werden ebenfalls genannt."),
                       ("Nein, nur wenn der Vertrag es vorsieht", "Artikel 32 gilt unmittelbar.")),
        ],
    },
    "O05": {
        "title": "Verletzungen des Schutzes personenbezogener Daten",
        "summary": "Eine Verletzung des Schutzes personenbezogener Daten erkennen, sie, wenn nötig, binnen 72 Stunden der Aufsichtsbehörde melden und bei hohem Risiko die betroffenen Personen benachrichtigen.",
        "prerequisites": {
            "G01": "Die Meldung geht an die Aufsichtsbehörde.",
            "G05": "Auftragsverarbeiter müssen dem Verantwortlichen Verletzungen melden.",
            "P03": "Eine Verletzung ist ein Versagen der Sicherheit.",
            "O04": "Eine angewandte Verschlüsselung kann die Pflicht entfallen lassen, die betroffenen Personen zu benachrichtigen.",
        },
        "sources": [("GDPR", "Art. 4 Nr. 12, 33, 34"), ("GDPR-REC", "Erwägungsgrund 85")],
        "screens": [
            [
                "Eine **Verletzung des Schutzes personenbezogener Daten** ist eine Verletzung der Sicherheit, die, ob unbeabsichtigt oder unrechtmäßig, zur **Vernichtung, zum Verlust, zur Veränderung oder zur unbefugten Offenlegung von beziehungsweise zum unbefugten Zugang zu** personenbezogenen Daten führt (Art. 4 Nr. 12).",
                "Gemeint ist nicht nur ein Hackerangriff. Eine E-Mail an die falsche Person, ein verlorener Laptop und Ransomware, die Dateien zerstört: All das sind Verletzungen des Schutzes personenbezogener Daten.",
            ],
            [
                "**Meldung an die Aufsichtsbehörde**: Der Verantwortliche meldet der Aufsichtsbehörde eine Verletzung „unverzüglich und möglichst binnen 72 Stunden, nachdem ihm die Verletzung bekannt wurde“, **es sei denn**, sie führt „voraussichtlich nicht zu einem Risiko für die Rechte und Freiheiten natürlicher Personen“ (Art. 33 Abs. 1).",
                "Erfolgt die Meldung nicht binnen 72 Stunden, ist eine Begründung für die Verzögerung beizufügen.",
            ],
            [
                "Wird einem **Auftragsverarbeiter** eine Verletzung bekannt, meldet er sie dem Verantwortlichen unverzüglich (Art. 33 Abs. 2).",
                "Die Meldung beschreibt zumindest die Art der Verletzung und die ungefähre Zahl der betroffenen Personen und Datensätze. Sie nennt eine Anlaufstelle und beschreibt die wahrscheinlichen Folgen und die ergriffenen Maßnahmen (Art. 33 Abs. 3). Ist noch nicht alles bekannt, können die Informationen **schrittweise** zur Verfügung gestellt werden (Art. 33 Abs. 4).",
            ],
            [
                "**Dokumentieren Sie jede Verletzung**, auch die, die Sie nicht melden: die Fakten, ihre Auswirkungen und die ergriffenen Abhilfemaßnahmen (Art. 33 Abs. 5).",
                "Mit dieser Dokumentation kann die Aufsichtsbehörde Ihre Entscheidungen überprüfen.",
            ],
            [
                "**Benachrichtigen Sie die betroffenen Personen** unverzüglich, wenn die Verletzung **voraussichtlich ein hohes Risiko** für ihre Rechte und Freiheiten zur Folge hat (Art. 34 Abs. 1).",
                "Verwenden Sie klare und einfache Sprache, und nennen Sie die Anlaufstelle, die wahrscheinlichen Folgen und die ergriffenen Maßnahmen (Art. 34 Abs. 2).",
                "Erwägungsgrund 85 nennt mögliche Schäden, etwa Identitätsdiebstahl oder -betrug, finanzielle Verluste, Diskriminierung und Rufschädigung.",
            ],
            [
                "Eine Benachrichtigung der betroffenen Personen ist nicht erforderlich, wenn (Art. 34 Abs. 3):",
                {"type": "list", "items": [
                    "a) auf die betroffenen Daten Schutzvorkehrungen angewandt wurden, die sie für alle Unbefugten unzugänglich machen, etwa eine **Verschlüsselung**;",
                    "b) nachfolgende Maßnahmen sicherstellen, dass das hohe Risiko aller Wahrscheinlichkeit nach nicht mehr besteht; oder",
                    "c) die Benachrichtigung mit einem unverhältnismäßigen Aufwand verbunden wäre. Dann erfolgt stattdessen eine öffentliche Bekanntmachung.",
                ]},
                "Die Aufsichtsbehörde kann trotzdem verlangen, dass Sie die Personen benachrichtigen (Art. 34 Abs. 4).",
            ],
            [
                "Fälle der Bäckerei Sonnenfeld:",
                {"type": "list", "items": [
                    "Ein unverschlüsselter Laptop mit Krankmeldungen der Beschäftigten wird gestohlen. Gesundheitsdaten liegen offen. Die Bäckerei meldet die Verletzung deshalb binnen 72 Stunden der Aufsichtsbehörde und benachrichtigt die Beschäftigten.",
                    "Ein stark verschlüsselter Laptop wird gestohlen, und der Schlüssel ist sicher. Die Ausnahme für Verschlüsselung in Art. 34 Abs. 3 Buchst. a greift wahrscheinlich. Die Bäckerei dokumentiert die Verletzung trotzdem und prüft, ob sie sie der Aufsichtsbehörde melden muss.",
                ]},
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "Was davon ist eine Verletzung des Schutzes personenbezogener Daten?", "Welches Ereignis erfüllt die Definition in Art. 4 Nr. 12?",
                       ("Ein Beschäftigter schickt die Kundenliste per E-Mail an den falschen Lieferanten", "Unbefugte Offenlegung (Art. 4 Nr. 12)."),
                       ("Eine Kundin ändert ihre E-Mail-Adresse", "Eine normale, befugte Änderung."),
                       ("Die Bäckerei Sonnenfeld löscht alte Daten nach ihrer Löschregel", "Eine befugte Löschung ist keine Verletzung der Sicherheit.")),
            assessment([1], [2], "Wann muss eine meldepflichtige Verletzung der Aufsichtsbehörde gemeldet werden?", "Welche Frist setzt Art. 33 Abs. 1 für die Meldung einer Verletzung an die Aufsichtsbehörde?",
                       ("Unverzüglich und möglichst binnen 72 Stunden, nachdem sie bekannt wurde", "Art. 33 Abs. 1."),
                       ("Binnen 72 Stunden, nachdem die Verletzung geschehen ist", "Die Frist läuft ab dem Zeitpunkt, zu dem die Verletzung bekannt wurde."),
                       ("Binnen eines Monats", "Ein Monat ist die Frist für die Antwort auf Anträge betroffener Personen.")),
            assessment([1], [4], "Die Bäckerei Sonnenfeld kommt zu dem Schluss, dass eine kleine Verletzung voraussichtlich zu keinem Risiko führt, und meldet sie nicht. Muss sie sie trotzdem dokumentieren?", "Müssen Verletzungen, die nicht gemeldet werden, trotzdem dokumentiert werden?",
                       ("Ja, alle Verletzungen sind zu dokumentieren", "Art. 33 Abs. 5."),
                       ("Nein, nur gemeldete Verletzungen werden festgehalten", "Artikel 33 Abs. 5 erfasst jede Verletzung."),
                       ("Nein, aber sie muss sie trotzdem melden", "Führt die Verletzung voraussichtlich zu keinem Risiko, ist keine Meldung nötig. Die Dokumentation schon.")),
            assessment([2], [6, 7], "Die Daten auf einem gestohlenen Laptop waren stark verschlüsselt, und der Schlüssel ist sicher. Müssen die Beschäftigten benachrichtigt werden?", "Müssen betroffene Personen immer benachrichtigt werden, wenn stark verschlüsselte Daten von einer Verletzung betroffen sind?",
                       ("Nicht unbedingt: Art. 34 Abs. 3 Buchst. a ist eine Ausnahme", "Eine Verschlüsselung, die die Daten für Unbefugte unzugänglich macht, ist eine genannte Ausnahme."),
                       ("Ja, immer, gleich, wie die Daten geschützt sind", "Artikel 34 Abs. 3 nennt Ausnahmen."),
                       ("Nur wenn die Aufsichtsbehörde eine Geldbuße gegen die Bäckerei verhängt", "Auslöser ist nicht eine Geldbuße, sondern ein hohes Risiko.")),
            assessment([2], [5], "Wann müssen betroffene Personen über eine Verletzung benachrichtigt werden?", "Wann löst eine Verletzung die Pflicht nach Art. 34 aus, die betroffenen Personen zu benachrichtigen?",
                       ("Wenn sie voraussichtlich ein hohes Risiko für sie zur Folge hat", "Art. 34 Abs. 1."),
                       ("Nach jeder Verletzung, wie klein sie auch ist", "Auslöser ist ein voraussichtlich hohes Risiko."),
                       ("Nie, nur die Aufsichtsbehörde wird informiert", "Artikel 34 verlangt bei hohem Risiko, die betroffenen Personen zu benachrichtigen.")),
        ],
    },
    "O06": {
        "title": "Datenschutz-Folgenabschätzungen",
        "summary": "Entscheiden, wann eine Datenschutz-Folgenabschätzung erforderlich ist und was sie enthalten muss.",
        "prerequisites": {
            "P08": "Ein genannter Fall für eine Datenschutz-Folgenabschätzung ist die umfangreiche Verarbeitung besonderer Kategorien personenbezogener Daten.",
            "R07": "Ein genannter Fall für eine Datenschutz-Folgenabschätzung ist die systematische automatisierte Bewertung mit erheblichen Auswirkungen.",
            "O01": "Eine Datenschutz-Folgenabschätzung ist eine risikobasierte Maßnahme des Verantwortlichen.",
        },
        "sources": [("GDPR", "Art. 35")],
        "screens": [
            [
                "Hat eine Form der Verarbeitung, insbesondere bei Verwendung neuer Technologien, **voraussichtlich ein hohes Risiko** für die Rechte und Freiheiten von Menschen zur Folge, muss der Verantwortliche eine **Datenschutz-Folgenabschätzung** durchführen, und zwar **vorab**, also bevor die Verarbeitung beginnt (Art. 35 Abs. 1).",
                "Für mehrere ähnliche Verarbeitungsvorgänge mit ähnlich hohen Risiken kann eine einzige Abschätzung vorgenommen werden.",
            ],
            [
                "Artikel 35 Abs. 3 nennt Fälle, in denen eine Datenschutz-Folgenabschätzung insbesondere erforderlich ist:",
                {"type": "list", "items": [
                    "a) systematische und umfassende **Bewertung** persönlicher Aspekte, die sich auf automatisierte Verarbeitung einschließlich Profiling gründet und als Grundlage für Entscheidungen dient, die Rechtswirkung entfalten oder Menschen in ähnlich erheblicher Weise beeinträchtigen;",
                    "b) **umfangreiche** Verarbeitung besonderer Kategorien personenbezogener Daten oder von Daten über strafrechtliche Verurteilungen und Straftaten;",
                    "c) systematische umfangreiche **Überwachung öffentlich zugänglicher Bereiche**.",
                ]},
            ],
            [
                "Jede Aufsichtsbehörde erstellt und veröffentlicht eine **Liste** der Verarbeitungsvorgänge, für die eine Datenschutz-Folgenabschätzung durchzuführen ist (Art. 35 Abs. 4). Sie kann außerdem eine Liste der Arten von Verarbeitungsvorgängen veröffentlichen, für die keine erforderlich ist (Art. 35 Abs. 5).",
                "Prüfen Sie die Liste Ihrer Aufsichtsbehörde. Über sie finden Sie in der Praxis die Fälle, die über Art. 35 Abs. 3 hinausgehen.",
            ],
            [
                "Eine Datenschutz-Folgenabschätzung enthält zumindest (Art. 35 Abs. 7):",
                {"type": "list", "items": [
                    "a) eine systematische Beschreibung der geplanten Verarbeitungsvorgänge und der Zwecke der Verarbeitung;",
                    "b) eine Bewertung der **Notwendigkeit und Verhältnismäßigkeit**;",
                    "c) eine Bewertung der **Risiken** für die Rechte und Freiheiten der betroffenen Personen;",
                    "d) die zur Bewältigung der Risiken geplanten **Abhilfemaßnahmen**.",
                ]},
            ],
            [
                "Holen Sie den Rat des Datenschutzbeauftragten ein, sofern einer benannt wurde (Art. 35 Abs. 2). Holen Sie gegebenenfalls den Standpunkt der betroffenen Personen oder ihrer Vertreter ein (Art. 35 Abs. 9).",
                "Überprüfen Sie die Folgenabschätzung zumindest dann, wenn sich das Risiko ändert (Art. 35 Abs. 11).",
            ],
            [
                "Die Bäckerei Sonnenfeld plant eine Software, die Bewerberinnen und Bewerber mit Punkten bewertet und bei niedriger Punktzahl automatisch ablehnt. Das ist eine systematische, automatisierte Bewertung mit erheblichen Auswirkungen, wie sie Art. 35 Abs. 3 Buchst. a beschreibt. Vorher ist also eine Datenschutz-Folgenabschätzung nötig.",
                "Ob die Kameras in den Filialen eine brauchen, hängt vom Umfang und von der Liste der Aufsichtsbehörde ab. Die Bäckerei prüft diese Liste, statt zu raten.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "Wann muss eine Datenschutz-Folgenabschätzung durchgeführt werden?", "Zu welchem Zeitpunkt verlangt Art. 35 Abs. 1 eine Datenschutz-Folgenabschätzung?",
                       ("Vor einer Verarbeitung, die voraussichtlich ein hohes Risiko zur Folge hat", "Art. 35 Abs. 1."),
                       ("Nachdem es zu einer Datenpanne gekommen ist", "Die Folgenabschätzung erfolgt vor der Verarbeitung."),
                       ("Jedes Jahr für jede Verarbeitung", "Artikel 35 zielt auf Verarbeitungen mit voraussichtlich hohem Risiko.")),
            assessment([0], [2, 6], "Für welchen Fall verlangt Art. 35 Abs. 3 ausdrücklich eine Datenschutz-Folgenabschätzung?", "Welche Verarbeitung wird in Art. 35 Abs. 3 als Fall für eine Datenschutz-Folgenabschätzung genannt?",
                       ("Die umfangreiche Verarbeitung besonderer Kategorien personenbezogener Daten", "Art. 35 Abs. 3 Buchst. b."),
                       ("Der Versand eines monatlichen Newsletters", "Kein genannter Fall und normalerweise kein hohes Risiko."),
                       ("Das Führen einer Kontaktliste der Kundschaft", "Kein genannter Fall.")),
            assessment([0], [4], "Was muss jede Datenschutz-Folgenabschätzung enthalten?", "Welchen Inhalt verlangt Art. 35 Abs. 7 für eine Datenschutz-Folgenabschätzung?",
                       ("Eine Bewertung der Notwendigkeit und Verhältnismäßigkeit", "Art. 35 Abs. 7 Buchst. b."),
                       ("Den Marketingplan des Unternehmens", "Artikel 35 Abs. 7 verlangt ihn nicht."),
                       ("Eine vorherige Genehmigung der Aufsichtsbehörde", "Artikel 35 verlangt keine Genehmigung.")),
            assessment([0], [3], "Wo findet die Bäckerei Sonnenfeld weitere Arten von Verarbeitungen, für die eine Datenschutz-Folgenabschätzung nötig ist?", "Wo sollte die Bäckerei Sonnenfeld nach Fällen suchen, die über die in Art. 35 Abs. 3 genannten hinaus eine Datenschutz-Folgenabschätzung erfordern?",
                       ("In der veröffentlichten Liste ihrer Aufsichtsbehörde", "Art. 35 Abs. 4."),
                       ("Nirgends, Art. 35 Abs. 3 ist abschließend", "Artikel 35 Abs. 3 sagt „insbesondere“. Die Aufzählung ist nicht abschließend."),
                       ("Im Jahresbericht der Kommission", "Artikel 35 Abs. 4 weist die Listen den Aufsichtsbehörden zu.")),
        ],
    },
    "O07": {
        "title": "Der Datenschutzbeauftragte",
        "summary": "Entscheiden, ob ein Datenschutzbeauftragter vorgeschrieben ist, und die Unabhängigkeit der Rolle schützen.",
        "prerequisites": {
            "G01": "Der Datenschutzbeauftragte arbeitet mit der Aufsichtsbehörde zusammen und ist ihre Anlaufstelle.",
            "G05": "Der Datenschutzbeauftragte wird vom Verantwortlichen oder Auftragsverarbeiter benannt und berät ihn.",
            "P08": "Ein Fall, in dem ein Datenschutzbeauftragter vorgeschrieben ist, ist die umfangreiche Verarbeitung besonderer Kategorien personenbezogener Daten.",
        },
        "sources": [("GDPR", "Art. 37, 38, 39")],
        "screens": [
            [
                "Ein **Datenschutzbeauftragter** ist auf jeden Fall zu benennen, wenn (Art. 37 Abs. 1):",
                {"type": "list", "items": [
                    "a) die Verarbeitung von einer **Behörde oder öffentlichen Stelle** durchgeführt wird, mit Ausnahme von Gerichten, soweit sie im Rahmen ihrer justiziellen Tätigkeit handeln;",
                    "b) die **Kerntätigkeit** in Verarbeitungsvorgängen besteht, die eine **umfangreiche regelmäßige und systematische Überwachung** von betroffenen Personen erforderlich machen; oder",
                    "c) die **Kerntätigkeit** in der **umfangreichen** Verarbeitung besonderer Kategorien von Daten oder von Daten über strafrechtliche Verurteilungen und Straftaten besteht.",
                ]},
            ],
            [
                "In anderen Fällen ist die Benennung eines Datenschutzbeauftragten freiwillig, **es sei denn, das Recht der Union oder der Mitgliedstaaten schreibt sie vor** (Art. 37 Abs. 4).",
                "Einige Länder stellen eigene Anforderungen auf. Dieser Kurs behandelt kein nationales Recht, in Deutschland etwa das Bundesdatenschutzgesetz (BDSG). Prüfen Sie deshalb das Recht Ihres Landes.",
            ],
            [
                "Der Datenschutzbeauftragte muss **Fachwissen** auf dem Gebiet des Datenschutzrechts und der Datenschutzpraxis besitzen (Art. 37 Abs. 5). Er kann Beschäftigter des Unternehmens sein oder seine Aufgaben auf der Grundlage eines Dienstleistungsvertrags erfüllen (Art. 37 Abs. 6). Eine Unternehmensgruppe darf einen gemeinsamen Datenschutzbeauftragten ernennen, sofern er von jeder Niederlassung aus leicht erreicht werden kann (Art. 37 Abs. 2).",
                "Die Kontaktdaten des Datenschutzbeauftragten sind zu veröffentlichen und der Aufsichtsbehörde mitzuteilen (Art. 37 Abs. 7).",
            ],
            [
                "**Unabhängigkeit** (Art. 38). Der Datenschutzbeauftragte",
                {"type": "list", "items": [
                    "wird ordnungsgemäß und frühzeitig in alle Fragen des Datenschutzes eingebunden;",
                    "erhält die erforderlichen Ressourcen;",
                    "erhält **keine Anweisungen** bezüglich der Ausübung seiner Aufgaben;",
                    "darf wegen der Erfüllung seiner Aufgaben **nicht abberufen oder benachteiligt** werden;",
                    "berichtet unmittelbar der **höchsten Managementebene**;",
                    "darf andere Aufgaben nur wahrnehmen, wenn sie nicht zu einem Interessenkonflikt führen.",
                ]},
            ],
            [
                "**Aufgaben** (Art. 39 Abs. 1): das Unternehmen und seine Beschäftigten unterrichten und beraten; die **Einhaltung überwachen**, einschließlich Schulungen und Überprüfungen; zu Datenschutz-Folgenabschätzungen beraten; **mit der Aufsichtsbehörde zusammenarbeiten** und als ihre Anlaufstelle tätig sein.",
                "Betroffene Personen können den Datenschutzbeauftragten zu allen Fragen rund um ihre Daten und ihre Rechte zu Rate ziehen (Art. 38 Abs. 4).",
            ],
            [
                "Die Kerntätigkeit der Bäckerei Sonnenfeld ist das Backen und Verkaufen von Brot. Die Verarbeitung von Daten der Beschäftigten und der Kundschaft unterstützt diese Tätigkeit. Sie ist aber nicht offensichtlich eine umfangreiche Überwachung oder eine umfangreiche Verarbeitung sensibler Daten.",
                "Nach Art. 37 Abs. 1 ist ein Datenschutzbeauftragter daher möglicherweise nicht vorgeschrieben. Nationales Recht kann ihn nach Art. 37 Abs. 4 trotzdem verlangen, und die Bäckerei muss das prüfen.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1, 2], "Wer muss nach Art. 37 Abs. 1 einen Datenschutzbeauftragten benennen?", "Wer muss schon nach dem Text der DSGVO selbst einen Datenschutzbeauftragten benennen?",
                       ("Eine Behörde oder öffentliche Stelle", "Art. 37 Abs. 1 Buchst. a."),
                       ("Jedes Unternehmen mit einer Website", "Kein Fall nach Art. 37 Abs. 1."),
                       ("Jedes Unternehmen mit mehr als zehn Beschäftigten", "Der Text der DSGVO nennt keine Beschäftigtenzahl. Nationales Recht kann Regeln ergänzen (Art. 37 Abs. 4).")),
            assessment([0], [4], "Wem berichtet der Datenschutzbeauftragte?", "Welcher Ebene berichtet der Datenschutzbeauftragte nach Art. 38 Abs. 3?",
                       ("Der höchsten Managementebene", "Art. 38 Abs. 3."),
                       ("Der IT-Abteilung", "Artikel 38 Abs. 3 verlangt die höchste Managementebene."),
                       ("Der Aufsichtsbehörde", "Der Datenschutzbeauftragte arbeitet mit der Behörde zusammen, berichtet intern aber der höchsten Managementebene.")),
            assessment([0], [4], "Der Datenschutzbeauftragte der Bäckerei Sonnenfeld meldet ein Problem bei der Einhaltung des Datenschutzes. Darf die Bäckerei ihn deswegen abberufen?", "Darf ein Datenschutzbeauftragter wegen der Erfüllung seiner Aufgaben benachteiligt werden?",
                       ("Nein, Art. 38 Abs. 3 verbietet das", "Ein Datenschutzbeauftragter darf wegen der Erfüllung seiner Aufgaben nicht abberufen oder benachteiligt werden."),
                       ("Ja, wenn der Datenschutzbeauftragte ein Beschäftigter ist", "Der Schutz gilt auch für Datenschutzbeauftragte, die bei dem Unternehmen beschäftigt sind."),
                       ("Ja, wenn die Meldung Kosten verursacht hat", "Kosten heben den Schutz nicht auf.")),
            assessment([0], [5], "Was gehört zu den Aufgaben des Datenschutzbeauftragten?", "Welche Aufgabe weist Art. 39 Abs. 1 dem Datenschutzbeauftragten zu?",
                       ("Die Überwachung der Einhaltung der DSGVO", "Art. 39 Abs. 1 Buchst. b."),
                       ("Die Festlegung der Zwecke der Verarbeitung", "Das ist die Rolle des Verantwortlichen."),
                       ("Die Verhängung von Geldbußen gegen das Unternehmen", "Geldbußen verhängen die Aufsichtsbehörden.")),
        ],
    },
    "O08": {
        "title": "Abschluss: die Datenschutzprüfung der Bäckerei Sonnenfeld",
        "summary": "Die zentralen Pflichten gemeinsam auf die Bäckerei Sonnenfeld anwenden und herausfinden, was fehlt.",
        "prerequisites": {
            "O01": "Die Prüfung beginnt mit dem Verzeichnis von Verarbeitungstätigkeiten.",
            "O03": "Die Prüfung kontrolliert die Verträge mit den Auftragsverarbeitern.",
            "O05": "Die Prüfung enthält ein Szenario mit einer Datenpanne.",
            "O06": "Die Prüfung entscheidet, ob eine Datenschutz-Folgenabschätzung nötig ist.",
        },
        "sources": [("GDPR", "Art. 5, 6, 13, 22, 28, 30, 33, 34, 35")],
        "screens": [
            [
                "Diese Abschlusslektion wendet die Module 0 bis 3 auf ein einziges erfundenes Unternehmen an. Lesen Sie jeden Schritt, und prüfen Sie ihn anhand dessen, was Sie gelernt haben.",
                {"type": "callout", "tone": "note", "text": "**Die Bäckerei Sonnenfeld ist für diesen Kurs erfunden.** Das Szenario ist eine Veranschaulichung und keine Vorlage für eine echte Prüfung."},
            ],
            [
                "**Schritt 1, das Verzeichnis** (Art. 30): Die Bäckerei Sonnenfeld verarbeitet regelmäßig Daten, darunter Gesundheitsdaten. Deshalb führt sie ein Verzeichnis. Es nennt sechs Tätigkeiten: Vorbestellungen, Kundenkarte, Newsletter, Kameras, Lohnabrechnung und Bewerbungsverfahren, jeweils mit Zwecken, Datenkategorien, Empfängern, Löschfristen und Sicherheitsmaßnahmen.",
            ],
            [
                "**Schritt 2, Rechtsgrundlagen und Datenschutzhinweise** (Art. 6 und 13):",
                {"type": "list", "items": [
                    "Vorbestellungen: Vertrag;",
                    "Newsletter: Einwilligung;",
                    "Kameras im Verkaufsraum: berechtigte Interessen, nach der Abwägung;",
                    "Lohnabrechnung: rechtliche Verpflichtung, im Übrigen Vertrag.",
                ]},
                "Jede Tätigkeit ist in Datenschutzhinweisen beschrieben, die die Menschen zum Zeitpunkt der Erhebung erhalten.",
            ],
            [
                "**Schritt 3, Auftragsverarbeiter** (Art. 28): Der App-Hoster, der Newsletter-Dienst und der Lohnabrechnungsdienstleister verarbeiten jeweils Daten im Auftrag der Bäckerei Sonnenfeld.",
                "Die Prüfung ergibt, dass für den Newsletter-Dienst keine schriftlichen Vertragsbedingungen zur Auftragsverarbeitung vorliegen. Das ist eine Lücke: Erforderlich ist ein Vertrag mit den Inhalten nach Art. 28 Abs. 3.",
            ],
            [
                "**Schritt 4, eine Übung zu einer Datenpanne** (Art. 33 und 34): Der Lohnabrechnungsdienstleister meldet einen Ransomware-Angriff, der Gehaltsdateien zerstört hat. Der Bäckerei wird das am **Freitag um 18:00 Uhr** bekannt.",
                "Die Bäckerei meldet die Verletzung der Aufsichtsbehörde möglichst bis **Montag um 18:00 Uhr**, also binnen 72 Stunden, es sei denn, sie führt voraussichtlich nicht zu einem Risiko. Einzelheiten können schrittweise folgen. In jedem Fall dokumentiert die Bäckerei die Verletzung und prüft, ob den Beschäftigten ein hohes Risiko droht.",
            ],
            [
                "**Schritt 5, ein neues Projekt** (Art. 22 und 35): Die Bäckerei Sonnenfeld möchte eine Software einsetzen, die Bewerberinnen und Bewerber mit niedriger Punktzahl automatisch ablehnt.",
                "Das ist ein Fall für eine Datenschutz-Folgenabschätzung nach Art. 35 Abs. 3 Buchst. a und eine ausschließlich auf einer automatisierten Verarbeitung beruhende Entscheidung nach Art. 22. Die Bäckerei muss zuerst die Folgenabschätzung abschließen. Außerdem muss sie entweder eine echte menschliche Prüfung beibehalten oder eine Ausnahme nach Art. 22 Abs. 2 erfüllen und die angemessenen Maßnahmen nach Art. 22 Abs. 3 treffen.",
            ],
        ],
        "questions": [
            assessment([0], [5], "Der Bäckerei Sonnenfeld wird die Datenpanne bei ihrem Lohnabrechnungsdienstleister am Freitag um 18:00 Uhr bekannt. Bis wann sollte sie die Verletzung, falls eine Meldung erforderlich ist, der Aufsichtsbehörde möglichst melden?", "Die Bäckerei Sonnenfeld hat am Freitag um 18:00 Uhr von einer meldepflichtigen Verletzung erfahren. Bis wann sollte sie die Verletzung der Aufsichtsbehörde möglichst melden?",
                       ("Bis Montag um 18:00 Uhr", "72 Stunden, nachdem ihr die Verletzung bekannt wurde (Art. 33 Abs. 1)."),
                       ("Innerhalb eines Monats", "Ein Monat ist die Frist für die Antwort auf Anträge betroffener Personen."),
                       ("Erst wenn alle Einzelheiten bekannt sind", "Die Informationen können schrittweise zur Verfügung gestellt werden (Art. 33 Abs. 4).")),
            assessment([0], [4], "Die Prüfung der Bäckerei Sonnenfeld ergibt, dass für ihren Newsletter-Dienst keine schriftlichen Vertragsbedingungen zur Auftragsverarbeitung vorliegen. Was fehlt?", "Welches Dokument fehlt laut der Datenschutzprüfung der Bäckerei Sonnenfeld für den Newsletter-Dienst, der für sie als Auftragsverarbeiter tätig ist?",
                       ("Ein Vertrag mit den Inhalten nach Art. 28 Abs. 3", "Für jeden Auftragsverarbeiter erforderlich."),
                       ("Nichts, weil der Anbieter bekannt ist", "Ein guter Ruf ersetzt keinen Vertrag."),
                       ("Eine Datenschutz-Folgenabschätzung für den Newsletter", "Die festgestellte Lücke ist der Vertrag, nicht eine Folgenabschätzung.")),
            assessment([0], [2], "Welcher Umstand führt dazu, dass die Ausnahme für weniger als 250 Beschäftigte bei der Bäckerei Sonnenfeld nicht greift?", "Warum muss die Bäckerei Sonnenfeld mit ihren 40 Beschäftigten trotzdem ein Verzeichnis nach Art. 30 führen?",
                       ("Ihre Verarbeitung erfolgt nicht nur gelegentlich und umfasst Gesundheitsdaten", "Art. 30 Abs. 5."),
                       ("Sie nutzt eine App", "Eine App zu nutzen ist keine Bedingung nach Art. 30 Abs. 5."),
                       ("Sie hat drei Filialen", "Die Zahl der Filialen ist keine Bedingung.")),
            assessment([0], [6], "Was muss die Bäckerei Sonnenfeld tun, bevor sie Bewerberinnen und Bewerber per Software automatisch ablehnt?", "Was verlangt die Datenschutzprüfung der Bäckerei Sonnenfeld, bevor ihr Projekt zur automatischen Ablehnung von Bewerbungen beginnt?",
                       ("Eine Datenschutz-Folgenabschätzung durchführen und Art. 22 einhalten", "Art. 35 Abs. 3 Buchst. a und Art. 22."),
                       ("Nichts, weil die Personalauswahl eine interne Angelegenheit ist", "Bewerberinnen und Bewerber sind betroffene Personen mit Rechten."),
                       ("Nur die Datenschutzhinweise aktualisieren", "Hinweise allein erfüllen Art. 22 und 35 nicht.")),
        ],
    },
}
