"""Modul 2 (deutsche Ausgabe): die Rechte der Menschen. Übersetzung von lesson_content_m2.py; die Bäckerei Sonnenfeld ist erfunden."""

from lesson_builder import assessment

ILLUSTRATION = {"type": "callout", "tone": "note", "text": "Diese Beispiele mit der Bäckerei Sonnenfeld sind **Veranschaulichungen**. Eine echte Beurteilung hängt von allen Umständen ab."}

LESSONS = {
    "R01": {
        "title": "Was Sie den Menschen mitteilen müssen",
        "summary": "Datenschutzhinweise auf die Angaben prüfen, die Art. 13 und 14 verlangen, und sie zum richtigen Zeitpunkt geben.",
        "prerequisites": {
            "G01": "Die Datenschutzhinweise müssen den Menschen sagen, dass sie sich bei der Aufsichtsbehörde beschweren können.",
            "G05": "Der Verantwortliche gibt die Datenschutzhinweise und muss darin angeben, wer er ist.",
            "P01": "Die Informationspflichten setzen den Grundsatz der Transparenz in die Praxis um.",
            "P04": "Die Datenschutzhinweise müssen die Rechtsgrundlage nennen, deshalb müssen Lernende die Rechtsgrundlagen kennen.",
        },
        "sources": [("GDPR", "Art. 12 Abs. 1, 13, 14")],
        "screens": [
            [
                "Wenn Sie personenbezogene Daten **bei der Person selbst** erheben, müssen Sie ihr bestimmte Informationen **zum Zeitpunkt der Erhebung** mitteilen (Art. 13 Abs. 1). Diese Informationen heißen meist Datenschutzhinweise.",
                "Die Kernangaben (Art. 13 Abs. 1):",
                {"type": "list", "items": [
                    "Ihr Name und Ihre Kontaktdaten sowie gegebenenfalls die Kontaktdaten Ihres Datenschutzbeauftragten;",
                    "die **Zwecke** und die **Rechtsgrundlage** der Verarbeitung sowie die berechtigten Interessen, wenn Sie sich auf diese stützen;",
                    "die Empfänger oder Kategorien von Empfängern;",
                    "ob Daten in ein Land außerhalb der EU gehen sollen und unter welchen Bedingungen.",
                ]},
            ],
            [
                "Weitere Angaben (Art. 13 Abs. 2):",
                {"type": "list", "items": [
                    "wie lange die Daten gespeichert werden oder nach welchen Kriterien sich diese Dauer richtet;",
                    "die Rechte der Person: Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Widerspruch und Datenübertragbarkeit;",
                    "das Recht, die Einwilligung zu widerrufen, wenn die Verarbeitung auf einer Einwilligung beruht;",
                    "das Recht, **sich bei einer Aufsichtsbehörde zu beschweren**;",
                    "ob die Bereitstellung der Daten gesetzlich oder vertraglich vorgeschrieben ist und welche Folgen es hätte, wenn die Person sie nicht bereitstellt;",
                    "jede automatisierte Entscheidungsfindung der Art, die später in diesem Modul behandelt wird, mit aussagekräftigen Informationen über die involvierte Logik.",
                ]},
            ],
            [
                "**Wie** Sie informieren: „in präziser, transparenter, verständlicher und leicht zugänglicher Form in einer klaren und einfachen Sprache“, insbesondere bei Informationen, die sich an Kinder richten (Art. 12 Abs. 1).",
                "Das kann schriftlich oder in anderer Form geschehen, auch elektronisch. Ein langer juristischer Text, den niemand versteht, erfüllt Art. 12 Abs. 1 nicht.",
            ],
            [
                "Stammen die Daten **aus einer anderen Quelle**, gilt Art. 14. Die Liste ist ähnlich, mit zwei Ergänzungen: die **Kategorien** personenbezogener Daten, die verarbeitet werden (Art. 14 Abs. 1 Buchst. d), und die **Quelle** der Daten, einschließlich der Angabe, ob sie aus öffentlich zugänglichen Quellen stammen (Art. 14 Abs. 2 Buchst. f).",
            ],
            [
                "Der **Zeitpunkt** nach Art. 14 Abs. 3, je nachdem, was zuerst eintritt:",
                {"type": "list", "items": [
                    "innerhalb einer angemessenen Frist nach Erlangung der Daten, **längstens jedoch innerhalb eines Monats**;",
                    "spätestens zum Zeitpunkt der **ersten Mitteilung** an die Person, wenn die Daten verwendet werden, um mit ihr Kontakt aufzunehmen;",
                    "spätestens zum Zeitpunkt der **ersten Offenlegung**, wenn die Daten einem anderen Empfänger offengelegt werden sollen.",
                ]},
            ],
            [
                "**Ausnahmen**: Eine Information ist nicht nötig, wenn und soweit die Person bereits über die Informationen verfügt (Art. 13 Abs. 4 und 14 Abs. 5 Buchst. a).",
                "Für Daten aus einer anderen Quelle gibt es wenige, eng begrenzte weitere Ausnahmen: wenn die Information unmöglich ist oder einen unverhältnismäßigen Aufwand erfordern würde (dann mit Schutzmaßnahmen, etwa indem die Informationen öffentlich bereitgestellt werden), wenn Rechtsvorschriften der EU oder eines EU-Staats die Erlangung oder Offenlegung der Daten ausdrücklich regeln, oder wenn ein Berufsgeheimnis gilt (Art. 14 Abs. 5).",
            ],
            [
                "Die Bäckerei Sonnenfeld zeigt bei der Registrierung in ihrer App kurze Datenschutzhinweise und verlinkt auf die vollständige Fassung. Das ist ein Fall von Art. 13.",
                "Die Bäckerei erhält außerdem Lebensläufe von Bewerberinnen und Bewerbern über eine Personalvermittlung. Das ist ein Fall von Art. 14: Sie muss jede Bewerberin und jeden Bewerber längstens innerhalb eines Monats informieren, oder früher, wenn sie vorher Kontakt mit ihnen aufnimmt.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1, 2], "Welche Angabe müssen die Datenschutzhinweise enthalten, wenn die Bäckerei Sonnenfeld Daten bei einer Kundin erhebt?", "Welche dieser Angaben gehört in Datenschutzhinweise nach Art. 13?",
                       ("Die Zwecke und die Rechtsgrundlage", "Art. 13 Abs. 1 Buchst. c."),
                       ("Die Namen aller Beschäftigten der Bäckerei Sonnenfeld", "Das verlangt Art. 13 nicht."),
                       ("Der Jahresumsatz der Bäckerei Sonnenfeld", "Das verlangt Art. 13 nicht.")),
            assessment([0], [1, 3], "Wann müssen die Informationen nach Art. 13 erteilt werden?", "Zu welchem Zeitpunkt verlangt Art. 13 die Information der Person?",
                       ("Zum Zeitpunkt der Erhebung der Daten", "Art. 13 Abs. 1: zum Zeitpunkt der Erhebung."),
                       ("Innerhalb eines Monats nach der Erhebung", "Das ist die Regel des Art. 14 für Daten aus einer anderen Quelle."),
                       ("Nur wenn die Kundin oder der Kunde danach fragt", "Art. 13 verlangt die Information, ohne dass jemand danach fragen muss.")),
            assessment([1], [5, 7], "Die Bäckerei Sonnenfeld erhält über eine Personalvermittlung einen Lebenslauf und schreibt der Bewerberin zwei Wochen später zum ersten Mal eine E-Mail. Wann muss sie die Bewerberin nach Art. 14 informieren?", "Eine Personalvermittlung schickt der Bäckerei Sonnenfeld einen Lebenslauf. Zwei Wochen später schreibt die Bäckerei der Bewerberin zum ersten Mal eine E-Mail. Wann muss sie die Bewerberin spätestens informieren?",
                       ("Spätestens mit der ersten E-Mail, längstens innerhalb eines Monats", "Art. 14 Abs. 3: bei der ersten Mitteilung, längstens jedoch innerhalb eines Monats."),
                       ("Nur wenn sie fragt, welche Daten die Bäckerei über sie hat", "Art. 14 verlangt die Information, ohne dass jemand danach fragen muss."),
                       ("Wenn sie bei der Bäckerei zu arbeiten beginnt", "Art. 14 Abs. 3 setzt frühere Fristen.")),
            assessment([1], [4], "Welche Angabe fügt Art. 14 der Liste des Art. 13 hinzu?", "Was müssen Datenschutzhinweise für Daten, die aus einer anderen Quelle stammen, zusätzlich angeben?",
                       ("Woher die Daten stammen", "Art. 14 Abs. 2 Buchst. f verlangt die Quelle."),
                       ("Die private Telefonnummer der Person, die die Daten geliefert hat", "Das verlangt Art. 14 nicht."),
                       ("Die Steuernummer der Bäckerei Sonnenfeld", "Das verlangt Art. 14 nicht.")),
        ],
    },
    "R02": {
        "title": "Einen Antrag auf Wahrnehmung der Rechte bearbeiten",
        "summary": "Einen Antrag auf Wahrnehmung der Rechte fristgerecht beantworten und die Regeln zu Entgelt, Weigerung und Identitätsprüfung richtig anwenden.",
        "prerequisites": {
            "G01": "Wer auf einen Antrag nicht tätig wird, muss die Person darauf hinweisen, dass sie sich bei der Aufsichtsbehörde beschweren kann.",
            "G05": "Die Fristen sind Pflichten des Verantwortlichen.",
        },
        "sources": [("GDPR", "Art. 12 Abs. 2 bis 6")],
        "screens": [
            [
                "Artikel 15 bis 22 geben den Menschen Rechte: Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch, dazu Schutz vor bestimmten automatisierten Entscheidungen. Die nächsten Lektionen behandeln jedes dieser Rechte.",
                "Artikel 12 regelt das Verfahren für alle diese Rechte. Zunächst muss der Verantwortliche der Person die Ausübung ihrer Rechte **erleichtern** (Art. 12 Abs. 2).",
            ],
            [
                "**Frist**: Reagieren Sie auf einen Antrag **unverzüglich**, in jedem Fall aber **innerhalb eines Monats** nach Eingang des Antrags (Art. 12 Abs. 3).",
                "Die Frist kann „um weitere zwei Monate verlängert werden, wenn dies unter Berücksichtigung der Komplexität und der Anzahl von Anträgen erforderlich ist“. Die Person muss innerhalb eines Monats nach Eingang des Antrags über die Fristverlängerung informiert werden, zusammen mit den Gründen für die Verzögerung.",
                "Wurde der Antrag elektronisch gestellt, antworten Sie nach Möglichkeit auf elektronischem Weg, sofern die Person nichts anderes angibt.",
            ],
            [
                "Werden Sie auf einen Antrag hin **nicht tätig**, müssen Sie die Person ohne Verzögerung, spätestens aber innerhalb eines Monats nach Eingang des Antrags informieren (Art. 12 Abs. 4). Nennen Sie:",
                {"type": "list", "items": ["die Gründe dafür;", "ihr Recht, sich bei einer Aufsichtsbehörde zu beschweren;", "ihr Recht, einen gerichtlichen Rechtsbehelf einzulegen."]},
            ],
            [
                "**Unentgeltlich**: Die Bearbeitung von Anträgen kostet nichts (Art. 12 Abs. 5).",
                "Nur bei **offenkundig unbegründeten oder exzessiven** Anträgen, insbesondere im Fall von häufiger Wiederholung, darf der Verantwortliche ein angemessenes Entgelt verlangen oder sich weigern, tätig zu werden. Er muss nachweisen können, dass der Antrag offenkundig unbegründet oder exzessiv ist.",
            ],
            [
                "**Identität**: Haben Sie **begründete Zweifel** daran, wer einen Antrag stellt, dürfen Sie die zusätzlichen Informationen anfordern, die zur Bestätigung der Identität erforderlich sind (Art. 12 Abs. 6).",
                "Fragen Sie nur nach dem, was zur Bestätigung der Identität nötig ist, und nur, wenn Sie begründete Zweifel haben.",
            ],
            [
                "Eine Kundin schreibt der Bäckerei Sonnenfeld am **10. März** eine E-Mail und fragt, welche Daten die Bäckerei über sie hat. Die Antwort ist bis zum **10. April** fällig.",
                "Ist der Antrag tatsächlich komplex, darf die Bäckerei die Frist um bis zu zwei weitere Monate verlängern. Sie muss die Kundin aber bis zum 10. April darüber informieren und die Gründe nennen.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [2, 6], "Ein Antrag geht am 10. März ein. Bis wann muss die Antwort ohne Fristverlängerung spätestens erfolgen?", "Die Bäckerei Sonnenfeld erhält am 10. März den Antrag einer Kundin auf Wahrnehmung ihrer Rechte. Wann endet die reguläre Frist von einem Monat?",
                       ("10. April", "Art. 12 Abs. 3: innerhalb eines Monats nach Eingang des Antrags."),
                       ("10. Juni, weil die DSGVO drei Monate erlaubt", "Drei Monate sind nur mit einer mitgeteilten Fristverlängerung möglich."),
                       ("Wann es passt, sobald der Eingang bestätigt ist", "Eine Eingangsbestätigung hält die Frist nicht an.")),
            assessment([0], [2], "Ein Antrag ist ungewöhnlich komplex. Wie kann die Bäckerei Sonnenfeld mehr Zeit bekommen?", "Was erlaubt Art. 12 Abs. 3, wenn die Bearbeitung eines Antrags mehr Zeit braucht?",
                       ("Bis zu zwei weitere Monate, wenn die Person innerhalb des ersten Monats mit Gründen informiert wird", "Art. 12 Abs. 3."),
                       ("So lange wie nötig, ohne jemanden zu informieren", "Verlängerungen sind begrenzt und müssen mitgeteilt werden."),
                       ("Sechs weitere Monate, wenn das Unternehmen klein ist", "Eine solche Regel kennt die DSGVO nicht.")),
            assessment([1], [4], "Darf die Bäckerei Sonnenfeld 20 EUR dafür verlangen, den ersten, gewöhnlichen Auskunftsantrag einer Kundin zu bearbeiten?", "Darf ein Unternehmen für einen gewöhnlichen Antrag einer Person auf Wahrnehmung ihrer Rechte ein Entgelt verlangen?",
                       ("Nein, die Bearbeitung muss unentgeltlich sein", "Art. 12 Abs. 5: unentgeltlich, außer bei offenkundig unbegründeten oder exzessiven Anträgen."),
                       ("Ja, eine Bearbeitungsgebühr ist immer erlaubt", "Ein Entgelt ist nur bei offenkundig unbegründeten oder exzessiven Anträgen möglich."),
                       ("Ja, wenn der Antrag per Post kommt", "Der Übermittlungsweg begründet kein Recht auf ein Entgelt.")),
            assessment([1], [5], "Ein Antrag kommt von einer unbekannten E-Mail-Adresse, und die Bäckerei Sonnenfeld zweifelt, ob er wirklich von der Kundin stammt. Was darf sie tun?", "Was erlaubt Art. 12 Abs. 6, wenn begründete Zweifel an der Identität der antragstellenden Person bestehen?",
                       ("Die Informationen anfordern, die zur Bestätigung der Identität erforderlich sind", "Art. 12 Abs. 6."),
                       ("Den Antrag einfach ignorieren", "Der Verantwortliche muss tätig werden oder erklären, warum er es nicht tut."),
                       ("Von allen Antragstellenden eine Kopie des Reisepasses verlangen", "Nur erforderliche Informationen, und nur bei begründeten Zweifeln.")),
        ],
    },
    "R03": {
        "title": "Das Auskunftsrecht",
        "summary": "Sagen können, was eine vollständige Antwort auf einen Auskunftsantrag enthält, einschließlich der Kopie und der Grenzen, die andere Menschen schützen.",
        "prerequisites": {"R02": "Ein Auskunftsantrag wird innerhalb der Frist nach Art. 12 beantwortet."},
        "sources": [("GDPR", "Art. 12 Abs. 5, 15")],
        "screens": [
            [
                "Das **Auskunftsrecht** (Art. 15 Abs. 1) hat zwei Teile. Eine Person kann verlangen:",
                {"type": "list", "items": ["eine **Bestätigung** darüber, ob personenbezogene Daten über sie verarbeitet werden; und", "wenn das der Fall ist, **Auskunft** über diese Daten sowie bestimmte Informationen."]},
                "Nach der DSGVO muss die Person dafür keinen Grund nennen.",
            ],
            [
                "Die Informationen, die Sie geben müssen (Art. 15 Abs. 1 Buchst. a bis h):",
                {"type": "list", "items": [
                    "die Verarbeitungszwecke, die Kategorien der Daten und die Empfänger, insbesondere Empfänger außerhalb der EU;",
                    "wie lange die Daten gespeichert werden oder nach welchen Kriterien sich diese Dauer richtet;",
                    "die Rechte auf Berichtigung, Löschung oder Einschränkung der Verarbeitung sowie das Widerspruchsrecht;",
                    "das Recht, sich bei einer Aufsichtsbehörde zu beschweren;",
                    "die Herkunft der Daten, wenn sie nicht bei der Person erhoben wurden;",
                    "jede automatisierte Entscheidungsfindung, die eine spätere Lektion behandelt, mit aussagekräftigen Informationen über die involvierte Logik.",
                ]},
                "Wurden Daten in ein Land außerhalb der EU übermittelt, hat die Person außerdem das Recht, über die geeigneten Garantien unterrichtet zu werden (Art. 15 Abs. 2).",
            ],
            [
                "**Die Kopie**: Der Verantwortliche muss eine Kopie der personenbezogenen Daten zur Verfügung stellen, die er verarbeitet (Art. 15 Abs. 3). Die erste Kopie ist unentgeltlich (Art. 12 Abs. 5).",
                "Für **alle weiteren Kopien** darf er ein angemessenes Entgelt auf der Grundlage der Verwaltungskosten verlangen. Wurde der Antrag elektronisch gestellt, wird die Kopie in einem gängigen elektronischen Format zur Verfügung gestellt, sofern die Person nichts anderes angibt.",
            ],
            [
                "**Schutz anderer Menschen**: Das Recht auf Erhalt einer Kopie „darf die Rechte und Freiheiten anderer Personen nicht beeinträchtigen“ (Art. 15 Abs. 4).",
                "Das ist kein Grund, alles zu verweigern. Es ist ein Grund, die Daten anderer Menschen innerhalb der Kopie zu schützen.",
            ],
            [
                "Eine Kundin fragt die Bäckerei Sonnenfeld: »Was haben Sie über mich gespeichert?« Die Bäckerei bestätigt, dass sie Daten über sie verarbeitet. Sie schickt ihr ihre Kontodaten, ihren Bestellverlauf, ihre Treuepunkte und den Nachweis ihrer Newsletter-Anmeldung, zusammen mit den Informationen nach Art. 15.",
                "Die Kundin verlangt auch die Kameraaufnahmen ihres Besuchs. Darauf sind andere Kundinnen und Kunden zu sehen. Die Bäckerei schützt diese Menschen, zum Beispiel indem sie sie in der Kopie unkenntlich macht.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1, 2], "Eine Kundin fragt die Bäckerei Sonnenfeld, ob die Bäckerei Daten über sie hat. Was verlangt Art. 15 zuerst?", "Eine Kundin fragt die Bäckerei Sonnenfeld, welche Daten die Bäckerei über sie hat. Was muss die Bäckerei nach Art. 15 zuerst tun?",
                       ("Bestätigen, ob ihre Daten verarbeitet werden, und dann Auskunft und Informationen geben", "Art. 15 Abs. 1."),
                       ("Eine kurze Zusammenfassung schicken, ohne jede Kopie", "Art. 15 Abs. 3 verlangt eine Kopie der Daten."),
                       ("Nichts, bis sie ihren Grund erklärt", "Art. 15 verlangt keinen Grund.")),
            assessment([0], [3], "Nach einer unentgeltlichen ersten Kopie verlangt die Kundin eine zweite Kopie. Was darf die Bäckerei Sonnenfeld tun?", "Eine Person hat ihre erste Kopie bereits erhalten. Was erlaubt Art. 15 Abs. 3, wenn sie weitere Kopien verlangt?",
                       ("Ein angemessenes Entgelt auf der Grundlage der Verwaltungskosten verlangen", "Art. 15 Abs. 3 erlaubt das für weitere Kopien."),
                       ("Auch für die erste Kopie ein Entgelt verlangen", "Die erste Kopie ist unentgeltlich (Art. 12 Abs. 5)."),
                       ("Jede Kopie ausnahmslos unentgeltlich zur Verfügung stellen", "Art. 15 Abs. 3 erlaubt ein Entgelt für weitere Kopien.")),
            assessment([0], [4, 5], "Kameraaufnahmen, die eine Kundin verlangt, zeigen auch andere Menschen. Was sollte die Bäckerei Sonnenfeld tun?", "Eine Kopie, die eine Kundin verlangt, enthält auch Daten anderer Menschen. Was folgt daraus nach Art. 15 Abs. 4?",
                       ("Die Kopie herausgeben und dabei die anderen Menschen schützen, etwa durch Unkenntlichmachen", "Art. 15 Abs. 4 schützt andere Menschen, ohne das Recht aufzuheben."),
                       ("Den ganzen Antrag automatisch ablehnen", "Art. 15 Abs. 4 ist kein pauschaler Ablehnungsgrund."),
                       ("Die Kopie unbearbeitet herausgeben", "Das könnte die Rechte anderer Menschen beeinträchtigen.")),
            assessment([0], [2], "Welche Angabe muss eine Antwort auf einen Auskunftsantrag enthalten?", "Was muss die Bäckerei Sonnenfeld einer Person, die Auskunft verlangt, nach Art. 15 Abs. 1 neben den Daten selbst mitteilen?",
                       ("Die Verarbeitungszwecke", "Art. 15 Abs. 1 Buchst. a."),
                       ("Die internen IT-Passwörter der Bäckerei Sonnenfeld", "Sie gehören nicht zur Auskunft und müssen sicher bleiben."),
                       ("Eine Liste aller Kundinnen und Kunden der Bäckerei Sonnenfeld", "Damit würden Daten anderer Menschen offengelegt.")),
        ],
    },
    "R04": {
        "title": "Berichtigung und Löschung",
        "summary": "Die Rechte auf Berichtigung und Löschung anwenden und erkennen, wann das Recht auf Löschung nicht gilt.",
        "prerequisites": {
            "P02": "Mit der Berichtigung kann jede Person selbst den Grundsatz der Richtigkeit durchsetzen.",
            "P05": "Ein Löschungsgrund ist der Widerruf der Einwilligung, wenn es keine andere Rechtsgrundlage gibt.",
            "R02": "Anträge auf Berichtigung folgen dem Verfahren nach Art. 12.",
        },
        "sources": [("GDPR", "Art. 16, 17")],
        "screens": [
            [
                "**Berichtigung** (Art. 16): Eine Person kann verlangen, dass **unrichtige** personenbezogene Daten über sie **unverzüglich** berichtigt werden.",
                "Sie kann außerdem verlangen, dass **unvollständige** Daten unter Berücksichtigung der Zwecke der Verarbeitung vervollständigt werden, auch mittels einer ergänzenden Erklärung.",
            ],
            [
                "**Löschung** (Art. 17 Abs. 1), oft „Recht auf Vergessenwerden“ genannt: Der Verantwortliche muss Daten unverzüglich löschen, wenn einer dieser Gründe zutrifft:",
                {"type": "list", "items": [
                    "a) die Daten sind für ihre Zwecke nicht mehr notwendig;",
                    "b) die Person widerruft ihre Einwilligung, und es fehlt an einer anderweitigen Rechtsgrundlage;",
                    "c) die Person legt Widerspruch ein (ein Recht, das eine spätere Lektion behandelt), und es liegen keine vorrangigen berechtigten Gründe vor, oder sie widerspricht der Direktwerbung;",
                    "d) die Daten wurden unrechtmäßig verarbeitet;",
                    "e) eine rechtliche Verpflichtung verlangt die Löschung;",
                    "f) die Daten wurden bei einem Kind für einen Online-Dienst nach Art. 8 Abs. 1 erhoben.",
                ]},
            ],
            [
                "Das Recht auf Löschung **gilt nicht**, soweit die Verarbeitung erforderlich ist (Art. 17 Abs. 3):",
                {"type": "list", "items": [
                    "zur Ausübung des Rechts auf freie Meinungsäußerung und Information;",
                    "zur Erfüllung einer **rechtlichen Verpflichtung** oder zur Wahrnehmung einer öffentlichen Aufgabe;",
                    "aus Gründen der öffentlichen Gesundheit;",
                    "für im öffentlichen Interesse liegende Archivzwecke, für Forschung oder für Statistik, wenn die Löschung diese Zwecke ernsthaft beeinträchtigen würde;",
                    "zur Geltendmachung, Ausübung oder Verteidigung von **Rechtsansprüchen**.",
                ]},
            ],
            [
                "Hat der Verantwortliche die Daten öffentlich gemacht und muss er sie löschen, trifft er unter Berücksichtigung der verfügbaren Technologie und der Implementierungskosten angemessene Maßnahmen. Damit informiert er andere Verantwortliche, die die Daten verarbeiten, dass die Person die Löschung aller Links zu den Daten und aller Kopien verlangt hat (Art. 17 Abs. 2).",
            ],
            [
                "Eine ehemalige Kundin bittet die Bäckerei Sonnenfeld, alles über sie zu löschen. Die Bäckerei löscht ihr Kundenkonto und ihre Newsletter-Daten.",
                "Ihre Rechnungen behält die Bäckerei, wenn eine rechtliche Verpflichtung, etwa aus dem nationalen Buchführungsrecht, die Aufbewahrung verlangt. Dieser Teil fällt unter Art. 17 Abs. 3 Buchst. b. Die Bäckerei teilt der Kundin mit, welche Daten sie behalten hat und warum.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "Der Nachname einer Kundin ist im System der Bäckerei Sonnenfeld falsch geschrieben. Was verlangt Art. 16?", "Wie schnell müssen unrichtige personenbezogene Daten berichtigt werden, wenn die Person das verlangt?",
                       ("Unverzüglich berichtigen", "Art. 16."),
                       ("Bei der nächsten jährlichen Prüfung berichtigen", "Das ist nicht unverzüglich."),
                       ("Nur berichtigen, wenn der Fehler einen Schaden verursacht hat", "Art. 16 knüpft die Berichtigung nicht an einen Schaden.")),
            assessment([1], [2], "Eine Kundin widerruft ihre Einwilligung in den Newsletter und verlangt, dass die Bäckerei Sonnenfeld ihre Newsletter-Daten löscht. Für nichts anderes werden die Daten gebraucht. Was gilt?", "Eine Kundin widerruft ihre Einwilligung, und für ihre Daten gibt es keine andere Rechtsgrundlage. Was geschieht mit den Daten?",
                       ("Sie werden gelöscht, nach Art. 17 Abs. 1 Buchst. b", "Die Einwilligung ist widerrufen, und es fehlt an einer anderweitigen Rechtsgrundlage."),
                       ("Sie bleiben gespeichert, weil die Einwilligung bei ihrer Erteilung wirksam war", "Der Widerruf löst zusammen mit der fehlenden anderen Rechtsgrundlage die Löschung aus."),
                       ("Sie bleiben gespeichert, bis sich die Kundin bei einer Aufsichtsbehörde beschwert", "Die Daten sind unverzüglich zu löschen.")),
            assessment([1], [3, 5], "Eine Kundin verlangt, dass alle ihre Rechnungen gelöscht werden, aber ein Gesetz verpflichtet die Bäckerei Sonnenfeld, Buchführungsunterlagen aufzubewahren. Was folgt daraus?", "Wie wirkt sich eine gesetzliche Pflicht, Unterlagen aufzubewahren, auf das Recht auf Löschung aus?",
                       ("Diese Unterlagen dürfen nach Art. 17 Abs. 3 Buchst. b aufbewahrt werden", "Das Recht auf Löschung gilt nicht, soweit die Verarbeitung zur Erfüllung einer rechtlichen Verpflichtung erforderlich ist."),
                       ("Trotzdem muss alles gelöscht werden", "Art. 17 Abs. 3 Buchst. b ist eine Ausnahme."),
                       ("Der ganze Antrag darf abgelehnt werden, auch für die Werbedaten", "Die Ausnahme erfasst nur, was die Verpflichtung verlangt.")),
        ],
    },
    "R05": {
        "title": "Einschränkung der Verarbeitung und Mitteilung an Empfänger",
        "summary": "Die Einschränkung der Verarbeitung in den vier genannten Fällen nutzen und Empfänger über Berichtigungen, Löschungen und Einschränkungen informieren.",
        "prerequisites": {"R04": "Die Einschränkung greift, während die Richtigkeit überprüft wird."},
        "sources": [("GDPR", "Art. 4 Nr. 3, 18, 19")],
        "screens": [
            [
                "**Einschränkung der Verarbeitung** ist „die Markierung gespeicherter personenbezogener Daten mit dem Ziel, ihre künftige Verarbeitung einzuschränken“ (Art. 4 Nr. 3).",
                "Stellen Sie sich das als Pause vor: Die Daten bleiben gespeichert, werden aber nicht verwendet.",
            ],
            [
                "Eine Person kann die Einschränkung in vier Fällen verlangen (Art. 18 Abs. 1):",
                {"type": "list", "items": [
                    "a) sie **bestreitet die Richtigkeit** der Daten, und zwar für die Dauer, die die Überprüfung braucht;",
                    "b) die Verarbeitung ist unrechtmäßig, und sie verlangt die Einschränkung **statt der Löschung**;",
                    "c) der Verantwortliche braucht die Daten nicht mehr, die Person braucht sie aber für **Rechtsansprüche**;",
                    "d) sie hat **Widerspruch eingelegt**, und es steht noch nicht fest, ob die berechtigten Gründe des Verantwortlichen gegenüber ihren Gründen überwiegen.",
                ]},
            ],
            [
                "Solange die Verarbeitung eingeschränkt ist, darf der Verantwortliche die Daten **speichern**. Jede andere Verarbeitung braucht die Einwilligung der Person oder muss der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen, dem Schutz der Rechte einer anderen Person oder einem wichtigen öffentlichen Interesse dienen (Art. 18 Abs. 2).",
                "Die Person muss informiert werden, bevor die Einschränkung aufgehoben wird (Art. 18 Abs. 3).",
            ],
            [
                "**Mitteilung an Empfänger** (Art. 19): Der Verantwortliche teilt jede Berichtigung, Löschung oder Einschränkung **allen Empfängern** mit, denen die Daten offengelegt wurden, es sei denn, dies erweist sich als unmöglich oder ist mit einem unverhältnismäßigen Aufwand verbunden.",
                "Verlangt die Person es, muss der Verantwortliche ihr sagen, wer diese Empfänger sind.",
            ],
            [
                "Eine Kundin bestreitet den Eintrag der Bäckerei Sonnenfeld, nach dem sie ihre Treuepunkte eingelöst hat. Während die Bäckerei das prüft, markiert sie den Eintrag als eingeschränkt und verwendet ihn nicht für Werbeaktionen.",
                "Früher hat die Bäckerei die Daten der Kundin für das gemeinsame Bonusprogramm an ein Partnercafé weitergegeben. Als sie den Eintrag berichtigt, informiert sie das Café.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [2, 5], "Eine Kundin bestreitet die Richtigkeit ihres Eintrags. Was kann sie verlangen, während die Bäckerei Sonnenfeld das prüft?", "Was erlaubt Art. 18 Abs. 1 Buchst. a, wenn eine Person die Richtigkeit ihrer Daten bestreitet?",
                       ("Die Einschränkung für die Dauer der Überprüfung", "Art. 18 Abs. 1 Buchst. a."),
                       ("Die sofortige Löschung aller Daten", "Wer die Richtigkeit bestreitet, kann die Einschränkung verlangen, nicht die Löschung."),
                       ("Nichts, bis die Prüfung abgeschlossen ist", "Sie kann die Einschränkung schon während der Prüfung verlangen.")),
            assessment([0], [3], "Die Verarbeitung bestimmter Daten ist eingeschränkt. Was darf die Bäckerei Sonnenfeld ohne Einwilligung der betroffenen Person noch mit ihnen tun?", "Welche Verarbeitung bleibt nach Art. 18 Abs. 2 bei eingeschränkten Daten ohne Weiteres erlaubt?",
                       ("Die Daten speichern", "Die Speicherung ist erlaubt; andere Verwendungen brauchen eine Einwilligung oder einen der genannten Gründe."),
                       ("Die Daten weiter wie bisher verwenden", "Die Einschränkung begrenzt jede Verarbeitung über die Speicherung hinaus."),
                       ("Die Daten sofort löschen", "Bei der Einschränkung bleiben die Daten erhalten. Sie werden nicht gelöscht.")),
            assessment([1], [4, 5], "Die Bäckerei Sonnenfeld berichtigt Daten, die sie an ein Partnercafé weitergegeben hatte. Was muss sie tun?", "Die Bäckerei Sonnenfeld berichtigt die Daten einer Kundin, die sie an ein Partnercafé weitergegeben hatte. Was verlangt Art. 19?",
                       ("Das Café informieren, es sei denn, das ist unmöglich oder unverhältnismäßig aufwendig", "Art. 19."),
                       ("Nichts, weil das Café ein eigenes Unternehmen ist", "Art. 19 erfasst alle Empfänger."),
                       ("Alle Kundinnen und Kunden über die Änderung informieren", "Art. 19 betrifft die Empfänger der Daten dieser Person.")),
            assessment([1], [4], "Nach einer Berichtigung fragt eine Kundin die Bäckerei Sonnenfeld, welche Empfänger darüber informiert wurden. Muss die Bäckerei antworten?", "Eine Kundin fragt, welche Empfänger über die Berichtigung ihrer Daten informiert wurden. Muss die Bäckerei Sonnenfeld ihr das nach Art. 19 sagen?",
                       ("Ja, auf Verlangen muss sie die Kundin darüber unterrichten", "Art. 19 Satz 2."),
                       ("Nein, Empfänger sind vertraulich", "Art. 19 verlangt diese Information, wenn die Person sie verlangt."),
                       ("Nur, wenn die Kundin ein Entgelt zahlt", "Art. 19 sieht kein Entgelt vor.")),
        ],
    },
    "R06": {
        "title": "Datenübertragbarkeit und Widerspruchsrecht",
        "summary": "Entscheiden, wann das Recht auf Datenübertragbarkeit gilt, und mit allgemeinen Widersprüchen und Widersprüchen gegen Direktwerbung umgehen.",
        "prerequisites": {
            "P04": "Die Datenübertragbarkeit setzt eine Verarbeitung auf Grundlage einer Einwilligung oder eines Vertrags voraus.",
            "P06": "Der allgemeine Widerspruch richtet sich gegen eine Verarbeitung, die auf berechtigten Interessen oder einer öffentlichen Aufgabe beruht.",
            "R02": "Widersprüche folgen dem Verfahren nach Art. 12.",
        },
        "sources": [("GDPR", "Art. 20, 21"), ("GDPR-REC", "Erwägungsgründe 68, 70")],
        "screens": [
            [
                "**Datenübertragbarkeit** (Art. 20 Abs. 1): Eine Person kann die personenbezogenen Daten, **die sie bereitgestellt hat**, in einem „strukturierten, gängigen und maschinenlesbaren Format“ erhalten und sie einem anderen Verantwortlichen ohne Behinderung übermitteln. Das gilt nur, wenn:",
                {"type": "list", "items": ["die Verarbeitung auf einer **Einwilligung** oder einem **Vertrag** beruht; und", "die Verarbeitung mithilfe **automatisierter Verfahren** erfolgt."]},
            ],
            [
                "Soweit technisch machbar, kann die Person verlangen, dass die Daten **direkt** einem anderen Verantwortlichen übermittelt werden (Art. 20 Abs. 2).",
                "Die Datenübertragbarkeit gilt nicht, wenn die Rechtsgrundlage eine öffentliche Aufgabe (Art. 20 Abs. 3) oder eine rechtliche Verpflichtung ist (Erwägungsgrund 68). Die Verantwortlichen müssen keine technisch kompatiblen Systeme übernehmen (Erwägungsgrund 68). Das Recht darf die Rechte und Freiheiten anderer Personen nicht beeinträchtigen (Art. 20 Abs. 4).",
            ],
            [
                "**Widerspruchsrecht** (Art. 21 Abs. 1): Eine Person kann aus Gründen, die sich aus ihrer **besonderen Situation** ergeben, Widerspruch gegen eine Verarbeitung einlegen, die auf einer **öffentlichen Aufgabe oder berechtigten Interessen** beruht.",
                "Der Verantwortliche muss die Verarbeitung dann beenden, es sei denn, er kann **zwingende schutzwürdige Gründe** nachweisen, die die Interessen, Rechte und Freiheiten der Person überwiegen, oder er braucht die Daten für Rechtsansprüche.",
            ],
            [
                "**Direktwerbung** (Art. 21 Abs. 2 und 3): Eine Person kann **jederzeit** Widerspruch einlegen. Dann werden ihre Daten **nicht mehr** für Zwecke der Direktwerbung verarbeitet.",
                "Hier gibt es keine Abwägung, und nach Erwägungsgrund 70 ist der Widerspruch unentgeltlich.",
            ],
            [
                "Die Person muss spätestens zum Zeitpunkt der ersten Kommunikation mit ihr **ausdrücklich** auf das Widerspruchsrecht **hingewiesen** werden, und zwar „in einer verständlichen und von anderen Informationen getrennten Form“ (Art. 21 Abs. 4).",
            ],
            [
                "Beispiele aus der Bäckerei Sonnenfeld:",
                {"type": "list", "items": [
                    "Eine Kundin möchte ihren Vorbestellverlauf als Datei, die sie in eine andere App hochladen kann. Die Daten werden aufgrund eines Vertrags und mithilfe automatisierter Verfahren verarbeitet, also gilt das Recht auf Datenübertragbarkeit.",
                    "Eine Beschäftigte widerspricht einer Kamera, die ihren Arbeitsplatz erfasst und auf berechtigten Interessen beruht. Die Bäckerei muss die Verarbeitung beenden, es sei denn, sie kann zwingende Gründe nachweisen, die die Interessen der Beschäftigten überwiegen.",
                    "Eine Kundin widerspricht den Werbe-E-Mails. Die Bäckerei schickt ihr keine mehr, ohne jede Abwägung.",
                ]},
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1, 2], "Eine Beschäftigte verlangt ihre Lohnsteuerdaten nach dem Recht auf Datenübertragbarkeit. Rechtsgrundlage ist eine rechtliche Verpflichtung. Gilt das Recht auf Datenübertragbarkeit?", "Gilt das Recht auf Datenübertragbarkeit, wenn die Rechtsgrundlage der Verarbeitung eine rechtliche Verpflichtung ist?",
                       ("Nein, es gilt nur bei Einwilligung oder Vertrag", "Art. 20 Abs. 1 Buchst. a und Erwägungsgrund 68."),
                       ("Ja, es gilt für alle personenbezogenen Daten", "Es ist auf Einwilligung oder Vertrag und auf automatisierte Verfahren beschränkt."),
                       ("Ja, wenn die Daten auf Papier geführt werden", "Die Datenübertragbarkeit setzt auch eine automatisierte Verarbeitung voraus.")),
            assessment([0], [1], "In welcher Form müssen Daten nach dem Recht auf Datenübertragbarkeit bereitgestellt werden?", "Welches Format verlangt Art. 20 Abs. 1 für Daten, die eine Person nach dem Recht auf Datenübertragbarkeit erhält?",
                       ("Strukturiert, gängig und maschinenlesbar", "Art. 20 Abs. 1."),
                       ("Als Ausdruck per Post", "Papier ist nicht maschinenlesbar."),
                       ("Als Bildschirmfotos der Kontoseiten", "Bilder sind kein strukturiertes, maschinenlesbares Format.")),
            assessment([1], [4, 6], "Eine Kundin widerspricht den Werbe-E-Mails der Bäckerei Sonnenfeld. Darf die Bäckerei sie weiter schicken, wenn ihr Interesse daran groß ist?", "Eine Kundin hat der Direktwerbung der Bäckerei Sonnenfeld widersprochen. Darf die Bäckerei jetzt ihre eigenen Interessen gegen die der Kundin abwägen?",
                       ("Nein, sie muss die Werbung an die Kundin einstellen", "Art. 21 Abs. 3: keine weitere Verarbeitung für Zwecke der Direktwerbung."),
                       ("Ja, wenn ihr Interesse zwingend ist", "Die Prüfung zwingender Gründe gilt für den allgemeinen Widerspruch, nicht für Werbung."),
                       ("Nur, nachdem die Kundin ihre Gründe erklärt hat", "Ein Widerspruch gegen Werbung braucht keine Begründung.")),
            assessment([1], [3, 6], "Eine Beschäftigte widerspricht einer Kamera an ihrem Arbeitsplatz, die auf berechtigten Interessen beruht. Was muss die Bäckerei Sonnenfeld tun?", "Eine Beschäftigte legt nach Art. 21 Abs. 1 allgemein Widerspruch gegen eine Kamera ein, die auf berechtigten Interessen beruht. Wie muss die Bäckerei Sonnenfeld reagieren?",
                       ("Die Verarbeitung beenden, es sei denn, zwingende Gründe überwiegen die Interessen der Beschäftigten", "Art. 21 Abs. 1."),
                       ("Nichts; der Widerspruch gilt nur für Verarbeitungen auf Grundlage einer Einwilligung", "Art. 21 Abs. 1 betrifft Verarbeitungen auf Grundlage einer öffentlichen Aufgabe oder berechtigter Interessen."),
                       ("Die Verarbeitung sofort beenden, ohne jede mögliche Ausnahme", "Art. 21 Abs. 1 lässt zwingende Gründe und Rechtsansprüche zu.")),
        ],
    },
    "R07": {
        "title": "Profiling und automatisierte Entscheidungen",
        "summary": "Profiling erkennen und die Regeln des Art. 22 für Entscheidungen anwenden, die ausschließlich auf einer automatisierten Verarbeitung beruhen.",
        "prerequisites": {
            "G04": "Profiling ist eine Form der automatisierten Verarbeitung.",
            "P05": "Eine Ausnahme ist die ausdrückliche Einwilligung, die auf den allgemeinen Bedingungen für die Einwilligung aufbaut.",
        },
        "sources": [("GDPR", "Art. 4 Nr. 4, 13 Abs. 2 Buchst. f, 15 Abs. 1 Buchst. h, 22"), ("GDPR-REC", "Erwägungsgrund 71")],
        "screens": [
            [
                "**Profiling** ist jede Art der automatisierten Verarbeitung personenbezogener Daten, mit der **bestimmte persönliche Aspekte** eines Menschen **bewertet** werden (Art. 4 Nr. 4).",
                "Insbesondere geht es darum, Aspekte wie Arbeitsleistung, wirtschaftliche Lage, Gesundheit, persönliche Vorlieben, Interessen, Zuverlässigkeit, Verhalten, Aufenthaltsort oder Ortswechsel zu analysieren oder vorherzusagen.",
            ],
            [
                "Nach Art. 22 Abs. 1 hat eine Person das Recht, „**nicht einer ausschließlich auf einer automatisierten Verarbeitung — einschließlich Profiling — beruhenden Entscheidung unterworfen zu werden**, die ihr gegenüber **rechtliche Wirkung** entfaltet oder sie **in ähnlicher Weise erheblich beeinträchtigt**“.",
                "Erwägungsgrund 71 nennt Beispiele: die automatische Ablehnung eines Online-Kreditantrags und „Online-Einstellungsverfahren ohne jegliches menschliche Eingreifen“.",
            ],
            [
                "Artikel 22 Abs. 1 gilt nicht, wenn die Entscheidung (Art. 22 Abs. 2):",
                {"type": "list", "items": [
                    "a) für den Abschluss oder die Erfüllung eines Vertrags mit der Person **erforderlich** ist;",
                    "b) nach Rechtsvorschriften der EU oder eines EU-Staats zulässig ist, die angemessene Maßnahmen zum Schutz der Person enthalten; oder",
                    "c) mit **ausdrücklicher Einwilligung** der Person erfolgt.",
                ]},
            ],
            [
                "In den Fällen nach Buchst. a und c muss der Verantwortliche angemessene Maßnahmen treffen. Dazu gehört **mindestens** das Recht, das **Eingreifen einer Person**, also eines Menschen, seitens des Verantwortlichen zu erwirken, den eigenen **Standpunkt darzulegen** und die Entscheidung **anzufechten** (Art. 22 Abs. 3). Erwägungsgrund 71 nennt außerdem eine Erläuterung der Entscheidung.",
                "Solche Entscheidungen dürfen nicht auf besonderen Kategorien personenbezogener Daten beruhen (den sensiblen Kategorien nach Art. 9 Abs. 1, etwa Gesundheitsdaten). Ausnahmen gelten nur bei ausdrücklicher Einwilligung oder erheblichem öffentlichem Interesse und nur mit angemessenen Maßnahmen zum Schutz der Person (Art. 22 Abs. 4).",
            ],
            [
                "Daraus folgen Pflichten zur Transparenz. Datenschutzhinweise und Antworten auf Auskunftsanträge müssen eine solche automatisierte Entscheidungsfindung erwähnen, mit **aussagekräftigen Informationen über die involvierte Logik** sowie über die Tragweite und die angestrebten Auswirkungen (Art. 13 Abs. 2 Buchst. f und 15 Abs. 1 Buchst. h).",
            ],
            [
                "Die App der Bäckerei Sonnenfeld schlägt Gebäck vor, je nachdem, was eine Kundin früher gekauft hat. Das ist Profiling. Ein Vorschlag hat aber in der Regel keine rechtliche Wirkung und beeinträchtigt die Kundin auch nicht in ähnlicher Weise erheblich.",
                "Würde die Bäckerei eine Software einsetzen, die Bewerbungen automatisch und ohne menschliche Prüfung ablehnt, fiele das unter Art. 22. Erwägungsgrund 71 nennt Online-Einstellungsverfahren als Beispiel.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "Was davon ist Profiling?", "Welche Tätigkeit bewertet persönliche Aspekte eines Menschen durch automatisierte Verarbeitung?",
                       ("Eine App, die aus den Käufen einer Kundin ihre Vorlieben vorhersagt", "Sie sagt persönliche Vorlieben vorher (Art. 4 Nr. 4)."),
                       ("Das Speichern der Lieferanschrift einer Kundin", "Speichern ist eine Verarbeitung, aber es wird nichts bewertet."),
                       ("Das Drucken eines Kassenbons", "Über die Person wird nichts analysiert oder vorhergesagt.")),
            assessment([1], [2, 6], "Eine Software lehnt Bewerbungen automatisch ab, ohne dass ein Mensch beteiligt ist. Spielt Art. 22 hier eine Rolle?", "Fällt eine vollautomatische Ablehnung von Bewerbungen unter Art. 22?",
                       ("Ja, es ist eine ausschließlich automatisierte Entscheidung mit erheblicher Wirkung", "Erwägungsgrund 71 nennt Online-Einstellungsverfahren ohne jegliches menschliche Eingreifen."),
                       ("Nein, weil man sich jederzeit erneut bewerben kann", "Die Möglichkeit, sich erneut zu bewerben, beseitigt die Wirkung nicht."),
                       ("Nein, Art. 22 betrifft nur Kreditentscheidungen", "Kredite sind nur eines der Beispiele in Erwägungsgrund 71.")),
            assessment([1], [4], "Eine ausschließlich automatisierte Entscheidung beruht auf einer ausdrücklichen Einwilligung. Was muss der Verantwortliche mindestens anbieten?", "Welche Maßnahmen verlangt Art. 22 Abs. 3 mindestens, wenn eine ausschließlich automatisierte Entscheidung auf einem Vertrag oder einer ausdrücklichen Einwilligung beruht?",
                       ("Das Recht auf Eingreifen einer Person, auf Darlegung des eigenen Standpunkts und auf Anfechtung der Entscheidung", "Art. 22 Abs. 3."),
                       ("Nichts weiter, weil die Person eingewilligt hat", "Art. 22 Abs. 3 gilt auch bei einer Einwilligung."),
                       ("Nur die Erstattung eines gezahlten Entgelts", "Art. 22 Abs. 3 verlangt die dort genannten Maßnahmen.")),
            assessment([0, 1], [1, 2, 6], "Die App der Bäckerei Sonnenfeld empfiehlt Gebäck auf Grundlage früherer Käufe. Wie ordnet die DSGVO das ein?", "Produktvorschläge auf Grundlage des Kaufverlaufs: Ist das Profiling, eine Entscheidung nach Art. 22 oder keins von beiden?",
                       ("Profiling, aber in der Regel keine Entscheidung nach Art. 22", "Es bewertet Vorlieben, aber ein Vorschlag hat selten rechtliche Wirkung oder eine ähnlich erhebliche Beeinträchtigung zur Folge."),
                       ("Eine nach Art. 22 verbotene Entscheidung", "Art. 22 setzt eine rechtliche Wirkung oder eine ähnlich erhebliche Beeinträchtigung voraus."),
                       ("Überhaupt keine Verarbeitung personenbezogener Daten", "Ein Kaufverlauf, der einer Kundin zugeordnet ist, besteht aus personenbezogenen Daten.")),
        ],
    },
    "R08": {
        "title": "Beschwerde, Klage und Schadenersatz",
        "summary": "Zwischen einer Beschwerde, einer Klage und einem Anspruch auf Schadenersatz wählen und verstehen, wie die Haftung verteilt ist.",
        "prerequisites": {
            "G01": "Eine Beschwerde wird bei einer Aufsichtsbehörde eingelegt.",
            "G05": "Eine Klage richtet sich gegen einen Verantwortlichen oder einen Auftragsverarbeiter.",
        },
        "sources": [("GDPR", "Art. 77, 79, 80, 82"), ("GDPR-REC", "Erwägungsgrund 146")],
        "screens": [
            [
                "**Beschwerde** (Art. 77): Jede betroffene Person hat das Recht auf Beschwerde bei einer **Aufsichtsbehörde**, insbesondere in dem EU-Staat, in dem sie ihren gewöhnlichen Aufenthaltsort oder ihren Arbeitsplatz hat oder in dem der mutmaßliche Verstoß stattfand.",
                "Die Aufsichtsbehörde muss die Person, die sich beschwert hat, über den Stand und die Ergebnisse der Beschwerde unterrichten.",
            ],
            [
                "**Gericht** (Art. 79): Eine Person kann auch gegen einen Verantwortlichen oder Auftragsverarbeiter vor Gericht gehen. Das gilt **unbeschadet** einer Beschwerde: Der eine Weg muss nicht vor dem anderen beschritten werden.",
                "Zuständig sind die Gerichte des EU-Staats, in dem der Verantwortliche oder Auftragsverarbeiter eine Niederlassung hat. Wahlweise kann die Person auch dort klagen, wo sie ihren gewöhnlichen Aufenthaltsort hat, es sei denn, die beklagte Stelle ist eine Behörde, die in Ausübung ihrer hoheitlichen Befugnisse gehandelt hat.",
            ],
            [
                "**Vertretung** (Art. 80): Eine Person kann eine ordnungsgemäß gegründete Einrichtung ohne Gewinnerzielungsabsicht, die im Datenschutz tätig ist, beauftragen, in ihrem Namen Beschwerde einzulegen oder vor Gericht zu gehen.",
                "Die EU-Staaten können außerdem vorsehen, dass solche Einrichtungen auch ohne Auftrag einer Person handeln dürfen.",
            ],
            [
                "**Schadenersatz** (Art. 82 Abs. 1): **Jede Person**, der wegen eines Verstoßes ein **materieller oder immaterieller Schaden** entstanden ist, hat Anspruch auf Schadenersatz gegen den Verantwortlichen oder gegen den Auftragsverarbeiter.",
                "Nach Erwägungsgrund 146 sollte der Begriff des Schadens weit ausgelegt werden, und der Schadenersatz sollte vollständig und wirksam sein.",
            ],
            [
                "**Wer zahlt** (Art. 82 Abs. 2 bis 5):",
                {"type": "list", "items": [
                    "Ein an der Verarbeitung beteiligter Verantwortlicher haftet für den Schaden, der durch eine Verarbeitung entsteht, die gegen die DSGVO verstößt.",
                    "Ein Auftragsverarbeiter haftet nur, wenn er seine speziell den Auftragsverarbeitern auferlegten Pflichten verletzt hat oder unter Nichtbeachtung der rechtmäßig erteilten Anweisungen des Verantwortlichen oder gegen diese Anweisungen gehandelt hat.",
                    "Beide sind nur dann von der Haftung befreit, wenn sie nachweisen, dass sie **in keinerlei Hinsicht** verantwortlich sind.",
                    "Sind mehrere verantwortlich, haftet **jeder für den gesamten Schaden**. Wer gezahlt hat, kann von den anderen deren Anteil zurückfordern.",
                ]},
            ],
            [
                "Angenommen, das Lohnbüro der Bäckerei Sonnenfeld verletzt seine eigenen Sicherheitspflichten, und Gehaltsdaten gelangen nach außen. Die betroffenen Beschäftigten könnten Ansprüche gegen die Bäckerei und gegen das Lohnbüro geltend machen.",
                "Sind beide verantwortlich, kann jeder von beiden zur Zahlung des vollen Betrags verpflichtet werden und dann vom anderen dessen Anteil zurückfordern.",
                ILLUSTRATION,
            ],
        ],
        "questions": [
            assessment([0], [1], "Eine Kundin, die in Österreich lebt, meint, die Bäckerei Sonnenfeld mit Sitz in Deutschland habe ihre Daten missbraucht. Wo kann sie sich beschweren?", "Die Bäckerei Sonnenfeld hat ihren Sitz in Deutschland. Eine Kundin, die in Österreich lebt, will sich über sie beschweren. Wo kann sie das nach Art. 77 tun?",
                       ("Unter anderem bei der österreichischen Aufsichtsbehörde", "Art. 77 Abs. 1 nennt den Mitgliedstaat ihres gewöhnlichen Aufenthaltsorts."),
                       ("Nur in Deutschland, wo die Bäckerei ihren Sitz hat", "Art. 77 lässt eine Beschwerde in mehreren Ländern zu."),
                       ("Nur bei der Europäischen Kommission", "Beschwerden gehen an eine Aufsichtsbehörde.")),
            assessment([0], [2], "Eine Kundin will die Bäckerei Sonnenfeld wegen ihrer Daten verklagen. Muss sie sich zuerst bei einer Aufsichtsbehörde beschweren?", "Ist eine Beschwerde bei einer Aufsichtsbehörde Voraussetzung für eine Klage nach Art. 79?",
                       ("Nein, der Weg zum Gericht steht ebenfalls offen", "Art. 79 gilt unbeschadet des Art. 77."),
                       ("Ja, eine Beschwerde muss immer zuerst kommen", "Keiner der beiden Wege ist Voraussetzung für den anderen."),
                       ("Nur die Aufsichtsbehörde kann vor Gericht gehen", "Art. 79 gibt dieses Recht der betroffenen Person.")),
            assessment([1], [4], "Eine Kundin hat durch einen Verstoß eine seelische Belastung erlitten, aber keinen finanziellen Verlust. Kann sie Schadenersatz verlangen?", "Erfasst Art. 82 auch Schäden, die nicht finanzieller Art sind?",
                       ("Ja, auch immaterieller Schaden ist erfasst", "Art. 82 Abs. 1."),
                       ("Nein, nur finanzielle Verluste zählen", "Art. 82 Abs. 1 erfasst auch immaterielle Schäden."),
                       ("Nur, wenn die Aufsichtsbehörde zuerst eine Geldbuße gegen die Bäckerei Sonnenfeld verhängt", "Art. 82 kennt keine solche Bedingung.")),
            assessment([1], [5, 6], "Der Auftragsverarbeiter, der für die Bäckerei Sonnenfeld die Lohnabrechnung macht, hat seine eigenen Pflichten verletzt, und es kam zu einem Datenleck. Wer kann den Beschäftigten gegenüber haften?", "Ein Auftragsverarbeiter verletzt seine eigenen Pflichten, und dadurch gelangen Daten der Beschäftigten der Bäckerei Sonnenfeld nach außen. Wie ist die Haftung gegenüber den Beschäftigten verteilt?",
                       ("Jeder von beiden kann für den gesamten Schaden haften", "Art. 82 Abs. 4, mit Rückgriff nach Art. 82 Abs. 5."),
                       ("Nur der Auftragsverarbeiter", "Auch der beteiligte Verantwortliche kann haften."),
                       ("Nur die Bäckerei Sonnenfeld, weil Auftragsverarbeiter nie haften", "Auftragsverarbeiter haften, wenn sie ihre eigenen Pflichten verletzen.")),
        ],
    },
}
