"""Annex III essential services and public decision use cases."""

from lesson_builder import assessment

LESSONS = {
    "S01": {
        "locator": "Article 3(62); Annex III 2; Article 49(5)",
        "summary": "Identify the listed infrastructure sectors and their safety-component condition.",
        "additional_sources": [{"title": "Critical Entities Resilience Directive (EU) 2022/2557, Article 2(4), 2(5)", "url": "https://eur-lex.europa.eu/legal-content/EN-DE/ALL/?uri=CELEX:32022L2557"}],
        "screens": [
            ["**Critical infrastructure** includes assets, equipment, networks or systems necessary to provide an essential service. The AI Act refers to the definition in Directive (EU) 2022/2557, which links essential services to vital societal, economic, health, safety or environmental functions.", "Importance to a business alone does not prove the listed AI use. Begin with the actual infrastructure and service."],
            ["Annex III point 2 lists AI intended as safety components in managing or operating critical digital infrastructure, road traffic, or the supply of water, gas, heating or electricity.", "This is a sector-and-function test. Not every AI used by a utility is automatically in point 2. A billing helper and a safety-dependent control function have different intended purposes."],
            ["Fictional Northbridge case: a water service uses AI in a safety function whose malfunction can endanger people. The record identifies the supply function and the safety dependency.", "Change the facts to a purely clerical invoice sorter with no safety role. The same organisation's identity does not preserve the safety-component fact. Test actual operation and dependencies."],
            ["If point 2 applies, continue the full Article 6 analysis. Registration also has a particular route: Article 49(5) assigns high-risk systems in point 2 to national-level registration.", "Do not turn that registration distinction into an exclusion from high-risk classification. The classification, obligations, registration location and application dates answer different questions."],
        ],
        "questions": [
            assessment([0], [1, 2], "A utility buys an AI invoice sorter with no safety role. What does the utility's identity alone establish?", "Does every AI tool used by a water supplier satisfy Annex III point 2?", ("Not the listed safety-component use by itself", "The point requires the specified infrastructure and safety function."), ("Automatic high-risk status for every tool", "That omits the function condition."), ("A universal exclusion for utility software", "A safety-dependent function may meet the listed use.")),
            assessment([0], [2, 3], "AI acts as a safety component in water-supply operation. Which listed point needs comparison?", "Which Annex III infrastructure facts are relevant for an AI-dependent water safety function?", ("Point 2's sector and safety function", "Both the water-supply context and safety role are relevant."), ("Only the supplier's logo", "A logo does not establish the function."), ("Only whether invoices are digital", "Invoice format does not decide the safety use.")),
            assessment([0], [4], "Where does Article 49(5) place registration for high-risk Annex III point 2 systems?", "Does the national registration route remove point 2 systems from classification?", ("At national level, without removing classification", "The provision specifies registration location rather than an exemption."), ("Nowhere, because utilities are exempt", "That contradicts the registration provision."), ("Only in the vendor's private marketing list", "A marketing list is not the statutory registration route.")),
        ],
    },
    "S02": {
        "locator": "Annex III 5(b), 5(c); Article 6(2), 6(3)",
        "summary": "Distinguish creditworthiness, fraud detection and life/health insurance purposes.",
        "screens": [
            ["The **credit use** in Annex III 5(b) concerns evaluating a natural person's creditworthiness or establishing their credit score. The point expressly excepts systems used to detect financial fraud.", "Northbridge's fictional lender must separate repayment-risk scoring from fraud detection. The exception is purpose-specific; it does not exempt every product marketed to financial institutions."],
            ["The **life/health insurance use** in point 5(c) concerns risk assessment and pricing in relation to natural persons for life and health insurance.", "Do not silently expand this exact point to every insurance product. Other functions can still meet another listed use or other law. Record the insurance type, person and output purpose."],
            ["A combined tool both detects suspicious transactions and evaluates creditworthiness. The fraud purpose does not erase the separate credit function.", "For each function, retain inputs, personal evaluation and its role in eligibility or pricing. A final human reviewer does not automatically remove the intended evaluation purpose."],
            ["Compare the precise Annex III point before the later paragraph 3 and profiling checks. A not-listed result under one point is a narrow conclusion, not a general compliance certificate.", "Changing from fraud flags to repayment scoring or life-insurance pricing changes the facts. Northbridge should update the record rather than copy the old exception."],
        ],
        "questions": [
            assessment([0], [1], "A lender's tool predicts a person's repayment ability. Which purpose is directly relevant?", "Does creditworthiness evaluation become fraud detection simply because a bank operates the tool?", ("Creditworthiness under Annex III 5(b)", "The actual repayment evaluation is the listed purpose."), ("The fraud exception solely from the bank context", "The exception depends on detection purpose, not industry alone."), ("No relevant purpose if a person approves", "Human approval alone does not remove credit evaluation.")),
            assessment([1], [2], "Which insurance types are expressly named in point 5(c)?", "Which insurance risk/pricing purpose does Annex III 5(c) specify?", ("Life and health insurance for natural persons", "Those are the named insurance contexts."), ("Every kind of insurance without distinction", "That expands the point beyond its wording."), ("Only warehouse property insurance", "That is not the life/health purpose stated in the point.")),
            assessment([0, 1], [3, 4], "One tool detects fraud and also sets personal credit scores. What should the analysis retain?", "Can a combined product's fraud feature erase its credit-scoring function?", ("Separate the purposes and assess each relevant function", "The exception is not platform-wide permission."), ("Only the fraud function's result", "That hides the listed credit evaluation."), ("Only whether the supplier calls it analytics", "A broad label cannot replace the use-case facts.")),
        ],
    },
    "S03": {
        "locator": "Annex III 5(a), 5(d); Article 6(2), 6(3)",
        "summary": "Recognise public-assistance eligibility and emergency triage/dispatch decisions.",
        "screens": [
            ["The **public-benefits use** covers AI used by or on behalf of public authorities to evaluate eligibility for essential public assistance benefits or services, including healthcare, and to grant, reduce, revoke or reclaim them.", "A fictional municipal Northbridge service evaluates applications for essential assistance. Identify the public-authority connection and the particular decision; not all public-sector administration performs this function."],
            ["The **emergency-triage use** includes evaluating/classifying emergency calls, dispatching or prioritising emergency first response, including police, firefighters and medical aid, and emergency healthcare patient triage.", "A tool sorting callers by urgency directly raises the listed comparison. A tool organising an unrelated office rota has different facts."],
            ["Changed case: a benefits assistant only provides office hours. It later recommends whether an applicant's entitlement should be withdrawn. That is a substantial change in the intended decision function.", "Changed case: a call transcription tool also assigns priority. Record the added evaluation instead of treating it as mere text conversion."],
            ["Northbridge's packet records actor, person affected, decision type, input, output and influence. The point identifies the classification route; it does not supply a lawful basis under every benefits, health or data-protection rule.", "Apply the remaining paragraph 3, profiling, scope and timing checks. Keep a missing decision-use fact explicit rather than assuming outputs have no effect."],
        ],
        "questions": [
            assessment([0], [1], "AI used for a municipality recommends reclaiming an essential assistance benefit. Which listed purpose is relevant?", "Which Annex III function includes public-authority decisions to revoke or reclaim essential benefits?", ("Public-benefits use in point 5(a)", "The point includes evaluation and grant/reduction/revocation/reclaim functions."), ("Only an office-hours information service", "The case makes an entitlement recommendation."), ("Only a private supplier's billing process", "That does not describe the public assistance decision.")),
            assessment([1], [2], "An AI assigns priority to emergency medical responses. Which listed use is indicated?", "Does emergency response prioritisation belong to the emergency call/dispatch point?", ("Emergency-triage/dispatch use in point 5(d)", "The point expressly includes establishing dispatch priority."), ("Only ordinary office scheduling", "Emergency response consequences are different."), ("Only building access verification", "That is an unrelated purpose.")),
            assessment([0, 1], [3, 4], "A transcription assistant adds priority scoring for emergency calls. What changes in the assessment?", "Why should adding emergency priority recommendations trigger a new function check?", ("It now contributes to a listed emergency decision", "The added evaluation changes the relevant intended purpose."), ("Nothing because text still appears on screen", "Output format does not erase decision influence."), ("All rules disappear because it started as transcription", "The historical label does not settle the new use.")),
        ],
    },
    "S04": {
        "locator": "Article 3(45), 3(46); Annex III 6(a)–(e); Article 5(1)(d)",
        "summary": "Separate legally permitted enforcement use cases from the criminal-risk prohibition.",
        "screens": [
            ["**Law enforcement** concerns defined authorities, or activity on their behalf, for prevention, investigation, detection or prosecution of offences, execution of penalties and protection against public-security threats.", "A commercial firm using the phrase 'security analytics' does not by that label establish the definition. Record the legally authorised actor, purpose and relationship."],
            ["Annex III 6 lists permitted enforcement uses: assessing victimisation risk, polygraphs or similar tools, evidence-reliability evaluation, specified offending/re-offending or trait/past-behaviour assessment, and personal profiling in criminal detection, investigation or prosecution.", "Keep the five points separate. A victim-risk tool asks a different question from a suspected-offender tool. The lawfulness condition comes before treating the list as permission."],
            ["Article 5(1)(d) separately prohibits certain individual criminal-risk prediction based solely on profiling or personality assessment. Its factual human-assessment-support boundary is taught in the prohibition module.", "An Annex III enforcement listing cannot cure that prohibition. A system may require prohibition analysis before its high-risk duties are even considered."],
            ["Fictional case: an authorised enforcement body assesses evidence reliability with AI. Record the evidence function under point 6(c), the authority and permitted-use basis, then the remaining classification checks.", "Changed case: it predicts offending solely from personal traits. That introduces a separate prohibition question. Keep supporting evidence and unresolved legal permission distinct from vendor claims."],
        ],
        "questions": [
            assessment([0], [1], "A supplier calls a product 'security analytics'. What establishes the enforcement context?", "Which facts should be checked rather than relying on a security product label?", ("Authorised actor, activity and on-behalf relationship", "The definitions concern legal authority and specified activities."), ("Only the product's security branding", "Branding cannot establish statutory enforcement authority."), ("Only whether the software is expensive", "Price does not identify legal authority or purpose.")),
            assessment([1], [2, 4], "An enforcement body uses AI to evaluate reliability of case evidence. Which point is directly relevant?", "Which enforcement listed use concerns evidence-reliability evaluation?", ("Annex III 6(c)", "That point specifically addresses reliability of evidence."), ("Only victimisation risk under 6(a)", "Victim risk is a different function."), ("Only school admission under 3(a)", "That has a different actor and purpose context.")),
            assessment([1], [2, 3], "A criminal-risk tool uses solely personality assessment. Can an Annex III listing authorise it?", "What should happen before a high-risk result is treated as permission for criminal-risk prediction?", ("Apply the separate Article 5 prohibition test", "Listed high-risk purposes remain subject to permitted use and prohibitions."), ("Accept the listing as unconditional permission", "That ignores the separate prohibition."), ("Ignore its input basis entirely", "The sole profiling/personality basis is central to the prohibition question.")),
        ],
    },
    "S05": {
        "locator": "Annex III 7(a)–(d); Articles 5, 6",
        "summary": "Identify migration risk, polygraph, application and identity uses and the travel-document limit.",
        "screens": [
            ["The **migration use** area covers specified AI used by or on behalf of competent public authorities or Union bodies in migration, asylum and border management, insofar as use is legally permitted.", "Point 7(a) covers polygraphs or similar tools. Point 7(b) covers assessing security, irregular-migration or health risk posed by a person entering or already in a Member State. Do not replace these exact functions with a generic border-software label."],
            ["Point 7(c) covers assistance in examining asylum, visa or residence-permit applications and associated complaints concerning eligibility, including evidence-reliability assessments.", "Fictional Northbridge authority compares an application-review assistant with that point. A general opening-hours chatbot has different facts from evaluating whether an applicant qualifies."],
            ["Point 7(d) covers detecting, recognising or identifying people in migration/asylum/border management, except verification of travel documents.", "The exact travel-document exception is not an exemption for every identity system used at a border. Record what is verified and whether the tool also identifies people or performs another listed assessment."],
            ["A multi-function border platform may engage several points. Record each intended use, public-authority connection, data, person affected and decision influence, then examine the other Article 6 and Article 5 tests.", "The high-risk list supplies no independent legal authorisation to collect data or use the system. National and Union law, scope and dates need their own evidence."],
        ],
        "questions": [
            assessment([0], [1, 2], "AI assists a competent authority in evaluating an asylum application and its evidence. Which point needs comparison?", "Which migration listed use concerns eligibility and evidence in asylum, visa or residence applications?", ("Annex III 7(c)", "That point specifies the application-examination function."), ("Only general office-hours support", "Eligibility/evidence evaluation has different facts."), ("Only internal stationery purchasing", "That is not an application assessment.")),
            assessment([0], [3], "A supplier claims every border identity tool fits the travel-document exception. What should be checked?", "How broad is the travel-document verification exception in point 7(d)?", ("The actual document-verification function and added uses", "The exception cannot erase separate identity or risk-assessment functions."), ("It excludes all border software automatically", "The exception is narrower than the whole listed area."), ("The vendor's slogan is sufficient evidence", "A slogan does not establish the exact purpose.")),
            assessment([0], [1, 4], "A listed migration purpose is found. What does 'insofar as legally permitted' require?", "Does the migration high-risk list itself supply a legal basis for every proposed use?", ("A separate permitted-use analysis under relevant law", "Classification is not independent permission."), ("No further legality check", "That omits the list's express lawfulness condition."), ("Only a software subscription receipt", "A purchase does not establish public-authority legal permission.")),
        ],
    },
    "S06": {
        "locator": "Annex III 8(a), 8(b); Article 6(2), 6(3)",
        "summary": "Distinguish judicial assistance and voter influence from narrowly described administrative functions.",
        "screens": [
            ["The **justice use** in point 8(a) concerns AI used by a judicial authority or on its behalf to help research/interpret facts and law and apply law to concrete facts, or similarly in alternative dispute resolution.", "A fictional decision assistant suggesting how law applies to a case differs from a tool only booking meeting rooms. The actual decision-related purpose needs evidence."],
            ["The **election-influence use** in point 8(b) concerns influencing election/referendum outcomes or people's voting behaviour when exercising their vote.", "Targeted voter persuasion is different from organising a campaign's internal calendar. The exclusion describes tools whose outputs people are not directly exposed to, such as administrative/logistical campaign organisation."],
            ["Examine both intended function and who encounters the output. A campaign tool beginning as internal scheduling may later generate messages directly shown to voters.", "Do not infer the administrative exclusion merely from the customer being a campaign organisation. A tool supporting interpretation in a judicial case similarly differs from general administrative support."],
            ["Northbridge's fictional public-decision clinic records the exact point and boundary. The evidence should show whether outputs assist case reasoning or directly influence voters, not just the platform's customer category.", "Then complete paragraph 3, profiling, prohibition, scope, other-law and date analyses. Neither a judge's review nor a logistical label automatically supplies an exemption."],
        ],
        "questions": [
            assessment([0], [1], "AI suggests how law applies to specific facts for a judicial authority. Which purpose is relevant?", "Which justice listed use concerns assistance with applying law to a concrete case?", ("Annex III 8(a)", "That point addresses judicial reasoning assistance and similar dispute resolution."), ("Only ordinary meeting-room booking", "The stated function concerns case reasoning."), ("No listed use because a judge reviews it", "Human review alone does not erase the intended assistance purpose.")),
            assessment([1], [2], "An internal campaign calendar has no outputs shown directly to voters. Which boundary matters?", "Which fact distinguishes administrative campaign logistics from the point 8(b) voter-facing purpose?", ("Administrative function and no direct voter exposure", "The point's exception refers to that output/purpose boundary."), ("Only whether a political group bought it", "The customer's identity alone does not determine the purpose."), ("Only whether the server is large", "Server size is not the statutory function distinction.")),
            assessment([0, 1], [3, 4], "A logistics tool starts creating targeted messages shown to voters. What should the assessor do?", "Can a campaign tool keep its administrative result after adding voter-facing persuasion?", ("Reassess the changed purpose and output exposure", "The new function changes the listed-use comparison."), ("Keep the old result because the invoice is unchanged", "An invoice does not establish unchanged intended use."), ("Assume voter exposure is irrelevant", "Exposure and influence are material to this point.")),
        ],
    },
}
