"""Article 6 product route, with explicitly stipulated sector-assessment facts."""

from lesson_builder import assessment

LESSONS = {
    "P01": {
        "locator": "Article 6(1)–(4), Annexes I and III",
        "summary": "Select the product route or listed-use route without treating classification as permission.",
        "screens": [
            ["**High-risk classification** brings a system into a defined regulatory category. Article 6 contains two routes. Paragraph 1 concerns certain products or safety components under listed product legislation; paragraph 2 concerns the use cases in Annex III.", "The routes are additional to each other. A system can require analysis under both. A result under one route does not erase the other route or an Article 5 prohibition."],
            ["For the **product route**, identify the product legislation in Annex I, whether the AI is itself a covered product or a safety component, and whether the relevant product must undergo third-party conformity assessment. The paragraph 1 conditions are cumulative.", "Northbridge considers an AI-enabled protective device. Calling it safety-related is a starting fact, not sufficient proof of the entire product-route test."],
            ["For the **listed-use route**, compare the intended purpose with each relevant Annex III point. These cover specified biometric, infrastructure, education, employment, services, enforcement, migration and justice/democratic uses.", "Northbridge's applicant evaluation needs the employment points. 'It is office software' is too broad to decide this. Paragraph 3 then supplies a limited derogation and profiling rule, taught later."],
            ["Keep three conclusions separate: whether a practice is prohibited, whether a system is high-risk, and which obligations apply when. Transparency and other law need separate checks too.", "Write the exact route and facts supporting it. 'Low-risk because a human is present' is not an Article 6 test. The date rules are also separate: a later high-risk application date does not postpone all other duties."],
        ],
        "questions": [
            assessment([0], [1, 4], "A use is classified high-risk. What does this establish?", "Does high-risk classification itself authorise an AI practice?", ("Its regulatory category, with other checks remaining", "Classification is not a blanket permission or completed compliance assessment."), ("Permission to disregard every prohibition", "Article 5 remains a separate test."), ("That human review is never needed", "Classification does not remove applicable oversight duties.")),
            assessment([1], [2, 3], "Northbridge evaluates applicants with an AI tool. Which route directly needs comparison?", "Which Article 6 route addresses the listed recruitment purposes?", ("Article 6(2) and Annex III", "Recruitment is among Annex III's specified purposes."), ("Only Annex I product legislation", "The listed-use route must still be examined."), ("Only the model's general capabilities", "The system's purpose is central to the use-case route.")),
            assessment([1], [1, 2, 4], "A product-route condition is not met. Can Northbridge end the assessment of a hiring function?", "Does failing one Article 6(1) condition remove the need to check Annex III?", ("No; the listed-use route remains separate", "Paragraph 2 adds a further route to classification."), ("Yes; there is only one route", "Article 6 expressly provides more than the product route."), ("Yes; an AI label decides both routes", "A label supplies neither statutory test.")),
        ],
    },
    "P02": {
        "locator": "Article 3(14), Article 6(1a) and (1b)",
        "summary": "Distinguish genuine non-safety functions from functions whose failure endangers safety.",
        "screens": [
            ["A **safety component** fulfils a product or system safety function, or its failure or malfunction endangers health and safety of people or property. A safety function aims to prevent or mitigate those risks.", "Northbridge's fictional protective device uses AI to preserve warning sounds while limiting harmful noise. If protection depends on the AI's correct operation, that is a safety-function fact to investigate."],
            ["Article 6(1a) excludes systems solely used for non-safety aspects of assistance, optimisation, efficiency, automation, convenience or quality control from being safety components.", "The word **solely** matters. A convenience interface that changes a safety-critical action is different from a convenience function isolated from all safety effects. The category name 'optimisation' cannot prove exclusivity."],
            ["Article 6(1b) qualifies that limit: if failure or malfunction would endanger health and safety, the system qualifies as a safety component notwithstanding paragraph 1a.", "Compare an AI choosing a harmless display colour with an AI wrongly suppressing a safety warning. The failure consequence changes the analysis. Obtain design and failure evidence rather than trusting the feature's marketing category."],
            ["Record the function, affected safety mechanism, failure modes and consequences. In our invented device case, assume failure removes required hearing protection: the non-safety exclusion is not established.", "This finds a safety-component fact only. Annex I coverage and the required third-party assessment still need separate evidence before the full Article 6(1) conclusion."],
        ],
        "questions": [
            assessment([0], [1], "AI controls a protective function preventing harmful exposure. Which fact is most relevant?", "What makes an AI component's function safety-related?", ("Its purpose prevents or mitigates safety risks", "Article 3(14) connects the function to health and safety protection."), ("Its interface uses a green icon", "Interface colour does not establish a safety function."), ("Its subscription is inexpensive", "Price does not establish safety effects.")),
            assessment([1], [2], "A vendor calls a safety-linked feature 'convenience automation'. What must be checked for paragraph 1a?", "When does the non-safety function limit apply to a purported convenience feature?", ("Whether its use is exclusively non-safety-related", "The statute requires solely non-safety aspects."), ("Whether the vendor chose that label", "A label is not evidence of the actual function."), ("Whether it is used by any employee", "The user's identity does not establish the exclusion.")),
            assessment([2], [3, 4], "A supposedly non-safety optimisation feature can endanger health when it fails. What follows?", "How does a safety-endangering malfunction affect the paragraph 1a limit?", ("Paragraph 1b makes it a safety component", "The failure rule overrides the non-safety-function limit."), ("Its optimisation label always excludes it", "Paragraph 1b expressly qualifies that limit."), ("It automatically proves every product-route condition", "Product coverage and assessment requirements still need evidence.")),
        ],
    },
    "P03": {
        "locator": "Annex I Sections A and B; Article 2(2), 2(13); Article 6(1)",
        "summary": "Find the exact listed product instrument and avoid applying all obligations from classification alone.",
        "screens": [
            ["An **Annex I lookup** identifies the exact Union product instrument. The list includes toys, lifts, radio and pressure equipment, protective equipment, medical devices and other specified sectors.", "Northbridge records the instrument, product scope and intended function. A product being generally regulated is not enough: the relevant legislation must be listed and actually cover this product."],
            ["Read the current section and point, not an old diagram. In our July 2026 baseline, Section A point 1 is deleted and the Machinery Regulation (EU) 2023/1230 appears in Section B point 21.", "This is a concrete reason to retain the source version. Do not continue citing the deleted machinery entry as operative. The sector legislation's own application and transition rules remain relevant."],
            ["**Sector scope limits** concern which AI Act provisions apply after classification. Under Article 2(2), high-risk Article 6(1) systems related to Section B products have specified limited AI Act application, with conditions for certain innovation provisions.", "A Section B classification does not automatically import every Chapter III duty. The wording lists Article 6(1), Article 60a and Articles 102–112; Articles 57–59 have an integration condition. Look up the actual list."],
            ["Article 2(13) permits specified limitations for equivalent-or-higher protection under Section A legislation without reducing overall protection, with delegated specification. It is a conditional mechanism, not a vendor-created exemption.", "Northbridge's record links product scope, list entry, assessment route and obligation-scope questions. If the sector classification is unresolved, state the missing evidence instead of declaring an assumed product class."],
        ],
        "questions": [
            assessment([0], [1, 2], "A product is regulated somewhere in EU law. What else does an Annex I lookup need?", "Does the existence of any product regulation establish the Article 6(1) coverage condition?", ("The exact listed instrument and its product scope", "Annex I coverage must be established for this product."), ("Only the statement 'regulated industry'", "That does not identify a listed covering instrument."), ("Only an old deleted annex entry", "The current operative list must be checked.")),
            assessment([1], [3], "A system relates to a Section B product and meets Article 6(1). What should the obligations analysis do?", "Does a Section B product-route classification automatically apply every high-risk duty?", ("Apply the specific Article 2(2) scope limits", "Section B has a specified AI Act application list."), ("Apply every AI Act duty without a scope check", "That ignores the express sector limitation."), ("Declare the system wholly outside EU law", "A limited AI Act list is not a blanket legal exclusion.")),
            assessment([0, 1], [2, 4], "An assessment relies on the old Section A machinery entry. What is the best correction?", "How should a reviewer handle an obsolete Annex I machinery locator?", ("Update the locator and recheck sector consequences", "List location and applicable rules must match the current baseline."), ("Retain it because the product name is familiar", "Familiarity does not restore a deleted entry."), ("Treat the list change as no regulation at all", "The current list includes the new Section B entry.")),
        ],
    },
    "P04": {
        "locator": "Article 3(20)–(22); Article 6(1)(a), 6(1)(b), 6(1c)",
        "summary": "Distinguish a legally required third-party route from voluntary testing and the non-safety-risk limit.",
        "screens": [
            ["**Conformity assessment** demonstrates whether specified requirements are met. A third-party assessment involves an external assessment body. The product route asks whether the relevant product is legally required to undergo that route under listed product law.", "A voluntary laboratory test or consultant review is not automatically the required statutory third-party assessment. Identify the instrument, product category and mandated route."],
            ["Article 6(1) joins two conditions: covered AI product or safety component, and the relevant product's required third-party conformity assessment. The AI may be marketed independently of the product; separate supply does not remove the test.", "If a fictional case explicitly establishes both conditions, the product-route conclusion follows subject to the statutory qualifications. If the assessment route is missing, the conclusion is conditional."],
            ["Paragraph 1c says the assessment condition is not met when third-party assessment is required solely for risks other than health and safety, including specified spectrum/interference risks that do not affect health and safety.", "The word **solely** again matters. Do not exclude a route involving both safety and non-safety risks merely because spectrum is one reason for assessment."],
            ["Northbridge asks for the product classification and exact assessment obligation rather than inferring them from 'medical AI' or 'certified'. A real medical-device example requires the medical-device scope and classification rules; a protective-device example requires the protective-equipment rules.", "Our course cases stipulate those sector facts when they test Article 6 logic. They do not assign an actual device class from a short description. This keeps a useful legal reasoning exercise separate from an unsupported sector determination."],
        ],
        "questions": [
            assessment([0], [1], "A vendor voluntarily pays a testing laboratory. Is that alone proof of Article 6(1)(b)?", "What evidence is required for the product route's third-party assessment condition?", ("A legally required route under the listed sector law", "The condition concerns required assessment, not any external test."), ("Any optional laboratory invoice", "Voluntary testing does not establish the legal requirement."), ("Any internal quality review", "An internal review is not proof of a required third-party route.")),
            assessment([1], [2, 4], "Covered product status is documented, but the mandatory assessment route is unknown. What is the sound conclusion?", "Can one documented product-route condition replace the missing other condition?", ("Keep the conclusion conditional and verify the route", "Both cumulative conditions need evidence."), ("The first condition automatically proves the second", "Product scope and assessment route are distinct."), ("Independent software supply automatically excludes it", "Paragraph 1 expressly addresses independent placement.")),
            assessment([2], [3], "Third-party assessment is required solely for spectrum risks with no health or safety effect. What follows under paragraph 1c?", "Does an exclusively non-safety spectrum assessment fulfil Article 6(1)(b) in this baseline?", ("That assessment does not fulfil the condition", "Paragraph 1c expressly excludes this solely non-safety-risk case."), ("Every third-party assessment fulfils the condition", "That ignores the paragraph 1c qualification."), ("All radio equipment is exempt from every law", "The rule concerns this condition, not blanket legality.")),
        ],
    },
    "P05": {
        "locator": "Article 6(1), 6(1a)–(1c); Annex I; Article 2(2)",
        "summary": "Apply the full product-route test to changed facts while retaining separate scope and date checks.",
        "screens": [
            ["**Product-route assessment** combines function, listed coverage and required assessment. We use a fictional protective device. Stipulated facts: it is covered by a current Annex I instrument, AI fulfils its safety function, and the product must undergo third-party assessment for health and safety risks.", "These are supplied case facts, not a sector classification derived by this lesson. Record them and their evidence in a real assessment."],
            ["On those facts, both paragraph 1 conditions are met. The solely non-safety-function limit does not fit a genuine protective function, and paragraph 1c does not remove a health/safety assessment route.", "The conclusion is high-risk by the product route. It still requires separate examination of Article 2 sector limits, prohibition facts, applicable obligations and dates."],
            ["Changed fact: the AI now changes display colours only, with evidence that its failure has no safety effect. Paragraph 1a may remove safety-component status. But check whether the AI is itself a covered product; paragraph 1(a) has that alternative.", "Changed fact: a claimed convenience feature's failure disables protection. Paragraph 1b restores safety-component status. Assess actual failure consequences rather than relabelling the feature."],
            ["Changed fact: only voluntary external testing is documented. The required-assessment condition is not established. The sound record names that gap rather than assuming the same result.", "A conclusion should state which route was tested, which facts were stipulated or verified, and which conclusions remain open. Annex III can still matter where a separate listed use is present."],
        ],
        "questions": [
            assessment([0], [1, 2], "The fictional case establishes listed coverage, an AI safety function and a required safety assessment. What is the Article 6 route result?", "With both product-route conditions established and no stated qualification removing them, what classification follows?", ("High-risk by Article 6(1)", "The stipulated facts meet the cumulative product-route test."), ("Excluded because an AI component is separately supplied", "Independent supply does not remove the paragraph 1 test."), ("Exempt because a user operates it", "Human operation is not a product-route exemption.")),
            assessment([0], [3], "The component is renamed 'convenience', but its failure disables protection. Which fact controls this part of the test?", "Can a convenience label exclude a component whose malfunction endangers safety?", ("The safety-endangering failure consequence", "Article 6(1b) qualifies the non-safety limit."), ("Only the new feature name", "A name cannot negate the failure evidence."), ("Only the colour of the interface", "Appearance does not resolve safety-component status.")),
            assessment([0], [4], "The supplier replaces the legal assessment evidence with a voluntary test report. What should the record say?", "What happens if the compulsory assessment route is not established in a product case?", ("The required-assessment fact remains unresolved", "An optional test is not proof of a mandatory route."), ("Nothing changes because any testing is enough", "The statutory condition specifically concerns required assessment."), ("Every other legal question is now answered", "Missing evidence cannot complete the wider assessment.")),
        ],
    },
    "P06": {
        "locator": "Article 6(5)–(8), Article 7, Article 97",
        "summary": "Track guidance and delegated changes without confusing drafts or proposals with binding amendments.",
        "additional_sources": [{"title": "Commission draft classification guidance: publication and draft status checked 6 October 2026", "url": "https://digital-strategy.ec.europa.eu/en/library/draft-commission-guidelines-classification-high-risk-ai-systems"}],
        "screens": [
            ["This **extension lesson** explains change mechanisms. It does not gate the core classification path. Article 6(5) provides for Commission classification guidance and examples. Examples help compare facts but are not exhaustive or replacements for the law.", "The publication checked on 6 October 2026 remains labelled draft. Always check document identity, status and date again before applying an example to a live decision."],
            ["A **delegated act** is a legal mechanism for specified changes under a regulation's authority. Article 6(6) allows adding or modifying paragraph 3 conditions where concrete, reliable evidence shows relevant Annex III systems lack significant harm risk.", "A consultation or vendor request is not itself such an amendment. Track the adopted instrument and when it has legal effect."],
            ["Article 6(7) requires deleting a derogation condition when concrete, reliable evidence shows that doing so is needed to maintain protection. Paragraph 8 bars decreasing the overall level of protection and requires consistency with the Annex III change mechanism.", "Change powers are therefore constrained. The lesson does not predict which conditions will be added or deleted."],
            ["Article 7 concerns adding or modifying Annex III use cases in the listed areas using its risk criteria; removal has separate conditions. Keep this distinct from paragraph 3 derogation changes.", "A maintainable assessment stores the baseline, monitors actual amendments and rechecks affected facts and rules. Do not freeze a draft example as a permanent statutory exemption."],
        ],
        "questions": [
            assessment([0], [1], "A draft guideline supplies a useful classification example. What status should the record preserve?", "How should an assessor cite an example from a still-draft classification document?", ("Draft non-binding guidance with its date", "Its interpretive and draft status must remain visible."), ("A binding statutory exemption", "Guidance does not itself amend the Act."), ("An exhaustive list of every possible system", "The publication does not claim exhaustive coverage.")),
            assessment([1], [2, 4], "A consultation proposes a new paragraph 3 condition. What should an assessor verify before applying it as law?", "Does a proposed change become an operative derogation when a consultation opens?", ("The adopted legal instrument and its effect date", "A proposal is distinct from a legally effective change."), ("Only the consultation's popularity", "Popularity does not establish legal effect."), ("Only a supplier's agreement with it", "Supplier agreement cannot enact an amendment.")),
            assessment([2], [3], "What constrains paragraph 3 changes under Article 6(8)?", "Can the paragraph 3 change mechanism reduce overall protection without qualification?", ("They must preserve overall protection and consistency", "Paragraph 8 supplies those express constraints."), ("They may ignore health and fundamental rights", "That contradicts the protection constraint."), ("They automatically repeal Article 5", "The mechanism does not confer a power to erase prohibitions.")),
        ],
    },
}
