"""Release identity, scope, dates and evidence for commercial-product reviews."""

from high_risk_content import lesson, question
from conformity_sources import add_registered_sources

LESSONS = {
    "F01": lesson("Articles 3(3), 3(12), 3(19)–(25), 16(f)–(i), 43–49", "Define the release before evaluating its paperwork.", [
        ["An **assessment** checks whether a specified system meets applicable requirements. A **declaration** is the provider's signed statement of conformity. **CE marking** displays conformity under applicable Union legislation. **Registration** records the actor and system. These serve different purposes; one does not replace the others."],
        ["The **assessed system** needs an identity: intended purpose, version, operating boundaries, model and software dependencies, input/output interfaces and release form. Intended purpose means the use the provider specifies, including its supplied instructions and promotional statements. A certificate for a different version or purpose may not support this release."],
        ["The **provider** develops a system, or has it developed, and places it on the market or puts it into service under its own name or trademark. Putting into service includes first use for the provider's own purposes in the Union. Buying a model does not transfer responsibility for your own branded system to its model supplier."],
        ["Our fictional product **Northbridge Hiring** ranks applicants for an employer's shortlist. Its purpose materially influences recruitment decisions. **Harbour Diagnostics** is a fictional medical product whose case stipulates Medical Devices Regulation coverage and sector-required third-party assessment. Real medical-device classification is a separate question."],
        ["Start a release record: system name and version; intended purpose; responsible provider; intended users; release date and countries; applicable laws; unresolved facts. This is a practical working record, not a prescribed statutory form. The case exercises will add evidence before making a release recommendation."],
    ], [
        question([0], [1], "A supplier says its registration number proves conformity. What should you conclude?", "Does a database entry replace the assessment and declaration?", ("Registration alone does not establish conformity.", "It records information; the other release steps have separate functions."), ("Registration replaces the conformity assessment.", "A database entry does not perform the assessment."), ("Registration transfers responsibility to the database operator.", "The provider remains responsible for the applicable obligations.")),
        question([1], [2], "Northbridge changes the product's purpose but retains an old certificate. What is the first check?", "Which record must be matched before relying on earlier assessment evidence?", ("Match purpose, version and boundaries to the assessed system.", "Evidence must concern the system being released."), ("Match only the product's marketing name.", "The same name can conceal a different purpose or version."), ("Match only the model supplier's name.", "The model is only one dependency of the assessed system.")),
        question([2], [3], "A firm commissions a system and first uses it under its own name internally. Can it have provider duties?", "Can keeping a branded system for the firm's own first use engage provider duties?", ("Yes; own-use putting into service can engage provider duties.", "Provider status is not restricted to sales to another person."), ("No; only selling a system can create provider duties.", "The definition also includes putting into service."), ("No; commissioning always makes the model supplier the provider.", "Developing or having developed under one's own name can establish provider status.")),
    ]),
    "F02": lesson("Articles 2(2), 5, 6(1)–(4), 43; Annexes I and III", "Separate classification, applicable scope and prohibited use.", [
        ["**High-risk classification** identifies a legal route; it is not permission to use the system. Check Article 5 prohibitions separately, including each prohibition's conditions and exceptions. A conformity procedure cannot make a prohibited practice lawful."],
        ["Article 6(1) concerns a product or safety component covered by an Annex I law and subject to the specified third-party assessment condition. For **Annex I Section A**, the relevant product-law assessment route matters. Section A is a defined list, not every law regulating products."],
        ["For **Annex I Section B**, Article 2(2) limits which AI Act provisions apply; this course's ordinary Chapter III conformity pathway does not automatically apply. Record the particular sector regime rather than sending every Annex I product through the same checklist."],
        ["Article 6(2) covers the specified uses in **Annex III**. Article 6(3) can exclude certain listed systems when they pose no significant risk, including by not materially influencing decision-making, and meet a listed condition. Profiling natural persons remains high-risk. Providers relying on exclusion must document it and meet the relevant registration duty."],
        ["Northbridge's case stipulates material influence on applicant shortlisting, an Annex III employment use. Harbour's case stipulates a qualifying Section A medical-product route. Neither case determines the status of your actual product. Record unknown facts rather than treating an industry label as a completed classification."],
    ], [
        question([0], [2, 3], "A product is listed in Annex I Section B. Which review is appropriate?", "Should every Annex I product automatically follow the Section A assessment route?", ("Check the limited AI Act scope and the sector regime.", "Article 2(2) gives Section B a distinct boundary."), ("Apply the Section A assessment route automatically.", "Section A and Section B have different scope rules."), ("Ignore its sector law because AI is included.", "AI does not displace the relevant sector framework.")),
        question([1], [1], "An Article 5 practice is prohibited on the stated facts. Can a favourable assessment authorise it?", "Can a certificate cure an otherwise prohibited use?", ("No; assessment does not override the prohibition.", "Classification and conformity do not supply permission to breach Article 5."), ("Yes, if the certificate is independently issued.", "Independence does not create an exception to Article 5."), ("Yes, once the system is registered.", "Registration cannot override the prohibition.")),
        question([0], [4, 5], "The Northbridge case materially influences applicant shortlists. What should the reviewer avoid?", "Can the case be excluded from high-risk status just because a human signs the final decision?", ("Treating human sign-off alone as an Article 6(3) exclusion.", "The stipulated material influence requires a supported classification analysis."), ("Checking the specified recruitment use.", "Intended use is central to Annex III classification."), ("Recording the degree of influence on decisions.", "That fact is needed for the Article 6(3) analysis.")),
    ]),
    "F03": lesson("Articles 111(2), 113", "Use the date for the provision, not a single date for the entire course.", [
        ["A **provision-specific timeline** records which obligation applies to which system on which date. In the retained 27 July 2026 baseline, Article 113 gives a general application date of 2 August 2026 and several exceptions. Recheck the legal version for an actual release."],
        ["Chapter III **Section 4**, concerning notifying authorities and notified bodies, applies from 2 August 2025. Article 113(c) moves **Sections 1–3**, except Article 6(5), to 2 December 2027 for Article 6(2)/Annex III systems and 2 August 2028 for Article 6(1)/Annex I systems."],
        ["Chapter III **Section 5**, containing assessment, declaration, marking and registration provisions, is not expressly included in that Sections 1–3 postponement. Do not conclude that every conformity-related duty is postponed by the high-risk dates. Record the interacting provisions and seek a supported interpretation for a real transitional release."],
        ["Article 111(2) has an **existing-system transition** for qualifying high-risk systems placed on the market or put into service before the relevant Article 113(c) date: this Regulation applies only if significant design changes occur from that date, without prejudice to Article 5. The paragraph also sets a 2 August 2030 compliance deadline for providers and deployers of high-risk systems intended for public authorities. These are conditions, not a universal grace period."],
        ["For each case record first market/service date, classification route, intended public-authority use, later design changes and the provision being assessed. In these exercises a temporal question can produce **needs specialist review**, rather than an unsupported ready/not-ready verdict."],
    ], [
        question([0], [2, 3], "A reviewer says Article 113(c) postpones all of Chapter III, including Section 5. What is missing?", "Does the Sections 1–3 exception expressly postpone Section 5 too?", ("A separate reading of Section 5 and the interacting dates.", "The specified exception does not expressly list Section 5."), ("Nothing; the exception names all of Chapter III.", "It expressly identifies Sections 1–3, with an additional exception."), ("Nothing; all provisions began in August 2025.", "Section 4's date is not the date for every provision.")),
        question([1], [4], "An existing private system's provider claims a universal deadline of August 2030. Is that supported?", "Can every existing system use the public-authority provision's 2030 date?", ("No; apply the actual transition conditions to its facts.", "The public-authority deadline is not a blanket rule for all systems."), ("Yes; 2030 applies to every existing private system.", "The paragraph distinguishes the public-authority condition."), ("Yes; first-use evidence is unnecessary for transitions.", "The first market/service date is central to the transition analysis.")),
        question([0, 1], [5], "A release date is known, but first use and later design changes are unknown. What should the record say?", "What outcome fits an unresolved transition fact?", ("Needs further evidence and a dated interpretation.", "The missing facts prevent a supported temporal conclusion."), ("Ready because the product already exists.", "Existing status alone does not resolve the legal conditions."), ("Permanently prohibited because the date is uncertain.", "An unresolved transition is not itself an Article 5 prohibition.")),
    ]),
    "F04": lesson("Article 43(3); Annex I Section A", "Find the sector procedure and its additional AI evidence.", [
        ["A **sector assessment** is the conformity procedure under a particular Union product law. For high-risk systems covered by Annex I Section A, Article 43(3) directs the provider to the relevant sector procedure. The AI Act Section 2 requirements form part of that assessment; Article 17 quality management and specified Annex VII points also apply."],
        ["The specified Annex VII elements are point 3, points 4.3–4.5, the fifth paragraph of 4.6 and point 5. They concern quality management, technical evidence/assessment, changes and surveillance. Their inclusion does not mean you mechanically run two entirely separate assessment procedures."],
        ["Where sector law offers an assessment without a third party conditioned on harmonised standards, the provider must also meet Article 43(3)'s complete AI requirement-coverage condition through standards or, where applicable, common specifications. High-risk classification alone does not force a third party where sector law does not require that choice. This is a conditional option, not permission to ignore Article 6(1)'s classification test."],
        ["**Dual-route priority:** where the same system falls under both Annex I Section A and Annex III, the relevant sector procedure applies. Harbour's case stipulates the sector-required third party. Adding an Annex III use does not automatically change it to the employment internal-control route."],
        ["A sector-notified body needs the specified Article 31(4), (5), (10) and (11) competence/independence assessment evidence for transitional AI assessment powers, and must apply for Section 4 designation by 28 January 2028. Verify that evidence; a sector badge alone is insufficient. Real device class and current sector procedure remain separate source lookups."],
    ], [
        question([0], [1, 2], "Harbour follows its required medical-product procedure. Where do AI Section 2 requirements belong?", "Does sector assessment dispense with the specified AI requirements?", ("Within the relevant sector conformity assessment.", "Article 43(3) incorporates them and the specified additional elements."), ("Outside the assessment because sector law replaces them.", "They remain part of the assessment."), ("Only in the marketing description.", "Descriptions do not substitute for assessment evidence.")),
        question([1], [4], "The same Harbour system also has an Annex III use. Which assessment procedure controls?", "Which route applies to a system covered by both Section A and Annex III?", ("The applicable sector conformity procedure.", "Article 43(3)'s final subparagraph establishes this priority."), ("The Annex III route automatically replaces sector procedure.", "The amended paragraph gives the sector procedure priority."), ("The provider may choose whichever route has less paperwork.", "Convenience is not the legal route-selection rule.")),
        question([0], [3, 5], "A sector body offers AI assessment with no evidence of the specified Article 31 checks. What should Harbour do?", "Is an existing sector notification alone enough to verify transitional AI assessment powers?", ("Verify the required assessment evidence and designation timetable.", "The transitional powers are conditional on specified checks."), ("Accept the offer solely because it has a sector badge.", "The badge alone does not demonstrate the additional conditions."), ("Assume no sector body can ever assess AI requirements.", "The paragraph provides conditional transitional powers.")),
    ]),
    "F05": lesson("Articles 8–18; Annex IV(1)–(9)", "Make a usable evidence matrix and technical-file index.", [
        ["An **evidence matrix** is a practical table linking each applicable requirement to a versioned record, responsible person, demonstrated result, gap and action. The law requires conformity evidence; this table is our review method. A document's existence is not proof that its contents establish conformity."],
        ["**Technical documentation** explains the system and demonstrates its requirements. Annex IV(1) covers intended purpose/provider/version, interaction with other software and hardware, versions, market form, hardware, applicable product illustrations, interface and instructions. An index helps a reviewer locate these records for this release."],
        ["Annex IV(2) covers development and integration methods, design logic and key choices, architecture and resources, data requirements and governance, human oversight, predetermined changes, validation/testing and cybersecurity. Testing includes datasets, metrics, discriminatory-impact checks where relevant and dated signed reports. Naming a model is not a substitute for these records."],
        ["Annex IV(3)–(9) adds detailed monitoring/function/control information; appropriateness of performance metrics; risk-management description; lifecycle changes; applied standards or detailed other compliance solutions; declaration copy; and post-market monitoring system and plan. Annex IV is an index of required substance, not a claim that every sector-law file requirement is taught here."],
        ["Northbridge's matrix lists oversight controls, the tested interface version and dated human-review evidence. A blank test report remains a gap even if its index entry exists. Harbour must add the applicable sector-law records; a shared file can be useful, but every required element must still be traceable."],
    ], [
        question([0], [1, 5], "A matrix links oversight to an empty test-report file. What is the appropriate status?", "Does a filename establish that an applicable control has been demonstrated?", ("Evidence gap; obtain and evaluate the test result.", "The index entry does not establish the control's performance."), ("Complete because the file has a responsible owner.", "Responsibility does not replace the missing result."), ("Complete because oversight appears in the matrix.", "A listed requirement is not proof of conformity.")),
        question([1], [2, 3], "Northbridge's file identifies only its model supplier. What is missing?", "Can a model name stand in for system technical documentation?", ("System-specific design, data, oversight and testing records.", "Annex IV describes the system and its development, not just its supplier."), ("Only a more prominent supplier logo.", "A logo adds no design or testing evidence."), ("Nothing if the supplier promises quality.", "An assurance alone does not fulfil the technical-file content.")),
        question([0, 1], [4, 5], "Harbour combines AI and sector records in one dossier. What makes it reviewable?", "What should a reviewer require from a combined evidence file?", ("Trace each applicable requirement to current supporting evidence.", "Combination is useful only if coverage and gaps remain visible."), ("Count documents without checking their scope.", "Volume alone does not establish coverage."), ("Use the AI index to dismiss all sector requirements.", "The relevant sector obligations still need their own evidence.")),
    ]),
    "F06": lesson("Articles 3, 5, 6, 43(3), 111(2), 113; Annex IV", "Record the boundary of two fictional releases.", [
        ["**Case facts:** Northbridge v1 materially ranks recruitment applicants for a private employer. Harbour v1 analyses diagnostic images; this exercise stipulates an Annex I Section A medical product with a sector-required third party. Both providers ask whether their releases are ready. No real customer or device is being classified."],
        ["Start with intended purpose, version, named provider and release countries/date. Check prohibited practices independently. Northbridge's stipulated Annex III employment use supports its high-risk route. Harbour's stipulated sector facts support the relevant product-law route; its actual device class is outside this exercise."],
        ["The proposed Northbridge release is during an unresolved transitional period. Record the Section 5/Sections 1–3 interaction and refer it for dated interpretation. Harbour's body has not supplied the transitional competence evidence. Record that as an assessor evidence gap, not as an automatically valid appointment."],
        ["The **scope record** should distinguish a supported conclusion, an explicit case assumption and an unknown needing evidence. Add the technical-file gaps from F05. A readiness verdict must be limited to the questions actually checked; it is not a comprehensive legal clearance."],
    ], [
        question([0], [1, 2], "Which route fact is expressly stipulated for Harbour?", "What sector fact may the exercise rely on without classifying a real device?", ("Its sector law requires third-party assessment.", "That is an explicit fictional case assumption."), ("Every medical AI device has exactly the same class.", "No universal device-class conclusion is stipulated or taught."), ("A medical purpose removes all AI Act requirements.", "The stipulated route incorporates applicable AI requirements.")),
        question([0], [3], "Northbridge's Section 5 timing is unresolved. Which conclusion is supported?", "What should the case report say when the applicable-date interaction is unsettled?", ("Needs a dated interpretation before release advice.", "The record should preserve the specific uncertainty."), ("Ready because all obligations are certainly postponed.", "That blanket conclusion is not supported by the section-specific text."), ("Prohibited because any timing uncertainty is a ban.", "Unresolved timing is not itself an Article 5 prohibition.")),
        question([0], [3, 4], "Harbour's appointed body supplies no additional competence evidence. What should be recorded?", "How should an unsupported assessor qualification be handled?", ("An evidence gap with an owner and required follow-up.", "This makes the missing support visible and actionable."), ("An assumed qualification because the provider trusts it.", "Trust does not demonstrate the statutory conditions."), ("A completed medical-law compliance conclusion.", "The exercise does not establish complete sector compliance.")),
    ]),
}

LESSONS = add_registered_sources(LESSONS)
