"""Article 5 harmful behaviour, scoring and criminal-risk assessment."""

from lesson_builder import assessment

LESSONS = {
    "B01": {
        "locator": "Article 5(1), 5(8); Article 6; Article 113",
        "summary": "Read the regulated action and every prohibition element before comparing high-risk duties.",
        "screens": [
            ["A **regulated action** is what a prohibition restricts: placing on the market, putting into service, use, or a specifically qualified combination. Read the action in the relevant point.", "Some Article 5 points qualify supply by a specific purpose; the real-time remote-identification point restricts use in a particular setting. Do not replace these distinctions with 'all development is banned'. Scope exclusions still need their own test."],
            ["**Prohibition elements** are the conditions that must be examined together. A point may specify a technique, people affected, context, effect or harm, plus an exception or qualification.", "Northbridge's practical table gives each element its own evidence and records unknowns. A troubling product label may justify investigation, but does not substitute for showing the legal elements."],
            ["**Prohibited versus high-risk** separates two legal questions. A permitted practice can be high-risk and have requirements. A prohibited practice does not become permitted by meeting a high-risk checklist.", "A human reviewer, consent assertion, warning label or certificate is not a universal exception. Read the exact point to see whether and how it matters."],
            ["Also record the application date and other-law limits. Most original Chapter II rules apply from 2 February 2025; specified new provisions apply from 2 December 2026. Article 5(8) preserves prohibitions arising under other Union law.", "Our fictional cases test specified elements. Their conclusions are tied to those facts and dates; they do not authorise an actual deployment or settle every related legal issue."],
        ],
        "questions": [
            assessment([0], [1], "A reviewer says Article 5 bans every form of research and development. What should be checked?", "How should a prohibition's action scope be established?", ("The exact regulated action and relevant scope provisions", "The points regulate specified conduct with different qualifications."), ("Only a general dislike of the technology", "That does not establish the statutory action."), ("Only the phrase 'AI ban' in a headline", "A headline collapses the legal distinctions.")),
            assessment([1], [2, 4], "A case has missing harm or purpose facts. What is the sound prohibition record?", "How should unresolved elements of a prohibition be handled?", ("Identify each element and its evidence or gap", "A full test requires facts rather than assumed satisfaction."), ("Declare the label proves every element", "A name does not prove the legal conditions."), ("Hide missing facts to make a clear answer", "Clarity does not justify unsupported conclusions.")),
            assessment([2], [3], "A prohibited practice has a vendor certificate for high-risk compliance. What follows?", "Does a high-risk checklist cure an Article 5 prohibition?", ("The prohibition still needs to be respected", "Classification compliance is not permission for forbidden conduct."), ("The certificate overrides every prohibition", "No general certificate exception is supplied."), ("A disclosure alone removes the prohibition", "Disclosure is not a universal Article 5 exception.")),
        ],
    },
    "B02": {
        "locator": "Article 5(1)(a)",
        "summary": "Trace the manipulation/deception test from technique through impaired decision-making to significant harm.",
        "screens": [
            ["The **manipulation-technique test** concerns subliminal techniques beyond awareness or purposefully manipulative or deceptive techniques deployed by an AI system.", "Not every persuasive recommendation automatically meets this point. Identify the technique and facts supporting its character instead of treating 'advertising' as either always banned or always permitted."],
            ["The point requires an objective or effect of materially distorting behaviour by appreciably impairing the ability to make an informed decision. That leads to a decision the person would not otherwise take.", "Our **causal test** traces the chain: technique, impaired informed choice, changed decision and harm. Each connection needs evidence; mere AI use or an unpopular decision does not prove the chain."],
            ["The decision must cause or be reasonably likely to cause significant harm to that person, another person or a group. Harm need not already have happened, but its likelihood and significance cannot simply be asserted.", "Fictional Northbridge case: stipulated deceptive pressure impairs an informed choice and produces a purchase decision reasonably likely to cause significant harm. The stipulated facts support the element exercise, not a general conclusion about all recommendations."],
            ["Changed fact: the communication is clear and informative with no appreciable impairment. The same sale outcome does not by itself prove the prohibition. Changed fact: intended manipulation causes no completed injury yet. Examine the reasonably-likely harm branch.", "Record technique, objective/effect, behavioural distortion, changed decision and significant harm. Do not invent a universal monetary threshold that the point does not supply."],
        ],
        "questions": [
            assessment([0], [1], "An AI-generated advert exists. Does that fact alone establish the manipulation prohibition?", "Which starting fact does Article 5(1)(a) require beyond the mere presence of persuasion?", ("A relevant subliminal/manipulative/deceptive technique", "The point specifies techniques rather than all advertising."), ("Only that a product was promoted", "Promotion alone does not establish the technique."), ("Only that a viewer disagreed with the message", "Disagreement is not the specified technique test.")),
            assessment([1], [2], "What must connect the technique to the changed decision?", "Why does a harmful outcome alone not establish every element of Article 5(1)(a)?", ("Appreciably impaired informed choice and material distortion", "The point requires this causal decision-making relationship."), ("Only the same software being installed", "Installation does not establish impaired choice or causation."), ("Only a human being somewhere in the business", "General human presence does not supply the causal test.")),
            assessment([1], [3, 4], "No injury has occurred yet, but the changed decision is reasonably likely to cause significant harm. Is completed harm required?", "Can the harm branch apply before significant harm actually occurs?", ("Reasonably likely significant harm is also covered", "The point expressly includes a reasonably-likely branch."), ("Completed harm is always required", "That omits the alternative statutory branch."), ("No harm analysis is ever necessary", "Likelihood and significance still need evidence.")),
        ],
    },
    "B03": {
        "locator": "Article 5(1)(b)",
        "summary": "Identify protected vulnerability, exploitation and the material-distortion/significant-harm relationship.",
        "screens": [
            ["The **protected-vulnerability test** concerns vulnerabilities due to age, disability, or a specific social or economic situation. Identify the relevant person or group and the actual vulnerability.", "A broad statement that 'everyone can be influenced' does not by itself show the stated basis. Nor does membership of a group automatically prove the system exploits a vulnerability."],
            ["Article 5(1)(b) concerns an AI system exploiting such vulnerability with the objective or effect of materially distorting behaviour in a way causing, or reasonably likely to cause, significant harm to that person or another person.", "The **exploitation-harm test** keeps these elements linked. The point does not say every service offered to older people or disabled people is forbidden."],
            ["Fictional Northbridge case: a system deliberately exploits a specified economic vulnerability to materially distort choices, with stipulated reasonably likely significant harm. Those facts support the prohibition-element exercise.", "Changed case: a system offers accessible instructions that help a person make an informed choice without exploitation. The audience's vulnerability alone does not produce the same conclusion."],
            ["Record the vulnerability's stated basis, exploitative operation, objective/effect, material distortion and significant harm. Distinguish helpful adaptation from exploitation using evidence.", "No completed injury is required where the reasonably-likely harm branch is established. Conversely, do not erase the harm test merely because the system targets a protected vulnerability."],
        ],
        "questions": [
            assessment([0], [1], "Which basis is expressly named in the vulnerability prohibition?", "What vulnerability basis should be checked under Article 5(1)(b)?", ("Age, disability or specific social/economic situation", "Those are the point's specified vulnerability bases."), ("Only whether a person dislikes computers", "That does not establish one of the stated bases by itself."), ("Only a supplier's small company size", "The point concerns vulnerabilities of affected people or groups.")),
            assessment([1], [2, 3], "Accessible instructions help a disabled user choose without exploitation or material distortion. Does the audience alone prove the prohibition?", "Does serving a vulnerable group automatically establish exploitative AI conduct?", ("No; exploitation and the remaining elements need evidence", "The group context does not replace the conduct/harm test."), ("Yes; every accessible service is forbidden", "That turns protection into an unsupported blanket ban."), ("Yes; significant harm never needs assessment", "The point includes significant harm or its reasonable likelihood.")),
            assessment([1], [2, 4], "A system exploits economic vulnerability and distorts behaviour, but the significant-harm facts are missing. What should the record say?", "How should an incomplete exploitation-harm chain be assessed?", ("The harm element remains unresolved", "The test requires evidence for causation or reasonable likelihood of significant harm."), ("The audience proves every missing element", "Vulnerability cannot substitute for harm evidence."), ("A warning automatically cures the exploitation", "No blanket warning exception is supplied.")),
        ],
    },
    "B04": {
        "locator": "Article 5(1)(c), 5(1)(c)(i), 5(1)(c)(ii)",
        "summary": "Apply the social-scoring test and its alternative unrelated-context and disproportionate-treatment branches.",
        "screens": [
            ["The **social-scoring test** concerns AI evaluating or classifying people or groups over time from social behaviour or known, inferred or predicted personal/personality characteristics.", "That evaluation must lead to specified detrimental or unfavourable treatment. A score existing alone does not establish the whole prohibition; examine what it does to people."],
            ["The first treatment branch concerns social contexts unrelated to where the data were generated or collected. Trace the source context and the treatment context rather than assuming all data use crosses this boundary.", "Fictional Northbridge case: a score drawn from unrelated social conduct is used to deny a service in another context. The stipulated unrelated contexts and detrimental effect let us test this branch."],
            ["The second branch concerns treatment unjustified or disproportionate to the social behaviour or its gravity. It can matter even without an unrelated-context finding.", "The branches are alternatives: either or both can satisfy this part of the test. Do not require both in every case. A relevant data context does not by itself cure disproportionate treatment."],
            ["Record evaluation over time, input characteristics, score, treatment and the applicable branch. This point is not a general prohibition on every numerical score or every credit assessment.", "Other Article 5 points, high-risk classification and personal-data law can still apply when this particular social-scoring test is not established. Keep the conclusion exact."],
        ],
        "questions": [
            assessment([0], [1, 4], "A number is assigned to a person. Is that enough for the full social-scoring prohibition?", "Which fact must a social-scoring assessment establish beyond a numerical output?", ("The specified evaluation and detrimental-treatment relationship", "The point contains both evaluation and treatment elements."), ("Every number is automatically prohibited", "A score alone does not establish the complete test."), ("Only a colourful chart", "Display form does not establish legal elements.")),
            assessment([0], [2], "A social score causes detrimental treatment in an unrelated context. Which branch is relevant?", "What should be traced for the unrelated-context social-scoring branch?", ("Data-generation context and resulting treatment context", "The branch compares those contexts."), ("Only the server's country", "That does not establish context relationship."), ("Only the software's price", "Price does not decide the treatment branch.")),
            assessment([0], [3], "Treatment is stipulated disproportionate to the scored behaviour, but the context is related. Must both branches fit?", "Can the disproportionate-treatment branch operate without the unrelated-context branch also being met?", ("Either treatment branch can suffice", "Article 5(1)(c) states either or both."), ("Both branches are always required", "That incorrectly makes alternative branches cumulative."), ("No treatment element is required at all", "At least a specified detrimental-treatment branch still matters.")),
        ],
    },
    "B05": {
        "locator": "Article 5(1)(d); Annex III 6",
        "summary": "Distinguish individual criminal-risk prediction from support of human assessment already based on linked facts.",
        "screens": [
            ["The **criminal-risk ban** concerns AI risk assessment predicting whether a natural person will commit a criminal offence, based solely on personal profiling or assessment of personality traits and characteristics.", "Identify the predicted event, person and basis. A tool's output being called 'risk intelligence' does not resolve those elements."],
            ["The point provides a boundary for AI supporting human assessment of involvement in criminal activity already based on objective, verifiable facts directly linked to criminal activity.", "The **factual-human-support boundary** is not satisfied by adding a person after a purely trait-based prediction. The existing human assessment and linked facts must be shown."],
            ["Fictional Northbridge clinic: a system predicts offending solely from personality traits. A human signs the flag without a pre-existing linked factual assessment. Those facts do not establish the support boundary.", "Changed case: a human assessment of involvement already rests on specified objective/verifiable facts directly linked to criminal activity, and the AI supports it. Examine that boundary and other law separately; it is not blanket permission for any later use."],
            ["Keep Article 5 distinct from Annex III enforcement classification. A permitted support function may still require high-risk analysis. A prohibited trait-based function cannot be authorised by an Annex III listing.", "Record the facts, their direct link, human assessment's timing and the actual support function. Do not invent criminal suspicion from a demographic or personality correlation."],
        ],
        "questions": [
            assessment([0], [1], "AI predicts an individual's offending risk solely from personality traits. Which issue is directly raised?", "What basis is central to the individual criminal-risk prohibition?", ("Sole profiling or personality assessment", "That basis is expressly covered by the point's test."), ("Only the product's short name", "A name does not establish the prediction basis."), ("Only the presence of a user interface", "Interface presence does not resolve the prohibition.")),
            assessment([1], [2, 3], "A person approves a trait-based prediction with no earlier linked factual assessment. Is that enough for the support boundary?", "Can human approval alone establish the factual-support exception in Article 5(1)(d)?", ("No; a prior linked factual assessment must be established", "The boundary requires more than a final signature."), ("Yes; any human button is sufficient", "That omits the objective/verifiable directly linked facts."), ("Yes; personality correlation creates linked facts", "A trait correlation is not automatically the required direct factual link.")),
            assessment([0, 1], [4], "The factual-support boundary is established in a stipulated case. What remains?", "Does being outside this particular ban settle every enforcement AI duty?", ("Other law and high-risk classification still need checks", "The boundary is narrow, not complete compliance permission."), ("Every legal duty disappears", "One prohibition result does not erase the other rules."), ("Annex III now permits prohibited functions too", "Classification cannot authorise a separate prohibited practice.")),
        ],
    },
    "B06": {
        "locator": "Article 5(1)(a)–(d), Article 6; Annex III 5(b), 6",
        "summary": "Compare manipulation, exploitation, social scoring and criminal prediction using changed facts.",
        "screens": [
            ["The **harmful-decision case** follows fictional Northbridge across three proposals: a persuasive sales assistant, a service eligibility score and an individual offending predictor.", "The same AI model can appear in all three, but the legal tests differ. Record techniques, vulnerabilities, evaluation over time, treatment, prediction basis and people affected."],
            ["For sales persuasion, check whether the relevant technique appreciably impairs informed choice, materially changes behaviour/decision and causes or is reasonably likely to cause significant harm. Vulnerability exploitation has its own stated basis and chain.", "A helpful, accessible explanation and a deceptive harmful pressure technique have different stipulated facts. Do not classify them identically just because both influence decisions."],
            ["For eligibility scoring, test evaluation over time and the unrelated-context or unjustified/disproportionate-treatment branch. For offending prediction, test sole profiling/personality basis and the linked-facts human-support boundary.", "A creditworthiness function is not automatically prohibited social scoring. A final human approver is not automatically sufficient for the criminal-risk support boundary."],
            ["The case result should cite the exact point, elements, evidence and unresolved facts. If this particular prohibition is not established, continue high-risk, scope, date and other-law analysis.", "If a prohibition is established, a warning label or high-risk checklist does not cure it. The exercise teaches traceable legal reasoning rather than a permanent label for a model or vendor."],
        ],
        "questions": [
            assessment([0], [1, 2], "A clear explanation and deceptive pressure both influence customers. What determines the manipulation analysis?", "Should all AI persuasion receive the same prohibition result?", ("The exact technique and causal harm elements", "Influence alone does not establish the full manipulation test."), ("Only the fact that AI is used", "The statutory elements need separate facts."), ("Only whether the same model powers them", "A shared model does not make conduct identical.")),
            assessment([0], [3], "A score causes disproportionate treatment in a related context. Which reasoning is sound?", "Does a related data context always rule out the social-scoring prohibition?", ("Test the alternative disproportionate-treatment branch", "Either treatment branch can matter."), ("Stop because unrelated context is always required", "That omits the alternative branch."), ("Assume every credit score is prohibited", "The full social-scoring elements still need evidence.")),
            assessment([0], [3, 4], "A human approves offending predictions solely from traits, without linked prior facts. What should the clinic record?", "Which conclusion cannot be justified by a final human signature alone?", ("The factual-human-support boundary is unproven", "A final signature does not establish the required earlier factual assessment."), ("All prohibition concerns are cured", "Human involvement is not a universal cure."), ("The model can never have any lawful use", "This case concerns specified conduct, not every possible model use.")),
        ],
    },
}
