"""Risk controls, data governance and exceptional bias processing."""
from high_risk_content import lesson, question as q

LESSONS = {
'H07': lesson('Article 9(4)–(10)', 'Choose feasible controls and define appropriate tests before supply.', [
['The **risk-control hierarchy** starts with eliminating or reducing identified risks as far as technically feasible through design and development. Where appropriate, add controls for risks that cannot be eliminated, then supply information and, where appropriate, deployer training.', 'For Northbridge, a feasible design limit preventing an unsupported automatic rejection deserves consideration before merely adding a disclaimer. These are illustrative measures, not a prescribed architecture.'],
['Take account of combined measures and the expected deployer’s technical knowledge, experience, education, training and use context. A control that only a specialist can operate may fail in the actual recruitment team.', 'A warning or training can matter, but it does not substitute automatically for feasible design risk reduction.'],
['**Prior test criteria** are purpose-appropriate metrics and probabilistic thresholds defined before testing. Tests identify suitable targeted measures and check consistent intended performance and compliance.', 'Test as appropriate throughout development and always before market placement or service. Real-world testing has its own Article 60 conditions; calling an unreviewed rollout a test does not remove them. The Act supplies no single recruitment accuracy percentage.'],
['**Vulnerable-person risk** requires considering whether the intended use is likely to harm people under 18 and, as appropriate, other vulnerable groups. For a stipulated youth-apprenticeship use, include the relevant risks rather than relying only on adult-office results.', 'Record a risk, its measure, the prior test criterion, findings and residual-risk judgment. Where another Union-law process applies, integration can preserve this evidence without duplicating the whole procedure.']], [
q([0],[1,2], 'A feasible design restriction reduces unsupported automatic rejection. May a disclaimer alone replace consideration of that restriction?', 'Which control approach fits a feasible design reduction of a recruitment hazard?', ('Consider design reduction, then remaining controls and information','Article 9 gives the design-first sequence.'),('Choose the disclaimer without evaluating the design','Information alone does not replace technically feasible reduction.'),('Ignore the actual reviewer’s capabilities','Measures must consider expected users and context.')),
q([1],[3], 'Northbridge chooses its pass threshold only after seeing favourable test results. What is missing?', 'Can a threshold selected after the results serve as the prior criterion?', ('A purpose-appropriate criterion defined before testing','Testing must use prior defined metrics and thresholds.'),('The universal EU recruitment score','No universal score is established here.'),('A rule that testing begins only after sale','Pre-supply testing is required.')),
q([2],[4], 'A ranking system is intended for youth apprenticeships but tested only for adult-office risks. What needs review?', 'Which intended-audience issue is missing from the apprenticeship review?', ('Likely adverse impacts on under-18 users and relevant vulnerable groups','Article 9(9) requires this consideration.'),('Only whether an adult accepted the disclaimer','That does not assess the intended youth risks.'),('Whether every conceivable group uses it','The requirement is related to intended purpose.'))]),
'H08': lesson('Article 10(1), (2)(a)–(e), (6)', 'Identify dataset purposes, origins and preparation decisions.', [
['A **training dataset** is used to fit a model. A **validation dataset** helps evaluate and choose or tune development choices. A **testing dataset** assesses performance against the chosen criteria.', 'Where model training uses data, Article 10’s quality criteria apply whenever the relevant sets are used. For high-risk systems not using model-training techniques, paragraphs 2–4 and Article 4a(1) apply only to testing sets. Do not demand a fictional training set where no training occurs.'],
['**Dataset provenance** records collection processes and origin. For personal data, include the original collection purpose. Northbridge receiving old applicant records does not by itself establish permission for every new use.', 'Data governance also records design choices, assumptions about what the data measures or represents, and availability, quantity and suitability of needed sets. A purchase receipt is not a complete provenance record.'],
['**Data preparation** includes annotation, labelling, cleaning, updating, enrichment and aggregation. Annotation adds descriptive information; labelling assigns the target or category used for a task.', 'A label “successful applicant” may reflect past hiring preferences rather than future job competence. Record the assumption before treating it as a suitable target. Document relevant preparation operations so the result can be explained.'],
['Case: Northbridge has applicant records, unknown original purpose, undocumented cleaning and labels based only on past selection. Ask for evidence of origins, permissions, preparation and what the target represents.', 'Keeping dataset roles distinct helps inspect which evidence supports which development choice. A large folder called “training” does not establish appropriate governance.']], [
q([0],[1], 'A high-risk system uses no model-training technique. Which data sets does Article 10(6) address?', 'Does Article 10(6) require inventing training data for a system that does not train models?', ('Testing data sets for the specified criteria','The paragraph confines those criteria to testing sets.'),('A compulsory new training set','No such invention is required by that paragraph.'),('No data-quality review at all','Testing sets remain covered.')),
q([1],[2,4], 'A purchased applicant file has no evidence of its original collection purpose. What is missing?', 'Does proof of purchase fully establish personal-data provenance?', ('Collection origin and original-purpose evidence','Article 10(2)(b) includes these facts.'),('Only a larger file size','Quantity does not explain origin or purpose.'),('Only the customer’s trading name','That does not establish collection history.')),
q([2],[3,4], 'Northbridge labels past selected applicants as competent without checking the assumption. What should it document and examine?', 'What is the concern when old hiring decisions define the training target?', ('Preparation and what the labels actually represent','Labels can reflect decisions rather than the claimed ability.'),('Only the name of the folder','A label on storage does not establish suitable targets.'),('No preparation information once labels exist','Preparation and assumptions require governance.'))]),
'H09': lesson('Article 10(2)(e), (h), (3), (4)', 'Assess data suitability for people and deployment context.', [
['**Representation** means the data adequately reflects relevant people or groups for the intended purpose. Sets must be relevant, sufficiently representative and, to the best extent possible, error-free and complete.', 'Appropriate statistical properties may be met within individual sets or their combination. Neither “perfect data always” nor “large data is enough” states the statutory standard.'],
['**Deployment-context fit** asks whether data reflects relevant geographical, contextual, behavioural and functional settings. Northbridge’s past office-role applicants do not automatically validate a new apprenticeship use in another labour market.', 'Record which differences matter to the intended purpose. Size does not answer whether language, application forms or job types have changed.'],
['**Data-gap remediation** identifies relevant missing or weak data that prevents compliance and how to address it. Include needed availability, quantity and suitability in the assessment.', 'For an unsupported group or context, possible responses include obtaining suitable data, changing the permitted scope or holding that use pending evidence. These are assessor choices; the statute does not prescribe one universal collection method.'],
['Case: a very large set excludes a group relevant to the intended deployment. An overall performance claim cannot by itself establish suitability for that group.', 'The file should connect purpose, people, context, gaps, measures and resulting evidence. An unresolved gap stays a limitation or gate rather than disappearing into the average.']], [
q([0],[1,4], 'Northbridge’s large dataset excludes a relevant applicant group. Does size establish sufficient representation?', 'Can volume alone cure missing evidence for an intended group?', ('No; assess relevant representation and statistical properties','Purpose and relevant groups determine suitability.'),('Yes; volume replaces group analysis','Large sets can still omit relevant groups.'),('Only absolutely perfect sets satisfy the law','The text uses “to the best extent possible” for errors and completeness.')),
q([1],[2], 'An office-role dataset is reused for apprenticeships in a different language setting. What matters?', 'Which review is needed when job and language settings change?', ('Fit to the relevant deployment context','Geographical, behavioural and functional elements can matter.'),('Only keeping the old dataset name','A name does not prove fit.'),('Only the supplier’s total customer count','Customer count does not validate this use.')),
q([2],[3,4], 'The intended group has no supporting data and the gap prevents compliance. What is supported?', 'How should an unresolved material data gap affect the dossier?', ('Specify remediation or hold/restrict the unsupported use','Identify gaps and how they can be addressed.'),('Hide it inside the overall average','That removes material evidence from the review.'),('Treat it as resolved when the team signs','Signatures cannot supply missing evidence.'))]),
'H10': lesson('Article 10(2)(f), (g); Article 15(4), continuing-learning clause', 'Detect harmful bias and address feedback that reinforces it.', [
['A **bias feedback loop** occurs when outputs influence inputs for future operation. Northbridge recommends candidates; resulting hires become its next learning records. Prior mistakes may then be reinforced.', 'Article 10 examines possible biases likely to affect health/safety, harm fundamental rights or cause prohibited discrimination, especially with such feedback. A prediction’s repetition does not independently validate it.'],
['**Bias mitigation** means appropriate measures to detect, prevent and mitigate the biases identified through that examination. Start by examining collection, labels, representation and operation against the intended purpose.', 'An equal-looking aggregate statistic is not conclusive evidence that every relevant group or decision context is protected. Do not infer prohibited discrimination from one unexplained difference either; investigate evidence and applicable law.'],
['For systems continuing to learn after supply, Article 15(4) requires reducing or eliminating as far as possible the risk of biased outputs influencing future inputs, with appropriate mitigation measures.', 'Illustrative controls include separately reviewing labels or restricting automatic reuse pending validation. Select controls on evidence rather than declaring one method universally mandatory.'],
['Case: Northbridge retrains from its own accepted recommendations and reports growing agreement with past hires. That agreement can measure a self-reinforcing pattern rather than better recruitment performance.', 'Document the identified bias, its likely rights or safety consequence, the control and the evidence after correction. Sensitive personal data is not automatically authorised merely because the project concerns fairness.']], [
q([0],[1,3,4], 'Northbridge trains on hires produced by its earlier ranking and treats growing agreement as proof of fairness. What is the concern?', 'Why may agreement with past model-influenced hires fail to prove improved performance?', ('Outputs may reinforce biased future inputs','The data can carry the system’s own prior selection pattern.'),('Agreement always independently proves fairness','The supposed evidence is affected by earlier outputs.'),('Only independent random errors can create bias','Selection and labels can contribute too.')),
q([1],[2,4], 'An overall score looks equal but relevant-group evidence is missing. What should the assessor do?', 'Can one aggregate equality statistic close the identified-bias review?', ('Examine the relevant bias and appropriate targeted measures','Aggregate appearance is not conclusive purpose-specific evidence.'),('Declare compliance from that statistic alone','Relevant groups and contexts remain unresolved.'),('Declare unlawful discrimination from any difference alone','Evidence and the applicable discrimination law matter.')),
q([1],[3], 'A system keeps learning after supply. How should biased-output reuse be handled?', 'Does continuing learning justify uncontrolled reuse of prior recommendations?', ('Reduce the feedback risk with appropriate mitigation','Article 15 specifically addresses continuing-learning feedback.'),('Reuse outputs automatically without review','That can propagate the identified risk.'),('Treat every fixed method as legally required','Controls must fit the circumstances and risks.'))]),
'H11': lesson('Article 4a(1)(a)–(f), (2); Article 10(2)(f), (g)', 'Apply strict necessity and every safeguard for exceptional sensitive-data processing.', [
['**Special categories of personal data** include particularly protected data such as health or racial/ethnic-origin information. Article 4a(1) permits exceptional processing by high-risk providers only to the extent strictly necessary for the specified bias detection and correction.', 'First show that other data, including synthetic or anonymised data, cannot effectively achieve the objective. Synthetic data is generated rather than collected from the actual person; anonymised data no longer identifies the person. Convenience or curiosity is not strict necessity. Applicable data-protection provisions continue to apply.'],
['**Sensitive-bias safeguards** all apply: technical limits on reuse; state-of-the-art security and privacy-preserving measures, including pseudonymisation; protected data with strict documented access only by authorised persons under confidentiality duties.', 'Pseudonymisation replaces identifying details while keeping the possibility of re-linking under protection; it is not anonymisation. A confidentiality promise alone does not establish the required access or technical measures.'],
['The data must not be transmitted, transferred or otherwise accessed by other parties. Delete it when the bias is corrected or its retention period ends, whichever comes first.', 'The processing record must explain strict necessity and why other data could not achieve the objective. Sending the sensitive dataset to an external analytics supplier fails the no-other-party condition, even if that supplier signs confidentiality terms.'],
['The **extended bias permission** in 4a(2) reaches other-system/model providers and deployers, including high-risk deployers, for strictly necessary correction of qualifying likely safety/rights/discrimination biases. Every paragraph 1 condition and safeguard still applies.', 'Paragraph 2 creates no new obligation to perform bias detection and correction. It is a conditional permission, not a general right to collect sensitive data and not an exemption from data law.'],
['Case: Northbridge wants health information to investigate a specific suspected bias. Its file must substantiate necessity, failed alternatives, all protections, access limits, deletion timing and the data-law analysis.', 'If any required condition is absent, this exception is not established. Keep the proposal on hold under this route rather than treating a fairness aim as enough.']], [
q([0],[1,5], 'Northbridge wants health data because it is easier, while anonymised data could effectively detect the bias. Is necessity established?', 'Does convenience satisfy Article 4a when effective other-data alternatives exist?', ('No; effective alternatives defeat this necessity condition','The objective must not be effectively achievable using other data.'),('Yes; any fairness purpose is enough','The exception requires strict necessity and all conditions.'),('Yes; protection is optional after naming a bias','Safeguards remain mandatory.')),
q([1],[2,3], 'A confidential external analyst requests the special-category dataset. Does a confidentiality contract alone satisfy 4a(1)(d)?', 'May another party access the exceptional-bias data solely because it promised secrecy?', ('No; other-party access is barred by this condition','Confidentiality does not remove the no-transfer/access rule.'),('Yes; the promise replaces all access restrictions','The conditions operate together.'),('Yes; pseudonymisation automatically makes it anonymous','Pseudonymisation can preserve re-identification.')),
q([2],[4], 'A deployer relies on 4a(2) for qualifying bias correction. What changes?', 'Does the broader actor permission remove the paragraph 1 safeguards or create a new duty?', ('Neither; permission remains conditional and adds no new bias duty','Both limits are explicit.'),('It grants unrestricted sensitive-data collection','Strict necessity and every safeguard still apply.'),('It requires every deployer to collect sensitive data','Paragraph 2 creates no such obligation.'))]),
'H12': lesson('Articles 4a and 10; Article 15(4)', 'Review a concrete data and bias proposal with an evidence-based hold decision.', [
['Case file: Northbridge’s recruitment data excludes a relevant group; historic selected applicants define the target label; its own recommendations feed the next training batch. These stipulated facts create questions about representation, assumptions and feedback.', 'Do not classify every statistical difference as unlawful. Identify the actual harm or discrimination concern, its supporting evidence and the intended use affected.'],
['The proposed fix is to collect health information without checking alternatives and send it to an external analytics vendor. Neither convenience nor a vendor confidentiality promise meets Article 4a’s complete test.', 'Request evidence that bias correction is strictly necessary and cannot effectively use other data. The stated external-party access is incompatible with that exception’s safeguard.'],
['A revised file needs purpose-fit and group evidence, explained labels, feedback measures and their validation. If exceptional sensitive processing is proposed, substantiate every condition, protected authorised access, processing records and deletion at the earlier event.', 'These are practical evidence requests derived from the requirements. The Act does not prescribe this course’s invented folder names or a single fairness score.'],
['Supported decision: hold the unsupported use and the proposed exceptional processing route until the material gaps are resolved. Assign owners for data evidence, revised controls and applicable data-law checks.', 'A conditional hold is stronger reasoning than calling the entire company non-compliant on incomplete facts. State exactly what the file fails to establish, and what evidence could change the decision.']], [
q([0],[1,3], 'A huge dataset omits the intended group and uses unexamined historic selections as targets. What should the review request?', 'Which evidence is missing from Northbridge’s supplied data case?', ('Group/context fit and an explanation of the target assumptions','Quantity does not establish suitability or label validity.'),('Only a larger record count','That can reproduce the same gap.'),('Only a new name for the target label','Renaming does not examine what it measures.')),
q([0],[2,3], 'Can the proposed health-data transfer proceed under Article 4a on the stated facts?', 'Do an untested necessity claim and external confidential analytics access establish the exception?', ('No; necessity is unproved and other-party access fails a safeguard','Every condition must hold.'),('Yes; the objective is labelled fairness','An objective alone is insufficient.'),('Yes; the vendor signs a confidentiality promise','The no-other-party-access condition still applies.')),
q([0],[4], 'Which case decision is best supported by the evidence?', 'How should the assessor state the outcome of these unresolved material gaps?', ('Hold the unsupported proposal, identify gaps and owners','The conclusion is specific and conditional.'),('Certify the whole product immediately','The material evidence is missing.'),('Declare every future use permanently forbidden','The evidence does not support that blanket conclusion.'))]),
}
