"""Deployment operation, information, impact assessment and final dossier."""
from high_risk_content import lesson, question as q

DPIA = [{'title': 'EDPB: data protection impact assessment and its separate likely-high-risk trigger', 'url': 'https://www.edpb.europa.eu/topics/accountability-and-compliance-tools/data-protection-impact-assessment_en'}]

LESSONS = {
'H25': lesson('Article 26(1)–(4)', 'Implement instructed use with capable oversight and controlled-input quality.', [
['**Instructed use** requires appropriate technical and organisational measures to use a high-risk system according to its accompanying instructions. A supplier’s design obligations and an employer’s actual operating arrangements are different.', 'For Northbridge’s employer customer, map the permitted recruitment purpose, limits, maintenance and intervention arrangements to the actual workflow. Buying the service does not itself implement those measures.'],
['**Oversight assignment** is to natural persons with the necessary competence, training, authority and support. Competence concerns ability to perform the task; authority and support enable them to act on it.', 'A trained recruiter who is forbidden to override a result is not an adequately empowered overseer. A senior title without the needed understanding is also insufficient. The system must separately enable effective controls.'],
['Other Union or national duties still apply. The deployer remains free to organise its own resources and activities to implement the provider’s indicated oversight measures.', 'This freedom does not permit removing effective oversight. Record responsibilities and demonstrate that the arrangement works in the intended operating context.'],
['**Controlled-input quality** under current Article 26(4) means ensuring inputs are relevant and sufficiently representative for the intended purpose to the extent the deployer controls them. It is distinct from provider dataset-development governance.', 'Case: the employer can change the candidate fields it submits. It must assess those controlled inputs; it cannot dismiss the duty because the supplier trained the model. Conversely, do not claim this paragraph makes it control unavailable upstream data.']], [
q([0],[1,3], 'The employer buys Northbridge but has no workflow implementing its required limits. What is missing?', 'Does purchase alone establish instructed use?', ('Appropriate operating measures implementing the instructions','Article 26 concerns actual use arrangements.'),('Only evidence of payment','Payment does not implement limits.'),('Only the provider’s private technical file','The deployer must arrange its own instructed use.')),
q([1],[2,3], 'A trained reviewer lacks permission or support to stop use. Is oversight assignment established?', 'Does training alone satisfy the assignment requirements?', ('No; competence, training, authority and support all matter','The assigned person needs the stated capacities and backing.'),('Yes; training replaces authority','Authority is separately required.'),('Yes; a job title replaces demonstrated competence','Title alone proves no capability.')),
q([2],[4], 'The employer controls the input fields but says only supplier training data matters. What should it check?', 'Which input obligation applies to data the deployer actually controls?', ('Relevance and sufficient representation for intended purpose','Article 26(4) applies to its controlled inputs.'),('Only the upstream model’s original filename','That does not assess these inputs.'),('Every upstream datum it cannot control','The paragraph qualifies the duty by control.'))]),
'H26': lesson('Articles 3(49), 26(5), (6), 79(1)', 'Monitor operation, suspend qualifying risk use and preserve controlled logs.', [
['**Deployer monitoring** follows the instructions and, where relevant, informs providers under the post-market monitoring framework. Article 79 risk includes the relevant health/safety or fundamental-rights concerns.', 'If there is reason to consider instructed use may produce that risk, inform the provider or distributor and the relevant market-surveillance authority without undue delay, and suspend use. Monitoring is not just recording that the page loaded.'],
['A **serious incident** is an AI-system incident or malfunction that directly or indirectly leads to death or serious health harm, serious irreversible disruption of critical-infrastructure management or operation, infringement of Union-law obligations protecting fundamental rights, or serious property/environment harm. Establish the outcome and the causal connection.', 'When identified, the deployer also immediately informs first the provider, then importer or distributor and relevant market-surveillance authorities. If the provider cannot be reached, Article 73 applies with the necessary adaptations. Detailed incident categorisation and deadlines require the operations course.'],
['The communication obligation does not cover sensitive operational data of law-enforcement deployers. Specified financial institutions’ Union financial-law governance arrangements can fulfil the stated monitoring obligation.', 'These are qualified boundaries, not permission for every organisation to ignore monitoring or withhold all incident information. Record which qualification is actually established.'],
['**Deployer log custody** concerns automatically generated logs to the extent under its control. Keep them for a purpose-appropriate period of at least six months unless applicable law provides otherwise, particularly data-protection law.', 'Specified financial institutions maintain them within their relevant financial documentation. Provider logging capability and provider custody do not automatically establish the employer’s separate controlled-log arrangements.'],
['Case: an employer has reason to consider instructed use creates qualifying rights risk, yet keeps ranking candidates while it waits for its vendor’s quarterly reply. Suspend and escalate under the stated trigger.', 'Identify actual controlled logs, preservation and access arrangements. Do not conceal relevant risk evidence by treating log minimisation as a universal permission to delete everything.']], [
q([0],[1,5], 'The employer has the specified reason to consider instructed use may create Article 79 risk. What should happen?', 'May the employer keep using the system while waiting for the next vendor review?', ('Suspend use and notify the specified parties without undue delay','Article 26(5) states this risk response.'),('Continue until the vendor grants permission to stop','Suspension does not depend on that permission.'),('Only log that the page loaded','That does not address the identified risk.')),
q([0],[2], 'The employer identifies a serious incident. What sequence belongs in its immediate information response?', 'Who is informed first under the deployer serious-incident clause?', ('First provider, then importer/distributor and relevant authorities','The paragraph specifies this sequence.'),('Only its marketing department','That omits the statutory recipients.'),('No one if the provider cannot be reached','The Article 73 adapted route remains.')),
q([1],[4], 'The employer controls operational logs but says the provider’s custody policy removes its own duty. Is that sound?', 'Does vendor log custody alone settle the deployer’s controlled-log retention?', ('No; establish its own controlled-log arrangements and qualified period','Article 26(6) allocates a separate duty.'),('Yes; only one actor can hold a log duty','Provider and deployer obligations can both apply.'),('Yes; every controlled record may be deleted immediately','That ignores the qualified minimum period.'))]),
'H27': lesson('Article 26(7), (8), (11), (12)', 'Distinguish workplace, public-registration and affected-person information gates.', [
['**Workplace information** is required before an employer puts a high-risk system into service or uses it at work. Inform workers’ representatives and affected workers that they will be subject to its use.', 'Apply relevant Union/national worker-information rules and procedures where applicable. A notice after use begins does not meet the stated before-use timing. Specific national procedures need a separately sourced jurisdiction check.'],
['**Public-deployer registration** applies to public authorities and Union institutions, bodies, offices or agencies through Article 49. If such a deployer finds its proposed high-risk system unregistered in the relevant EU database, it must not use it and must inform provider or distributor.', 'Determine the applicable registration route and any protected database arrangements rather than relying only on a public search page. Our public-authority case expressly stipulates that required registration is missing.'],
['**Affected-person information** under 26(11) concerns Annex III high-risk systems making or assisting decisions about natural persons. Inform those persons that they are subject to use of the high-risk system.', 'It is separate from Article 50’s interaction and content notices. The law-enforcement qualification refers to Article 13 of the Law Enforcement Directive; do not copy an ordinary recruitment notice into that specialist context without checking it.'],
['Deployers also cooperate with competent authorities in actions implementing the Regulation. Put each information/cooperation task against its own actor, recipient, trigger and timing.', 'Case: informing workers does not automatically inform job applicants affected by an Annex III assisted decision. A private employer is not a public authority merely because its recruitment affects people. Keep the three gates distinct.']], [
q([0],[1], 'An employer informs affected workers and their representatives only after high-risk workplace use starts. What is wrong?', 'What timing belongs to the Article 26(7) information step?', ('Inform before the specified workplace use begins','The paragraph sets prior timing.'),('Inform only after a problem occurs','This is not only an incident duty.'),('No information is needed if a vendor built it','Employer use has its own obligation.')),
q([1],[2], 'A public authority finds the required registration missing for its proposed system. What follows?', 'What should the stipulated public deployer do when the required EU registration is absent?', ('Do not use it; inform provider or distributor','Article 26(8) states this consequence.'),('Use it while making a private note','That ignores the no-use instruction.'),('Assume every private employer has the identical trigger','The public-deployer provision has specified actors.')),
q([2],[3,4], 'Workers received a notice, but applicants subject to assisted Annex III decisions did not. Is the applicant-information gate closed?', 'Does a workplace notice automatically fulfil affected-person information for applicants?', ('No; check and provide the separate required person notice','Different triggers and recipients apply.'),('Yes; any notice reaches every required person','The recipient population differs.'),('Yes; Article 50 replaces all high-risk notices','Article 26 preserves its own trigger.'))]),
'H28': lesson('Articles 26(9), 27(1)–(5); GDPR Article 35 / LED Article 27 as separate applicability lookups', 'Test the FRIA trigger and reuse applicable data-protection evidence without a waiver.', [
['A **fundamental-rights impact assessment**, or FRIA, examines the effects of a deployment on people’s fundamental rights before deploying the specified system. Article 27 concerns Article 6(2) Annex III systems, except Annex III point 2 critical infrastructure.', 'Within that route, the actor/use triggers are bodies governed by public law, private entities providing public services, and deployers of Annex III 5(b)/(c) systems: creditworthiness/credit scoring and life/health-insurance risk/pricing. A purely private recruitment employer is not automatically covered solely because recruitment is high-risk.'],
['**FRIA content** includes the actual process and intended use, time/frequency, affected people/groups, specific likely harms informed by provider information, implementation of human oversight, and responses if risks materialise, including internal governance and complaint mechanisms.', 'A provider’s generic test report does not by itself assess a public-service deployer’s actual process, people or complaints arrangements. Link evidence to each assessment element.'],
['The duty applies to first use. Similar cases may rely on previous assessments or provider assessments, but changed or outdated elements require updating. After assessment, notify the market-surveillance authority with the filled template; the Article 46(1) exceptional route may exempt notification.', 'Article 27 directs the AI Office to develop a questionnaire/template, including an automated tool. Verify the actual available version before treating a form as official. The course does not assert that a usable template has been published.'],
['A **data protection impact assessment**, or DPIA, is the separate assessment required under data-protection law when its conditions apply. GDPR Article 35’s general trigger is processing likely to cause high risk to individuals’ rights/freedoms. The Law Enforcement Directive has its own Article 27 route.', 'Article 26(9) requires using provider information for a DPIA where applicable. High-risk AI classification alone does not decide every DPIA condition. Check processing facts, the relevant data law and authority guidance/lists; specialist triggers are lookup gates here.'],
['**FRIA/DPIA reuse** under 27(4) lets a deployer cross-reference relevant sections or include relevant material where the DPIA already fulfils FRIA obligations. It does not waive the remaining FRIA elements or notification.', 'Case variant: a public-law body uses the stipulated Annex III recruitment system. Its DPIA covers personal-data risks but lacks complaint/governance arrangements and deployment frequency. Reuse relevant content and complete the missing applicable FRIA elements.']], [
q([0],[1], 'A purely private recruitment employer, providing no public service, uses Annex III 4(a). Is Article 27 automatically triggered solely by high-risk status?', 'Does the supplied private-employer recruitment fact alone establish the FRIA duty?', ('No; test the specified actor/use trigger','High-risk status alone is insufficient for this provision.'),('Yes; every high-risk deployer has a FRIA duty','The provision has limited triggers and a point 2 exclusion.'),('No public-law body can ever trigger it','Public-law actors are expressly within the stated route.')),
q([1],[2,3], 'A covered public body changes affected groups and deployment frequency after its first assessment. What should happen?', 'May a covered deployer rely unchanged on a now-outdated first-use assessment?', ('Update the changed/outdated elements','Article 27(2) requires necessary updates.'),('Keep the first document permanently unchanged','First-use assessment does not remove update duties.'),('Replace all process evidence with a supplier logo','That does not assess the actual deployment.')),
q([2],[4,5], 'A covered deployer has a DPIA but it omits required FRIA complaint and governance elements. What follows?', 'Does a completed DPIA automatically waive the whole applicable FRIA?', ('Reuse relevant content and complete the remaining FRIA duties','Cross-references are allowed where obligations are already met.'),('Omit the FRIA entirely because a DPIA exists','Existence alone does not fulfil missing elements.'),('Discard all useful DPIA evidence and duplicate everything','The amended paragraph explicitly allows relevant reuse.'))], DPIA),
'H29': lesson('Articles 3(41), 12(3), 14(5), 26(10)', 'Optional specialist route: authorisation, human verification and biometric records.', [
['**Remote biometric identification** identifies people without their active involvement, typically at a distance, by comparing biometric data with a reference database. Biometric data concerns physical/physiological/behavioural characteristics used for identification. Post-remote identification is delayed identification rather than the real-time form.', 'This optional lesson does not authorise a real biometric use. First check scope, Article 5, data law and the exact Annex III point; confirm national rules. The supplied exercise assumes a legally permitted targeted post-remote investigation route subject to the stated controls.'],
['For the specified targeted search of a suspect or convicted person, Article 26(10) requests judicial or binding, judicially reviewable administrative authorisation in advance or without undue delay and no later than 48 hours. The narrow initial-identification exception uses objective/verifiable facts directly linked to the offence.', 'Limit use to what is strictly necessary for the specific criminal investigation. Rejected authorisation requires immediately stopping the linked use and deleting linked personal data. Untargeted law-enforcement use is barred; no adverse legal decision may rest solely on the output. Data-law and stricter national rules remain.'],
['**Biometric dual verification** under 14(5) requires identification from Annex III 1(a) systems to be separately verified and confirmed by at least two competent, trained and authorised natural persons before the deployer acts on it.', 'The qualified exception concerns law enforcement, migration, border control or asylum where Union/national law considers dual verification disproportionate. Sector membership alone does not establish the exception.'],
['**Biometric log fields** under 12(3) include each use’s start/end date and time, reference database, matched input data, and the identity of verifying natural persons. This system capability differs from custody periods and operational police records.', 'Article 26(10) also requires each use in the relevant police file regardless of purpose/deployer, authority availability on request, and annual reports to market-surveillance and data-protection authorities; sensitive law-enforcement operational-data qualifications apply. Reports may aggregate deployments.'],
['Case: a permitted targeted search has authorisation refused; the team proposes continuing because one person approved a match. Stop the linked use and delete linked data. Neither a match nor internal approval overrides refusal.', 'Record the national-law verification rather than inventing a universal approving office. This extension has no core-course lesson depending on it.']], [
q([0],[2,5], 'Authorisation for the specified linked post-remote use is rejected. What follows?', 'Can the team continue the linked use because a match was found?', ('Immediately stop linked use and delete linked personal data','The refusal clause expressly requires these actions.'),('Continue until the annual report is due','Reporting does not override refusal.'),('Continue if one staff member agrees','Internal agreement is not the requested authorisation.')),
q([1],[3], 'A law-enforcement team claims sector membership alone removes dual verification. Is that enough?', 'What must be established for the stated dual-verification exception?', ('Union or national law considers the requirement disproportionate','The exception is legally qualified.'),('Only that it is a law-enforcement team','Sector membership alone is insufficient.'),('Only that its score is high','Confidence does not establish the exception.')),
q([2],[4], 'The system records match confidence but not use times, reference database, matched input or verifiers. What is missing?', 'Does a confidence score alone fulfil the special remote-identification log capability?', ('The specified minimum use/database/input/verifier fields','Article 12(3) lists these fields.'),('Only the supplier’s annual revenue','That is not a listed field.'),('Nothing because a police file exists','Operational files do not replace system logging capability.'))]),
'H30': lesson('Core Articles 4a, 8–27; Articles 111, 113 and market-entry/operations handoffs', 'Issue a supported hold or conditional decision with evidence, owners and review triggers.', [
['Final case uses the stipulated Northbridge Annex III recruitment purpose and amended timetable. The dossier contains earlier scope, data, technical, actor and operating records. “Dossier” is this course’s practical evidence collection, not a statutory certificate.', 'A **dossier evidence gap** is a missing or unsubstantiated fact needed to support an applicable conclusion. A statement that a test passed is weaker than the version-relevant report and its purpose-appropriate criteria.'],
['Case evidence: required technical-version testing is unresolved; supplier assistance for a changed high-risk purpose is unproved; sensitive-bias processing still proposes external-party access. These are supplied material gaps.', 'Specify what is missing, which duty it affects, whose responsibility it is and what evidence would resolve it. The sensitive-data proposal does not establish the exception while the access safeguard fails.'],
['A **deployment-gate review** separately checks applicable duty dates/transition facts, instructed operation, supported oversight, monitoring/escalation and workplace/person-information duties. It also tests the actual Article 27 actor/use trigger.', 'In the private-employer recruitment variant, Article 27 is not established solely from high-risk status. In the stipulated public-law deployment variant it is triggered, with relevant assessment elements and update/notification review. Do not turn either variant into a universal rule.'],
['A **compliance decision** states the supported outcome, conditions, responsible owners and reassessment triggers. For the supplied material technical and supplier gaps, hold the proposed readiness decision pending evidence. Describe the sensitive-data proposal’s incompatible access condition separately.', 'An internal reviewer’s signature or a passed course cannot supply missing compliance proof. Set review triggers for purpose, meaningful design changes, new risk evidence, changed operation and changed law; each can reopen relevant parts of the dossier.'],
['This course identifies Article 16 market-entry gates but does not complete conformity procedures, declaration/marking/registration implementation or all sector/national and other-law analysis. Likewise, detailed serious-incident deadlines need the operations course.', 'Final practical task: for your own product, write system/purpose, actor, provision/test, yes/no/unknown finding, evidence, duty date, action/owner and remaining gates. A conditional readiness statement is justified only for its stated scope after the material evidence is established.']], [
q([0],[1,2], 'The case has mismatched technical evidence and unproved necessary supplier access. What should the dossier do?', 'How should the assessor handle the supplied material proof gaps?', ('Identify affected duties, owners and evidence needed','The finding remains conditional until evidence supports it.'),('Treat a signature as supplying the missing proof','A signature does not replace applicable evidence.'),('Remove the unresolved fields before review','Hiding gaps makes the conclusion unsupported.')),
q([1],[3], 'The private-employer recruitment case is changed to a public-law deployer. What needs reassessment?', 'Which deployment assessment gate changes with the stipulated public-law actor?', ('The Article 27 FRIA trigger and applicable assessment duties','The actor facts change the specific trigger.'),('Nothing because the software is unchanged','Deployment obligations can depend on the actor and context.'),('Only the product’s colour scheme','Appearance does not determine the actor trigger.')),
q([2],[2,4,5], 'Which conclusion fits the supplied final case and this course’s scope?', 'Can completion of this course authorise release despite its stated material gaps?', ('Hold pending evidence, with owners and separate remaining release gates','The decision must match what is actually established.'),('Unconditional certification of compliance with all law','The dossier and teaching scope do not support that claim.'),('Permanent prohibition of every product using the model','The supplied evidence concerns this proposed use and gaps.'))]),
}
