"""Provider organisation and value-chain duties."""
from high_risk_content import lesson, question as q

ACCESS = [
{'title': 'Commission: scope of the Web Accessibility Directive', 'url': 'https://digital-strategy.ec.europa.eu/en/policies/web-accessibility'},
{'title': 'Commission: European Accessibility Act covered products and services', 'url': 'https://commission.europa.eu/strategy-and-policy/policies/justice-and-fundamental-rights/disability/european-accessibility-act-eaa_en'}]

LESSONS = {
'H19': lesson('Article 16(a)–(l); Articles 2(2), 43, 47–49; Directives 2016/2102 and 2019/882', 'Map provider duties and leave unproved market-entry gates visible.', [
['A **provider duty map** allocates Article 16 tasks to an accountable actor. For the applicable full high-risk regime it includes system requirements, a quality-management system, documentation and controlled logs, correction and information, and conformity evidence for authorities.', 'A quality-management system is the documented organisational process for ensuring compliance. The next lesson develops it. Do not apply this full map automatically to the limited Annex I Section B route.'],
['Market-entry gates include the relevant Article 43 conformity-assessment procedure before supply/service, an Article 47 EU declaration of conformity, Article 48 CE marking and applicable Article 49 registration.', 'A conformity assessment demonstrates specified compliance; the declaration states conformity and CE marking communicates it. This lesson identifies the gates. Selecting the actual procedure, assessment body, marking method and registration category needs the later market-entry course and the applicable product facts.'],
['**Provider identity** must be indicated on the system or, where not possible, on packaging or accompanying documentation as applicable: name, registered trade name or trademark, and contact address.', 'A logo with no contact address does not establish this item. Record whose identity appears and where. The identified provider must still fulfil the other applicable obligations.'],
['**Provider accessibility** under Article 16(l) concerns compliance in accordance with Directives 2016/2102 and 2019/882. Establish their scope and relevant national implementing rules rather than inventing one universal AI certificate.', 'The Web Accessibility Directive concerns websites/apps of public-sector bodies. The European Accessibility Act covers specified products and services, including certain computers, banking and e-commerce. A commercial product needs its actual category tested; not every website has identical directive obligations.'],
['Case: Northbridge has a name/address record but no conformity-route evidence and no accessibility-scope analysis. Identity alone does not close its provider map.', 'Keep the missing gates, relevant sources and responsible owners in the dossier. Do not treat a supplier’s general “compliant” declaration as proof that each applicable gate has been discharged.']], [
q([0],[1,2,5], 'Northbridge has passed technical checks but no relevant conformity-route evidence. What remains?', 'Does technical testing alone close the Article 16 provider map?', ('The applicable assessment, declaration, marking and registration gates','System evidence and market-entry steps are distinct.'),('No further provider task','Article 16 includes more than technical checks.'),('The same full map for every Section B system automatically','That ignores limited applicability.')),
q([1],[3], 'Only a logo appears on the system and no contact address appears in the relevant material. What is missing?', 'Which identity detail must the assessor check alongside the provider name or trademark?', ('The address at which the provider can be contacted','Article 16(b) includes it.'),('Only its advertising slogan','A slogan does not supply contact identity.'),('Every customer’s private address','This is the provider identity requirement.')),
q([2],[4], 'A reviewer says every AI website needs the same certificate under both accessibility directives. What should happen?', 'How should Northbridge establish its Article 16(l) accessibility duties?', ('Check the covered product/service and applicable implementation rules','The directives have defined scopes.'),('Accept a universal certificate claim without scope analysis','That substitutes an invented rule.'),('Ignore accessibility because it is commercial','The EAA includes specified private-sector products/services.'))], ACCESS),
'H20': lesson('Article 17(1)(a)–(m), (2)–(4)', 'Build a written quality system with proportionate implementation and preserved rigour.', [
['A **quality-management system** uses systematic written policies, procedures and instructions to ensure compliance. It includes a compliance strategy and change management, design/control/verification, development/quality assurance, and test/validation procedures with frequencies.', 'Name accountable people and how decisions produce records. A folder of policy titles without operating procedures does not establish implementation.'],
['It also covers technical specifications and standards or alternative compliance means, data operations, risk management, post-market monitoring, serious-incident reporting and communications with authorities, assessment bodies, operators and customers.', 'Post-market monitoring gathers evidence after supply; serious-incident reporting has a specific statutory route. Detailed Articles 72–73 procedures are later-course work, but a quality system must include them rather than waiting for an incident.'],
['Include relevant documentation/record procedures, resources and security of supply, and management/staff accountability. **Proportionate implementation** fits the organisation’s size, particularly SMEs, start-ups and SMCs.', 'SMEs and SMCs are defined enterprise size categories; verify eligibility under the applicable definitions. Proportionate processes still preserve the required rigour and level of protection. Small size is not a waiver of risk management or accountability.'],
['**Sector integration** allows the required aspects within an equivalent sector-law quality function. Specified financial institutions’ Union financial-law governance can fulfil much of the quality-system obligation.', 'The financial equivalence excludes Article 17(1)(g), (h), (i): risk management, post-market monitoring and serious-incident reporting. Preserve these aspects. Also take the relevant harmonised standards into account; do not assume a standard’s current publication status.'],
['Case: a small Northbridge team proposes informal chat approval with no owner for incident reporting or record keeping. A simpler documented process can be proportionate, but the missing responsibilities still need to be supplied.', 'Evidence should show who acts, when, using what criteria, how records are retained and how the procedure is reviewed. This is a practical way to inspect the statutory system, not a mandatory template.']], [
q([0],[1,2,5], 'Northbridge has written policy names but no test frequency or incident-reporting owner. What is needed?', 'Does a list of documents establish the required operating quality system?', ('Documented procedures, frequencies and accountability','The system must include the specified operational aspects.'),('Only a more attractive folder','Presentation cannot establish operating procedures.'),('A rule to create incident processes only after harm','The quality system includes them beforehand.')),
q([1],[3,5], 'A small supplier says it can omit risk-management rigour because of its size. What is the correct boundary?', 'How does proportionality affect a start-up’s quality implementation?', ('Fit implementation to size while preserving protection and rigour','Article 17(2) retains the compliance standard.'),('Remove the high-risk system requirements','Proportionality is not a waiver.'),('Require an identical organisation chart for every provider','Implementation can be proportionate.')),
q([2],[4], 'A qualifying financial institution relies on sector governance. Which aspects remain outside the Article 17(4) equivalence?', 'Which three aspects cannot be dismissed under the financial quality-system equivalence?', ('Risk management, post-market monitoring and serious-incident reporting','Points (g), (h), (i) are excluded.'),('Only marketing, sales and pricing','Those are not the stated exceptions.'),('None; financial governance replaces everything','That omits the explicit exclusions.'))]),
'H21': lesson('Articles 18(1)–(3), 21(1)–(3)', 'Preserve provider documentation and supply necessary authority evidence.', [
['**Documentation custody** under Article 18 keeps specified provider records at authorities’ disposal for a period ending ten years after market placement or service. These include technical and quality-system documentation and the EU declaration.', 'Include approved changes and decisions/documents from notified bodies where applicable. A notified body is an authorised assessment body for the relevant procedure. Do not invent a certificate for a procedure that requires none.'],
['Ten-year documentation custody differs from controlled-log retention, whose separate qualified rule is taught elsewhere. Financial institutions within the specified financial-law governance rules keep technical documentation as part of the relevant financial documentation.', 'Record which evidence belongs to which rule, its relevant start event, retrieval location and responsible actor. A six-month document deletion policy would not meet the ten-year documentation rule.'],
['**Authority cooperation** follows a reasoned competent-authority request. Supply all information and documentation needed to demonstrate system-requirement conformity in an easily understood Union official language indicated by the Member State.', 'Give applicable access to automatically generated logs to the extent under the provider’s control. Information received by authorities is subject to Article 78 confidentiality. A private trade-secret assertion does not itself cancel the cooperation duty.'],
['**Documentation continuity** remains a concern if a provider or its representative becomes bankrupt or ceases activity before the period ends. Each Member State determines conditions for keeping the specified documentation available.', 'Case: Northbridge plans to close and delete its records. Check the relevant Member State arrangements and implement continuity. Do not assume the duty simply vanishes, or invent a national handover procedure without a source.']], [
q([0],[1,2], 'Northbridge proposes deleting technical documentation after six months. Which rule is being confused?', 'Does the controlled-log minimum define the provider technical-file custody period?', ('Article 18’s ten-year documentation period is separate','The documented record categories have their own rule.'),('All records share the log minimum','That conflates distinct obligations.'),('Every system needs a notified-body certificate','The document applies where the procedure involves one.')),
q([1],[3], 'A competent authority makes a reasoned request for conformity evidence and controlled logs. How should the provider respond?', 'Does a private confidentiality claim automatically defeat the requested evidence access?', ('Supply necessary evidence/access under the specified language and confidentiality framework','Articles 21 and 78 govern cooperation and protection.'),('Refuse all information as secret','Confidentiality does not erase the duty.'),('Supply only the advertising brochure','The authority needs necessary conformity evidence.')),
q([2],[4], 'The provider will cease activity before ten years end. What is the correct next step?', 'May the provider delete its required documentation simply because it closes?', ('Check Member State continuity conditions and preserve availability','Article 18(2) addresses cessation and bankruptcy.'),('Delete everything on the last trading day','Closure does not establish permission to end availability.'),('Use an invented universal handover office','The Member State conditions require actual sourcing.'))]),
'H22': lesson('Article 20(1), (2); Article 79(1)', 'Respond immediately to non-conformity and communicate qualifying risks.', [
['**Provider corrective action** begins when a provider considers or has reason to consider its supplied high-risk system is not in conformity. Immediately take necessary action to bring it into conformity, withdraw, disable or recall it as appropriate.', 'These are different available responses, not a command to recall every issue. Select effective action for the actual non-conformity and circumstances.'],
['Inform affected distributors and, where applicable, deployers, authorised representative and importers accordingly. A quiet internal ticket does not establish these required communications.', 'Northbridge discovering that its supplied instructions omit a critical limitation must examine necessary correction and who needs the information. The action and communication should match the issue.'],
['**Provider risk information** is additional where the system presents Article 79 risk and the provider becomes aware. Immediately investigate causes, collaborating with the reporting deployer where applicable.', 'Inform competent market-surveillance authorities and, where applicable, the notified body that issued the certificate, particularly about non-conformity and relevant corrective action. Market-surveillance authorities oversee compliance in the relevant jurisdiction.'],
['Case: an employer reports harmful ranking behaviour and the provider has evidence of a qualifying risk. Waiting for the next quarterly meeting does not fit the immediate investigation/information duties.', 'Record the finding, necessary action and communication. Specific Article 73 incident definitions and reporting deadlines require the later operations analysis; do not invent one universal deadline for every problem.']], [
q([0],[1,2], 'A provider has reason to consider its supplied system non-conforming. May it wait for a quarterly review?', 'What response timing belongs to the Article 20(1) trigger?', ('Immediate necessary corrective action','The paragraph requires immediate appropriate action.'),('No action until a court judgment','Reason to consider non-conformity is already the trigger.'),('Automatic recall for every minor issue regardless of context','The action is chosen as appropriate.')),
q([1],[3,4], 'The provider becomes aware of a qualifying Article 79 risk reported by a deployer. What follows?', 'Which response fits the supplied qualifying-risk case?', ('Immediate investigation and competent-authority information','Article 20(2) adds these duties.'),('Only a private note to the sales team','That does not fulfil investigation and external information.'),('No investigation because the customer reported it','Reporting-deployer collaboration may be required.')),
q([0,1],[2,3], 'A relevant certificate was issued by a notified body and a qualifying risk is found. Which communication is supported?', 'Does a certificate remove the duty to inform its issuing assessment body where applicable?', ('Inform the relevant authorities and issuing body where applicable','Prior certification does not remove risk information duties.'),('Keep the issuing body uninformed because it certified','The paragraph explicitly includes it where applicable.'),('Send every internal ticket to every body worldwide','Recipients depend on the system, risk and applicability.'))]),
'H23': lesson('Articles 22–24', 'Verify what representatives, importers and distributors must do.', [
['A third-country high-risk provider appoints an EU **authorised representative** by written mandate before making the system available on the Union market. Enable the representative’s tasks and allow authorities to address it alongside or instead of the provider.', 'The mandate includes verifying technical documentation, declaration and appropriate assessment; ten-year custody of specified provider contact details, documentation, declaration and applicable certificate; authority evidence/controlled-log access and cooperation; and applicable registration checks.'],
['The representative must terminate the mandate if it considers or has reason to consider the provider acts contrary to its obligations. Immediately inform the relevant market-surveillance authority and applicable notified body, with the reasons.', 'A nominal representative unable to perform its mandated tasks is not evidence that the appointment requirement is effectively implemented.'],
['**Importer verification** before market placement includes assessment, technical documentation, CE marking, declaration, accompanying instructions and the representative appointment. Suspected non-conformity or falsified documentation means no placement until corrected; qualifying risk also requires informing provider, representative and authorities.', 'Include importer identity/contact address, suitable storage/transport, ten-year custody of applicable certificate, instructions and declaration, necessary authority information including access to technical documentation, and cooperation.'],
['**Distributor verification** before making available checks CE marking, declaration, instructions, provider identity and quality-system obligations, and importer identity obligations. Suspected non-conformity means withhold until corrected; qualifying risk requires relevant information.', 'Maintain suitable storage/transport; correct, withdraw or recall, or ensure the relevant operator acts when later non-conformity is suspected. For qualifying risk, immediately inform provider/importer and competent authorities. Supply action documentation on reasoned request and cooperate.'],
['Case: the stipulated EU importer has reason to believe a third-country system’s assessment document is falsified. It cannot satisfy its verification merely by forwarding the product to a distributor.', 'These roles have their own checks. A supply-chain table should locate each record and communication owner; it is not enough that someone somewhere has a document.']], [
q([0],[1,2], 'The representative has reason to consider the provider acting contrary to its duties. What must it do?', 'Can a representative keep a nominal mandate despite the specified contrary conduct?', ('Terminate and immediately inform the relevant authority and applicable body','Article 22(4) specifies this response.'),('Keep the mandate and hide the concern','That contradicts the required response.'),('Become the provider automatically by being appointed','A mandate alone does not establish that role change.')),
q([1],[3,5], 'An importer suspects falsified conformity documentation. Can it place the product while checking later?', 'Which supply decision fits the importer’s documented falsification concern?', ('Withhold placement until conformity is established','Article 23 does not allow supply despite that concern.'),('Place it because another actor wrote the document','The importer has its own verification duty.'),('Treat a disclaimer as verifying the document','A disclaimer does not resolve falsification.')),
q([2],[4], 'A distributor finds post-supply non-conformity. Does passing the issue to the provider discharge everything?', 'What responsibility remains for a distributor after identifying the supplied non-conformity?', ('Take necessary action or ensure the relevant operator acts','The distributor must act or ensure action, with applicable information.'),('Only forward a note with no follow-up','That does not establish the necessary response.'),('Apply the importer’s ten-year list as its own express rule','The roles’ specified custody and checks differ.'))]),
'H24': lesson('Article 25(1)–(5)', 'Reassign provider duties after changes and secure necessary supplier assistance.', [
['**Changed provider role** under Article 25 can arise for distributors, importers, deployers or others that rebrand an existing high-risk system, substantially modify one so it remains high-risk, or change a non-high-risk system’s intended purpose so it becomes high-risk.', 'Substantial modification is an unplanned post-assessment change affecting requirement compliance or changing assessed purpose. Rebranding has the stated contractual-allocation qualification. Section A safety-component product manufacturers also become providers in the specified own-name supply/service circumstances.'],
['For the specific changed system, the initial provider is no longer its provider under the paragraph. It must closely cooperate with the new provider, supply necessary information and reasonably expected assistance, including relevant documentation, limitations/failure modes and targeted testing access.', 'The cooperation paragraph does not apply where the initial provider clearly specified the system must not be changed into a high-risk system. Do not assume the new provider can compel support under this route regardless of that boundary.'],
['A **supplier-access agreement** specifies in writing necessary information, capabilities, technical access and other assistance from third-party systems/models/tools/services/components/processes for the high-risk provider to comply, based on the generally acknowledged state of the art.', 'The exception for publicly accessible free/open-source tools/services/processes/components excludes general-purpose AI models. A general-purpose model serves many distinct tasks: open licensing does not automatically remove it from this agreement rule. IP, confidential information and trade secrets remain protected.'],
['The AI Office may develop voluntary model contract terms; verify availability before relying on a supposed standard contract. A signed generic purchase contract without needed information/access is not automatically a sufficient agreement.', 'Case: a customer converts a general writing assistant into materially influential recruitment ranking. Assume the exact Annex III route is established. Its changed purpose triggers a fresh provider-role analysis, not only an employer-use label.'],
['The **value-chain case** asks who now supplies the changed high-risk system and what evidence/access it needs. Preserve applicable importer and corrective duties; a role change does not make all other activities irrelevant.', 'Record new-provider responsibilities, upstream cooperation conditions, written assistance scope and unresolved access. If the original supplier forbade high-risk conversion, keep the support gap explicit. Do not declare readiness without a route to necessary evidence.']], [
q([0],[1,4], 'A customer changes a non-high-risk writing assistant into the stipulated high-risk applicant-ranking use. Which analysis is needed?', 'Does the customer remain only a deployer after this established high-risk purpose change?', ('Its new provider role under Article 25','The specified purpose change is a trigger.'),('Only its original purchase label','Actual changed conduct controls the role analysis.'),('No reassessment because the upstream model is unchanged','Purpose can change classification and role.')),
q([1],[2,3,4], 'An open-licensed general-purpose model is integrated into the high-risk system. Does that fact alone establish the agreement exception?', 'Does the open-source supplier exception automatically include general-purpose models?', ('No; general-purpose models are excluded from that exception','Article 25(4) expressly preserves them.'),('Yes; any open licence removes the agreement rule','The exception is limited.'),('Yes; a generic invoice supplies technical access','An invoice does not establish the needed assistance.')),
q([2],[2,5], 'The initial provider clearly forbade high-risk conversion and necessary testing access is absent. What is supported?', 'What should the changed-system dossier say about the missing upstream support?', ('Keep the support gap and cooperation boundary explicit','The exception can limit the cooperation route; missing evidence remains.'),('Assume compelled support regardless of the stated limit','That ignores Article 25(2)’s exception.'),('Certify readiness because someone else developed it','The new provider still needs evidence for its duties.'))]),
}
