"""Real-time identification safeguards and the final assessment."""

from lesson_builder import assessment

LESSONS = {
    "R01": {
        "locator": "Article 3(41)–(44), Article 5(1)(h); Annex II",
        "summary": "Identify the public-space law-enforcement ban and its three strictly limited objective branches.",
        "screens": [
            ["**Real-time remote biometric identification** identifies people without their active involvement, typically at a distance, by comparison with a reference database, with capture, comparison and identification occurring without significant delay. Limited short delays cannot be used to evade the real-time definition.", "A **publicly accessible space** is a physical place accessible to an undetermined number of people, regardless of ownership or access conditions. A privately owned station can qualify. Establish real-time identification, public accessibility and law-enforcement purpose together."],
            ["Article 5(1)(h) generally prohibits this use for law enforcement. An exception objective must be strictly necessary: targeted search for specific victims of abduction, human trafficking or sexual exploitation, or search for missing persons.", "A second objective concerns preventing a specific, substantial and imminent threat to life or physical safety, or a genuine and present or genuine and foreseeable terrorist-attack threat. Generic crime prevention is not the wording of either objective."],
            ["The third objective concerns locating/identifying a suspect for investigation, prosecution or execution of a criminal penalty. The offence must be in **Annex II** and punishable in the Member State by a maximum custodial sentence or detention order of at least four years.", "Annex II lists terrorism; human trafficking; child sexual exploitation/pornography; drug trafficking; weapons trafficking; murder/grievous bodily injury; organ/tissue trafficking; nuclear/radioactive-material trafficking; kidnapping/unlawful restraint/hostage-taking; International Criminal Court crimes; aircraft/ship hijacking; rape; environmental crime; organised/armed robbery; sabotage; participation in a criminal organisation involved in a listed offence. Verify the exact entry and national maximum penalty separately."],
            ["Fictional Northbridge station case: police seek a specified missing person. The objective can enter the exception assessment; it does not dispense with target limits, impact assessment, registration, authorisation and national law taught next.", "Changed case: police scan everyone merely to discourage minor disorder. That general objective does not establish a listed exception. A post-event system or private-access system needs its own classification and other-law assessment; a different fact is not universal permission."],
        ],
        "questions": [
            assessment([0], [1], "A system compares faces to an identity database with only a short operational delay. What matters for the real-time definition?", "Can a limited short delay automatically avoid real-time remote identification?", ("The actual capture/comparison/identification timing", "The definition includes limited short delays to prevent circumvention."), ("Any delay makes identification entirely unregulated", "Limited short delays do not automatically avoid the definition."), ("Only whether a vendor says the product is retrospective", "The actual operation determines the definition.")),
            assessment([1], [1], "A privately owned station admits an undetermined number of ticket holders. What public-space fact matters?", "Does private ownership alone exclude a station open to an undetermined public?", ("Public accessibility can exist despite ownership or conditions", "The definition concerns an undetermined number of persons, irrespective of those facts."), ("Every private owner makes the space legally inaccessible", "Ownership alone does not determine public accessibility."), ("Only outdoor places can qualify", "The definition is not limited to outdoor places.")),
            assessment([2], [2, 3, 4], "For the suspect branch, an Annex II entry is established but the national maximum penalty is unknown. What remains unresolved?", "Is an Annex II offence name alone enough for the suspect exception objective?", ("The national maximum of at least four years and other conditions", "The offence list and national penalty threshold are cumulative, with further safeguards."), ("Nothing; any listed offence automatically permits every use", "The penalty threshold and safeguards cannot be omitted."), ("Only the sentence police would prefer", "The statutory national maximum is the relevant threshold.")),
        ],
    },
    "R02": {
        "locator": "Article 5(2); Articles 27 and 49 (cross-references)",
        "summary": "Balance use and non-use harms, limit the target and separate impact assessment from urgent registration.",
        "screens": [
            ["A listed objective starts the assessment; **necessity and proportionality** still need evidence. Consider the nature of the situation, particularly the seriousness, probability and scale of harm if the system were not used.", "Also consider the consequences of using it for the rights and freedoms of all concerned, particularly seriousness, probability and scale. A record discussing only operational benefits omits this second side."],
            ["Permitted use must confirm the identity of the **specifically targeted individual**. Necessary and proportionate national safeguards include temporal, geographic and personal limitations.", "Fictional Northbridge search: specify the person, limited station area and necessary duration. Do not expand a particular missing-person objective into indefinite identity screening of everyone throughout the city."],
            ["Authorisation requires the law-enforcement authority to have completed a **fundamental rights impact assessment** under Article 27 and registered the system under Article 49.", "In duly justified urgency, use may begin before EU database registration if registration follows without undue delay. This paragraph's urgency allowance concerns registration; it does not waive the completed impact assessment."],
            ["Keep three records distinct: impact assessment, database registration and the authorisation process in R03. Different urgency provisions have different conditions and deadlines.", "For the fictional case, evidence must support target, objective, both sides of the harm analysis, narrow limits, completed assessment and registration or its justified urgent sequence. Missing facts remain missing facts, even if the search is important."],
        ],
        "questions": [
            assessment([0], [1], "A request records only the harm of not using identification. What analysis is missing?", "What must accompany non-use harm in the necessity/proportionality record?", ("Rights/freedoms consequences of use for all concerned", "Article 5(2) expressly requires consideration of both sides."), ("Only the supplier's subscription cost", "Cost alone does not supply the missing rights analysis."), ("Nothing if police consider the objective useful", "A useful objective does not replace the required assessment.")),
            assessment([1], [2], "A specific-person search becomes indefinite city-wide screening without further justification. What safeguard problem arises?", "Which limits must stay tied to the specifically targeted individual?", ("Necessary temporal, geographic and personal limits", "The use must remain specifically targeted and limited."), ("Only the model's brand", "A brand does not limit time, place or persons."), ("No limits once an objective is named", "The objective does not erase paragraph 2 safeguards.")),
            assessment([2], [3, 4], "Duly justified urgency delays EU database registration. Can the authority also skip its completed impact assessment under this allowance?", "Which requirement is deferred by Article 5(2)'s urgent registration allowance?", ("Registration alone, completed without undue delay", "The paragraph does not waive the completed fundamental rights impact assessment."), ("Both registration and the impact assessment indefinitely", "The allowance is narrower and requires prompt registration."), ("Every safeguard until the investigation ends", "The exception does not erase other requirements.")),
        ],
    },
    "R03": {
        "locator": "Article 5(3), first and second subparagraphs",
        "summary": "Apply prior binding authorisation, the urgent request deadline and immediate refusal consequences.",
        "screens": [
            ["Each use requires **prior authorisation** by a judicial authority or an independent administrative authority whose decision is binding in the Member State of use, following a reasoned request and national detailed rules.", "The competent authority needs objective evidence or clear indications that use is necessary and proportionate to a listed objective. Permission from a supplier or an operational colleague is not this binding authorisation."],
            ["In a duly justified situation of urgency, use may commence without authorisation if authorisation is requested **without undue delay, at the latest within 24 hours**.", "Twenty-four hours is the outside limit, not a normal waiting period. Record why urgency is justified and why the request is prompt. This rule concerns the request; it does not promise approval."],
            ["If authorisation is rejected, use must stop with immediate effect. All data, results and outputs of that use must be immediately discarded and deleted.", "Fictional Northbridge case: the authority refuses an urgent search request. Continuing while appealing or keeping outputs for possible future identification contradicts the specified immediate consequences."],
            ["The authorising authority must keep time, geography and personal scope strictly necessary and consider the paragraph 2 harm/rights factors. A broad request cannot bypass these limits through urgency.", "Maintain the request, evidence, decision and compliance record. An urgent request submitted promptly remains only a request until decided; the separate no-adverse-decision rule is taught in R05."],
        ],
        "questions": [
            assessment([0], [1, 4], "An operational manager approves a scan, but there is no decision from the competent judicial or independent binding administrative authority. What is missing?", "Which decision fulfils the prior-authorisation requirement?", ("The competent judicial or independent binding administrative decision", "Article 5(3) specifies the authorising authority and binding character."), ("Any internal manager's informal agreement", "That does not establish the specified competent authorisation."), ("A supplier's technical readiness certificate", "Technical readiness is not legal authorisation.")),
            assessment([1], [2], "A duly justified urgent use starts now. What is the request timing rule?", "Does the 24-hour limit entitle the authority to wait routinely until its end?", ("Without undue delay, and no later than 24 hours", "Both the promptness requirement and outside limit apply."), ("Wait at least 24 hours before requesting", "The statute requires promptness, not a waiting period."), ("Request only when the operation has finished", "That could breach both timing requirements.")),
            assessment([2], [3], "The competent authority rejects an urgent authorisation request. What follows immediately?", "May rejected-use data be retained just in case it is useful later?", ("Stop use and discard/delete all its data, results and outputs", "The refusal consequences are immediate and cover each listed category."), ("Continue use but rename the operation", "A name change cannot avoid immediate stopping."), ("Keep every output pending a convenient review", "That contradicts immediate discard/deletion.")),
        ],
    },
    "R04": {
        "locator": "Article 5(4)–(7)",
        "summary": "Locate national permission rules and trace each-use notifications through annual reporting.",
        "screens": [
            ["This optional extension starts with **national authorisation rules**. A Member State may choose full or partial permission within the EU limits and must specify detailed request, issuance, exercise, supervision and reporting rules.", "National law specifies permitted objectives and offences, and may be more restrictive consistently with Union law. Member States notify the adopted rules to the Commission within 30 days. The EU exception alone does not establish permission in an unspecified country."],
            ["**Each-use notification** goes to the relevant market surveillance authority and the national data protection authority under the national rules. It includes at least the paragraph 6 information, without sensitive operational data.", "Notification is distinct from prior authorisation and registration. Sending one email to one authority cannot be assumed to satisfy all three processes or the two-recipient notification requirement."],
            ["The **annual reporting chain** begins with notified national market surveillance and data protection authorities reporting to the Commission. The Commission supplies a template including numbers and results of competent-authority authorisation decisions.", "The Commission then publishes annual reports based on aggregated Member-State data. Those published reports must not include sensitive operational law-enforcement data."],
            ["Fictional Northbridge cross-border case: a team wants to reuse one country's permission elsewhere. Obtain each governing country's actual national rules and competent-authority procedure; do not invent a harmonised blanket permit.", "Use a checklist with separate national-law, authorisation, registration, notification and annual-report fields. The core path does not depend on completing this extension; it offers a deeper administrative lookup method."],
        ],
        "questions": [
            assessment([0], [1, 4], "An assessor knows an EU exception objective but not the Member State's permission rules. What can they conclude?", "Does the EU exception itself prove the use is permitted in every Member State?", ("National permission and detailed rules still need verification", "A Member State may decide whether and how to authorise within EU limits."), ("Every Member State must permit the full exception", "The national choice may be partial and stricter."), ("A vendor can select whichever country's rules it prefers", "The governing jurisdiction and competent process matter.")),
            assessment([1], [2], "After a use, a notification is sent only to market surveillance. Which other recipient is specified?", "Who joins the relevant market surveillance authority in each-use notification?", ("The national data protection authority", "Article 5(4) specifies both recipients."), ("Only the supplier's sales team", "Sales notification is not the second statutory recipient."), ("Only the newspaper editor", "Public reporting is distinct from each-use authority notification.")),
            assessment([2], [3], "What does the Commission publish from the national annual reports?", "Should annual public reports expose sensitive operational case data?", ("Annual aggregated reports without sensitive operational data", "Article 5(7) specifies aggregation and excludes sensitive operational data."), ("Every person's operational identification record", "The publication excludes sensitive operational details."), ("Only a supplier's advertising summary", "The chain concerns official annual reporting.")),
        ],
    },
    "R05": {
        "locator": "Article 5(1), second subparagraph; 5(3), final sentence; 5(8)",
        "summary": "Keep other Union prohibitions and independent evidence checks after a biometric exception assessment.",
        "additional_sources": [{"title": "GDPR: biometric special-category processing, Article 9", "url": "https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng"}],
        "screens": [
            ["An Article 5 exception result is not complete legal permission. Paragraph 8 preserves **prohibitions under other Union law**. The non-law-enforcement biometric-processing clause expressly leaves GDPR Article 9 unaffected.", "For a non-police biometric use, check applicable privacy rules, including the special-category prohibition and available legal conditions. Being outside the public-space law-enforcement test does not itself provide a data-processing basis."],
            ["The separate **no adverse legal decision solely on output** rule applies to real-time remote identification. A decision producing an adverse legal effect cannot be based solely on its output.", "A match signal is not a substitute for independent evidence and proper procedure. This is a substantive decision limit even after the system's use has satisfied the exception safeguards."],
            ["Fictional Northbridge search returns a match, and officials propose an adverse legal decision using only that output. The final-sentence limit remains relevant despite an authorised operation.", "Changed case: the use is a private non-law-enforcement verification. The specific public-space law-enforcement ban may differ; applicable privacy, biometric, accuracy and other legal obligations remain to be checked."],
            ["Separate conclusions: the specific Article 5 test; Annex III/Article 6 classification; rules governing processing; and any adverse decision's evidence/procedure. Each result answers a different question.", "Record unresolved facts plainly. Do not write 'fully compliant' from a single exception finding, a technical accuracy claim or the absence of a particular prohibition."],
        ],
        "questions": [
            assessment([0], [1, 3], "A private biometric use falls outside this particular law-enforcement prohibition. What happens to applicable privacy prohibitions?", "Does an Article 5 exception waive prohibitions under other Union law?", ("They remain independently applicable", "Paragraph 8 preserves other Union prohibitions; the biometric clause preserves GDPR Article 9."), ("They disappear after one favourable AI Act finding", "A point-specific result is not a universal exemption."), ("They apply only if a vendor volunteers", "Statutory obligations do not depend on vendor preference.")),
            assessment([1], [2, 3], "An authorised scan produces a match; an adverse legal decision is proposed solely from it. What limit applies?", "Does authorisation allow adverse legal effects based only on identification output?", ("No adverse legal decision solely on that output", "Article 5(3)'s final sentence supplies this independent limit."), ("Authorisation makes the output conclusive for every decision", "The decision rule remains after authorisation."), ("Technical confidence alone removes the limit", "A confidence score cannot waive the statutory requirement.")),
            assessment([0, 1], [4], "One exception is established, but privacy and decision evidence have not been checked. How should the result be described?", "What does a precise point-specific exception conclusion leave open?", ("Separate processing and decision-law checks", "Each legal question needs its own facts and test."), ("Complete compliance with every applicable law", "That broader claim is unsupported."), ("Permission to rely solely on every biometric match", "The separate adverse-decision limit remains.")),
        ],
    },
    "R06": {
        "locator": "Articles 2–6, 5(1a)–(8), 6(3)–(4), 113; Annexes I–III",
        "summary": "Combine biometric-practice analysis with prohibition, classification, timing and evidence in a bounded final assessment.",
        "screens": [
            ["For **biometric-practice synthesis**, identify the function before the legal label: identity verification, remote identification, categorisation or emotion inference. Then establish data, purpose, actor, setting and timing.", "Fictional Northbridge bundle contains workplace facial emotion scoring, post-event identification and a missing-person real-time station search. Shared camera hardware does not make their intended functions or prohibition tests identical."],
            ["The workplace emotion function needs Article 5(1)(f)'s elements and medical/safety boundary; do not substitute a wellbeing label. The real-time search needs a listed strictly necessary objective plus paragraphs 2–3 and applicable national rules.", "The post-event function has a different real-time fact, but may remain listed under Annex III and subject to other law. A narrowly permitted use remains subject to independent classification, privacy and decision requirements."],
            ["A **final prohibition and classification assessment** begins with source version, scope, AI-system/actor definitions, intended purpose and evidence. Apply each relevant prohibition with its complete elements. Then test the appropriate Annex I or Annex III classification route.", "For an Annex III exception, retain the no-significant-harm/material-influence gateway, a qualifying condition and the profiling override. Document any exemption assessment and registration obligations. Stipulated sector facts are case assumptions, not an unsourced real-world product classification."],
            ["Finish with dates and unresolved questions. In this baseline, the new synthetic-media points apply on 2 December 2026; Annex III high-risk obligations have a 2 December 2027 date and Annex I a 2 August 2028 date under Article 113's specified section rules. Other applicable rules have their own dates.", "A useful handoff identifies the conclusion, exact provision, facts supporting each element, remaining evidence, responsible reviewer and applicable date. This English first release teaches foundations, Article 6 and Article 5; full downstream obligations and the dedicated Article 50 block remain follow-on teaching."],
        ],
        "questions": [
            assessment([0], [1, 2], "Three functions share a camera: emotion scoring, post-event identification and real-time missing-person search. What is the sound first step?", "Can common hardware establish one identical prohibition result for every biometric function?", ("Separate intended functions, settings and relevant tests", "Different functions and facts engage different definitions and conditions."), ("Treat all three as automatically permitted identity verification", "The bundle contains materially different functions."), ("Assign one result from the camera brand", "Brand does not establish the legal function or purpose.")),
            assessment([1], [3], "An Annex III workflow is called administrative but significantly influences decisions and profiles people. What can be concluded about the exception?", "Do administrative labels remove the harm/material-influence gateway and profiling override?", ("Those facts do not establish the Article 6(3) exception", "Labels cannot waive the gateway, and profiling keeps an Annex III system high-risk."), ("Any administrative label automatically grants exemption", "The full statutory exception conditions must be met."), ("Only the low subscription price decides classification", "Price is not the gateway or profiling test.")),
            assessment([0, 1], [3, 4], "A final memo gives a classification but no version, supporting facts or applicable date. What should be added?", "What makes the course's final assessment useful for a responsible reviewer?", ("Sources, element-by-element evidence, dates and unresolved questions", "A bounded conclusion must be supported and timed, with gaps visible."), ("Only a confident claim of universal compliance", "Confidence does not replace evidence or scope."), ("A new jurisdiction-specific defence invented for the case", "National qualifications require actual governing sources.")),
        ],
    },
}
