"""Annex III biometrics, education and employment."""

from lesson_builder import assessment

LESSONS = {
    "A01": {
        "locator": "Article 3(34)–(36), 3(41); Annex III 1(a)",
        "summary": "Distinguish identity verification from remote identification using technical and interaction facts.",
        "screens": [
            ["**Biometric data** result from specific technical processing of physical, physiological or behavioural characteristics. A facial image used for such processing can be relevant; do not treat every photograph as the same processing activity.", "Northbridge's fictional access desk uses a face comparison. Record the processed characteristic, purpose and reference data before deciding which identity test is being used."],
            ["**Biometric verification** is one-to-one confirmation of a person's claimed identity. Identification seeks to establish identity through comparison with stored individuals. Ask whether the question is 'Are you the person you claim to be?' or 'Who is this person?'", "A person actively confirming their identity against their own enrolled record differs from searching an unknown visitor against many records. The purpose and comparison matter more than the word 'login'."],
            ["**Remote biometric identification** identifies people without their active involvement, typically at a distance, by comparing biometric data with a reference database. Distance alone is not the complete definition.", "An entrance camera identifying passers-by against a reference database illustrates facts relevant to the remote test. Record involvement, matching process and intended identity purpose."],
            ["Annex III 1(a) lists remote biometric identification, where use is otherwise permitted by law. It excludes verification whose sole purpose is confirming the specific person's claimed identity.", "That point-specific exclusion does not make every verification use free of every AI Act or privacy duty. Article 5's separate real-time/public-space/law-enforcement rule will be taught later."],
        ],
        "questions": [
            assessment([0], [1], "What should Northbridge record about facial data before applying the biometric definitions?", "What makes the facial-data processing relevant to the biometric definition?", ("The specific technical processing and characteristic", "The definition concerns data resulting from technical characteristic processing."), ("Only the camera's brand", "Brand does not establish the relevant processing."), ("Only whether the image is colourful", "Colour alone does not establish biometric processing.")),
            assessment([1], [2, 4], "A user claims one identity and actively confirms it against their own enrolled record only. Which distinction fits?", "Which identity question describes one-to-one claimed-identity verification?", ("Confirming the person is who they claim to be", "That is the verification definition and the specific Annex III limit."), ("Finding an unknown person among many records", "That describes identification rather than the stated sole verification purpose."), ("Inferring the person's emotion", "Emotion inference is a different purpose.")),
            assessment([2], [3, 4], "A camera identifies passers-by without involvement against a reference database. Which analysis is directly relevant?", "Which identity category concerns matching people without active involvement, typically at a distance?", ("Remote biometric identification", "Those facts match the remote identity definition."), ("Only sole-purpose claimed-identity verification", "The passers-by are not actively confirming a claim."), ("No biometric analysis because a camera is distant", "Distance does not exclude; it can be part of the remote facts.")),
        ],
    },
    "A02": {
        "locator": "Article 3(39), 3(40); Annex III 1(b), 1(c); Article 5(1)(f), 5(1)(g)",
        "summary": "Separate biometric emotion inference from sensitive categorisation and check prohibitions first.",
        "screens": [
            ["**Emotion recognition** identifies or infers emotions or intentions from a person's biometric data. Inferring engagement from facial processing differs from reading an explicit questionnaire answer: the data and inference matter.", "Northbridge must record what is inferred and from which processed signals. A product title such as 'wellbeing assistant' cannot establish or remove this definition."],
            ["**Biometric categorisation** assigns people to categories using biometric data, subject to the definition's ancillary-service and objective technical-necessity limit. Both parts of that narrow exclusion need evidence.", "A commercial service label alone cannot justify the exclusion. Ask which category is inferred, from which biometric data, and why the ancillary function is technically necessary."],
            ["Annex III 1(b) concerns categorisation by sensitive or protected attributes inferred from biometric data; point 1(c) concerns emotion recognition. They are listed only insofar as their use is otherwise legally permitted.", "Article 5 can prohibit specific emotion settings or sensitive-category inference. High-risk treatment does not make those uses lawful. The later prohibition module examines each exact boundary."],
            ["Fictional case: Northbridge considers two tools—one infers intentions from facial signals, another infers a sensitive category from those signals. Keep their purposes distinct and check each relevant rule.", "An emotion system is not defined by categorising a person into any group; a categorisation system is not automatically emotion recognition. Do not collapse the definitions into 'all cameras'."],
        ],
        "questions": [
            assessment([0], [1], "A tool infers intention from processed facial signals. Which definition needs examination?", "Which concept connects inferred intentions with biometric inputs?", ("Emotion recognition", "Article 3(39) includes emotion or intention inference from biometrics."), ("Every explicit survey response automatically", "A response alone does not establish biometric inference."), ("Only identity verification", "Confirming identity is a distinct purpose.")),
            assessment([1], [2], "A vendor calls categorisation 'ancillary to our commercial service'. What evidence is still needed for the definition's limit?", "Does ancillary commercial use alone satisfy the categorisation exclusion?", ("Strict necessity for objective technical reasons", "The definition requires this as well as ancillary status."), ("Only an attractive product name", "A name proves neither condition."), ("Only a profitable business model", "Profitability is not objective technical necessity.")),
            assessment([0, 1], [3, 4], "A sensitive biometric function is listed in Annex III but may be prohibited. How should it be handled?", "Does inclusion in the biometrics high-risk list establish permission?", ("Check the applicable prohibition and other law", "The list is limited to legally permitted uses."), ("Treat high-risk status as an authorisation", "Classification cannot cure a prohibited practice."), ("Ignore its specific inferred attribute", "The actual attribute determines the relevant categorisation test.")),
        ],
    },
    "A03": {
        "locator": "Annex III 3(a), 3(b); Article 6(2), 6(3)",
        "summary": "Recognise educational admission and learning-outcome functions at every institutional level.",
        "screens": [
            ["The **educational-access use** includes determining access or admission, or assigning people to educational and vocational-training institutions at all levels. It is not limited to universities.", "Northbridge's fictional training college considers an admissions assistant recommending which applicants enter a programme. Identify that concrete purpose rather than classifying all learning software alike."],
            ["The **learning-outcome use** includes evaluating learning outcomes in those institutions, including when the outcomes steer a person's learning process.", "An AI assessor evaluating a student's work and changing the next learning path needs comparison with point 3(b). A system's feedback being called 'helpful' does not eliminate the evaluation function."],
            ["These listed purposes differ from simply organising administrative documents or providing general information. The exact intended institutional use is decisive.", "If a claimed administrative tool actually evaluates applications or work, record that. If it only formats a file, examine the actual narrow function; a later lesson applies the full paragraph 3 derogation rather than granting one from this description."],
            ["Northbridge describes admissions and learning evaluation separately even when one platform performs both. Record the institutional context, input, output and how the result is used.", "Annex III listing establishes the route needing analysis. Complete the prohibition, paragraph 3, profiling, scope and date checks before claiming a complete outcome."],
        ],
        "questions": [
            assessment([0], [1], "An AI recommends admissions to a vocational college. Which Annex III educational purpose is directly relevant?", "Does vocational-programme admission fall outside the educational-access point because it is not a university?", ("Educational access/admission at institutional levels", "Point 3(a) includes vocational institutions at all levels."), ("Only university entrance is covered", "That improperly narrows the point's institutional scope."), ("Only document storage is being assessed", "The stated function recommends admission, not just storage.")),
            assessment([1], [2], "A college uses AI to evaluate work and steer each student's learning path. Which point should be compared?", "Which educational use includes evaluation of outcomes used to direct learning?", ("Learning-outcome evaluation, Annex III 3(b)", "The point expressly includes that steering use."), ("Only building maintenance", "That does not describe educational outcome evaluation."), ("Only the price of the learning software", "Price does not decide the intended-purpose comparison.")),
            assessment([0, 1], [3, 4], "One platform handles admission recommendations and learning evaluation. What should the record preserve?", "How should a multi-function educational platform's intended uses be assessed?", ("Separate relevant functions and legal tests", "Each purpose needs comparison with the appropriate listed point."), ("Only the least consequential feature", "That would hide relevant educational decisions."), ("An automatic exemption because it is educational", "The list specifically contains educational purposes.")),
        ],
    },
    "A04": {
        "locator": "Annex III 3(c), 3(d); Article 6(2), 6(3)",
        "summary": "Recognise educational-level assessment and exam-behaviour monitoring without conflating them.",
        "screens": [
            ["**Educational-level assessment** concerns deciding the appropriate level of education a person receives or can access in or within educational and vocational institutions at all levels.", "An institution's AI deciding which level of programme a learner can enter illustrates the purpose. Voluntary study advice outside that institutional decision requires its own factual comparison rather than inheriting this case's result."],
            ["**Examination monitoring** includes AI monitoring and detecting prohibited student behaviour during tests in or within these institutions.", "A fictional exam tool flagging suspected prohibited conduct is relevant even if a teacher later reviews its output. A human in the workflow does not automatically remove the listed intended purpose."],
            ["Keep purpose and reliability separate. A product can have the relevant listed purpose while its claims about accuracy remain unproven. Record both what it is designed to do and how its output affects people.", "Northbridge records whether a flag is shown, ignored, investigated or used to stop an exam. Those downstream consequences matter to the later significant-risk and decision-influence analysis."],
            ["In a combined system, identify level-placement and exam-monitoring functions separately. Compare their institutional facts with points 3(c) and 3(d); then examine the remaining legal tests.", "Calling a monitoring system 'student support' does not alter its actual conduct-detection purpose. Equally, do not claim every camera or every study tool fits the point without those facts."],
        ],
        "questions": [
            assessment([0], [1], "An institution's AI assesses which level of education an individual can access. Which function is indicated?", "What educational purpose does individual programme-level placement describe?", ("Educational-level assessment", "Point 3(c) concerns the appropriate level received or accessible."), ("Only exam misconduct monitoring", "Monitoring test behaviour is a separate purpose."), ("Only general room booking", "Room logistics do not establish educational-level decisions.")),
            assessment([1], [2], "An exam tool detects suspected prohibited conduct for teacher review. Does teacher review alone remove the listed purpose?", "Can human review alone erase an AI tool's exam-behaviour monitoring purpose?", ("No; compare the actual purpose with point 3(d)", "The point concerns monitoring/detection, not only automatic final penalties."), ("Yes; every reviewed output is exempt", "That is not the intended-purpose test."), ("Yes; the support label controls", "A label does not override the actual function.")),
            assessment([0, 1], [3, 4], "What should Northbridge record about an exam flag's use?", "Why describe what happens after the system detects suspected exam misconduct?", ("Its effects on review, examination and people", "Actual consequences support later risk and influence analysis."), ("Only the screen's colour scheme", "That omits the consequential use of the output."), ("Only the vendor's accuracy slogan", "A slogan is not evidence of actual decision use.")),
        ],
    },
    "A05": {
        "locator": "Annex III 4(a), 4(b); Article 6(2), 6(3)",
        "summary": "Identify recruitment and worker-management functions, including targeting, ranking and individual monitoring.",
        "screens": [
            ["**Recruitment use** includes recruitment or selection of people, particularly targeted job advertisements, analysis/filtering of applications and candidate evaluation.", "Northbridge's assistant predicts applicant suitability and ranks applications. Compare that function with point 4(a). A person still choosing interviews does not automatically make a ranking unrelated to selection."],
            ["**Worker-management use** includes decisions affecting work terms, promotion or termination, task allocation based on individual behaviour or traits, and monitoring/evaluation of work performance and behaviour.", "An AI assigning work based on an individual's observed behaviour differs from a simple neutral calendar. Record the basis for allocation and how the output affects work, rather than treating all scheduling alike."],
            ["The listed area includes access to self-employment as well as employment and workers' management. A contractor or platform-worker label should not end the intended-purpose comparison.", "For each function, identify the affected person, personal inputs, output and decision context. Other employment and personal-data rules need their own checks."],
            ["Fictional changed case: Northbridge first uses a tool only to convert application files. It later adds suitability predictions and shortlists. Reassess the actual new function.", "A limited processing function and an evaluative selection function have different evidence. The later derogation module tests whether a listed use qualifies; it does not automatically exempt every tool called administrative."],
        ],
        "questions": [
            assessment([0], [1], "AI filters applications into a shortlist for recruiters. Which Annex III purpose should be checked?", "Which listed use includes analysing and filtering applications?", ("Recruitment or selection", "Point 4(a) expressly includes these recruitment functions."), ("Only unrelated inventory control", "That is not the system's stated intended purpose."), ("No listed purpose whenever a person decides", "Human involvement alone does not remove recruitment purpose.")),
            assessment([1], [2], "AI allocates tasks using individual behavioural records. Which function is directly relevant?", "Which employment point includes behaviour-based task allocation?", ("Worker-management use under point 4(b)", "The basis for individual allocation matches that listed use."), ("Only ordinary date sorting", "The case involves individual behaviour-based allocation."), ("Only applicant admission to a college", "That is a different institutional purpose.")),
            assessment([0, 1], [3, 4], "A file-conversion assistant adds candidate suitability ranking. What should Northbridge do?", "Why reassess an administrative hiring tool when evaluative selection is added?", ("The intended function and decision effects changed", "The new function needs its own listed-use and risk analysis."), ("Keep the old result because the product name stayed", "A stable name does not preserve unchanged legal facts."), ("Treat every administrative label as an exemption", "The actual function, not the label, is assessed.")),
        ],
    },
    "A06": {
        "locator": "Annex III 1–4; Articles 3(12), 5, 6",
        "summary": "Separate platform functions and trace changed decisions across learning and work.",
        "screens": [
            ["**Platform-function assessment** checks each concrete intended use within a platform. Northbridge's fictional platform offers document conversion, programme admission recommendations, applicant ranking and exam-behaviour detection.", "A general 'learning and work assistant' title does not select one legal category for all functions. Map users, inputs, outputs, affected people and decisions for each."],
            ["Admission recommendations need comparison with educational access; candidate ranking needs recruitment comparison; exam monitoring needs its own educational point. These are separate purposes even if one model powers all of them.", "Document conversion has different facts. It does not prove that the platform's other functions are equally narrow. Assess whether each function is part of the same system or a genuinely separate system boundary."],
            ["Changed fact: a supposedly neutral conversion tool extracts personal features and assigns applicant scores before the recruiter sees them. The assessment must use that actual evaluative function.", "A component's internal name does not eliminate its contribution to decisions. Identify profiling and material influence questions, and collect evidence rather than asserting a derogation."],
            ["The case clinic ends with a record of each function's relevant point and open tests. Check prohibitions before permission is assumed, then paragraph 3, scope, dates and other law.", "An unresolved boundary or feature should be explicit. A platform-wide 'safe' conclusion based on its least consequential feature is not supported by the case facts."],
        ],
        "questions": [
            assessment([0], [1, 2], "The platform has admissions, recruitment and exam-monitoring functions. How should the first comparison be recorded?", "Can a shared model give every learning/work platform feature one automatic legal result?", ("By distinct functions and relevant listed purposes", "Shared technology does not erase different intended uses."), ("Only under the document-conversion feature", "That hides consequential functions."), ("Only from the general product title", "The title does not establish the legal facts.")),
            assessment([0], [3], "The 'conversion' component secretly scores applicants. What fact should the assessment use?", "What matters when a supposedly neutral component performs suitability evaluation?", ("The actual personal evaluation and decision use", "Labels do not replace the component's real operation."), ("Only its neutral internal name", "A name cannot negate the scoring facts."), ("Only the model's common vendor", "Vendor identity does not answer the function test.")),
            assessment([0], [4], "Northbridge cannot establish whether two features share decision-relevant outputs. What should it do?", "How should an unresolved platform boundary be treated in the case record?", ("Record the gap and investigate before concluding", "Unknown boundaries should remain visible until supported."), ("Assume separation and declare all uses safe", "That supplies unsupported facts and a blanket conclusion."), ("Use the cheapest feature's result for all uses", "Price and unrelated features do not determine classification.")),
        ],
    },
}
