"""Notification, independence and continuity of conformity assessors."""

from high_risk_content import lesson, question
from conformity_sources import add_registered_sources

LESSONS = {
    "F13": lesson("Articles 28, 30, 35, 39; Annex XIV", "Verify the assessor's legal role and exact notified scope.", [
        ["A **notifying authority** is the Member State authority responsible for procedures to assess, designate, notify and monitor conformity assessment bodies. States may use their national accreditation body for assessment and monitoring. The authority supervises assessors; it is not ordinarily the provider's product consultant."],
        ["Article 28 requires impartial organisation, notification decisions by competent people different from those assessing the body, confidentiality and adequate expert staff. Authorities may not commercially offer the assessors' activities or competing consultancy. These safeguards support trust in designation; they do not themselves assess your product."],
        ["A **notified body** is a conformity assessor designated and notified for particular tasks and system types. A consultant or ordinary certification business is not automatically a notified body. Article 35 provides a single Commission identification number and an updated public list of bodies and their activities; verify the actual entry and current status."],
        ["**Notified scope** includes the activity, assessment module and system types. Annex XIV supplies product codes, biometric codes and technology-specific codes for applications and notification. A code for one category is not authorisation for every AI system. Match the proposed task to the current entry, not just the body's name."],
        ["Annex XIV distinguishes Section A product categories, remote biometric identification, biometric categorisation and emotion recognition, plus symbolic, machine-learning, generative/GPAI-based and emerging technology codes. These are lookup categories, not a new high-risk classification test. Article 39 permits specified third-country bodies through a Union agreement and qualifying requirements or equivalent compliance; an overseas certificate alone establishes neither condition."],
    ], [
        question([0], [1, 2], "Who designates and monitors conformity assessors?", "Which role is responsible for the notification procedures?", ("The designated notifying authority.", "It establishes and carries out the relevant procedures."), ("Any provider's commercial sales team.", "Sales authority does not create legal designation powers."), ("Any consultant advertising compliance services.", "Consultancy is not the notifying-authority role.")),
        question([1], [3], "A consultant has an impressive certificate logo. What establishes notified-body status?", "What evidence is needed beyond a commercial assessor's branding?", ("Its current designation and notified tasks.", "The legal role depends on notification, not appearance."), ("Its popularity among suppliers.", "Popularity does not establish designation."), ("Its guarantee of a successful assessment.", "A guarantee is not proof of the notified role.")),
        question([2], [4, 5], "A body is notified for another system category. Can its number alone establish the needed scope?", "What must be matched before appointing a numbered body?", ("Task, system codes, current scope and status.", "The number identifies the body; the entry defines its tasks."), ("Only its name and office address.", "Identity alone does not establish task eligibility."), ("Only its cheapest available price.", "Price does not define legal assessment scope.")),
    ]),
    "F14": lesson("Articles 28(8)–(9), 29–30, 32, 43(3)", "Distinguish designation evidence, effective notification and sector arrangements.", [
        ["An assessor's **designation evidence** includes its requested activities, modules and system types, and an accreditation certificate where available. Existing designation documents are added. Without accreditation, the body must supply documentary evidence for verification and continuing monitoring. Relevant changes require updated documentation."],
        ["Article 32 gives a body a limited presumption of satisfying Article 31 where it conforms to the relevant cited harmonised standards, to the extent they cover those requirements. This is a presumption about the body, not conformity of a client's AI product."],
        ["Notification includes full scope and competence details. The **objection window** is two weeks where the notification includes the Article 29(2) accreditation certificate, or two months where it relies on Article 29(3) documentary evidence. The body may act only if no relevant objection is raised within that window. Objections lead to Commission consultation and a decision, not automatic authorisation."],
        ["A **unified designation procedure** combines AI Act and Section A sector applications where the relevant sector law provides for it. Authorities cooperate, use existing designation evidence and avoid duplication while checking both frameworks. The sector authority normally serves that procedure unless the State appoints another. A body with several qualifying sector designations applies once for the AI designation; its legal scope must still be checked."],
        ["For transitional sector assessment powers, Article 43(3) requires evidenced assessment of Article 31(4), (5), (10) and (11) under the existing notification, plus application for Section 4 designation by 28 January 2028. 'Already notified elsewhere' is not enough. Harbour should retain the specific evidence and current authority record."],
    ], [
        question([0], [1, 2], "A body qualifies for an Article 32 presumption. What does it concern?", "Does assessor accreditation or its presumption itself certify a client's system?", ("The covered Article 31 requirements for the body.", "The body and the client's product are different assessment subjects."), ("All products the body will ever assess.", "Product conformity requires its own procedure and evidence."), ("Every client's registration automatically.", "Body qualification does not perform provider registration.")),
        question([1], [3], "Notification relies on Article 29(3) documentary evidence. Which objection window applies?", "Which period differs from the accredited notification's two weeks?", ("Two months, with no relevant objection.", "Article 30(4) specifies that documentary-evidence window."), ("Two weeks regardless of the evidence type.", "The paragraph distinguishes the evidence routes."), ("Immediate effect upon submitting an application.", "Application alone is not effective notification.")),
        question([2], [4, 5], "Harbour's sector body seeks a combined designation. What should the reviewer check?", "When is a unified application available, and what remains necessary?", ("Sector-law availability and evidence satisfying both frameworks.", "The combined procedure avoids duplication, not compliance checks."), ("That combining applications removes all competence checks.", "Both frameworks' requirements remain relevant."), ("That any sector notification automatically gives unlimited AI scope.", "The specific scope and transitional conditions still matter.")),
    ]),
    "F15": lesson("Article 31(1)–(12); Article 34(3)", "Check impartiality, protected information and competent resources.", [
        ["An assessor must have legal personality under Member State law and suitable organisation, quality management, resources, processes and cybersecurity. Its structure and reporting lines must support confidence in its results. **Independence** requires separation from the provider, economically interested operators and competitors, with documented impartiality safeguards."],
        ["The body, management and assessment staff must avoid direct involvement and conflicts involving design, development, marketing, use or representation of the assessed systems. Conflicting consultancy is specifically relevant. Necessary operational or personal use permitted by Article 31(4) does not erase these conflict rules."],
        ["**Confidentiality** protects information received in assessment, including through staff, committees, associated bodies and subcontractors. Article 31(7) and Article 78 permit required legal disclosures. Article 34(3) requires relevant records, including provider documentation, for the notifying authority's work. 'Confidential' is not a reason to refuse every lawful authority request."],
        ["**Competence** means having the professional integrity, methods and experienced administrative, technical, legal and scientific staff needed for the notified tasks. The body needs internal ability to evaluate outsourced work, not just a list of external experts. Suitable liability insurance is required unless the stated State-liability exception applies."],
        ["Procedures take account of provider size, sector, structure and system complexity. Bodies participate in coordination and remain aware of relevant standards. For fictional Harbour, ask for competent scope evidence and conflict controls. A low fee, familiar brand or promise of approval does not establish these safeguards."],
    ], [
        question([0], [1, 2], "The assessment team also designed the product it will assess. What requires examination?", "Why does selling design consultancy to the assessed provider matter?", ("A conflict with independence and impartiality requirements.", "The assessment must meet the statutory separation safeguards."), ("Only whether the consultancy fee was small.", "Fee size does not remove the conflict question."), ("Nothing if the team knows the product well.", "Knowledge does not substitute for independence.")),
        question([1], [3], "A body refuses all notifying-authority documents because they are confidential. Is that justified?", "Does confidentiality automatically block a lawful assessment-record request?", ("No; protected handling and required disclosure must coexist.", "The law provides protected information and lawful authority access."), ("Yes; confidentiality prohibits every disclosure.", "That overlooks the stated legal exceptions and duties."), ("No; therefore every record must be published publicly.", "Required authority disclosure is not unrestricted publication.")),
        question([2], [4], "A body outsources all technical work but cannot evaluate it internally. What is missing?", "Can external experts replace the body's own evaluation competence?", ("Sufficient internal competence for the outsourced tasks.", "Article 31 requires the ability to evaluate work done on its behalf."), ("Only a more attractive expert directory.", "Listing names does not establish evaluation ability."), ("Nothing because outsourcing transfers all responsibility.", "The body retains responsibility and competence duties.")),
    ]),
    "F16": lesson("Articles 31(8), 33, 34", "Control outsourced assessment without reducing required protection.", [
        ["**Subcontracting accountability** stays with the notified body. It must ensure a subsidiary or subcontractor meets Article 31 requirements and inform the notifying authority. It retains full responsibility for the tasks; outsourcing does not create a responsibility gap."],
        ["The provider must agree to subcontracted/subsidiary activities. The body makes its subsidiary list public and retains qualification and work documents for the notifying authority for five years after subcontracting ends. A provider should know who performs the assessment and under which controls."],
        ["**Proportionate assessment** avoids unnecessary burdens and accounts for size, sector, structure and complexity, especially micro- and small-enterprise costs. Article 34 still requires the necessary rigour and protection. Proportionality is not an exemption from an applicable requirement."],
        ["Harbour agrees to a qualified specialist examining a defined dataset under the body's responsibility. That differs from transferring the assessment to an unidentified firm without consent. A shorter evidence package can be appropriate only when it still establishes the required substance."],
    ], [
        question([0], [1], "A subcontractor performs an assessment task. Who retains full responsibility?", "Does subcontracting transfer the notified body's accountability away?", ("The notified body.", "Article 33 preserves its full task responsibility."), ("Only the provider's sales representative.", "Sales staff do not replace the body's statutory responsibility."), ("Nobody once the task is outsourced.", "Outsourcing cannot create that accountability gap.")),
        question([0], [2, 4], "Harbour discovers undisclosed outsourced assessment without its agreement. What is missing?", "What condition is required for subcontracted activities?", ("Provider agreement and the specified qualification controls.", "Article 33 requires these conditions."), ("Only a change to the provider's logo.", "Branding does not establish consent or qualification."), ("A promise that the supplier will never use specialists.", "Qualified, agreed subcontracting can be permitted.")),
        question([1], [3], "A small provider asks to omit a necessary safety test merely to save cost. What does proportionality allow?", "Does reducing unnecessary burden mean lowering required protection?", ("Adapt the effort while preserving required rigour and protection.", "Article 34 requires both proportionality and the protection level."), ("Omit any requirement that costs money.", "Cost alone does not remove applicable requirements."), ("Always require identical paperwork for every system.", "The provision requires attention to relevant size and complexity.")),
    ]),
    "F17": lesson("Articles 36–38", "Respond to designation changes without assuming certificate continuity.", [
        ["A **designation change response** starts by identifying extension, restriction, suspension, withdrawal or cessation. Extensions follow Articles 29–30; other changes follow Article 36. Bodies notify affected providers within ten days of suspension, restriction or withdrawal. Authorities preserve records and assess affected certificates, including unduly issued ones."],
        ["For planned cessation, the body gives at least one year's notice. Certificates may remain valid for nine months after cessation only with another body's written assumption of responsibility and a full assessment completed by that period's end. This is a conditional continuity mechanism, not automatic renewal."],
        ["Suspension/restriction has distinct authority-confirmation conditions under Article 36(8), including no-risk/remedy-timeline or monitoring-capability arrangements. Withdrawal has a different nine-month mechanism: no-risk confirmation, written immediate responsibility by another body and assessment within twelve months. Possible three-month extensions are bounded by the twelve-month total. Unduly issued certificates are excluded. Look up the actual branch and deadlines before relying on continuity."],
        ["A **competence challenge** under Article 37 lets the Commission investigate doubts, obtain authority evidence confidentially and request corrective action. If the Member State fails to act, the Commission may suspend, restrict or withdraw designation through an implementing act. An allegation is not by itself proof that every certificate is invalid."],
        ["**Assessor coordination** under Article 38 supports sectoral cooperation, body participation and exchange of authority knowledge. It does not provide a new approval for your product. Retain the authority/body decisions and trace the actual effect on your certificate and monitoring arrangements."],
    ], [
        question([0], [1, 2], "A body plans to cease work. Is nine-month certificate continuity automatic?", "What must exist before relying on the cessation mechanism?", ("Written replacement responsibility and the specified assessment conditions.", "Article 36(3) makes the continuity conditional."), ("Only the provider's wish to keep using the certificate.", "Provider preference does not establish continuity."), ("Only an old certificate image stored locally.", "An image does not resolve the body change or conditions.")),
        question([1], [4], "A body's competence is credibly questioned. Which process can address it?", "What is the Article 37 response to doubts about continuing competence?", ("Commission investigation and the specified corrective process.", "The article defines investigation, evidence and corrective powers."), ("Immediate acceptance because the body was once notified.", "Past notification does not resolve continuing competence."), ("Automatic invalidation of every unrelated certificate.", "An allegation alone does not establish that conclusion.")),
        question([2], [5], "A body attends the sector coordination group. What does that establish for Harbour?", "Does coordination participation itself approve a client's system?", ("Participation supports coordination, not product approval.", "The product still needs the applicable assessment and evidence."), ("The product is automatically approved by the group.", "The group is not a substitute product assessment."), ("The product needs no current certificate checks.", "Coordination does not resolve certificate validity.")),
    ]),
    "F18": lesson("Articles 28–39; Annex XIV", "Select a fictional assessor using concrete evidence.", [
        ["**Fictional offers:** ClearScope has the stipulated current notified task and relevant system/technology scope, qualified staff and disclosed subcontracting controls. FastStamp has a number for another category and promises guaranteed approval. FamiliarDesign helped design Harbour and offers to assess its own work. These names do not describe actual notified bodies."],
        ["ClearScope is the strongest candidate on the stated evidence, subject to the remaining required checks and actual procedure. FastStamp's number does not establish scope for this task. FamiliarDesign raises an independence conflict that experience with the product does not cure."],
        ["Ask ClearScope for provider-agreed subcontracting, qualification evidence, confidential handling and access arrangements. Retain the current notified entry and appointment evidence. A suitable appointment does not guarantee that the assessed system will conform."],
        ["Later, ClearScope's designation is restricted. Read the actual authority decision and applicable Article 36 continuity branch. Record certificate effects, monitoring responsibility, file preservation, replacement arrangements and deadlines. Do not assume its earlier suitability makes the restriction irrelevant."],
    ], [
        question([0], [1, 2], "Which offer best matches the case's scope and qualification evidence?", "Which fictional assessor is supported by the stipulated current task and competence?", ("ClearScope, subject to remaining required checks.", "Its stated evidence matches the task without promising automatic conformity."), ("FastStamp because any identification number is sufficient.", "Its notified category does not match the task."), ("FamiliarDesign because self-assessment guarantees familiarity.", "Its design involvement raises an independence conflict.")),
        question([0], [3], "ClearScope uses a specialist. What should Harbour require?", "What supports lawful subcontracted assessment in the case?", ("Agreement, qualification and responsibility controls.", "These preserve the Article 33 conditions."), ("An assurance that the specialist needs no qualifications.", "Qualification controls apply to outsourced tasks."), ("A transfer of all body responsibility to Harbour.", "The notified body retains full responsibility for its outsourced work.")),
        question([0], [4], "ClearScope's designation is later restricted. What should Harbour do?", "Does the earlier appointment settle all later continuity questions?", ("Check the decision, certificate effect and continuity conditions.", "The later change requires its own supported response."), ("Ignore the restriction until its old certificate expires.", "Designation changes can affect monitoring and validity now."), ("Treat every Article 36 branch as the same automatic renewal.", "The branches have different conditions and deadlines.")),
    ]),
}

LESSONS = add_registered_sources(LESSONS)
