"""Foundations: original teaching text and assessment cases."""

from lesson_builder import assessment

LESSONS = {
    "I01": {
        "locator": "Articles 1, 3(2), 3(56), 4",
        "summary": "Find the right regulatory layer, distinguish likelihood from severity, and support practical AI literacy.",
        "screens": [
            ["**The AI Act** is Regulation (EU) 2024/1689. It promotes trustworthy AI and innovation while protecting health, safety and fundamental rights. It regulates specific activities and actors, rather than giving every technology a single permission label.", "We follow a fictional organisation, **Northbridge**, considering several AI tools. Its name and cases are invented. Each case needs its own facts and legal test."],
            ["Article 1 maps several regulatory layers: prohibited practices, high-risk systems, transparency, general-purpose models, governance and innovation support. A prohibition asks whether a particular practice is forbidden. High-risk classification asks which regulatory route a system enters.", "These questions can overlap. Passing one test does not answer all the others. This first course develops foundations, high-risk classification and prohibited practices; later parts cover the remaining layers."],
            ["**Risk** combines how likely harm is with how severe it would be. A frequent small inconvenience and a rare serious injury have different risk profiles. A low error rate alone cannot show that the consequences are acceptable.", "Northbridge records both the chance of a tool making a mistake and what that mistake could do to people. The statutory definition does not prescribe one numerical formula for every assessment."],
            ["**AI literacy** is knowledge and judgment enabling informed use and awareness of opportunities, risks and harm. Under amended Article 4, providers and deployers must take measures supporting staff and other people operating AI on their behalf, considering experience, training, use context and affected people.", "Northbridge trains its recruitment team on the tool's limits and review process. The rule does not require a particular certificate or a guaranteed level for each individual. Tailor the support to the actual work."],
        ],
        "questions": [
            assessment([0], [2], "Northbridge wants to know whether a practice is forbidden. Which layer should it examine first?", "Which regulatory layer answers whether a proposed AI practice is prohibited?", ("The prohibited-practices rules", "Article 5 addresses prohibitions; a classification alone is insufficient."), ("The model's general capabilities", "Model capabilities do not answer the specific prohibition test."), ("The innovation-support measures", "Support measures do not decide whether a practice is forbidden.")),
            assessment([1], [3], "A tool rarely makes errors, but one error could seriously injure someone. What must the risk record include?", "Why is an error-frequency report insufficient when an error could cause serious harm?", ("Both likelihood and severity of harm", "Article 3(2) combines probability and severity."), ("Only the number of recorded errors", "Frequency omits the seriousness of the outcome."), ("Only the tool's purchase price", "Price does not establish the probability or severity of harm.")),
            assessment([2], [4], "Which measure best fits Northbridge's literacy duty for staff using a recruitment tool?", "How should Northbridge support staff who operate an unfamiliar AI tool?", ("Train them on its limits and use context", "Support should reflect experience, context and people affected."), ("Guarantee every employee passes one exam", "Article 4 does not require a guaranteed individual level."), ("Buy a certificate and omit practical support", "A certificate alone does not establish relevant literacy support.")),
        ],
    },
    "I02": {
        "locator": "Article 3(1), 3(63), 3(66), recital 12",
        "summary": "Distinguish an AI system from ordinary automation and from a general-purpose model.",
        "additional_sources": [{"title": "Commission AI-system definition guidelines C(2025) 5053 final, paragraphs 8–10, 14–23, 26–31, 46–47, 61–64; non-binding", "url": "https://ec.europa.eu/newsroom/dae/redirection/document/112455"}],
        "screens": [
            ["An **AI system** is machine-based, operates with some autonomy and infers from inputs how to generate outputs for explicit or implicit objectives. Its predictions, content, recommendations or decisions can influence physical or digital environments.", "Ask what the system actually does, how it was built and where its output goes. A product being marketed as 'AI' is evidence to investigate, not a legal definition."],
            ["Inference is central to the definition. Learning approaches can derive patterns from data; logic or knowledge-based approaches can infer from encoded knowledge. Ordinary sorting or arithmetic that simply executes fixed human instructions is not automatically AI.", "In our fictional example, an ordinary list sorted by a specified date is different from a learned system predicting a person's suitability. Assess the actual architecture rather than relying only on the output's label."],
            ["Autonomy does not mean complete independence from people. A person may submit an input while the system generates the output itself. A later human review does not, by itself, remove the system from the definition.", "Adaptiveness after deployment is optional: the Act says a system may adapt. A trained system can remain an AI system even when its deployed parameters stay fixed. The Commission guidelines explain these elements but are non-binding."],
            ["A **general-purpose AI model** has significant generality and can competently perform many distinct tasks and be integrated into downstream applications. A model and an AI system are related but different objects.", "Northbridge integrates a model into an assistant with documents, an interface and permissions. Assess the assistant's actual function as a system. Do not copy a model-level conclusion to every application using it. Research/prototyping exclusions and model obligations require their own checks."],
        ],
        "questions": [
            assessment([0], [1, 2], "A sales tool sorts entries by a fixed date rule. What is the sound starting point?", "A spreadsheet follows explicit sorting instructions only. What should an assessor avoid?", ("Check the definition; automation alone is insufficient", "Inference and the other definition elements need evidence."), ("Classify all automated software as AI", "Automation alone does not establish the statutory definition."), ("Classify it solely from its marketing label", "Branding cannot replace architecture and functionality evidence.")),
            assessment([0], [3], "A learned recommendation system never retrains after deployment. Does that fact alone exclude it?", "Can a system with fixed deployed parameters still satisfy the AI-system definition?", ("Post-deployment adaptation is optional", "The definition uses an optional adaptation element."), ("Every AI system must keep retraining", "The statutory definition does not require continuing learning."), ("Human review always removes AI status", "Review does not remove the system's inference capability.")),
            assessment([1], [4], "One general-purpose model powers a chat assistant and a separate hiring tool. What follows?", "Why must two different applications built on one general-purpose model be examined separately?", ("Their system functions and contexts can differ", "A shared model does not give applications identical purposes or legal treatment."), ("Every application has the same classification", "The application and its intended use still matter."), ("The interface makes model rules disappear", "System and model rules are distinct and may both matter.")),
        ],
    },
    "I03": {
        "locator": "Article 3(12), 3(13), 3(52)",
        "summary": "Describe a concrete use case, distinguish intended use from misuse, and recognise personal profiling.",
        "additional_sources": [{"title": "GDPR Article 4(4): profiling", "url": "https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng"}, {"title": "Law Enforcement Directive Article 3(4): profiling", "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1748537587593&uri=CELEX:32016L0680"}],
        "screens": [
            ["**Intended purpose** is the provider's specified use, context and conditions. Evidence includes instructions, technical documentation, sales materials and statements. Read these together rather than taking one reassuring sentence as the whole purpose.", "Northbridge's assistant is advertised for internal policy questions. A new function ranking applicants changes the facts to be assessed. The provider's description and the actual configuration both belong in the record."],
            ["A useful **use-case description** states the system boundary, the people using it, inputs, outputs, people affected and the action following each output. This is a practical assessment method, not a statutory certificate.", "Compare 'uses an assistant' with 'HR enters applicants' experience; the tool predicts suitability; recruiters see a ranking before interviews'. The second description exposes decisions and people that a classification test can examine."],
            ["**Profiling** uses automated processing of personal data to evaluate aspects of a natural person, such as work performance, reliability, interests, health or behaviour. The AI Act refers to GDPR, law-enforcement and Union-institution definitions according to context.", "Predicting an applicant's suitability from their personal history is an illustrative profiling case. Merely alphabetising names does not, by that fact alone, evaluate personal aspects. A person approving the final decision does not mean the prior evaluation was not automated."],
            ["**Reasonably foreseeable misuse** is use outside intended purpose that can result from foreseeable human behaviour or interaction with systems. Record it separately from the specified purpose. Do not rewrite actual use as compliant by copying the provider's disclaimer.", "Northbridge records who sees the ranking, whether it changes interview selection and which documents support that conclusion. When a needed fact is unknown, mark it unknown and obtain evidence before issuing a definitive assessment."],
        ],
        "questions": [
            assessment([0], [1], "A sales page promises applicant ranking while instructions say 'general office assistance'. What should Northbridge do?", "Conflicting instructions and sales claims describe different uses. How should intended purpose be checked?", ("Examine all purpose evidence and resolve the conflict", "Article 3(12) includes several provider information sources."), ("Use only the least demanding description", "Selecting a convenient statement hides contradictory evidence."), ("Ignore every provider statement", "Provider information is central to intended purpose.")),
            assessment([1], [2, 4], "Which description lets an assessor examine Northbridge's hiring use?", "What should a use-case record say before a hiring tool is assessed?", ("Inputs, ranking output, affected people and recruitment action", "These facts connect the system to the actual use and decisions."), ("Only the vendor's name and monthly price", "Those facts omit what the system does to people."), ("Only the phrase 'responsible AI assistant'", "A slogan supplies no assessable operation or context.")),
            assessment([2], [3], "Software predicts an applicant's reliability from their personal history; a human later chooses. What is relevant?", "Does human approval erase automated evaluation of an applicant's personal reliability?", ("The automated evaluation can still be profiling", "Profiling concerns evaluating personal aspects, not only final decisions."), ("Profiling requires the final decision to be automatic", "That adds a condition not present in the profiling definition."), ("All alphabetical sorting is personal evaluation", "Handling a name does not itself evaluate personal aspects.")),
        ],
    },
    "I04": {
        "locator": "Article 3(3)–(8), 3(11), 25",
        "summary": "Assign provider and deployer roles from actions rather than informal job labels.",
        "screens": [
            ["A **provider** develops a system or model, or has it developed, and places it on the market or puts the system into service under its own name or trademark. Payment is not required.", "A company commissioning and supplying its own branded assistant may be a provider even if a contractor writes the software. An internal system for own use can also involve putting into service; 'we did not sell it' is not a complete test."],
            ["A **deployer** uses an AI system under its authority, except personal non-professional use. Northbridge using a vendor's recruitment system for its hiring process is an illustrative deployer case.", "The company is the relevant actor in this case, not automatically each employee who clicks a button. An organisation may occupy more than one role for different activities. Record the actor, action and system together."],
            ["Other defined roles matter in a supply chain. An **importer** in the Union first places a system bearing a third-country actor's name on the Union market. A **distributor** makes it available in the supply chain without being provider or importer. An **authorised representative** accepts a written mandate.", "These definitions cannot be inferred just from an invoice saying 'partner'. Identify where the actor is established, whose name appears, what is supplied and what mandate exists."],
            ["Use an **actor lookup**: list each participant and action, apply the definitions, and retain supporting contracts and documentation. Buying, integrating and commissioning create different fact patterns.", "Changes may require a fresh role analysis. Article 25 contains specific situations in which an actor becomes the provider of a high-risk system, including certain name, modification and purpose changes. This lesson flags the lookup; do not assume every minor edit transfers provider responsibility."],
        ],
        "questions": [
            assessment([0], [1], "Northbridge has an assistant developed and puts it into service under its own name. Which role needs assessment?", "A contractor codes a company's own branded assistant for first use. Can the company meet the provider definition?", ("Provider, even if it did not write the code", "Having the system developed and supplying it under its name is relevant."), ("Only deployer because it paid a contractor", "Outsourcing development does not rule out provider status."), ("No role because the assistant is free", "Payment is not required by the provider definition.")),
            assessment([1], [2], "Northbridge uses a vendor's system under its authority for recruitment. Which role is directly indicated?", "Which role describes an organisation operating a vendor's AI system for its own professional process?", ("Deployer", "The definition concerns use under the actor's authority."), ("Authorised representative", "That role needs an accepted written provider mandate."), ("Personal non-professional user", "Organisational recruitment is professional activity.")),
            assessment([2], [3, 4], "A contract calls a reseller a 'technology partner'. What should determine its legal role?", "How should Northbridge check the role of a vaguely labelled supply-chain partner?", ("Its actions, establishment, branding and mandate", "Definitions attach to specific conduct and relationships."), ("Only the contract's informal partner label", "An informal label does not establish a statutory role."), ("Only the number of staff it employs", "Headcount does not determine these actor definitions.")),
        ],
    },
    "I05": {
        "locator": "Article 2(1)–(13)",
        "summary": "Check the EU connection, exact exclusions and laws that continue to apply.",
        "screens": [
            ["**Territorial scope** is the Act's connection to the Union. It includes providers supplying systems or models in the Union, deployers established or located there, and certain third-country providers or deployers when system outputs are used in the Union.", "A non-EU vendor serving Northbridge in the EU is not outside scope merely because its server or office is overseas. First identify the actors and the relevant supply or use; location alone does not settle every paragraph."],
            ["**Scope exclusions** have exact conditions. Article 2 addresses exclusively military, defence or national-security purposes; sole scientific research and development; and research, testing or development before market placement or service.", "A commercial hiring pilot is not automatically excluded because someone calls it research. The pre-market research exclusion does not cover testing in real-world conditions. Exclusivity and the exact stage need evidence; other applicable law still matters."],
            ["Personal non-professional activity is treated differently from professional deployment. Free and open-source system releases have a conditional exclusion, with high-risk, Article 5 and Article 50 cases outside that exclusion.", "Northbridge cannot assume an open-source recruitment system is exempt. Article 2 also contains specific sector limits and conditional equivalent-protection provisions. Their exact product and obligation scope must be looked up; they are not a general exemption for regulated industries."],
            ["The **relationship with other law** is cumulative. Personal-data, privacy, consumer and product-safety rules can remain applicable. More protective worker rules can also matter. Completing an AI Act assessment does not grant permission under every other law.", "For Northbridge, retain a separate list of data-protection, employment and sector questions. A legally excluded AI Act activity may still be regulated elsewhere; 'out of this Act's scope' is a narrow conclusion."],
        ],
        "questions": [
            assessment([0], [1], "A vendor outside the EU supplies an AI system for Northbridge's EU use. What should the assessor do?", "Does an overseas supplier's location alone settle AI Act territorial scope for an EU customer?", ("Examine the Union supply and use connections", "Article 2 covers relevant connections regardless of supplier location."), ("Exclude it because the server is overseas", "Server location is not the entire territorial test."), ("Ignore the customer and assess only nationality", "Relevant actors, establishment and use must be examined.")),
            assessment([1], [2, 3], "Northbridge labels live applicant testing a research pilot. What follows?", "Can a professional real-world pilot claim the pre-market research exclusion from its label alone?", ("Check the exclusion's conditions; the label is insufficient", "Real-world testing is not covered by that particular exclusion."), ("All research-labelled activity is excluded", "The rule has purpose, stage and real-world limits."), ("Every open-source tool is excluded automatically", "High-risk and specified practice cases limit that exclusion.")),
            assessment([2], [4], "A use falls outside one AI Act rule. What should Northbridge record about personal-data law?", "Does an AI Act exclusion automatically remove GDPR or employment-law duties?", ("Other applicable laws require their own analysis", "Article 2 preserves other legal protections."), ("All other laws cease to apply", "An AI Act scope conclusion has no such effect."), ("A vendor can waive all laws by contract", "A contract does not supply a general legal exemption.")),
        ],
    },
    "I06": {
        "locator": "Article 6(3)–(8), Article 96; consolidation notice",
        "summary": "Read an exact legal locator and distinguish binding law, consolidated text and guidance.",
        "additional_sources": [{"title": "Commission publication: draft classification guidance, status checked 6 October 2026", "url": "https://digital-strategy.ec.europa.eu/en/library/draft-commission-guidelines-classification-high-risk-ai-systems"}],
        "screens": [
            ["**Legal source authority** asks what kind of text you are using. Authentic Official Journal regulations and amendments supply the binding instruments. A consolidated version combines changes for reading convenience; its documentation notice does not make it a new binding instrument.", "Our working baseline is the 27 July 2026 consolidation. Record its version and consult the authentic instruments where needed. A presentation, checklist or this course helps learning but cannot replace the legal text."],
            ["A **provision locator** identifies an exact place. Article 6(3)(a) means Article 6, paragraph 3, point (a). An annex may have its own numbered points and letters. Read the opening words and connected paragraphs too.", "A quotation of 'narrow procedural task' alone omits the paragraph's no-significant-risk gateway and the final profiling rule. To apply a condition, read the full test around it, not just the appealing phrase."],
            ["**Commission guidance** explains the Commission's interpretation and examples. Non-binding guidance does not amend a regulation. Draft guidance adds another status limit: its content may change and it is not an adopted legal rule.", "The classification publication checked for this course still labels its three documents draft. Record publication and checking dates. Never elevate an example into an exhaustive legal list or import an older guideline's dates over amended law."],
            ["A practical source note says: instrument and version, exact locator, whether the statement is law or interpretation, and facts to which it is being applied. Distinguish a proposed amendment from one that has actually entered into force.", "Northbridge's reviewer reads the operative paragraph, checks amendments and exclusions, then explains how the evidence meets each condition. 'The slide says so' is not a source-backed assessment."],
        ],
        "questions": [
            assessment([0], [1], "Which text supplies the authentic binding instrument when a slide and a regulation differ?", "A training slide simplifies an amended legal rule. Which source should control the legal test?", ("The authentic Official Journal instruments", "Training and consolidation tools do not replace the authentic law."), ("The slide because it is shorter", "Convenience does not confer legal authority."), ("The vendor checklist because it is branded", "Branding is not a source of binding EU law.")),
            assessment([1], [2], "A reviewer quotes Article 6(3)(a) but ignores the paragraph opening and profiling rule. What is missing?", "How should the 'narrow procedural task' condition be read?", ("The surrounding gateway and qualification", "The point operates within the full paragraph's conditions."), ("Only the article's title", "A title does not supply the omitted operative tests."), ("Only the tool's price", "Price does not repair an incomplete statutory test.")),
            assessment([2], [3, 4], "A draft guideline offers an example different from amended statutory wording. Which approach is sound?", "Can a draft Commission example itself replace an amended regulation's requirements?", ("Keep its draft status and apply binding law", "Guidance supports interpretation but does not amend the Act."), ("Treat the draft as a new binding exemption", "A draft example cannot create a statutory exemption."), ("Assume any newer webpage overrides law", "Publication recency alone does not establish authority.")),
        ],
    },
    "I07": {
        "locator": "Articles 111, 113; Regulation (EU) 2026/1744 Article 2",
        "summary": "Separate entry into force, provision-specific application and conditional transition rules.",
        "screens": [
            ["**Entry into force** is when a legal instrument becomes operative as law. **Application** is when particular provisions begin applying. These can be different dates. Publication is another distinct event.", "The original AI Act was published on 12 July 2024 and entered into force twenty days later, on 1 August 2024. The 2026 amendment entered into force on 27 July 2026. Use the authentic instruments for these events."],
            ["Article 113 supplies several application dates. Chapters I and II generally began on 2 February 2025. The newly inserted Article 5(1)(ba), (bb), (1a) and (1b) instead apply from **2 December 2026**. The default date is **2 August 2026**, with specified exceptions.", "Chapter V's model rules and other listed chapters began on 2 August 2025, with Article 101 excepted. Articles 102–110 apply from 27 July 2026. Identify the provision before selecting a date."],
            ["The amended high-risk timing separates the two routes. Chapter III Sections 1–3, except Article 6(5), apply to Annex III systems from **2 December 2027**, and Annex I systems from **2 August 2028**.", "Those dates do not postpone every other rule for a system. An applicable prohibition or transparency duty needs its own date. Article 6(5), concerning guidance, is explicitly excepted from this postponement."],
            ["A **transition check** examines Article 111 and the system's or model's market/service history. Relevant existing high-risk systems have conditional treatment tied to significant design changes, with a public-authority compliance date. It is not a universal grandfathering permission.", "GPAI models placed before 2 August 2025 have a 2 August 2027 compliance date. Article 111(4) gives specified synthetic-content system providers with pre-2-August-2026 placement until 2 December 2026 for Article 50(2). Apply exact conditions; do not extend that date to all Article 50 duties."],
        ],
        "questions": [
            assessment([0], [1], "A regulation is in force before one of its duties applies. Is that contradictory?", "Can a law's entry into force precede a particular rule's application date?", ("Entry into force and application are different legal events", "The instrument can phase application after entry into force."), ("All duties must apply immediately", "The Act explicitly provides staged dates."), ("Publication and application are identical", "Publication is distinct from both events.")),
            assessment([1], [2, 3], "Which date applies to the newly added intimate-media prohibition in this baseline?", "What date does Article 113 assign to Article 5(1)(ba), rather than the original Chapter II rules?", ("2 December 2026", "Article 113(a) specifically dates the new provisions."), ("2 February 2025", "That general chapter date has an express exception for this addition."), ("2 August 2028", "That date concerns the specified Annex I high-risk rules.")),
            assessment([2], [4], "A supplier says 'old systems are grandfathered'. What should Northbridge ask for?", "What evidence is needed before accepting an existing-system transition claim?", ("Exact transition, dates and design-change facts", "Article 111's conditions are specific to systems and provisions."), ("Only a statement that the product is old", "Age alone does not establish the applicable transition."), ("A promise that every prohibition is postponed", "The high-risk transition preserves the prohibition analysis.")),
        ],
    },
    "I08": {
        "locator": "Articles 2, 3(3), 3(4), 3(12), 5, 6, 111, 113",
        "summary": "Prepare an evidence packet and check prohibitions before treating classification as permission.",
        "screens": [
            ["A **prohibition precheck** asks whether the proposed conduct falls under Article 5 before a high-risk classification is mistaken for permission. 'High-risk' means a regulatory category; it is not a licence to perform a forbidden practice.", "At this stage, identify a potentially relevant prohibition and collect its missing facts. Later modules teach the complete tests. A disclosure, human reviewer or supplier certificate cannot by itself cure a prohibited practice."],
            ["An **assessment evidence packet** is a practical record: system/version and boundary, intended and actual purpose, inputs and outputs, actors, affected people, location, documents and dates. Separate verified facts, assumptions and unresolved questions.", "Northbridge's vendor supplies one broad platform, but its document helper and applicant ranking have different functions. Record each use rather than issuing a platform-wide conclusion from the safest function."],
            ["Fictional case: Northbridge buys an applicant-ranking assistant for EU hiring. The vendor supplies it under its own name; Northbridge uses the ranking to decide interviews. The tool evaluates personal work histories.", "The opening packet therefore identifies vendor and employer actions, applicant data, a recruitment decision and a profiling question. Scope and timing still need documentation. The next classification modules determine the legal route; this screen does not claim the whole compliance assessment is complete."],
            ["A defensible next step matches each needed legal fact to evidence. Request unclear instructions, review contradictory claims, record who actually makes decisions and check relevant dates. Retain the source version used.", "If a prohibition might apply, investigate that full test before proceeding. If the system enters a high-risk route, identify the consequent obligations separately. This workflow is our teaching method for applying Articles 2, 5 and 6, not a statutory safe-harbour form."],
        ],
        "questions": [
            assessment([0], [1], "A vendor calls a potentially prohibited use 'high-risk compliant'. What should Northbridge do first?", "Does a high-risk certificate settle whether the proposed practice is forbidden?", ("Check the full relevant prohibition", "Classification cannot authorise an otherwise prohibited practice."), ("Accept the label as blanket permission", "The label does not answer Article 5."), ("Add a disclosure and skip the legal test", "A disclosure is not a cure for a prohibition.")),
            assessment([1], [2, 3], "Which packet best supports assessment of the recruitment assistant?", "What should a reviewer receive for the fictional applicant-ranking use?", ("Purpose, actors, applicant inputs, outputs and decision use", "Those facts allow scope and classification tests to be applied."), ("Only a general platform brochure", "A brochure alone hides the actual function and decisions."), ("Only the safest unrelated platform feature", "A different function cannot stand in for the recruitment use.")),
            assessment([0, 1], [3, 4], "The vendor cannot explain whether ranking changes interview selection. What is the appropriate next step?", "A material decision-use fact is missing from a classification packet. How should it be handled?", ("Record the gap and obtain evidence before concluding", "Unresolved facts should not be silently treated as safe."), ("Assume the ranking has no effect", "That turns an unknown into an unsupported conclusion."), ("Declare the whole platform exempt", "Incomplete facts cannot justify a blanket exemption.")),
        ],
    },
}
