"""Article 5 biometrics and new synthetic-media provisions; non-graphic cases."""

from lesson_builder import assessment

LESSONS = {
    "B07": {
        "locator": "Article 5(1)(e)",
        "summary": "Identify untargeted scraping used to create or expand facial-recognition databases.",
        "screens": [
            ["**Untargeted scraping** in this point concerns collecting facial images from the internet or CCTV footage without a targeted selection as part of the stated database practice.", "Identify the source, selection and purpose. Data being publicly visible does not itself remove the prohibition; the point specifically names internet and CCTV sources."],
            ["The **facial-database ban** concerns AI systems creating or expanding facial-recognition databases through that untargeted scraping. Read creation/expansion, face images, source and untargeted collection together.", "The point specifies placing on the market, putting into service for this purpose, or use. Do not turn it into an unsupported statement that every photo database or every face-related function is identical."],
            ["Fictional Northbridge case: a supplier uses AI to gather facial images indiscriminately from internet pages to expand a recognition database. Those stipulated facts fit the conduct the point addresses.", "Changed case: a consented identity-enrolment process supplies specific records without such scraping. The facts of this point differ; other biometric, privacy and lawful-basis questions still need assessment."],
            ["Record collection sources, targeting, recognition-database role and regulated action. Do not accept 'public data' or a disclosure label as a universal exception.", "A result that the untargeted-scraping elements are not established does not establish lawful collection under every other law. The legal conclusion should remain tied to this point."],
        ],
        "questions": [
            assessment([0], [1], "A supplier collects facial images indiscriminately from the public internet. Does public visibility alone avoid this point?", "How should public availability be treated when the point names internet scraping?", ("It does not by itself remove the scraping test", "The point expressly addresses internet facial images."), ("It grants blanket permission to collect", "Public visibility is not a general exception."), ("It proves each person actively enrolled", "Visibility does not establish targeted active enrolment.")),
            assessment([1], [2, 3], "AI uses untargeted CCTV facial scraping to expand a recognition database. Which combined facts matter?", "What must be connected for the facial-database prohibition?", ("Untargeted named-source scraping and database creation/expansion", "The point ties those collection and purpose elements together."), ("Only owning a camera", "Camera ownership alone does not establish the conduct."), ("Only storing a single holiday photograph", "That does not establish the stated database practice.")),
            assessment([0, 1], [3, 4], "A targeted enrolment case does not establish untargeted scraping. What conclusion is appropriate?", "Does being outside this particular scraping test establish all biometric processing is lawful?", ("This test differs; other legal checks remain", "A point-specific conclusion is not blanket data-processing permission."), ("All privacy rules disappear", "Other law remains independently applicable."), ("Every face record must be this prohibited practice", "The point has specific collection and purpose elements.")),
        ],
    },
    "B08": {
        "locator": "Article 3(39), Article 5(1)(f), recital 18; Annex III 1(c)",
        "summary": "Check biometric emotion inference in workplace/education settings and the exact medical/safety boundary.",
        "screens": [
            ["The **emotion-setting ban** concerns AI used to infer a person's emotions in workplaces or education institutions, with a stated exception for systems intended for medical or safety reasons.", "First establish biometric emotion/intent inference under the definition, the setting and the regulated action. A sentiment questionnaire and facial emotion inference are not interchangeable just because both concern feelings."],
            ["The **medical/safety boundary** requires examining the actual intended use. Calling performance monitoring 'wellbeing' or 'safety' does not establish the exception.", "Fictional Northbridge employer infers emotions from facial signals to score motivation. A generic wellbeing claim is insufficient evidence of a medical or safety purpose. Assess precise facts rather than promises."],
            ["Recital 18 distinguishes physical states such as pain or fatigue from emotions or intentions. A driver-fatigue detector for accident prevention is not automatically emotion recognition.", "Do not reason that every bodily-state detector requires an emotion exception. Establish what the system infers. Other safety, product, personal-data or high-risk rules can remain relevant."],
            ["If a permitted medical/safety emotion use is established, that is a narrow prohibition result. Annex III emotion classification, transparency and other law still require checks.", "Record the inferred state, biometric basis, workplace/education context and purpose evidence. A consent form is not supplied here as a blanket cure for prohibited workplace inference."],
        ],
        "questions": [
            assessment([0], [1, 2], "An employer infers motivation from biometric facial signals. What facts need the Article 5(1)(f) check?", "Which combination is central to the workplace emotion rule?", ("Biometric emotion inference, workplace context and purpose", "The definition, setting and exception facts determine this test."), ("Only the wellbeing product name", "A label cannot establish a medical/safety boundary."), ("Only whether employees signed any form", "Consent is not a universal exception supplied by this point.")),
            assessment([1], [2, 4], "A vendor calls a motivation scorer 'safety AI' without supporting purpose evidence. What should be concluded?", "Does a safety label establish the medical/safety exception?", ("The exception remains unestablished pending evidence", "Actual intended medical/safety use needs examination."), ("The label automatically cures the prohibition", "Labels cannot substitute for the required facts."), ("Any workplace system is automatically medical", "The setting does not establish that purpose.")),
            assessment([0, 1], [3], "A tool detects physical driver fatigue to avoid accidents, without emotion inference. What should be distinguished?", "Does physical fatigue detection automatically constitute emotion recognition?", ("Physical-state detection differs from inferred emotion", "Recital 18 expressly distinguishes physical states such as fatigue."), ("All fatigue is legally an emotion", "That contradicts the recital's distinction."), ("No other rules can apply to fatigue detectors", "A definition result does not erase other legal duties.")),
        ],
    },
    "B09": {
        "locator": "Article 3(40); Article 5(1)(g); Annex III 1(b)",
        "summary": "Read the named sensitive-inference categories and the lawful-dataset/law-enforcement boundaries.",
        "screens": [
            ["The **sensitive-categorisation ban** concerns categorising individual people from biometric data to deduce/infer race, political opinions, trade-union membership, religious/philosophical beliefs, sex life or sexual orientation.", "Record the actual inferred category. The point's list is specific; do not silently substitute every imaginable attribute or ignore the biometric basis."],
            ["The point excludes specified labelling/filtering of lawfully acquired biometric datasets based on biometric data, and categorising biometric data in law enforcement. Read these stated boundaries without turning them into blanket permission.", "**Lawfully acquired** is a factual and legal condition. Public availability or an internal dataset label alone does not establish it. The precise processing purpose still matters."],
            ["Fictional Northbridge case: a workplace tool infers union membership from individual facial data. Those stipulated sensitive-inference facts raise the named prohibition.", "Changed case: an actual lawful-dataset filtering operation is established. Examine the boundary as written, then privacy and other rules. Do not use a dataset-management label to hide individual sensitive inference."],
            ["A function outside this particular ban can still be a listed sensitive/protected categorisation under Annex III. Conversely, high-risk classification cannot authorise the prohibited inference.", "The record should identify biometric data, individual categories, precise purpose, acquisition legality and regulated action. Keep each conclusion bounded to the actual processing."],
        ],
        "questions": [
            assessment([0], [1, 3], "A tool infers individual trade-union membership from biometric data. Which listed category matters?", "Which sensitive inference is expressly named in Article 5(1)(g)?", ("Trade-union membership", "That is one of the point's named sensitive categories."), ("Only a device's battery level", "That is not an individual sensitive biometric category."), ("Only an image's file extension", "That is not the stated personal inference.")),
            assessment([1], [2], "A vendor claims a lawful-dataset boundary because images were visible online. What fact remains to be checked?", "Does public visibility automatically establish a lawfully acquired biometric dataset?", ("The lawful acquisition and actual processing purpose", "The boundary cannot be established from visibility alone."), ("Nothing; all visible images are unrestricted", "Public availability is not blanket legal permission."), ("Only whether the folder is labelled lawful", "A label does not establish acquisition legality.")),
            assessment([0, 1], [3, 4], "A categorisation function is outside this exact prohibition. Can the assessor skip Annex III and privacy law?", "What follows from a point-specific sensitive-categorisation boundary result?", ("Other classification and legal checks still remain", "The boundary is not a complete compliance conclusion."), ("All sensitive inference is automatically authorised", "The conclusion must stay limited to the established facts."), ("The entire Act has no more relevant rules", "Other purposes and duties can apply.")),
        ],
    },
    "B10": {
        "locator": "Article 5(1)(ba), 5(1b), 5(1a); Article 113(a)",
        "summary": "Assess identifiable intimate synthetic material, exact consent and the limited manipulation boundary without graphic examples.",
        "screens": [
            ["The new **intimate-media provision** concerns AI generating/manipulating realistic intimate or sexually explicit material of an identifiable natural person without that person's freely given, specific, informed, unambiguous and explicit consent for that generation/manipulation.", "This lesson uses legal descriptions only. It needs no real material, demonstrations or identifiable person's images. Each stated subject, realism, identification and consent element must be checked."],
            ["An **intimate-media consent test** concerns consent for the particular generation or manipulation, not merely a prior agreement to take an ordinary photograph. Silence, an unrelated form or public availability does not establish the specified consent.", "Fictional Northbridge safeguarding case: ordinary-image permission exists but no consent for intimate synthesis. The prior permission does not by itself establish the new provision's consent element."],
            ["Article 5(1b) gives a limited **manipulation boundary**: altering material without increasing exposure of depicted intimate parts or changing the nature of depicted sexually explicit activities does not constitute manipulation for point (ba).", "Do not turn this exact boundary into a general exemption for all editing. Record what actually changes. The separate generation branch and other legal rules still need examination."],
            ["These new provisions apply from **2 December 2026** in the working baseline. Paragraph 1a further distinguishes supply and use, taught next in B12. The present lesson establishes content/consent and manipulation elements.", "A full conclusion must apply that actor-specific qualification and date. Other laws may already forbid conduct; this future application date is not permission to exploit people before it."],
        ],
        "questions": [
            assessment([0], [1, 2], "A person permitted an ordinary photograph, but did not consent to intimate synthetic generation. What follows for this element?", "Does ordinary image permission itself establish explicit consent to intimate generation?", ("The specified generation consent is not established", "Consent must concern the particular generation/manipulation with the stated qualities."), ("All later synthetic uses are automatically permitted", "Unrelated prior permission is not the specified consent."), ("Public availability supplies every consent quality", "Availability does not establish freely given specific explicit consent.")),
            assessment([1], [3], "An edit neither increases intimate exposure nor alters the depicted activity's nature. What does paragraph 1b say about this manipulation branch?", "How should the limited Article 5(1b) editing boundary be applied?", ("That edit is outside manipulation for point (ba)", "The stated boundary is specific to manipulation under that point."), ("Every form of editing is now exempt", "The boundary has exact effects-based conditions."), ("Every new generation is automatically exempt too", "Generation is a separate branch.")),
            assessment([0, 1], [4], "Which application date must be retained for the new point (ba) in this baseline?", "Does point (ba) use the original Chapter II date without exception?", ("2 December 2026, with other law checked separately", "Article 113 specifically dates the new provisions; other law is not waived."), ("2 February 2025 for this new point", "The new point has a stated exception to that chapter date."), ("Any date the vendor chooses", "Vendor preference cannot set statutory application.")),
        ],
    },
    "B11": {
        "locator": "Article 5(1)(bb), 5(1a); Article 113(a)",
        "summary": "Use the incorporated child-abuse material/performance definitions and check national-law qualifications without graphic content.",
        "additional_sources": [{"title": "Directive 2011/93/EU, Article 2(a), 2(c), 2(e): incorporated definitions", "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1447190728317&uri=CELEX:32011L0093"}],
        "screens": [
            ["The new point (bb) addresses AI generating or manipulating material or performance within Directive 2011/93/EU Article 2(c) and (e). The **incorporated-definition lookup** is essential: a cross-reference supplies part of the legal test.", "The Directive defines a child as under 18. Its material definitions include specified real/simulated depictions, persons appearing to be children, and realistic synthetic depictions. We teach the lookup without images or graphic examples."],
            ["Article 2(e) concerns a live exhibition aimed at an audience, including via communication technology, with specified child sexual-abuse content. A file and a live performance need comparison with the appropriate incorporated definitions.", "A synthetic origin does not by itself exclude the realistic-material category. Do not invent a blanket 'no real child means lawful' rule."],
            ["The **generation/manipulation ban** includes an exception where a 'without right' defence applies under national law. This requires the actual national provision and facts; it is not a self-declared exemption.", "Our fictional safeguarding case leaves jurisdiction unspecified. The correct outcome is to identify the national-law question, not assume a defence or give a jurisdiction-specific permission without a source."],
            ["Point (bb) and paragraph 1a apply from **2 December 2026** in the working baseline. The next lesson separates supplier and deployer tests. Other criminal and safeguarding law remains independently relevant.", "An assessment needs the incorporated content category, actor/action, date and any verified national-law qualification. No creation, demonstration or storage of abusive material is needed to learn this legal method."],
        ],
        "questions": [
            assessment([0], [1, 2], "A claim says realistic synthetic material is excluded because no real child was photographed. What should the legal lookup check?", "Does synthetic origin alone remove the incorporated realistic-material category?", ("Article 2(c)'s actual incorporated categories", "The definition includes a realistic synthetic-material category."), ("Only whether a camera was used", "Camera use alone does not decide those definitions."), ("Only whether the supplier calls it fictional", "A fiction label cannot replace the statutory lookup.")),
            assessment([1], [3], "The jurisdiction is unknown and a supplier asserts a 'without right' defence. What is the sound conclusion?", "How should a national-law defence claim be handled without the governing national source?", ("The defence remains unverified; obtain the law and facts", "The qualification depends on actual national law."), ("Any supplier assertion establishes the defence", "A claim is not the applicable legal provision."), ("The course should invent a national exception", "Inventing a defence would be unsupported.")),
            assessment([0, 1], [2, 4], "What is needed for this lesson's legal assessment exercise?", "Can the incorporated-definition and actor tests be learned without abusive material demonstrations?", ("Non-graphic legal categories and case facts", "The legal reasoning needs definitions and facts, not harmful demonstrations."), ("Real images must be generated to understand the rule", "No such generation is required for the legal lookup."), ("All other law can be ignored until December", "The AI Act date does not postpone independent law.")),
        ],
    },
    "B12": {
        "locator": "Article 5(1a)(a), 5(1a)(b), 5(1b); Article 3(13); Article 113(a)",
        "summary": "Apply the distinct supply and use qualifications for the new synthetic-media prohibitions.",
        "screens": [
            ["For new points (ba)/(bb), paragraph 1a qualifies the supply side. Placement or service is prohibited where generating/manipulating the specified material is the system's intended purpose, or under the alternative foreseeable/reproducible-outcome test.", "An imagined theoretical possibility alone is not the same as that second branch. Keep the material category, actor and regulated action in the record."],
            ["The alternative supply branch examines design, training, architecture, capabilities or user-facing features: the generation must be reasonably foreseeable and reproducible without significant technical modification, and reasonable/adequate safeguards to reliably prevent and correct observed/reported misuse must be absent.", "The **supplier-safeguards test** is substantive. A policy statement alone does not establish technical protection; equally, do not assume any conceivable misuse proves the entire branch."],
            ["On the use side, paragraph 1a(b) prohibits the specified generation/manipulation only where the **deployer uses the system for that purpose**. The supply and use tests are different.", "Fictional Northbridge case: a general tool's supplier has adequate safeguards, but a deployer intentionally uses it for the specified prohibited material. A favourable supply-side finding cannot automatically cure the separate use-side purpose."],
            ["Record intended purpose; foreseeable, reproducible output; technical modification needed; safeguard adequacy; and deployer purpose separately. Keep point (ba)'s manipulation boundary and the 2 December 2026 date in the full test.", "These statutory qualifications concern the new points, not a universal rewriting of every Article 5 prohibition. The case uses non-graphic descriptions and does not demonstrate harmful generation."],
        ],
        "questions": [
            assessment([0], [1, 2], "A supplier case shows only a theoretical misuse requiring significant technical modification. What is missing from the alternative branch?", "Does any imagined possibility establish the foreseeable/reproducible supply-side test?", ("Its full foreseeable, reproducible and modification facts", "The branch has specific conditions rather than mere possibility."), ("Nothing; theoretical possibility always suffices", "That ignores reproducibility and significant-modification qualifications."), ("Only whether the vendor dislikes the misuse", "Attitude does not establish the branch's technical facts.")),
            assessment([1], [2], "A supplier presents a policy but no evidence of prevention or correction safeguards. What should the assessor examine?", "What makes the new supplier safeguards claim substantively assessable?", ("Reasonable/adequate prevention and misuse correction measures", "The statute requires safeguards with the stated preventive/corrective function."), ("Only the policy's attractive formatting", "Formatting does not establish reliable safeguards."), ("Only a general claim that misuse is forbidden", "A rule alone does not prove the specified technical safeguards.")),
            assessment([2], [3, 4], "A deployer intentionally generates the specified prohibited material, despite favourable supplier-safeguard facts. Which test matters for its use?", "Can an adequate supplier-side safeguard finding automatically decide a deployer's intentional use purpose?", ("The separate deployer-purpose test", "Paragraph 1a(b) examines what the deployer uses the system to do."), ("Only the supplier result, ignoring the use", "Supply and use qualifications are distinct."), ("Every other prohibition is now replaced by this test", "Paragraph 1a's qualifications concern the specified new points.")),
        ],
    },
}
