"""System boundary, actors, classification and lifecycle: English teaching draft."""
from high_risk_content import lesson, question as q

LESSONS = {
'H01': lesson('Articles 2(1), 2(10), 2(12), 3(1), 3(12); recital 12', 'Identify the assessed system and its intended use before assigning duties.', [
['This course follows **Northbridge Hiring**, a fictional supplier of candidate-ranking AI used by employers. The case facts are stipulated teaching facts. You will build a decision dossier: the evidence and reasons supporting a decision, with unresolved facts kept visible.', 'An **AI system** is machine-based, operates with some autonomy and infers from inputs how to produce predictions, content, recommendations or decisions for explicit or implicit objectives. Its outputs can influence physical or digital environments. It may adapt after deployment; adaptation is not compulsory.'],
['**System boundary** means the functionality being assessed. A learned ranking service infers recommendations. A fixed rule that sorts dates, or a page displaying a stored article, does not establish AI status by itself.', 'Assess separate components and their combined operation. A conventional quiz displaying previously AI-written material is not automatically the same system as the AI authoring service. Human review does not remove the inference of that service.'],
['**Intended purpose** is the use intended by the provider, including context and conditions, as specified in instructions, promotional or sales material, statements and technical documentation. A label such as “assistant” does not substitute for that evidence.', 'Northbridge advertises ranking job applicants to support shortlisting. Record the actual functions, users, inputs, outputs and decisions supported. Later changes to that purpose can change the applicable rules.'],
['The **EU connection** can arise from placing a system on the Union market, EU-based deployment, or certain third-country activities where outputs are used in the Union. Record the actor and exact Article 2 connection; foreign hosting alone is not an exclusion.', 'Check exclusions on their terms. Purely personal non-professional use excludes deployer obligations, not every supplier duty. The free/open-source exclusion does not remove high-risk, Article 5 or Article 50 cases.'],
['First dossier entry: “Northbridge ranking service; intended to assist recruitment shortlisting; supplied to EU employers.” Keep the conventional document viewer separate.', 'For a real commercial product, unknown functionality or an unconfirmed EU connection remains a question to investigate. A confident product label is weaker evidence than the actual documented operation.']], [
q([0],[1,2], 'A page displays a fixed article previously written with AI. Does that fact alone make the page an AI inference system?', 'Does displaying stored AI-written text, without further inference, establish AI-system status?', ('No; inspect the actual functionality','Stored output does not itself establish inference.'),('Yes; every display of AI content is AI','The assessment concerns the operating system.'),('No AI authoring service needs assessment','The upstream inference service is a separate object.')),
q([1],[3], 'Northbridge calls its applicant-ranking tool a general assistant but advertises shortlisting. What establishes purpose?', 'What evidence matters when branding and the advertised recruitment use differ?', ('Its specified use, context and supplied information','Purpose includes instructions, promotion and technical material.'),('Only its broad assistant label','A label does not replace specified use.'),('Only the model supplier’s unrelated examples','Assess this supplied system and intended use.')),
q([2],[4], 'Northbridge hosts abroad and supplies EU employers. What is the next scope step?', 'Does overseas hosting alone exclude an EU-facing ranking service?', ('Record the relevant Union supply or use connection','Article 2 reaches specified connections beyond hosting.'),('Exclude it because its server is abroad','Server location alone does not settle scope.'),('Exclude it if any component is open source','The source exclusion has important conditions.'))]),
'H02': lesson('Articles 3(3)–(8)', 'Allocate roles from conduct rather than contractual labels.', [
['A **provider** develops an AI system, or has it developed, and places it on the market or puts it into service under its own name or trademark. Supply can be paid or free.', 'Northbridge commissions development and supplies its branded ranking service. It is a system provider even though a contractor wrote the software. An upstream model supplier needs its own role analysis.'],
['A **deployer** uses an AI system under its authority, except for purely personal non-professional activity. The employer operating Northbridge in recruitment is a deployer.', 'One organisation can have both roles when it builds and professionally uses its own system. Buying a complete vendor system normally indicates use, but examine any subsequent changes before assuming the role stays unchanged.'],
['An **authorised representative** is established in the Union and accepts a written mandate to carry out specified obligations on a provider’s behalf. An **importer** is an EU-established person placing on the market a system bearing a third-country person’s name or trademark.', 'A **distributor** is another person in the supply chain making the system available on the Union market. A customer merely using the service is not a distributor because it has a supplier relationship.'],
['Build an actor table with legal entity, establishment, supplied system, name on it, and actual conduct. Contracts help evidence the facts, but “partner” or “reseller” does not decide the statutory role.', 'Northbridge is provider; its employer customer is deployer. A stipulated EU importer introducing a third-country branded product occupies an additional role. Do not merge all actors into “the AI company”.']], [
q([0],[1], 'A contractor develops Northbridge’s branded system. Who is indicated as system provider?', 'Who has the provider role when Northbridge commissions and supplies its own branded ranking system?', ('Northbridge','Having it developed and supplying under its name is covered.'),('Only the coding contractor','Commissioning can establish provider status.'),('Only the customer employer','Professional use alone describes a deployer.')),
q([1],[2], 'An employer uses the complete purchased ranking service under its authority. Which role is directly indicated?', 'Which role describes professional operation of Northbridge by an employer?', ('Deployer','It professionally uses the system under its authority.'),('Authorised representative','Use does not establish a written representative mandate.'),('Distributor merely because it is a customer','A supply-chain making-available role needs its own facts.')),
q([2],[3,4], 'An EU company places a third-country branded AI system on the Union market. Which additional role fits?', 'What role fits an EU actor introducing a system bearing a third-country supplier’s trademark?', ('Importer','The establishment and placing-on-market facts match.'),('Private user','This is commercial supply conduct.'),('Representative without a mandate','A representative requires the written mandate.'))]),
'H03': lesson('Articles 2(2), 6(1)–(4), 8(2); Annexes I and III', 'Confirm the exact high-risk route, exceptions and applicable regime.', [
['**High-risk classification** has two routes. Article 6(1) requires both an Annex I covered product or safety component and mandatory third-party product conformity assessment. This is an assessment by a legally required independent body, not any voluntarily purchased audit.', 'Solely non-safety assistance, optimisation or quality control does not qualify as a safety component under 6(1a). Failure endangering health and safety overrides that under 6(1b). Assessment solely for non-health/safety risks does not meet 6(1)(b), under 6(1c).'],
['Article 6(2) covers the specific uses in **Annex III**. Read the point, not only a sector heading. Our case stipulates candidate ranking under point 4(a), materially influencing shortlisting, with no established exception.', 'Article 6(3) requires no significant risk of harm and a qualifying narrow procedural, improvement of completed human work, pattern-review, or preparatory task. The pattern condition preserves proper human review. Annex III profiling of people is always high-risk despite that exception. Profiling means automated personal-data processing evaluating personal aspects.'],
['**Limited sector applicability** is a distinct boundary. Article 2(2) limits the Act’s application to Annex I Section B systems to the specified provisions: 6(1), 60a and 102–112; Articles 57–59 apply only as integrated into sector law.', 'Do not automatically copy all Articles 8–27 to Section B. Section A systems instead retain applicable requirements: permitted integration of testing and documentation avoids duplication without waiving duties. Identify the exact Annex entry first.'],
['A **classification record** links functions and intended purpose to the exact route and evidence. Unknown exception facts do not establish an exemption.', 'A provider relying on 6(3) documents its assessment before market placement/service, registers under 49(2), and supplies it to authorities on request. Human review alone is not the complete exception test. Record route, Annex point, exception/profiling analysis, sources and owner.']], [
q([0],[1,2], 'Northbridge materially influences shortlisting under the stipulated Annex III 4(a) use. Does a human final decision alone establish exemption?', 'Does a recruiter approving the final shortlist by itself remove the supplied high-risk classification?', ('No; the complete exception conditions matter','Human involvement alone does not satisfy 6(3).'),('Yes; human approval always removes high risk','Material influence and the statutory tests remain relevant.'),('Yes; recruitment is absent from Annex III','The supplied point is a listed recruitment use.')),
q([1],[3], 'A supplied product is in Annex I Section B. May an assessor automatically require every Article 8–27 duty under this Act?', 'How should the assessor handle the stated Section B route?', ('Check Article 2(2)’s limited application','The specified provisions and sector integration govern.'),('Apply every high-risk provision without checking','That ignores the express applicability boundary.'),('Treat all Section A products as exempt too','Section A integration is not a general waiver.')),
q([2],[4], 'A provider substantiates Article 6(3). What remains before supplying the system?', 'Does a justified Annex III exception remove the assessment record and registration duties?', ('Document the assessment and register under 49(2)','Article 6(4) preserves these steps.'),('Discard the assessment because it is exempt','The provider must retain the documented justification.'),('Replace the assessment with a sales statement','A claim does not establish the tests.'))]),
'H04': lesson('Articles 4, 5, 50, 111(2), 113; amended 2026/1744 baseline', 'Separate classification, application dates, transition and parallel law.', [
['A **duty application date** tells you when a particular provision becomes applicable. Classification and date are separate findings. In the 27 July 2026 amended baseline, Chapter III Sections 1–3 apply to Annex III systems from **2 December 2027**, and Annex I systems from **2 August 2028**, subject to the stated exceptions.', 'Use the current Article 113 and actual route. Do not use the original 2026/2027 high-risk timetable from an older slide. The Article 6(5) guidance duty has a separate exception.'],
['A **legacy transition** can affect high-risk systems placed on the market or put into service before the relevant date. Article 111(2) ties application to significant changes in design from that date; public-authority intended use has the specified 2030 compliance endpoint.', 'This is not unlimited permission for any old product. Record initial supply/service date, route, design changes and public-authority use; check the exact transition. A marketing claim of “existing system” does not establish these facts.'],
['**Parallel obligations** use their own triggers. Most Article 5 prohibitions applied from 2 February 2025; inserted 5(1)(ba)/(bb) and 5(1a)/(1b) have the 2 December 2026 date. Article 50 generally applies from 2 August 2026, with a targeted 50(2) transition for systems placed on the market before that date until 2 December 2026.', 'Article 50 concerns interaction and specified synthetic content; a notice does not legalise an Article 5 forbidden practice. Data protection and sector or national rules also remain separate checks.'],
['The amended Article 4 requires providers and deployers to support development of AI literacy among staff and others operating systems on their behalf. Literacy concerns knowledge for informed use; the Act does not create a universal training certificate.', 'Dossier method: keep one row per actor and duty, with trigger, date, transition evidence and current action. A future high-risk date is not a conclusion that no present obligations exist. All dates in exercises use the stated baseline.']], [
q([0],[1], 'Under this baseline, when do Chapter III Sections 1–3 apply to Northbridge’s Annex III route, subject to exceptions?', 'Which amended high-risk date belongs to the stipulated Annex III route?', ('2 December 2027','Article 113 assigns this route’s date.'),('2 August 2028','That date belongs to the Annex I route.'),('2 August 2026 for every high-risk route','That ignores the amended differentiated timetable.')),
q([1],[2], 'A supplier says its old system is exempt forever. What evidence is needed?', 'Can initial pre-deadline supply alone establish unlimited grandfathering?', ('Dates, relevant design changes and public-use facts','Article 111(2) has conditions and a public-use endpoint.'),('Only the word legacy in a brochure','A label proves no transition facts.'),('No further check once an old invoice exists','Later changes and the relevant conditions still matter.')),
q([2],[3,4], 'A product is not high-risk or has a later high-risk duty date. What follows?', 'Does a later Chapter III date close the assessor’s other-law review?', ('Check separately triggered prohibitions, transparency and other law','Those duties are not erased by classification or its date.'),('All AI Act duties disappear','Other provisions have independent triggers.'),('Adding an AI label makes every use lawful','Disclosure does not cure a prohibition.'))]),
'H05': lesson('Articles 8(1), 9(1)–(5), 9(10)', 'Treat risk management as a continuing, purpose-specific cycle.', [
['**Lifecycle risk management** is an established, implemented, documented and maintained process, planned across the system’s whole lifecycle. It repeatedly identifies, evaluates, controls and reviews known and reasonably foreseeable health, safety and fundamental-rights risks.', 'Northbridge’s risk record is not closed by its first launch review. New evidence from use can require revised controls. Fundamental rights include protected interests such as non-discrimination; the actual legal issues need the relevant law.'],
['**Reasonably foreseeable misuse** differs from intended use but is reasonably predictable. An employer applying a shortlisting score as an automatic rejection might be foreseeable even if the instructions prohibit it.', 'Evaluate intended use and such misuse. Article 9 concerns risks reasonably mitigated or eliminated through design/development or adequate technical information. It does not promise to eliminate every imaginable societal risk.'],
['**Residual risk** is what remains after measures. Judge the residual risk for each hazard and for the system overall to be acceptable. “A warning exists” is not the same as that judgment.', 'Consider interactions between requirements and controls: a change reducing one risk may increase another. Record reasons, evidence and limits. Acceptance is purpose-specific; no invented score is a universal statutory pass threshold.'],
['The cycle includes risks emerging from post-market monitoring: evidence gathered after supply and use. Where Union law already requires internal risk-management procedures, Article 9 aspects may be part of or combined with them.', 'Case: recruiters systematically skip manual checks. Treat this as evidence for the misuse analysis and review the measures. A signed launch record does not justify ignoring the observed pattern.']], [
q([0],[1,4], 'Northbridge learns after launch that reviewers skip checks. Should its risk process stop at the signed launch record?', 'What does new evidence of routine reviewer behaviour require?', ('Review and update the lifecycle risk process','The process is continuous and uses monitoring evidence.'),('Ignore it after the initial sign-off','Launch does not end lifecycle duties.'),('Wait until the entire product is replaced','Regular review is not limited to replacement.')),
q([1],[2], 'Recruiters predictably use an advisory score for automatic rejection contrary to instructions. What should the risk analysis consider?', 'Is a foreseeable departure from instructed ranking use irrelevant because it is prohibited in the manual?', ('Reasonably foreseeable misuse','The evaluation covers reasonably foreseeable misuse.'),('Only the exact instructed use','That omits an explicit part of Article 9.'),('Every imaginable use equally','Foreseeability and mitigability constrain the analysis.')),
q([2],[3], 'A warning reduces a hazard but harm remains possible. What must Northbridge evaluate?', 'What judgment remains after a mitigation measure is added?', ('Each hazard’s and overall residual-risk acceptability','A control does not automatically establish acceptable remaining risk.'),('Only whether the warning was published','Presence of a warning is not the required judgment.'),('Only whether one risk decreased','Other hazards and combined effects still matter.'))]),
'H06': lesson('Articles 2, 3, 6, 111, 113; Annex III 4(a)', 'Produce a conditional scope record rather than a broad compliance claim.', [
['Case file: Northbridge supplies an inference-based candidate-ranking service to EU employers under its own name. Its specified purpose materially influences recruitment shortlisting. These are stipulated facts, not conclusions about a real supplier.', 'The employer operates it under its authority. Record Northbridge as provider and employer as deployer; distinguish upstream components and any additional supply-chain actors.'],
['The supplied purpose matches Annex III 4(a). No Article 6(3) exception is established. Do not substitute “a human decides” for the complete exception analysis.', 'Write the exact purpose, point, factual basis and unresolved evidence. If the facts change, reopen classification rather than copying the previous conclusion.'],
['The case uses the amended Annex III Chapter III Sections 1–3 date: 2 December 2027, subject to relevant exceptions and Article 111 evidence. First-supply dates and later design changes are not supplied in this case.', 'Keep transition status unresolved. Do not fabricate an invoice date or claim the legacy provision definitely applies.'],
['Suggested dossier entry: “High-risk Annex III recruitment purpose on stated facts; Northbridge provider; employer deployer; Chapter III date identified; legacy facts unresolved.”', 'Keep Article 5, Article 50, data-law and sector/national questions open for their own tests. This scope record starts the compliance work; it does not establish that every release gate has been met.']], [
q([0],[1,2], 'Northbridge commissions and supplies ranking; its employer customer operates it. Which scope entry fits?', 'Which actor allocation belongs in the supplied recruitment case record?', ('Northbridge provider; employer deployer','The conduct establishes separate roles.'),('Employer is always the sole provider','Use does not erase Northbridge’s branded supply.'),('No role until an incident occurs','Roles arise from the specified conduct.')),
q([0],[2,3], 'The legacy first-supply date is absent. Which conclusion is supported?', 'How should the record handle an unproved Article 111 transition?', ('Keep transition status unresolved with evidence requested','Unknown facts do not establish eligibility.'),('Assume exemption because development began earlier','Development start does not prove the relevant supply/service facts.'),('Use the original timetable despite the amendment','The exercise uses the amended baseline.')),
q([0],[4], 'What does the completed scope record authorise the assessor to conclude?', 'Does identifying the recruitment route certify readiness to launch?', ('The stated classification and remaining review gates','Classification identifies duties; it does not discharge them.'),('Full compliance with every applicable law','The evidence does not cover all gates.'),('No need for further factual evidence','Unresolved facts remain material.'))]),
}
