"""Standards, limited presumptions and evidence gaps."""

from high_risk_content import lesson, question
from conformity_sources import add_registered_sources

LESSONS = {
    "F07": lesson("Article 40", "Check the legal citation and the requirements it actually covers.", [
        ["A **harmonised standard** is a technical standard developed through the Union standardisation framework. Standards are generally voluntary. Article 40 gives a presumption of conformity where the relevant reference is published in the **Official Journal**, the Union's official publication, and the system conforms to the standard or applicable parts."],
        ["A **limited presumption** concerns only requirements covered by that standard or part. A standard's title, publication by a standards body, or development work does not establish the necessary Official Journal reference. Check the exact identifier, edition, citation, restrictions and coverage before relying on the presumption."],
        ["Keep a citation record and a requirement-by-requirement coverage map. The Commission's standardisation request must address coherence, sector frameworks and relevant technical requirements. Article 40(3) concerns participation in standards development; it does not turn every international standard into a harmonised AI Act standard."],
        ["Fictional **Standard S** has a stipulated Official Journal citation covering one logging requirement, with a stated restriction. This is an exercise, not a real cited standard. Its coverage does not establish conformity of Northbridge's oversight or data practices. For an actual release, look up the current citation rather than assuming this toy standard exists."],
    ], [
        question([0], [1, 2], "A standards body publishes an edition, but no Official Journal reference has been verified. What can you claim?", "Is a standards-body publication alone enough for the Article 40 presumption?", ("The legal citation still needs verification.", "The presumption requires the specified Official Journal reference."), ("The whole system is presumed compliant.", "Publication and coverage conditions remain unverified."), ("The technical standard must be unlawful.", "Lacking this presumption does not itself prohibit technical use.")),
        question([1], [2, 4], "Standard S covers logging only. What follows for oversight?", "Does a logging presumption automatically cover human oversight?", ("Oversight still needs its own supporting evidence.", "The presumption is limited to covered requirements."), ("Oversight is presumed compliant by association.", "A different requirement is outside the stated coverage."), ("Oversight no longer applies to this system.", "A narrow standard does not remove other applicable requirements.")),
        question([0, 1], [2, 3], "Which record best supports a standards claim?", "What should a reviewer retain before using a presumption?", ("Exact edition, citation, restrictions and requirement coverage.", "Those facts define the legal and technical boundary."), ("Only the supplier's standards logo.", "The logo does not establish edition, citation or coverage."), ("Only a count of standards purchased.", "Buying documents does not demonstrate conformity or coverage.")),
    ]),
    "F08": lesson("Article 40(1); Annex IV(7)", "Use standards where supported and explain other compliance solutions.", [
        ["A **standard coverage matrix** compares each applicable requirement with the parts of a cited standard used and the evidence of actual conformity. Mark uncovered requirements explicitly. A citation alone does not show that your implementation conforms to the cited standard."],
        ["**Alternative conformity evidence** can demonstrate an applicable requirement outside a standards presumption. Annex IV(7) asks for applied standards and, where they are not applied, detailed descriptions of the solutions adopted, including other relevant technical specifications. Avoid claiming that voluntary standards are the only possible evidence."],
        ["Northbridge uses Standard S for logging but has no cited coverage for oversight. Its alternative record should explain the oversight mechanism, the responsible people, how intervention works, relevant tests and results. This is a practical example of evidence, not an exhaustive statutory test protocol."],
        ["Evidence adequacy and assessment-route choice are separate checks. Another procedure may impose standards-dependent route conditions. A documented alternative solution does not automatically preserve an internal-control option for a biometric system or product-law route; check that specific procedure."],
    ], [
        question([0], [1], "A matrix says 'standard bought', with no implementation evidence. What is unresolved?", "Does purchasing the cited standard demonstrate conformity to it?", ("Actual application and covered-requirement evidence.", "Ownership of a document does not demonstrate implementation."), ("Only the purchase invoice's visual format.", "Invoice design cannot establish the technical result."), ("Nothing once the citation is known.", "Citation and actual conformity are distinct conditions.")),
        question([1], [2, 3], "No cited standard covers Northbridge's oversight requirement. What should it provide?", "How can a requirement outside a presumption be supported?", ("A detailed solution and evidence demonstrating the requirement.", "Annex IV allows explanations of other compliance solutions."), ("A claim that the requirement therefore disappears.", "The absence of a presumption does not remove the requirement."), ("A promise to buy any standard with 'AI' in its title.", "A title does not establish scope or conformity.")),
        question([0, 1], [4], "A biometric provider has alternative evidence but no applied qualifying standards. What still needs checking?", "Does an alternative solution by itself preserve every procedure choice?", ("The specific assessment procedure's route conditions.", "Evidence and eligibility for a procedure are separate questions."), ("Nothing; alternatives always permit internal control.", "Biometric route conditions can require a notified-body procedure."), ("Only whether the supplier calls it certified.", "A label does not resolve the statutory route conditions.")),
    ]),
    "F09": lesson("Article 41(1)–(6)", "Recognise an adopted common specification and justify equivalent solutions.", [
        ["A **common specification** under Article 41 is established by a Commission implementing act. The trigger combines a standardisation request problem—refusal, delay, insufficient fundamental-rights treatment or non-compliance with the request—with the stated absence of a citation expected within a reasonable period. A provider cannot create such an act by renaming its checklist."],
        ["The Commission informs the relevant standardisation committee before preparing the draft, consults the advisory forum and follows the examination procedure. These are adoption safeguards, not additional steps for each provider to perform. Compliance gives a presumption only for requirements covered by the specification or its parts."],
        ["An **equivalent technical solution** is not a waiver. Providers not complying with an applicable common specification must duly justify that their solution meets the applicable requirements to at least an equivalent level. Record the comparison, technical evidence and remaining uncertainties."],
        ["When an overlapping harmonised-standard reference is published, Article 41(4) provides for repeal of the corresponding implementing act or parts. A Member State can raise a supported inadequacy concern, which the Commission assesses and may address by amendment. Keep the legal version current."],
    ], [
        question([0], [1, 2], "A vendor calls its unpublished checklist an 'EU common specification'. What should you verify?", "What establishes a common specification's Article 41 authority?", ("The adopted Commission implementing act and its scope.", "The legal instrument establishes its authority and coverage."), ("The vendor's chosen name alone.", "Renaming a checklist does not create an implementing act."), ("Only how many suppliers signed the checklist.", "Industry support does not establish Article 41 adoption.")),
        question([1], [3], "Northbridge departs from an applicable common specification. What is required?", "What supports using a different technical solution under Article 41(5)?", ("A justified solution achieving at least equivalent compliance.", "The departure needs a supported equivalence explanation."), ("A statement that specifications are irrelevant.", "The paragraph requires justification, not dismissal."), ("A lower protection target chosen by the provider.", "At least equivalent compliance is required.")),
        question([0, 1], [4], "An overlapping standard is newly cited. What should the reviewer check?", "Why can an old common-specification reference need refreshing?", ("Repeal or amendment and the remaining applicable coverage.", "Article 41 provides a mechanism for replacing overlapping specifications."), ("Whether the old PDF still opens.", "Availability of a file does not establish continuing legal effect."), ("Whether every requirement has become optional.", "Changing the evidence instrument does not erase requirements.")),
    ]),
    "F10": lesson("Article 42(1)–(3); CRA Articles 2 and 12", "Limit data and cybersecurity claims to their conditions and scope.", [
        ["Article 42(1)'s **contextual data presumption** concerns relevant Article 10(4) requirements for systems trained and tested on data reflecting the intended geographical, behavioural, contextual or functional setting. It does not presume every data-governance or system requirement satisfied. Data from another setting needs an evidence-based relevance check."],
        ["Article 42(2)'s **cybersecurity presumption** requires a certificate or statement under a Regulation 2019/881 cybersecurity scheme whose references are published in the Official Journal. It extends only as far as that evidence covers Article 15 cybersecurity requirements. It is not a presumption about accuracy, robustness or every other requirement."],
        ["Article 42(3) points to the **Cyber Resilience Act**, or CRA. Its scope and Article 12(1) conditions must be met: product cybersecurity requirements, relevant manufacturer vulnerability-handling processes and declaration evidence. That bridge deems the AI Act cybersecurity requirement satisfied; it is not full AI Act conformity."],
        ["CRA Article 12(2)–(3) preserves particular assessment interactions and important/critical-product procedure rules. Read those conditions before choosing a route. The specified medical-device products are excluded by CRA Article 2(2), so Harbour's medical case does not automatically receive this CRA bridge. Current version and CRA application dates require a real-release lookup."],
    ], [
        question([0], [1], "Northbridge tests data reflecting its intended setting. What is the stated presumption's boundary?", "Does context-matched training and testing establish all data and system duties?", ("Relevant Article 10(4) requirements only.", "Article 42(1) gives this particular limited presumption."), ("Every AI Act obligation automatically.", "The provision does not extend to every obligation."), ("Only the provider's marketing obligations.", "The stated presumption concerns the relevant data requirements.")),
        question([1], [2], "A qualifying cybersecurity certificate covers only part of Article 15 cybersecurity. What remains?", "What should you do with requirements outside the certificate's coverage?", ("Obtain evidence for the uncovered requirements.", "The presumption is limited to what the certificate or statement covers."), ("Declare all accuracy and robustness requirements satisfied.", "Those claims exceed this cybersecurity presumption."), ("Ignore coverage because the certificate is independent.", "Independence does not expand the scope of the certificate.")),
        question([2], [3, 4], "Harbour claims CRA compliance proves complete medical AI conformity. What is the right response?", "Can the medical case automatically rely on the CRA bridge for its whole dossier?", ("Check CRA exclusions and the limited bridge conditions.", "The specified medical products are excluded; the bridge is limited even when applicable."), ("Accept the claim for every medical AI product.", "Scope and exclusions must be checked first."), ("Treat CRA evidence as proof of every AI requirement.", "The bridge concerns cybersecurity and has specified conditions.")),
    ]),
    "F11": lesson("Articles 40–41; Commission standardisation FAQ", "Refresh legal references and limit certificate claims.", [
        ["A **standards update watch** is a practical record of exact versions, citation changes, restrictions, replacement instruments and new applicable procedure rules. It supports a fresh review when relevant evidence or law changes. A standard being developed is not a current cited presumption."],
        ["Under Article 41(4), citation of an overlapping harmonised standard triggers repeal of corresponding common-specification provisions. Recheck both instruments' scope and timing; do not simply replace the name in the dossier and assume the technical coverage is identical."],
        ["An **international management-system certificate** can be useful evidence but is not automatically an AI Act assessment certificate. The Commission FAQ distinguishes ISO/IEC 42001 from the AI Act quality-management requirements. Check the claimed standard, system boundary and requirement coverage; a supplier assertion is not a completed system assessment."],
        ["Northbridge receives an ISO certificate about its supplier's organisation. It should record what that evidence supports and still check its own system-specific requirements and procedure. Keep claim, scope, version, expiry and source separate in the evidence matrix."],
    ], [
        question([0], [1, 2], "A new citation replaces overlapping common-specification provisions. What should Northbridge do?", "Does changing the reference name complete the standards update review?", ("Recheck legal effect, coverage and implementation evidence.", "The replacement may change the evidence boundary."), ("Only rename the old supporting document.", "A renamed document does not establish current coverage."), ("Discard every technical record without reviewing it.", "Existing evidence should be evaluated, not blindly discarded.")),
        question([1], [3], "A supplier's ISO/IEC 42001 certificate is offered as complete AI Act conformity. Is that sufficient?", "Does an international management-system certificate automatically settle the system's AI Act assessment?", ("No; check its scope and the separate AI Act requirements.", "The frameworks and covered requirements are not automatically identical."), ("Yes; every management certificate is an AI Act certificate.", "Certification types have different legal and technical scopes."), ("Yes; only the certificate's graphic design matters.", "Visual presentation does not determine conformity.")),
        question([0, 1], [4], "What belongs in Northbridge's supplier-evidence record?", "Which record best limits the certificate claim?", ("Claim, scope, version, expiry and supporting source.", "These let the reviewer evaluate the actual boundary."), ("A statement that the supplier accepts every obligation.", "A blanket assertion does not establish transferred system responsibility."), ("Only a screenshot of the certificate logo.", "A logo cannot establish scope or continuing validity.")),
    ]),
    "F12": lesson("Articles 40–42; Annex IV(7)", "Find the gaps in a fictional supplier pitch.", [
        ["**Case pitch:** Northbridge's vendor says, 'Our ISO certificate, a cited logging standard and a cybersecurity certificate make your whole recruitment product compliant.' The exercise stipulates that the logging citation is genuine and the cybersecurity scheme qualifies, but both cover limited requirements."],
        ["Separate the claims. The ISO certificate concerns its stated organisational scope. Logging evidence concerns its stated covered requirement. The cybersecurity evidence concerns only the specified cybersecurity coverage. None automatically settles Northbridge's data, oversight or complete procedure."],
        ["Request a coverage matrix and implementation evidence. For uncovered requirements obtain detailed compliance solutions and results. If an applicable common specification is not followed, add the duly justified equivalent-level comparison. Do not treat a supplier's commercial warranty as the missing technical evidence."],
        ["Case conclusion: **not ready on the evidence presented**. Record the gaps and follow-up owner. This conclusion concerns the incomplete pitch; it does not establish that the underlying product could never satisfy the law."],
    ], [
        question([0], [1, 2], "Which claim exceeds the case's stipulated evidence?", "What is unsupported by the three limited documents?", ("Whole-system conformity for Northbridge.", "The documents have narrower stated scopes."), ("A limited logging presumption where its conditions are met.", "The case expressly stipulates that limited citation."), ("A limited cybersecurity presumption within its coverage.", "The case stipulates qualifying, limited cybersecurity evidence.")),
        question([0], [3], "What evidence should Northbridge request next?", "How should the provider address the uncovered requirements?", ("A coverage matrix and system-specific compliance evidence.", "These expose and support the missing requirements."), ("A larger certificate image for the website.", "Image size does not expand the evidence."), ("A broader unsupported sales assurance.", "More sweeping language does not demonstrate conformity.")),
        question([0], [4], "Which verdict fits this incomplete pitch?", "What conclusion is supported without claiming permanent impossibility?", ("Not ready on the presented evidence; document the gaps.", "The evidence is incomplete, with actionable follow-up."), ("Fully ready for every law and every release.", "The evidence does not support that breadth."), ("Permanently prohibited under Article 5.", "A missing conformity record is not itself a prohibited practice.")),
    ]),
}

LESSONS = add_registered_sources(LESSONS)
