"""Article 6(3) derogation gateway, conditions, profiling and records."""

from lesson_builder import assessment

LESSONS = {
    "E01": {
        "locator": "Article 6(3), first and second subparagraphs; final subparagraph",
        "summary": "Apply the no-significant-risk gateway as well as a listed condition; assess actual influence.",
        "screens": [
            ["The **paragraph 3 derogation** is a limited departure from Annex III high-risk classification. The system must not pose significant harm risk to health, safety or fundamental rights, including by not materially influencing decision outcomes.", "This gateway is not satisfied by an 'administrative' label. Explain the possible harms and influence using the actual system and context."],
            ["A listed condition must also fit: narrow procedural task, improvement of completed human activity, the specified decision-pattern/review function, or preparation for a relevant assessment.", "At least one condition is required; it is not necessary to satisfy all four. But selecting one condition does not remove the gateway. Later lessons test each condition's own wording."],
            ["**Decision influence** is the role an output plays in what happens to a person. A suggestion can materially shape a decision even when someone signs the final form.", "Fictional Northbridge: staff almost always accept an AI shortlist without reassessing excluded applicants. The final human signature does not prove that the output lacks material influence. Investigate the actual review process."],
            ["The final subparagraph supplies a profiling override for Annex III systems. Keep it in the checklist, alongside documentation and registration if a provider concludes the system is not high-risk.", "Our teaching checklist is: listed use; gateway; matching condition; profiling; supporting record. It is an application method, not a new statutory safe harbour or complete set of other-law duties."],
        ],
        "questions": [
            assessment([0], [1, 2], "A listed-use tool performs a narrow task but still creates significant rights risks. Is one condition enough?", "Can the narrow-procedural condition replace the no-significant-risk gateway?", ("No; the gateway and a condition both matter", "Paragraph 3 combines the gateway with at least one listed condition."), ("Yes; a task label alone settles it", "That omits the gateway's substantive test."), ("Yes; all four conditions are irrelevant", "At least one listed condition is required.")),
            assessment([1], [3], "Staff accept an AI shortlist almost automatically, then sign the final choice. What should be assessed?", "Does a final signature alone show that AI did not materially influence selection?", ("The actual influence and quality of review", "A human step does not establish lack of material influence."), ("Only the presence of a signature", "A signature can accompany substantial AI influence."), ("Only whether outputs are called suggestions", "A label does not determine how decisions are shaped.")),
            assessment([0, 1], [2, 4], "How many paragraph 3 conditions must fit, in addition to the gateway and profiling check?", "Must a system satisfy all four listed conditions to use the paragraph 3 derogation?", ("At least one, with the other tests still satisfied", "The statute uses alternative conditions within the gateway."), ("All four in every case", "That incorrectly turns alternatives into cumulative conditions."), ("None if a vendor says the risk is low", "A vendor claim cannot dispense with a listed condition.")),
        ],
    },
    "E02": {
        "locator": "Article 6(3)(a), paragraph 3 gateway and profiling rule",
        "summary": "Distinguish a genuinely narrow procedural task from a substantive personal decision.",
        "screens": [
            ["The **narrow procedural-task condition** concerns intended performance of a limited process step. 'Procedural' is not a label that can be pasted onto applicant evaluation or another substantive assessment.", "Northbridge describes the exact operation, what it selects or changes, and what consequences follow. This lets a reviewer test narrowness rather than rely on a job title."],
            ["Fictional case: a tool converts already supplied application files into a consistent format without choosing applicants or evaluating personal suitability. This illustrates a narrow-function hypothesis.", "It is not an automatic legal conclusion. The system must meet the definition and relevant listed-use facts before a paragraph 3 derogation matters; the gateway and profiling rule still need evidence."],
            ["Changed fact: conversion drops applicants based on predicted suitability. The operation now contains substantive evaluation and changes who reaches the reviewer.", "A limited input or short output does not prove a narrow procedural task. Decision effects and actual evaluation matter. Reassess when features or integrations change."],
            ["An assessment records the operation and the reason it satisfies a condition, the no-significant-risk analysis, and whether it performs personal profiling. Retain evidence of what happens on errors and downstream use.", "If a supposedly narrow task's error removes an essential application from review, the gateway needs careful examination. Do not equate a small component with insignificant harm."],
        ],
        "questions": [
            assessment([0], [1, 2], "A tool merely reformats supplied files without assessing applicants. What is the appropriate approach?", "How should a strictly formatting-only function be considered under the procedural-task condition?", ("Examine the narrow-task hypothesis and remaining tests", "The function supports a condition analysis, not automatic exemption."), ("Declare every listed tool exempt", "Other functions and the gateway still matter."), ("Assume formatting necessarily predicts suitability", "The case expressly lacks that evaluative function.")),
            assessment([0], [3], "A 'formatting' tool removes people based on suitability predictions. What changes?", "Does evaluative candidate exclusion stay a narrow task merely because a file conversion also happens?", ("Substantive personal evaluation must be reassessed", "The new facts are not just file formatting."), ("Nothing; the old label decides", "Labels cannot override actual operation."), ("Only the output file extension", "The decision function matters beyond file type.")),
            assessment([0], [4], "A small formatting component's error prevents an application being considered. What does component size prove?", "Can a short procedural step still create significant consequences?", ("Size alone does not settle the harm gateway", "Assess consequence and influence, not merely software size."), ("Small components can never cause significant harm", "That is not the statutory gateway test."), ("Only the developer's effort matters", "Development effort does not establish risk to people.")),
        ],
    },
    "E03": {
        "locator": "Article 6(3)(b), paragraph 3 gateway and profiling rule",
        "summary": "Test improvement of genuinely completed human work rather than replacement of an unfinished judgment.",
        "screens": [
            ["The **completed-human-work condition** concerns AI intended to improve the result of a human activity already completed. Identify that earlier activity and its completed result.", "Do not treat a blank form or an unfinished recommendation as completed human assessment. Completion is a factual requirement, not a synonym for 'a person is somewhere in the process'."],
            ["Fictional Northbridge: a person has completed a written report; a tool corrects spelling without changing findings. The case illustrates an improvement-of-completed-work hypothesis.", "The actual function and effects still require the gateway and profiling checks. This example is not a guarantee that every writing assistant satisfies a derogation in every listed context."],
            ["Changed case: before the person has evaluated an applicant, the tool supplies the substantive suitability recommendation. That is different from improving a completed result.", "Changed case: the tool rewrites a completed finding and alters its meaning. Assess whether the claimed improvement now materially influences the decision or creates significant risk."],
            ["The record should identify the completed activity, the allowed changes, the person reviewing them and the effect on conclusions. Retain before/after evidence appropriate to the case.", "A contract saying 'editing only' does not answer whether the system actually changes findings. Apply the full paragraph 3 test to the demonstrated operation."],
        ],
        "questions": [
            assessment([0], [1], "What must be identified for the completed-human-work condition?", "Which fact distinguishes Article 6(3)(b) from AI supplying a judgment before a person completes it?", ("A previously completed human activity and result", "The condition expressly requires completion before improvement."), ("Only any human in the organisation", "General human presence does not establish prior completion."), ("Only a form awaiting assessment", "An unfinished assessment is not a completed result.")),
            assessment([0], [2, 3], "A tool corrects spelling in a completed report, then adds a new adverse finding. What should happen?", "Does altering a completed report's substantive conclusions preserve an automatic editing exemption?", ("Reassess the actual change and decision influence", "The full condition and gateway depend on actual effects."), ("Ignore findings because spelling is also corrected", "A cosmetic function cannot erase the substantive change."), ("Assume every edit is non-influential", "Edits can affect conclusions and harm risks.")),
            assessment([0], [1, 4], "A vendor says 'improvement only' but cannot show the earlier completed activity. What should be recorded?", "How should missing prior-completion evidence affect a paragraph 3(b) claim?", ("The condition remains unsupported pending evidence", "The claimed factual requirement has not been established."), ("The marketing phrase proves completion", "A label is not proof of the earlier human activity."), ("The condition is irrelevant to this derogation", "Completion is central to this condition.")),
        ],
    },
    "E04": {
        "locator": "Article 6(3)(c), paragraph 3 gateway and profiling rule",
        "summary": "Distinguish pattern detection with proper review from unreviewed alteration of a completed assessment.",
        "screens": [
            ["The **pattern-review condition** concerns detecting decision-making patterns or deviations. It is qualified by the requirement that the system is not meant to replace or influence a previously completed human assessment without proper human review.", "Read the entire condition together. 'Pattern detector' alone is not sufficient, and 'human review' needs a real process rather than a ceremonial button."],
            ["Fictional Northbridge: a tool flags a deviation across completed assessments; a competent reviewer examines the underlying work before any revision. Record the flag, access to evidence and what the reviewer can actually change.", "This illustrates facts relevant to the condition. It does not by itself establish the no-significant-risk gateway or eliminate the profiling check."],
            ["Changed case: each flag automatically replaces the prior assessment without proper review. That undermines the stated condition.", "Changed case: the reviewer sees only the flag and routinely approves it without examining the earlier basis. Evidence of actual review is needed before calling it proper. A workflow diagram alone cannot establish how review functions."],
            ["Keep the completed assessment, pattern function, review arrangements and consequences in the record. Assess whether output materially influences decisions and whether the person can challenge errors.", "The derogation is not a general authorisation for replacing decisions after a token human step. If facts do not establish the condition or gateway, do not claim the exception."],
        ],
        "questions": [
            assessment([0], [1, 2], "Which facts are important for a pattern-detection tool claimed under paragraph 3(c)?", "What distinguishes properly reviewed pattern detection from unreviewed replacement of a human assessment?", ("Completed assessment and substantive review before influence", "The condition connects pattern detection with completed work and proper review."), ("Only calling the function a pattern detector", "The label omits the qualifying review facts."), ("Only a vendor's favourite colour", "That is unrelated to the condition.")),
            assessment([0], [3], "A deviation flag automatically overwrites the completed human assessment. Which issue is raised?", "Does automatic replacement without proper review fit the stated pattern-review condition?", ("The condition's review qualification is not established", "Unreviewed replacement is exactly what the qualification addresses."), ("It automatically satisfies the condition", "That ignores the completed-assessment/review language."), ("The prior assessment no longer matters", "Its replacement and review are central to the test.")),
            assessment([0], [2, 4], "A review diagram shows a human button, but actual reviewers cannot inspect earlier evidence. What should be done?", "How should an assessor evaluate a claim of proper human review?", ("Examine actual access, actions and decision effects", "Review needs factual support beyond the diagram."), ("Accept the button as sufficient in every case", "A nominal human step does not prove proper review."), ("Skip the gateway once a diagram exists", "The gateway remains independently necessary.")),
        ],
    },
    "E05": {
        "locator": "Article 6(3)(d), paragraph 3 gateway and profiling rule",
        "summary": "Test genuinely preparatory work without assuming everything early in a pipeline is exempt.",
        "screens": [
            ["The **preparatory-task condition** concerns work preparing an assessment relevant to an Annex III use case. Identify the assessment, what the preparation supplies, and what it does not decide.", "Preparation is an intended-function question. A component appearing early in a pipeline may still make substantive choices that shape the final result."],
            ["Fictional Northbridge: a tool arranges already supplied materials into a neutral indexed bundle for a later assessment, without personal evaluation or substantive recommendations. This illustrates a preparation hypothesis.", "The gateway, actual decision effects and profiling rule still need evidence. A useful index can be different from a generated suitability score, even if both occur before the final reviewer."],
            ["Changed fact: the bundle silently omits unfavourably scored applicants. The tool now influences who can be assessed. Calling the omission 'preparation' does not prove it is harmless.", "Changed fact: it summarises materials selectively in a way that changes substantive assessment. Record that effect and investigate significance rather than declaring the output neutral."],
            ["Record inputs, transformation, selection rules, output and downstream reliance. Distinguish purely preparing material from evaluating people or steering outcomes.", "The full test remains the no-significant-risk gateway plus a fitting condition and no applicable profiling override. The four conditions are alternatives; their shared gateway is not optional."],
        ],
        "questions": [
            assessment([0], [1, 2], "A tool creates a neutral material index before a listed assessment. How should its role be considered?", "What should a preparatory-task analysis identify?", ("The assessment prepared and the exact non-decision function", "The condition depends on actual preparation, not just chronology."), ("Only that it runs first", "An early component can still steer a substantive decision."), ("Only the file's size", "Size does not establish the task's legal character.")),
            assessment([0], [3], "A preparatory bundle omits applicants based on suitability predictions. What is the key change?", "Can predictive applicant exclusion be ignored because the bundle is generated before final assessment?", ("Its substantive selection and influence need reassessment", "The tool now affects who reaches the decision process."), ("There is no change because it runs early", "Chronology does not erase evaluation or influence."), ("The omissions always establish insignificant harm", "Their consequences must be assessed.")),
            assessment([0], [4], "Which checks remain after a preparatory function is established?", "Does proving one preparatory task settle the whole paragraph 3 derogation?", ("The harm gateway and profiling rule still apply", "A fitting condition is one part of the combined test."), ("None; preparation is blanket permission", "That omits independent requirements."), ("Only the subscription renewal date", "Commercial renewal is not the required classification check.")),
        ],
    },
    "E06": {
        "locator": "Article 6(3), final subparagraph; Article 3(52)",
        "summary": "Apply the profiling override within Annex III without extending it to every AI system.",
        "screens": [
            ["The **profiling override** says an AI system referred to in Annex III is always high-risk where it performs profiling of natural persons, notwithstanding paragraph 3's gateway.", "Its scope matters: it is not a rule that every AI system anywhere becomes high-risk merely because it profiles. First establish the relevant Annex III use."],
            ["Recall profiling: automated personal-data processing evaluating personal aspects, with context-specific cross-referenced definitions. The record must show what is evaluated rather than inferring profiling from every name in a file.", "Northbridge's applicant reliability predictor performs a personal evaluation. A purely alphabetical list operation has different facts. Human final approval does not erase the earlier automated evaluation."],
            ["Fictional case: the system is stipulated to fall within Annex III recruitment and predicts personal suitability. A claimed narrow-task or preparatory condition cannot overcome the profiling override.", "Do not rearrange the test to accept a convenient condition before checking profiling. Record the exact personal evaluation and the corresponding listed use."],
            ["Changed case: profiling is shown, but no Annex III purpose has been established. Investigate the listed-use route and any product route, along with other law. Do not use this override as a universal classification formula.", "A result that the override does not apply is narrower than 'no obligations'. Other AI Act duties and personal-data rules can still matter."],
        ],
        "questions": [
            assessment([0], [1], "What must be established before applying the paragraph 3 profiling override?", "Does Article 6(3)'s profiling sentence classify every profiling AI system in every context?", ("A relevant Annex III system and personal profiling", "The sentence is expressly scoped to Annex III systems."), ("Only that software handles a person's name", "A name alone proves neither profiling nor the listed purpose."), ("Nothing about the intended use", "The Annex III comparison is essential.")),
            assessment([0], [2, 3], "An Annex III recruitment tool predicts applicant reliability but claims to be preparatory. What follows?", "Can a preparatory-task condition remove the Annex III profiling override?", ("The profiling override keeps it high-risk", "The final subparagraph overrides the paragraph 3 derogation."), ("Preparation always overrides profiling", "That reverses the statutory priority."), ("Human final approval always erases profiling", "Profiling concerns the earlier automated personal evaluation.")),
            assessment([0], [1, 4], "Profiling exists, but the listed use is unresolved. What conclusion is justified?", "How should an assessor handle a profiling fact without an established Annex III purpose?", ("Investigate classification routes and other applicable rules", "The override cannot substitute for the missing listed-use analysis."), ("Automatically classify every such system under this sentence", "That extends the sentence beyond its Annex III scope."), ("Automatically declare there are no legal duties", "An unresolved or inapplicable override does not erase other law.")),
        ],
    },
    "E07": {
        "locator": "Article 6(4); Article 49(2), 49(4); Annex VIII Section B",
        "summary": "Separate assessment documentation, registration and responding to competent-authority requests.",
        "screens": [
            ["A provider concluding an Annex III system is not high-risk under paragraph 3 must **document the assessment before market placement or service**. The record should show the facts and each legal test supporting that conclusion.", "A bare claim 'low risk' is not a documented analysis. This course's practical packet distinguishes scope, use, gateway, condition, profiling and the source version used."],
            ["**Classification registration** is a separate obligation under Article 49(2). The provider, or relevant authorised representative, registers itself and the system before market placement or service.", "Documentation and registration are not interchangeable. A report kept internally does not by itself prove registration. Nor does a registration entry establish that the underlying legal reasoning is correct."],
            ["On request, the provider must give competent national authorities the documentation of its assessment. Plan to locate the actual record and supporting evidence.", "A person asking informally on the internet is not automatically a competent-authority request. Verify the request and authority; do not confuse this obligation with general public disclosure of every internal document."],
            ["Check the applicable registration fields and access restrictions. Annex VIII Section B points 7 and 9 are deleted in our baseline. Article 49(4) specifies secure non-public registration for stated enforcement/migration contexts and still contains a cross-reference to point 9.", "Record that textual cross-reference issue; do not invent a deleted field. The documentation duty remains. Application dates and the exact secure-section context require their own check before making a real filing."],
        ],
        "questions": [
            assessment([0], [1], "When must a provider document its paragraph 3 not-high-risk assessment?", "Can the assessment record first be created after the system enters service?", ("Before market placement or putting into service", "Article 6(4) supplies the timing requirement."), ("Only after an error is reported", "The record is a prior requirement, not only incident response."), ("Never if the provider calls it low risk", "The conclusion triggers a documentation obligation.")),
            assessment([1], [2, 4], "A provider has an internal report but no registration evidence. What remains distinct?", "Does keeping a paragraph 3 assessment report itself satisfy the registration requirement?", ("Article 49(2) registration must be separately established", "Documentation and registration are different tasks."), ("The report automatically is a registration entry", "An internal file does not prove database registration."), ("A deleted field must be invented to register", "Use operative fields; do not reconstruct deleted requirements.")),
            assessment([2], [3], "A verified competent national authority requests the assessment. What must the provider be able to supply?", "What does Article 6(4) require on a competent-authority documentation request?", ("The documented assessment", "The provider must provide that assessment documentation on request."), ("Only a marketing brochure", "A brochure is not the actual documented assessment."), ("The same material publicly to every online stranger", "The stated duty concerns competent national authorities.")),
        ],
    },
    "E08": {
        "locator": "Articles 2, 3(12), 3(52), 5, 6, 49, 111, 113; Annexes I and III",
        "summary": "Produce a conditional classification conclusion that survives changed purpose, influence and profiling facts.",
        "screens": [
            ["**Classification capstone**: Northbridge's applicant platform first converts files and later adds personal suitability predictions. Assume the evaluation function is an AI system within scope and matches Annex III recruitment.", "Those stipulated facts isolate the remaining test. Record which facts are established and which are assumptions; in a real decision obtain their evidence."],
            ["For the evaluative function, inspect paragraph 3's gateway, candidate condition and personal profiling. Personal suitability predictions support a profiling fact, which keeps the Annex III system high-risk despite a preparatory label.", "For a separate formatting-only function, do not copy that result blindly; inspect its own system boundary, listed-purpose facts, errors and influence. Equally, do not copy its narrower result to the evaluator."],
            ["Changed case: the evaluator also performs a potentially prohibited practice. Classification is not a cure; investigate Article 5's complete test. Changed case: a new safety-product function is added. Check Article 6(1) separately.", "A maintainable conclusion says which route and purpose it addresses. It avoids one immutable platform-wide label."],
            ["The final packet records evidence, source baseline, actors, scope, prohibition findings, both classification routes, paragraph 3/profiling, records, relevant duties and their dates. Explain unresolved facts.", "This completes the classification reasoning exercise, not every high-risk compliance obligation. The later course programme covers those requirements. A defensible assessment states its limits rather than pretending the whole Act has been satisfied."],
        ],
        "questions": [
            assessment([0], [1, 2], "The case establishes Annex III recruitment and personal suitability profiling. What happens to a preparatory claim?", "How should the capstone classify the stipulated evaluative recruitment function under paragraph 3?", ("Profiling keeps that function high-risk", "The override applies to the established Annex III profiling system."), ("The preparation label exempts it automatically", "That ignores the final subparagraph."), ("The formatting feature exempts the evaluator", "A different function cannot determine this function's facts.")),
            assessment([0], [3], "A safety-product function is added to the platform. What should the assessor do?", "Does an old listed-use conclusion settle a newly added product safety function?", ("Check the separate product route and changed facts", "New purposes may engage a different classification route."), ("Reuse the old conclusion without checking", "The previous facts do not cover the added function."), ("Assume any classification cures prohibitions", "Article 5 remains independently relevant.")),
            assessment([0], [4], "Which final conclusion is most defensible after this first classification exercise?", "How should an assessment state its outcome without claiming all legal duties are complete?", ("Specify route, facts, source version and remaining duties", "That makes the conclusion traceable and bounded."), ("State only 'everything compliant forever'", "A broad permanent claim is unsupported by this exercise."), ("Hide every missing fact from the reader", "Unresolved facts must remain visible.")),
        ],
    },
}
