"""Article 50 foundations and interaction: original teaching and case questions."""

from lesson_builder import assessment

GUIDELINES = {"title": "Commission Article 50 Guidelines C(2026) 5054 final; non-binding interpretation", "url": "https://digital-strategy.ec.europa.eu/en/library/guidelines-transparency-obligations-providers-and-deployers-ai-systems"}
CODE = {"title": "Final Transparency Code, 10 June 2026; voluntary implementation framework", "url": "https://digital-strategy.ec.europa.eu/en/policies/code-practice-ai-generated-content"}

LESSONS = {
    "T01": {
        "locator": "Articles 2(1), 2(10), 2(12), 3(1), 3(63), 3(66)",
        "additional_sources": [GUIDELINES],
        "summary": "Recognise the system, separate its model and establish the EU connection.",
        "screens": [
            ["We follow **Harbour Services**, a fictional organisation building a customer assistant and a media workflow. Its people, suppliers and scenarios are invented. This course teaches Article 50 transparency; each conclusion still needs the actual facts of a real use.", "An **AI system** is machine-based, operates with some autonomy and infers from inputs how to produce predictions, content, recommendations or decisions for explicit or implicit objectives. Its outputs can influence physical or digital environments; it may adapt after deployment."],
            ["Inference matters. A learned assistant deriving an answer from inputs differs from a fixed rule that sorts a list by date. Automation or an 'AI' product label alone does not settle the definition.", "Human review does not itself remove AI status. Continuing retraining is optional, not a condition every deployed system must satisfy."],
            ["A **general-purpose AI model** has significant generality and can perform many distinct tasks. A model can be integrated into systems. A **general-purpose AI system** is based on such a model and can serve varied purposes directly or through integration.", "Harbour adds an interface, documents and actions around an external model. Assess the operated assistant as a system. Article 50 addresses specified systems; a model provider's separate model obligations require their own analysis."],
            ["The **EU scope check** asks how supply or use connects to the Union. Article 2 includes providers placing systems or models on the EU market, deployers established or located in the EU, and certain third-country actors where system output is used in the EU.", "An overseas server does not automatically exclude Harbour's EU-facing assistant. Record the relevant actor, supply and use facts; check the exact paragraph rather than deciding solely from server location."],
            ["Article 2(10) excludes obligations of deployers who use systems in purely personal, non-professional activity. That is not a universal exemption for suppliers serving private people.", "Article 2(12)'s free/open-source system exclusion is conditional: high-risk, Article 5 and Article 50 systems remain outside that exclusion. Harbour cannot dismiss transparency simply because it uses open weights. Other exclusions need their own exact tests."],
        ],
        "questions": [
            assessment([0], [1, 2], "Harbour's script only sorts names by a fixed date rule. What is the sound starting point?", "Does ordinary fixed-rule sorting establish AI-system status by itself?", ("Check inference and the other definition elements", "Automation alone is insufficient; actual functionality matters."), ("Classify it from the AI marketing label", "Branding cannot replace the statutory definition."), ("Require the script to retrain every day", "Adaptation after deployment is optional.")),
            assessment([1], [3], "Harbour wraps an external general-purpose model in a customer assistant. What must its assessment distinguish?", "What distinction matters when a reusable model powers Harbour's assistant?", ("The model and the operated system", "They are related but distinct regulatory objects."), ("Only the supplier's server brand", "Branding does not identify the actual system use."), ("Only the assistant's interface colour", "Appearance does not replace model/system analysis.")),
            assessment([2], [4, 5], "An overseas supplier offers Harbour an open-source AI assistant for EU customers. May Harbour exclude Article 50 solely on those facts?", "Do foreign hosting and an open-source licence alone remove transparency duties for an EU-facing system?", ("No; check EU connections and the conditional exclusion", "Article 2 reaches relevant EU connections and preserves Article 50 cases."), ("Yes; all overseas systems are outside scope", "Supply and output use in the EU can establish a connection."), ("Yes; every open-source system is exempt", "The exclusion expressly preserves Article 50 cases.")),
        ],
    },
    "T02": {
        "locator": "Articles 3(3), 3(4), 50(7), 96; consolidation notice",
        "additional_sources": [GUIDELINES, CODE],
        "summary": "Identify providers and deployers, and distinguish law from guidance and voluntary methods.",
        "screens": [
            ["A **provider** develops an AI system or has it developed and places it on the market or puts it into service under its name or trademark. Payment is not essential to the definition.", "Harbour commissions an assistant and puts it into service under its own name. Outsourcing development does not by itself transfer Harbour's provider role. Own professional use can involve putting a system into service."],
            ["A **deployer** uses an AI system under its authority, except for personal non-professional activity. Harbour using a vendor's complete assistant in its professional work is a deployer.", "One organisation can hold both roles for a system it develops and uses. Determine actions and responsibility rather than relying on a contract's informal label, such as 'technology partner'."],
            ["**Source authority** means which instrument creates a legal duty. The AI Act and its adopted amendments are binding law. Official Journal acts carry legal authority; a consolidated text helps read amendments together but is a documentation tool.", "Commission Guidelines explain interpretation and examples. They are not binding law; authoritative interpretation ultimately belongs to the courts. Compare older guidance with later amendments before copying wording."],
            ["A **Code of Practice** offers implementation commitments and methods. Signing the Transparency Code is voluntary; a signatory must implement the commitments on which it relies, while encouraged measures remain optional.", "A supplier's Code signature is evidence to examine, not conclusive proof of compliance. A claimed technical standard or visible icon does not replace the actual legal test."],
        ],
        "questions": [
            assessment([0], [1], "Harbour pays a contractor to develop an assistant and puts it into service under Harbour's name. Which role is indicated?", "Who has the provider role when Harbour commissions and launches its own branded system?", ("Harbour is a provider", "Having a system developed and putting it into service under one's name meets the relevant provider conduct."), ("Harbour is excluded because it hired a contractor", "Commissioning development does not remove the role."), ("Only a company selling models can be a provider", "The definition also covers AI-system providers.")),
            assessment([1], [2], "Harbour uses a vendor's complete assistant for professional customer support. Which role is directly indicated?", "Which role describes Harbour operating a purchased assistant under its authority at work?", ("Deployer", "Professional use under its authority meets the deployer definition."), ("Personal non-professional user", "The scenario is organisational professional activity."), ("No role because another company built it", "Using a vendor system can establish the deployer role.")),
            assessment([2], [3, 4], "A slide says a Code signature guarantees compliance, but the official assessment says it is not conclusive. What should Harbour do?", "How should Harbour treat a supplier's voluntary-Code claim?", ("Check implemented measures against the operative duties", "Law governs and signature alone is not conclusive evidence."), ("Treat the slide as overriding the statute", "A presentation cannot replace operative law."), ("Treat every encouraged Code measure as statutory", "Optional recommendations are not standalone legal duties.")),
        ],
    },
    "T03": {
        "locator": "Article 50(1)-(6), Article 5, Article 26(11)",
        "additional_sources": [GUIDELINES],
        "summary": "Assign the four transparency duties and preserve other applicable obligations.",
        "screens": [
            ["**Duty allocation** starts with the actor and activity. Article 50(1) addresses providers of systems intended to interact directly with people. Article 50(2) addresses providers of systems producing synthetic content, meaning artificially generated or manipulated content.", "A customer's use of the system does not erase the provider's design responsibility. A provider and deployer may be different companies or the same organisation."],
            ["Article 50(3) addresses deployers using emotion recognition or biometric categorisation: people exposed to those systems must be informed, subject to the provision's conditions. Those technical categories are taught later in this course.", "Article 50(4) addresses deployers of specified generated or manipulated media and public-interest text. Later lessons define the exact content tests and exceptions; do not assume every piece of text receives the same treatment."],
            ["**Cumulative duties** can operate together. An interactive content-generating assistant may trigger both provider paragraphs. Certain uses of its outputs may also trigger a deployer's duty.", "Record each duty separately. Showing someone that the assistant is AI does not automatically settle how its outputs must be marked or how published content must be disclosed."],
            ["Article 50(6) preserves Chapter III duties for high-risk systems and other applicable Union or national transparency duties. **High-risk** means a system classified under Article 6; it can have additional requirements. This lesson identifies that boundary rather than teaching the whole classification route.", "A **prohibited practice** is a use forbidden under Article 5. Disclosure cannot legalise it. For example, telling employees that a system infers emotions does not cure a prohibited workplace use. Check the prohibition before proceeding."],
            ["Harbour's review table records the system, actor, activity, relevant paragraph and other legal questions. A single product can occupy several rows.", "For a high-risk system helping make decisions about people, Article 26(11) may require a separate deployer notification. Look up its conditions. A supplier's 'low risk' description is not permission to ignore data protection, sector rules or transparency."],
        ],
        "questions": [
            assessment([0], [1, 2], "A vendor provides a generative assistant and Harbour uses its output in a campaign. How should responsibilities be analysed?", "How should Harbour analyse a workflow spanning the system supplier and output publisher?", ("Assign each paragraph by actor and activity", "Provider and deployer duties attach to different conduct."), ("Assign every duty only to the customer", "Provider duties do not disappear when a customer uses the system."), ("Assign every duty only to the model supplier", "Downstream systems and deployers need their own analysis.")),
            assessment([1], [3], "Harbour's assistant both converses with customers and generates content. Does interaction disclosure settle all transparency duties?", "Can one interaction notice replace the separate synthetic-output assessment?", ("No; applicable duties can operate together", "The paragraphs address different activities and can be cumulative."), ("Yes; one AI notice discharges every paragraph", "A notice is not automatically the required output treatment."), ("Yes; only one paragraph can apply per product", "The Act does not impose that exclusivity.")),
            assessment([1], [4, 5], "A proposed use is prohibited under Article 5. Harbour offers to add a prominent AI notice. What follows?", "Does disclosure make an otherwise prohibited AI use lawful?", ("The prohibition still prevents the use", "Transparency does not remove a prohibition."), ("The notice authorises the prohibited activity", "Disclosure is not a legal permission."), ("High-risk classification cancels the prohibition", "Classification does not legitimise a forbidden use.")),
        ],
    },
    "T04": {
        "locator": "Article 50(1)", "additional_sources": [GUIDELINES],
        "summary": "Test direct interaction, contextual obviousness and the authorised-law-enforcement exception.",
        "screens": [
            ["**Direct AI interaction** involves an intended exchange between an AI system and a natural person. Commission guidance describes a conversational or responsive character: input and contextual response, including voice, text or physical actions.", "A single exchange can qualify. A passive filter or a backend machine-to-machine call without intended human contact is different. Assess the actual interaction rather than classifying every interface as conversational."],
            ["Harbour's customer writes a question and receives the assistant's contextual reply: direct interaction. If a human employee uses AI privately, reviews the draft and sends their own message as the main interlocutor, the person may instead be interacting with that employee.", "A merely available human override does not automatically turn an AI-led conversation into human-mediated communication. The Commission examples are interpretation; trace who actually communicates with the person."],
            ["The provider must design the system so people know they are interacting with AI unless that is **obvious** to a reasonably well-informed, observant and circumspect person, considering context and circumstances.", "Human names, realistic voices and employee-style portraits may obscure the nature of a service. Do not assume users know because an AI reference appears somewhere else on the website. The standard is contextual, not a provider's private belief."],
            ["The law-enforcement exception requires a system authorised by law to detect, prevent, investigate or prosecute criminal offences, with appropriate safeguards for third-party rights and freedoms.", "An organisation calling a tool 'fraud prevention' does not establish that authorisation. Record the legal basis and safeguards; the exception cannot be established solely by the tool's purpose label."],
            ["The exception has a **public-reporting carve-back**: if the system is available for the public to report a criminal offence, the interaction disclosure obligation remains.", "In our stipulated case, Harbour supplies an AI reporting hotline with the required legal authorisation and safeguards. Because the public uses it to report offences, the provider must still ensure interaction disclosure."],
        ],
        "questions": [
            assessment([0], [1, 2], "A customer asks Harbour's AI assistant a question and gets a contextual answer. A staff member could intervene but does not. Which assessment fits?", "Does a possible human override remove direct interaction when AI actually answers the customer?", ("Direct AI interaction remains the relevant test", "The actual exchange is AI-led; a possible override is insufficient."), ("Every possible override makes it human-only", "Possibility is not the same as actual human mediation."), ("Only repeated conversations count as interaction", "A single responsive exchange can fall in scope.")),
            assessment([1], [3], "Harbour gives an assistant a staff portrait and human name and relies on an AI statement hidden on another page. What must it check?", "What matters when a realistic assistant's AI identity is unclear in the conversation?", ("Whether AI interaction is obvious in the actual context", "Article 50(1) uses a contextual person standard."), ("Whether the developers know it is artificial", "Their knowledge does not establish obviousness to the person concerned."), ("Whether an AI statement exists anywhere online", "A remote statement does not necessarily make this interaction obvious.")),
            assessment([2], [4, 5], "A legally authorised and safeguarded AI hotline lets the public report offences. Is its interaction disclosure removed?", "Does the authorised-law-enforcement exception remove disclosure for a public offence-reporting AI service?", ("No; public reporting restores the duty", "Article 50(1) expressly retains disclosure in this situation."), ("Yes; authorisation alone removes disclosure", "The public-reporting carve-back still applies."), ("Yes; reporting crime is always outside scope", "That contradicts the provision's express condition.")),
        ],
    },
    "T05": {
        "locator": "Article 50(1); Commission Guidelines paragraph 31", "additional_sources": [GUIDELINES],
        "summary": "Distinguish statutory AI disclosure from guidance about represented principals and supervisory steps.",
        "screens": [
            ["An **AI agent** is an AI system that can carry out tasks, for example managing correspondence or making bookings. When it can interact with people, the Article 50(1) analysis applies.", "Paragraph 31 of the Commission Guidelines explains how the interaction rule applies to agents. It is interpretative guidance, not three new numbered statutory duties."],
            ["The **principal** is the person or organisation on whose behalf the agent acts. The guidance says agents should disclose their artificial nature and that represented person, addressing origin, delegated authority and accountability.", "A suitable Harbour message is: 'I am Harbour Services' AI booking assistant, acting for Harbour Services.' Saying only 'I am an assistant' can leave both artificial nature and representation unclear."],
            ["A provider may not know every later context where an agent reaches a person. The guidance advises architecture-level design and instructions to disclose wherever human interaction is reasonably likely.", "Passing a task through another agent does not remove the need to consider the final human contact. Use a disclosure route that survives the actual handoff rather than assuming all later exchanges are machine-only."],
            ["The guidance also addresses the **instructing or supervising person**. The agent should disclose itself at authorisation, reporting and validation steps, and at every new interaction.", "This includes processing outputs from other AI systems. A report to a supervisor should not silently imply that an AI-generated result came directly from a person."],
        ],
        "questions": [
            assessment([0], [1, 2], "Harbour's booking agent contacts a hotel. Which introduction follows the agent-specific Commission guidance?", "What should the hotel be told when Harbour's AI agent acts for Harbour?", ("That it is AI and acts for Harbour Services", "The guidance addresses artificial nature and represented principal."), ("Only that it is called Alex", "A name does not explain AI nature or representation."), ("Only that the booking concerns a hotel", "Task subject does not explain origin and authority.")),
            assessment([1], [3, 4], "An agent sends its supervisor an AI-generated result obtained from another agent. What should its design account for?", "What matters at a supervisory validation step involving another agent's output?", ("Disclosure to the instructing person at that key step", "Guideline paragraph 31 includes reporting and validation, including AI-sourced inputs."), ("Silence because only direct human input matters", "The guidance explicitly includes reliance on other AI outputs."), ("Disclosure only when the booking is completed", "Relevant authorisation and validation steps can occur earlier.")),
            assessment([0, 1], [1, 3], "The provider cannot reliably predict whether a deployed agent will contact people. Which approach follows the guidance?", "How should disclosure be designed when later human contact is reasonably likely but unpredictable?", ("Design disclosure into likely human-contact situations", "The guidance advises architecture-level design for that uncertainty."), ("Omit disclosure until every recipient is known", "That would leave reasonably likely human interactions uncovered."), ("Treat the guidance as three new statutory paragraphs", "These are interpretations of Article 50(1), not separate enacted clauses.")),
        ],
    },
    "T06": {
        "locator": "Article 50(1), 50(5); Guidelines paragraphs 31, 137-144", "additional_sources": [GUIDELINES, CODE],
        "summary": "Make disclosure clear, timely and accessible in an agent-hotline case.",
        "screens": [
            ["**Clear and distinguishable disclosure** enables the person to recognise the relevant AI involvement. Article 50(5) sets a latest point: first interaction or exposure.", "A notice hidden in terms that appears after a conversation does not reliably inform the person at the required moment. Use plain wording near the relevant interaction."],
            ["**Accessible disclosure** conforms to the accessibility requirements applicable to the product, service or content. The Commission explains that Article 50 does not invent a separate universal accessibility regime.", "Check which accessibility rules apply, then design information the audience can perceive and understand. A visual badge alone is unsuitable as the only notification in an audio-only interaction."],
            ["Account for intended or reasonably likely vulnerable audiences, such as children and people with disabilities. Guidance recommends understandable, age-appropriate information where children may interact.", "The Code supplies practical approaches such as audible notices, screen-reader-compatible labels and sufficient contrast. These examples do not make one icon or technology a universal statutory requirement."],
            ["Case: Harbour provides a public offence-reporting AI hotline. Assume legal authorisation and safeguards are established. The service sounds like a human staff member and starts recording the report before giving an AI notice.", "Public reporting retains the interaction duty. The human-like context does not establish obviousness. Move a clear notification to the start of interaction rather than relying on the end-of-call notice."],
            ["The hotline's agent acts for Harbour and later seeks approval from a supervising person. Use the principal and supervisory disclosures described by paragraph 31 of the Guidelines.", "Provide a perceivable disclosure in the actual channel and the applicable accessible format. A logo in a web page is insufficient for a caller who only hears audio; another format may also be needed for people unable to hear it."],
        ],
        "questions": [
            assessment([0], [1, 4], "Harbour gives its AI notice only after collecting a caller's offence report. What correction addresses Article 50(5)?", "When should the hotline provide clear AI information rather than waiting until the call ends?", ("At the latest when interaction first begins", "The statutory latest point is first interaction or exposure."), ("Only after the caller's report is validated", "That is too late for the initial interaction."), ("Only when the caller opens a terms page", "Required information cannot depend on a delayed separate action.")),
            assessment([1], [2, 3, 5], "The hotline uses a visual AI badge, but callers interact only through audio. What must Harbour consider?", "Can a website badge alone adequately disclose an audio-only AI call?", ("A perceivable notice in the channel and applicable accessible formats", "Disclosure must work for the people and channel concerned."), ("A larger badge on an unrelated page", "It remains unavailable in the actual audio interaction."), ("One mandatory icon that overrides accessibility law", "The Act requires applicable accessibility; it does not prescribe that universal icon.")),
            assessment([2], [4, 5], "The authorised hotline is public-facing, sounds human and uses an agent representing Harbour. Which design is supported?", "Which correction fits the complete hotline scenario?", ("A clear opening AI notice, represented-principal information and supervisor-step disclosure", "The carve-back, timing and agent guidance operate together."), ("No notice because legal authorisation overrides public reporting", "Public offence reporting retains the interaction duty."), ("An end-of-call notice with no represented principal", "The timing is late and the agent guidance remains relevant.")),
        ],
    },
}
