"""Internal control, notified-body procedures, certificates and later changes."""

from high_risk_content import lesson, question
from conformity_sources import add_registered_sources

LESSONS = {
    "F19": lesson("Article 43(2); Annex VI(1)–(4)", "Perform the internal checks rather than substituting a certificate purchase.", [
        ["**Internal control** under Article 43(2) is the AI Act conformity procedure for Annex III points 2–8. Annex VI does not provide for a notified body. Northbridge's stipulated employment route falls here. This does not exclude other legal requirements, voluntary advice or a separate applicable sector route."],
        ["The provider verifies its **quality management system**—the documented processes and responsibilities for achieving and maintaining compliance—against Article 17. It examines technical documentation to assess the relevant Chapter III Section 2 requirements. Calling the process internal does not make it optional or unrecorded."],
        ["**Design-file consistency** means the actual design and development process and post-market monitoring agree with the technical documentation. If Northbridge's file promises a human override that the released interface lacks, the inconsistency needs correction and evidence, not merely a signature."],
        ["Record the checks, findings, gaps and corrective decisions. Verify the current legal version: Article 43(6) permits future delegated changes to procedures for Annex III points 2–8, and Article 43(5) permits updates to Annexes VI and VII. The retained baseline is not a promise that the route can never change."],
    ], [
        question([0], [1, 2], "Does Northbridge's stipulated employment route require an AI Act notified body under Article 43(2)?", "Which procedure applies to the stated Annex III employment case?", ("Annex VI internal control, without that notified-body involvement.", "Article 43(2) directs points 2–8 to internal control."), ("Annex VII solely because recruitment is high-risk.", "High-risk status does not make every procedure identical."), ("No conformity checks because the procedure is internal.", "Annex VI requires substantive provider checks.")),
        question([1], [3], "The file says users can override results, but the interface has no override. What should happen?", "What does a mismatch between the assessed file and released behaviour indicate?", ("Resolve and evidence the design-file inconsistency.", "Actual design and documented controls must be consistent."), ("Ignore it after signing the declaration.", "A signature does not fix actual behaviour."), ("Purchase an unrelated certificate instead.", "A different certificate does not resolve the missing control.")),
        question([0, 1], [2, 4], "What makes the internal-control record useful?", "What should the provider retain about its internal assessment?", ("The required checks, evidence, findings and corrective decisions.", "The procedure evaluates compliance and actual consistency."), ("Only a note saying 'internal, therefore exempt'.", "Internal control is a procedure, not a compliance exemption."), ("Only the model supplier's sales brochure.", "The provider must assess its own system evidence.")),
    ]),
    "F20": lesson("Article 43(1); Annexes VI and VII", "Choose the lawful biometric procedure from its precise conditions.", [
        ["**Biometric assessment route:** for Annex III point 1 systems, the provider can choose Annex VI internal control or Annex VII assessment with a notified body when the relevant Article 40 standards or applicable Article 41 common specifications have been applied to demonstrate Section 2 compliance. Always perform the separate Article 5 precheck first."],
        ["Annex VII is required where no harmonised standards and no common specifications are available; where the provider has not applied, or has applied only part of, the harmonised standard; where available common specifications are not applied; or where the relevant standard citation has a restriction on the part concerned. The exercise must specify the evidence facts rather than assume standards exist."],
        ["A **special authority assessor** applies where the system is intended for service by law-enforcement, immigration or asylum authorities or Union institutions, bodies, offices or agencies. The Article 74(8) or (9) market surveillance authority, as applicable, acts as notified body for the Annex VII assessment. Outside this specified case, the provider chooses a qualified body within the relevant scope."],
        ["Fictional **Beacon Biometrics** has a stipulated lawful Annex III point 1 use. In variant A, the relevant qualifying standards are fully applied with no relevant restriction; the choice may be available. In variant B, only part is applied; Annex VII is required. This is procedure analysis, not approval of an actual biometric deployment."],
    ], [
        question([0], [2, 4], "Beacon applies only part of the relevant harmonised standard. Which procedure follows?", "Does partial application preserve the point 1 internal-control choice?", ("Annex VII with the applicable notified-body assessment.", "Partial application is a specified mandatory Annex VII trigger."), ("Annex VI automatically because some work was done.", "Partial application does not satisfy this route condition."), ("No assessment because standards are voluntary.", "Voluntary standards do not remove the procedure requirement.")),
        question([1], [3], "Beacon is intended for an asylum authority's service under the stated Annex VII route. Who acts as assessor?", "Which special assessor rule applies in the specified authority-use case?", ("The applicable Article 74 market surveillance authority.", "Article 43(1) specifies that authority acting as notified body."), ("Any consultant chosen solely for its price.", "That does not satisfy the specified authority rule."), ("The provider's marketing team.", "The team is not the statutory special assessor.")),
        question([0], [1, 4], "Variant A fully meets the qualifying standards conditions with no relevant restriction. What may be available?", "Which procedure choice is conditional on the stipulated complete application?", ("A choice between Annex VI and Annex VII.", "Article 43(1) permits the choice when its conditions are satisfied."), ("An exemption from Section 2 requirements.", "The choice changes procedure, not the applicable requirements."), ("Permission to ignore Article 5.", "Conformity cannot authorise a prohibited practice.")),
    ]),
    "F21": lesson("Annex VII(1)–(5); Article 17", "Prepare quality management, technical assessment and continuing surveillance.", [
        ["**Quality-management approval** under Annex VII begins with the provider/representative identity, systems covered, each system's technical documentation, Article 17 process documentation, procedures keeping it effective and a declaration that the same application was not lodged elsewhere. The body assesses it and gives a reasoned decision. Approval must be implemented and maintained."],
        ["Notify intended changes to the approved quality-management system or covered-system list. The body examines them and decides whether the modified system still satisfies the requirements or needs reassessment. A provider cannot silently add a new covered product to an old approval."],
        ["**Technical-documentation assessment** has a system-specific application: provider identity, declaration about no duplicate application and Annex IV documentation. The body examines the records and may require additional evidence/tests or conduct appropriate tests itself if dissatisfied with the provider's tests."],
        ["Relevant training, validation and testing dataset access is limited to what is necessary, with appropriate secure remote means where suitable. Access to training/trained models and parameters has stricter conditions: necessity, other reasonable means exhausted and insufficient, a reasoned request, and protection of intellectual property and trade secrets. It is neither automatic unrestricted access nor an absolute secrecy veto."],
        ["A favourable technical decision produces a certificate identifying the system, provider, conclusions and validity conditions. Non-conformity leads to a reasoned refusal. If the training-data requirement is not met, retraining is needed before applying for a new assessment, with specific reasons about training-data quality."],
        ["**Quality-management surveillance** checks continuing compliance with the approval. The provider allows access to relevant design/development/testing premises and necessary information. Periodic audits produce reports and may include additional system tests. Approval is an ongoing responsibility, not a one-time purchase."],
    ], [
        question([0], [1, 2], "A provider wants to add a system to its approved quality-management list. What must it do?", "Can a covered-system list be expanded without notifying the body?", ("Notify the body for examination and a reasoned decision.", "Annex VII(3.4) requires assessment of intended changes."), ("Add it silently because the provider name is unchanged.", "The covered-system list is part of the approved scope."), ("Ask only the sales department to approve the logo.", "Marketing approval does not satisfy the body-change procedure.")),
        question([1], [3, 4, 5], "The body requests model parameters. Which condition set is relevant?", "Is model access always automatic under the technical assessment?", ("Necessity, exhausted alternatives, reasoned request and legal safeguards.", "Annex VII(4.5) specifies these additional access conditions."), ("No conditions; every model must always be publicly disclosed.", "Body access is conditional and protected, not unrestricted publication."), ("No access is ever possible because models are confidential.", "The paragraph permits access under its safeguards.")),
        question([2], [6], "An approved provider refuses every periodic audit. What is missing?", "Does quality-management approval end the body's surveillance role?", ("Continuing premises/information access and periodic surveillance.", "Annex VII(5) requires ongoing assessment arrangements."), ("Only a decorative certificate frame.", "Presentation does not maintain compliance."), ("Nothing; approval permanently ends monitoring.", "The approved system remains subject to surveillance.")),
    ]),
    "F22": lesson("Articles 44–45; Annex VII(4.6)–(4.7)", "Manage certificate scope, validity and required exchanges.", [
        ["A **certificate lifecycle** includes its system scope, conditions, expiry, reassessment and possible changes. Article 44 certificates are in a language easily understood by the relevant authorities where the body is established. Their indicated validity cannot exceed five years for Annex I systems or four for Annex III. Extensions require reassessment and the same maximum periods."],
        ["A certificate supplement depends on the underlying certificate remaining valid. If Section 2 requirements cease to be met, the body restricts, suspends or withdraws, unless appropriate corrective action within its deadline ensures compliance. Decisions need reasons and an appeal procedure. Appealing is not itself proof of conformity."],
        ["**Assessment-result sharing** has different recipients. The notifying authority receives issued certificates/supplements and approvals, adverse decisions, changed notification circumstances and relevant authority-information requests; on request it receives other assessment activity information, including cross-border work and subcontracting."],
        ["Other notified bodies receive specified refused, restricted, suspended or withdrawn certificates/approvals and positive ones on request. Similar bodies exchange relevant negative results and requested positive results. Confidentiality under Article 78 remains required. These exchanges are not instructions to publish all commercial records to the public."],
    ], [
        question([0], [1], "An Annex III certificate indicates a six-year validity period. What should be checked?", "Which limit applies to the stated Annex III certificate?", ("The four-year maximum and the applicable assessment evidence.", "Article 44(2) sets that maximum for Annex III."), ("Only whether the certificate is printed in colour.", "Colour does not establish lawful validity."), ("Nothing; Annex III certificates have unlimited validity.", "The paragraph expressly limits the period.")),
        question([0], [2], "A supplement is retained after its underlying certificate ceases to be valid. Is it independently sufficient?", "Can a supplement outlive the certificate it supplements?", ("No; its validity depends on the underlying certificate.", "Article 44(2) makes this dependency explicit."), ("Yes; every supplement starts an unlimited new period.", "That ignores the underlying-certificate condition."), ("Yes; keeping a PDF copy prevents expiry.", "Possession does not establish continuing validity.")),
        question([1], [3, 4], "A certificate is refused. What does result sharing require?", "Must the adverse result be treated as entirely private and unreportable?", ("The specified authority/body exchanges with confidentiality safeguards.", "Article 45 combines required exchanges and protected handling."), ("No exchange because refusal is commercially embarrassing.", "The article expressly covers negative decisions."), ("Public disclosure of every confidential model parameter.", "Required exchanges are not unrestricted publication.")),
    ]),
    "F23": lesson("Articles 3(23), 25, 43(4); Annex IV(2)(f); Annex VII(4.7)", "Evaluate changes rather than assuming every update is covered.", [
        ["A **substantial modification** is a post-market/service change not foreseen or planned in the initial conformity assessment that affects compliance with Chapter III Section 2, or modifies the assessed intended purpose. Article 43(4) requires a new assessment even if the same deployer continues using the modified system without onward distribution."],
        ["Article 25 can make a distributor, importer, deployer or other third party the provider when the specified change conditions apply, including substantial modification of a system remaining high-risk or changing a previously non-high-risk system's purpose so it becomes high-risk. Record the actor and duties; do not assume the original provider is accountable for every later third-party change."],
        ["A **predetermined learning change** is a change and performance variation established by the provider at initial assessment and included in Annex IV(2)(f) documentation for a system continuing to learn. Article 43(4) says those specified changes are not substantial modifications. This is a bounded documented exception, not permission for any later model replacement."],
        ["For an Annex VII certificate, notify intended or discovered changes that could affect compliance or purpose. The body decides whether a new assessment is required or an assessed supplement is sufficient. Northbridge changing from an advisory summary to materially ranking applicants is a purpose/compliance review; maintaining a product name does not settle it."],
    ], [
        question([0], [1], "An unplanned compliance-affecting modification stays with the same deployer. Is distribution required for reassessment?", "Does continuing internal use avoid Article 43(4)?", ("No; substantial modification can require a new assessment anyway.", "The paragraph explicitly includes continued use by the current deployer."), ("Yes; only a new sale triggers reassessment.", "The rule is not limited to onward distribution."), ("Yes; keeping the product name removes the change.", "A name does not determine purpose or compliance effects.")),
        question([1], [3], "A provider claims all future model updates were covered by saying 'we may update'. Is that sufficient?", "What supports the continuing-learning exception?", ("The specified changes/performance documented at initial assessment.", "The exception concerns predetermined documented changes."), ("Any general promise of future improvement.", "An open-ended statement does not establish the specified boundary."), ("Only the model supplier's release announcement.", "The provider's initial assessment documentation controls this exception.")),
        question([0, 1], [2, 4], "A third party changes a non-high-risk system's purpose so it becomes high-risk. What should be checked?", "Why can the changer's role matter as well as the new purpose?", ("The new classification, provider role and required assessment.", "Article 25 can assign provider duties to the actor making the specified change."), ("Only whether the original provider's logo remains.", "A logo does not resolve the changed actor and duties."), ("Nothing if no physical hardware changed.", "Purpose/software changes can affect legal obligations.")),
    ]),
    "F24": lesson("Articles 43–45; Annexes VI and VII; CRA Article 12(2)–(3)", "Defend the procedure using the actual case conditions.", [
        ["**Three route decisions:** Northbridge has the stipulated Annex III employment use. Beacon has a lawful point 1 biometric use and only partial application of the relevant standard. Harbour has the stipulated Section A medical product with sector-required third-party assessment. Assume a supported temporal interpretation for these exercises; actual release dates still need F03's check."],
        ["Northbridge follows Annex VI internal control; its provider verifies quality management, technical compliance and actual consistency. Beacon follows Annex VII because partial standard application triggers that procedure. Harbour follows the required sector procedure with incorporated AI requirements. Their common high-risk label does not make their procedures identical."],
        ["A proposed unplanned change affects an assessed system's compliance. Review whether it is substantial and apply reassessment even for continued use. Under Annex VII, involve the body in deciding new assessment versus supplement. Check the old certificate's conditions rather than assuming it covers the changed release."],
        ["A separate digital product claims CRA evidence allows any assessment route. Check CRA scope, deemed cybersecurity conditions and the distinct Article 12(2)–(3) interactions, especially important/critical products. The medical case's stipulated exclusion is not a CRA exemption for every other digital product."],
    ], [
        question([0], [1, 2], "Which route matches Northbridge's stipulated employment case?", "Which case follows Annex VI without the AI Act notified-body requirement?", ("Northbridge's internal-control route.", "Article 43(2) directs the stated employment use there."), ("Beacon's partial-standard biometric route.", "That condition requires Annex VII."), ("Harbour solely because it uses a commercial model.", "Its stipulated sector procedure controls.")),
        question([0], [2], "Beacon has only partial qualifying-standard application. What is the required procedure?", "Which route condition distinguishes Beacon from the employment case?", ("Annex VII assessment with the applicable body.", "Partial application is a specified trigger."), ("Internal control automatically for every commercial product.", "Commercial status does not override Article 43(1)."), ("No procedure once a standards document was purchased.", "Purchase alone does not satisfy application conditions.")),
        question([0], [3, 4], "A supplier says its old certificate and CRA statement cover any changed release. What should happen?", "Can these documents eliminate change and route checks?", ("Check modification, certificate scope and the relevant CRA conditions.", "Each document and procedure has a specific boundary."), ("Accept the claim because two documents are better than one.", "Document count does not establish scope."), ("Assume all procedures are interchangeable.", "The route conditions and incorporated laws remain distinct.")),
    ]),
}

LESSONS = add_registered_sources(LESSONS)
