"""Article 50 marking, detection and evidence: original teaching and cases."""

from lesson_builder import assessment
from lesson_content_n0 import CODE, GUIDELINES

OPINION = {"title": "Commission Opinion C(2026) 4839 final, conclusion 52: adequacy assessment", "url": "https://digital-strategy.ec.europa.eu/en/library/commission-opinion-assessment-code-practice-transparency-ai-generated-content"}

LESSONS = {
    "T07": {
        "locator": "Article 50(2), 50(4)-(5); Guidelines paragraphs 55-77",
        "additional_sources": [GUIDELINES, CODE],
        "summary": "Recognise synthetic content and distinguish machine-readable marks, human labels and detection.",
        "screens": [
            ["**Synthetic content** is content artificially generated or manipulated by an AI system. Article 50(2) addresses audio, images, video and text, including outputs of general-purpose AI systems.", "Harbour's system generates a voice clip and a text answer. Both need the paragraph 2 analysis. Realism, public publication or a deceptive purpose is not a universal condition of this provider duty."],
            ["**Machine-readable marking** embeds or attaches information that a machine can use to recognise artificial generation or manipulation. A **visible disclosure** tells people about AI involvement in a way they can perceive.", "These serve different duties. A visible 'AI' badge alone does not necessarily provide a machine-readable marker and a detection route. A hidden machine-readable marker alone does not necessarily give the person the required disclosure."],
            ["A **detection mechanism** reads or verifies the relevant marking. Pair the marker with a route capable of identifying it. A signed metadata record can have a verifier; a watermark needs a compatible detector.", "Metadata is information attached to a file. A digital signature helps verify its origin and integrity. A watermark places a marker within the content itself. Later lessons examine their different limits."],
            ["The Code's provider section addresses access to detection, readable results and privacy/security protections. For example, detection of metadata and public detection of non-free-form-text watermarks are generally offered free; specific exceptions and access conditions must be checked in Measure 2.1.", "For upload-based detection, Code Sub-measure 2.1.3 addresses confidentiality, minimisation and deletion of uploaded content immediately after detection; limited minimal security/abuse logs have distinct conditions. A verbatim copy is not retained. An AI-detection website guessing from style is not automatically a detector for the provider's marker. Such forensic detection examines characteristics without requiring a prior mark; it can err and is not the same evidence."],
            ["A detection result should explain what was detected clearly and accessibly. It does not certify that the content is accurate, lawful or harmless.", "In Harbour's review, first identify the paragraph 2 output, then its marker, its detection route and what the result actually establishes. Preserve the separate deployer disclosure analysis for later use."],
        ],
        "questions": [
            assessment([0], [1], "Harbour's system generates a text answer that is not publicly published. Does the absence of publication alone remove the paragraph 2 analysis?", "Is public publication a universal prerequisite for provider marking of synthetic text?", ("No; assess synthetic output under paragraph 2", "This provider duty is distinct from the public-interest publication rule."), ("Yes; every marking duty begins at publication", "That imports a condition from a different duty."), ("Yes; only realistic images are covered", "Paragraph 2 also covers audio, video and text.")),
            assessment([1], [2], "Harbour adds an AI badge to an image but cannot identify any machine-readable marker. What remains unresolved?", "Does a human-visible AI badge alone establish machine-readable marking and detection?", ("The provider's machine-marking and detection duties", "Human disclosure and machine-readable marking are distinct."), ("Only the badge's decorative style", "The missing technical treatment is substantive."), ("Nothing; a badge automatically meets every duty", "Visibility does not establish machine-readable detectability.")),
            assessment([2], [3, 4, 5], "A website guesses Harbour's answer is AI-written, but cannot verify the supplier's marker. What does that establish?", "Does a style-based detector verify the actual provider marking by itself?", ("A forensic estimate, not verification of that marker", "Forensic inference and mark detection are different mechanisms."), ("Proof that the answer is legally compliant", "The result does not establish all legal conditions."), ("Proof that every factual statement is correct", "AI-origin detection says nothing decisive about truth.")),
        ],
    },
    "T08": {
        "locator": "Article 50(2), sentence 3; Guidelines paragraphs 89-93", "additional_sources": [GUIDELINES],
        "summary": "Apply the editing and authorised-law-enforcement exceptions without blanket claims.",
        "screens": [
            ["The marking duty does not apply to the extent a system performs an **assistive function for standard editing**, or does not substantially alter provided input data or its semantics. Semantics means meaning.", "These are alternatives in the provision. Record the actual function and degree of alteration; 'has an editing button' does not exempt every output from a wider generation system."],
            ["A routine correction that leaves supplied content and meaning substantially unchanged differs from generating new arguments or materially replacing a scene. The Commission gives examples to help distinguish the cases.", "Harbour compares correction of a spelling error with rewriting a statement to assert the opposite conclusion. The second is a substantive semantic change; it cannot claim the no-substantial-alteration alternative on these facts."],
            ["Apply the exception **to the extent** the qualifying function is performed. A mixed product may offer standard assistance and substantive content generation.", "Do not turn uncertainty about one output into a system-wide exemption. Keep evidence of what the feature actually changes. Technical feasibility affects the separate quality assessment; it is not this editing test."],
            ["There is a distinct exception where authorised by law to detect, prevent, investigate or prosecute criminal offences. Merely intending to investigate wrongdoing is insufficient to establish legal authorisation.", "In a stipulated case with that authorisation, use the exact paragraph 2 exception. Do not copy its wording to every other paragraph: the conditions differ. Other applicable duties and law still need analysis."],
        ],
        "questions": [
            assessment([0], [1, 2], "An AI feature corrects a spelling error without substantially changing the supplied content or meaning. Which exception should Harbour examine?", "What provision should Harbour check for a routine correction that preserves supplied content and meaning?", ("The standard-editing or no-substantial-alteration alternatives", "Those alternatives concern qualifying assistance and alteration."), ("A universal exception for all AI-written text", "The provision does not exempt all generated text."), ("An exemption based only on the feature's name", "Actual function and output changes matter.")),
            assessment([0], [2, 3], "One feature corrects spelling; another generates a new claim contradicting the input. Can Harbour exempt both solely because the product is an editor?", "Does a mixed editing product's label exempt its substantively generated outputs?", ("No; apply the exception to qualifying functions and outputs", "The scope is limited by what the system actually performs or alters."), ("Yes; an editing interface exempts the whole system", "That ignores 'to the extent' and substantial changes."), ("Yes; altered meaning never matters", "The semantics of the input are expressly relevant.")),
            assessment([1], [4], "Harbour calls a generator an investigation tool but identifies no authorising law. Is that enough for the criminal-offence exception?", "Does an investigative purpose label establish paragraph 2's legal-authorisation exception?", ("No; establish the relevant legal authorisation", "Purpose alone is not the statutory authorisation condition."), ("Yes; any investigative business use qualifies", "That would remove the express authorisation requirement."), ("Yes; the exception follows from using an editor", "Editing and authorised law enforcement are distinct alternatives.")),
        ],
    },
    "T09": {
        "locator": "Article 50(2), sentence 2; Guidelines paragraphs 64-68, 78-88", "additional_sources": [GUIDELINES, CODE],
        "summary": "Evaluate four technical qualities and content-specific limitations rather than trusting a badge or benchmark alone.",
        "screens": [
            ["The legal technical-quality test requires solutions to be **effective, interoperable, robust and reliable**, as far as technically feasible. Consider content characteristics and limitations, implementation costs and the generally acknowledged state of the art.", "The Act does not prescribe one universal percentage or demand an impossible guarantee. Equally, an unexplained claim of difficulty does not establish that feasible measures can be omitted."],
            ["**Effectiveness** concerns achieving marking and detection. **Reliability** concerns dependable operation, including error rates across content and conditions.", "Test unmarked real content as well as marked generated content. A detector that labels everything AI may find all marked samples yet fail reliability through false positives: authentic content wrongly labelled artificial."],
            ["**Robustness** concerns preservation or recovery through relevant alterations and attempts to remove marks. **Interoperability** concerns working across tools and actors, rather than requiring an isolated incompatible workflow.", "Harbour tests resizing, cropping, export and re-encoding where relevant. A mark verified only in the supplier's preview does not establish that its published file will still be detectable."],
            ["Signed metadata records can describe origin and integrity but may be stripped by export. Watermarks are embedded in the content and have different alteration and detection limits. The Code generally takes a layered approach, while permitting specified alternative routes demonstrating equivalent compliance.", "A fingerprint is a compact descriptor for matching content; logging records content for later lookup. They have privacy and alteration constraints. Do not treat a database of outputs as an automatic substitute for the required marking route."],
            ["**Containerised text** lives inside a structured format such as a document file. **Free-form text** is a raw character sequence without such a container. Available marking routes and their limits can differ.", "The Code's glossary describes very short text using a contemporary 200-token feasibility benchmark. A token is a unit of model-processed text. This benchmark is not a statutory numerical exemption for every shorter reply; assess current feasibility and the actual output."],
            ["Commission guidance gives scope and technical-limit examples, including limited or predetermined text outputs. Do not turn an illustrative example into a universal exemption for every system carrying the same product label.", "The Code stages watermark-detection interoperability with a 2 February 2027 milestone in Measure 3.4. That Code milestone is different from the Act's application and targeted transition dates. Preserve the exact basis of each timetable."],
        ],
        "questions": [
            assessment([0], [1, 2], "A detector identifies all marked samples but also labels every authentic sample AI. Which finding must Harbour retain?", "Does perfect detection of marked samples alone establish a reliable solution when authentic samples are misclassified?", ("Its false positives undermine reliability", "All four qualities matter; detection success alone omits error behaviour."), ("It is reliable because all marked samples were found", "That ignores incorrect detections on authentic content."), ("The Act forbids every detector with any error", "The statutory test is feasibility-sensitive, not an absolute perfection requirement.")),
            assessment([1], [3, 4], "An export removes signed metadata, and Harbour has tested no other layer. What should it conclude?", "What does a preview-only success establish when the exported file loses its metadata marker?", ("The downstream preservation and detection route remains unverified", "The route must be evaluated through relevant transformations."), ("The export proves equivalent compliance automatically", "Losing the tested marker does not demonstrate an equivalent route."), ("Any output log automatically replaces a marker", "Logging alone does not establish the required technical marking route.")),
            assessment([2], [5, 6], "A supplier claims every reply below 200 tokens is legally exempt from Article 50(2). What correction is needed?", "How should Harbour treat the Code's very-short-text technical benchmark?", ("As a feasibility description, not a statutory blanket exemption", "The legal test considers feasibility and output specifics; it has no universal 200-token exemption."), ("As a permanent statutory cutoff", "That numerical threshold is not in the operative provision."), ("As proof that all text marking is impossible", "One limitation does not establish impossibility for every text output.")),
            assessment([0, 1], [1, 3, 6], "Harbour cannot use another supplier's detector and has no compatible routing solution. Which quality needs examination?", "Which statutory quality addresses verification across different tools and actors?", ("Interoperability", "Cross-actor compatibility and detection access are part of interoperability."), ("Only the visual size of the AI badge", "A human badge does not resolve detector compatibility."), ("Only the provider's marketing popularity", "Popularity is not evidence of technical interoperability.")),
        ],
    },
    "T10": {
        "locator": "Articles 50(2), 111(4), 113; Guidelines paragraphs 71-74, 153-154", "additional_sources": [GUIDELINES, CODE],
        "summary": "Verify the downstream provider's own route and apply the targeted marking transition.",
        "screens": [
            ["A **downstream system provider** integrates an upstream model or service into its own AI system. Upstream marking may support its compliance, but it remains responsible for the system it provides.", "Ask what is marked, how detection works, whether Harbour preserves the markers and whether the actual delivery path is covered. Self-hosting does not automatically make an organisation a model provider; assess the actions and objects supplied."],
            ["Procurement should seek implementation evidence, access to detection, limitations and responsibilities for correction. A supplier logo or Code signature is not a test report for Harbour's integration.", "The Code addresses non-removal in a provider's own processing pipeline and reasonable value-chain cooperation. Verify transformations within Harbour's control rather than asserting it can police every later copy everywhere."],
            ["**Application date** means when obligations apply, which differs from entry into force. Article 50's default application is 2 August 2026 under Article 113.", "Article 111(4) gives providers of systems placed on the market or put into service **before 2 August 2026** until **2 December 2026** to comply with Article 50(2). It is a targeted marking/detection transition, not a postponement of every transparency duty."],
            ["A qualifying older assistant may receive that paragraph 2 transition while still needing its applicable interaction disclosure from 2 August. A new system first placed on the market on 3 August does not qualify for the earlier-system transition.", "Check the system's placement or service date, not just the date its model was trained or the supplier company was founded."],
            ["Commission guidance separately addresses old outputs. It does not require retroactive marking/labelling of qualifying pre-2 August generated media; for public-interest text, both generation/manipulation and publication before that date matter.", "Text generated in July but first published to inform the public after 2 August needs the later publication analysis. This is interpretation about content dates, distinct from Article 111(4)'s system transition. Use the later publication lessons for its precise disclosure conditions."],
        ],
        "questions": [
            assessment([0], [1, 2], "Harbour wraps a supplier's marked generation service but its export removes the marker. May it rely solely on the supplier's claim?", "Does upstream marking settle Harbour's provider duty when its integration strips that marking?", ("No; verify and repair the actual downstream route", "Harbour's own product path must support its provider obligations."), ("Yes; the upstream company carries every later duty", "Downstream provider responsibility remains."), ("Yes; self-hosting automatically removes Article 50", "Hosting architecture is not a general exemption.")),
            assessment([1], [3, 4], "An assistant was put into service on 1 July 2026. Which duty receives the Article 111(4) transition to 2 December?", "What is postponed by the targeted transition for a qualifying pre-2 August system?", ("Article 50(2)'s marking and detection compliance", "The transition expressly concerns paragraph 2."), ("Every paragraph of Article 50", "Interaction and other disclosure duties are not generally postponed by this rule."), ("All applicable data-protection duties", "The AI Act transition does not defer those separate laws.")),
            assessment([1], [3, 4, 5], "A provider first puts a generator into service on 3 August 2026. May it use the earlier-system transition solely because training occurred in July?", "Does a July model-training date qualify an AI system first launched after 2 August for Article 111(4)?", ("No; the relevant earlier placement or service condition is unmet", "The rule concerns the system's placement/service, not its training date."), ("Yes; training date always controls the transition", "That substitutes the wrong event."), ("Yes; every new generator receives four extra months", "The transition is confined to qualifying existing systems.")),
        ],
    },
    "T11": {
        "locator": "Article 50(7), Article 56(6); Guidelines paragraphs 146-150", "additional_sources": [GUIDELINES, CODE, OPINION],
        "summary": "Understand Code adequacy and maintain evidence of implemented marking and disclosure measures.",
        "screens": [
            ["Article 50(7) says the **Commission** encourages and facilitates Union-level Codes for detection, marking and labelling. Under the amended provision it assesses adequacy taking utmost account of the Board's opinion, through Article 56(6)'s procedure.", "If a Code is inadequate, the Commission may adopt an implementing act specifying common implementation rules through Article 98(2). Older documents describe the previous assessment procedure; do not replace amended law with that earlier account."],
            ["The final Transparency Code has a provider section for marking/detection and a deployer section for deepfakes and specified published text. It is not a complete implementation manual for every Article 50 activity.", "The Commission's July adequacy assessment concludes it supports effective implementation of paragraphs 2, 4 and 5. Adherence is not conclusive evidence of compliance. Authorities can still examine whether the measures were actually implemented."],
            ["Signing is voluntary. Within the Code, **will** identifies mandatory commitments for the route a signatory relies on; **encouraged** identifies optional recommended measures; **may** permits optional measures or implementation flexibility.", "For example, richer provenance information and additional forensic detection are encouraged or optional in the provider section. Do not convert those recommendations into standalone statutory requirements for everyone."],
            ["**Compliance evidence** shows how the implementation meets the duty: a high-level process description, tests, limitations, preservation and detection arrangements, responsible people and maintenance.", "The Code's provider section requires ongoing testing and verification proportionate to circumstances. Its deployer section addresses internal processes, awareness, feedback, correction of substantiated mislabelling and cooperation with authorities."],
            ["Harbour's supplier has signed, but its detector is unavailable and no export test exists. A signature cannot fill those evidential gaps. Keep a documented correction process and retest when the implementation changes.", "Non-signatories can demonstrate compliance by adequate alternative means. Commission guidance suggests comparing those measures with the Code to identify gaps; a voluntary route does not remove the underlying legal duty."],
        ],
        "questions": [
            assessment([0], [1, 2], "An older slide describes the Code assessment procedure differently from amended Article 50(7). Which basis should Harbour use?", "Which source governs the current Code adequacy procedure when an older presentation conflicts with amended law?", ("The operative amended provision", "The Commission assesses with utmost account of the Board opinion under the current procedure."), ("The slide because it is easier to read", "Presentation convenience does not confer legal authority."), ("The supplier's preferred description", "A commercial claim does not amend the procedure.")),
            assessment([0], [2, 3], "Harbour's supplier has signed the Code. Does that conclusively establish compliance?", "What does Code adherence establish about actual implementation?", ("A recognised demonstration route, still subject to verification", "The assessment expressly does not make adherence conclusive evidence."), ("An exemption from every authority investigation", "Authorities retain verification and enforcement powers."), ("A requirement to implement every encouraged measure", "The Code distinguishes commitments from optional recommendations.")),
            assessment([1], [4, 5], "The supplier's detector is unavailable and Harbour has no export test, but it has a signature certificate. Which response fits?", "What should Harbour do when the evidence route has gaps despite Code adherence?", ("Document and repair the detection and workflow gaps", "Actual implementation and correction evidence matter."), ("Treat the certificate as replacing technical evidence", "Signing does not prove measures function in this workflow."), ("Abandon assessment because adherence is voluntary", "Voluntary adherence does not make the statutory duty optional.")),
        ],
    },
    "T12": {
        "locator": "Article 50(2), 50(5)-(7); Code Section 1 Commitments 1-4", "additional_sources": [GUIDELINES, CODE],
        "summary": "Trace marking and detection through generation, editing, export and delivery.",
        "screens": [
            ["Case: Harbour provides a generator using an external model. It delivers images and free-form text to customers. Assume its current outputs are in scope and do not qualify for an editing exception.", "The supplier marks the original image using signed metadata and a watermark. Harbour's preview verifies it. That preview is one stage of the delivery path, not evidence for every later stage."],
            ["Harbour's publishing export removes metadata. Its resizing step changes the image. The watermark detector still works on some outputs, but no representative final-file tests were retained.", "Test the actual transformations and final files. A layered approach can improve resilience, but the loss of one layer requires checking whether the remaining route still satisfies the relevant qualities and Code commitments."],
            ["Its detector sometimes mislabels authentic images. Harbour needs positive and negative test samples, relevant transformations and clear statements of the detection result's limitations.", "Document effectiveness, reliability, robustness and interoperability separately. A successful detection does not prove the image's statements or depiction are true."],
            ["For free-form text, Harbour must evaluate the route suited to that format and current technical limits. It cannot copy a document-file metadata result to raw text without explaining how the delivered marking is detectable.", "Retain the verified detection route and proportionate privacy/security arrangements. Preserve the distinctions between mandatory Code commitments, optional methods and the law's feasibility-sensitive test."],
            ["A defensible workflow record identifies who provides the system, which outputs are marked, the preservation path, compatible detection, actual tests and the correction owner.", "Do not declare 'compliant' solely from a supplier signature or a visible badge. This exercise checks the current ordinary commercial workflow; it does not decide criminal-law authorisation or grandfathering dates."],
        ],
        "questions": [
            assessment([0], [1, 2], "Harbour's preview verifies a mark but export strips metadata and resizes content. What evidence is still needed?", "Does preview detection establish the final transformed file's marking route?", ("Tests of the actual delivered outputs and remaining route", "The final pipeline can change preservation and detectability."), ("Only a screenshot of the successful preview", "That omits later transformations."), ("Only the supplier's Code signature", "A signature is not final-file verification.")),
            assessment([0], [3], "Harbour's detector finds marked images but wrongly calls authentic images artificial. What should the review include?", "Which evidence should Harbour retain when authentic inputs produce false detections?", ("Negative-sample results and reliability limitations", "Reliability must account for misclassification, not only successful positive detection."), ("Only successful detections of marked examples", "That hides an important part of detector behaviour."), ("A claim that detection guarantees truth", "Detection of artificial origin does not certify factual truth.")),
            assessment([0], [4, 5], "The image workflow works, but raw text delivery has no demonstrated detectable marking. Which handoff is justified?", "How should Harbour assess a different output format without carrying over an unsupported conclusion?", ("Evaluate its own format-specific route and document the gaps", "Different delivery formats can require different feasible methods."), ("Reuse the image conclusion without checking text", "The image test does not establish raw-text detectability."), ("Replace all technical checks with a visible label", "A visible label alone does not establish paragraph 2 compliance.")),
        ],
    },
}
