"""Technical evidence, logging, instructions, oversight and performance."""
from high_risk_content import lesson, question as q

LESSONS = {
'H13': lesson('Articles 8, 11; Annex IV points 1–9', 'Build an inspectable, current technical file linked to requirements.', [
['A **technical file** is the documentation demonstrating compliance with the system requirements. Article 11 requires it before market placement or service and requires it to stay current. Give authorities and relevant assessment bodies clear, comprehensive information.', 'A brochure saying “tested and safe” is not equivalent evidence. Article 8 connects compliance to intended purpose, generally acknowledged state of the art and risk management.'],
['A **technical evidence index** connects Annex IV elements to the actual version and records. Include purpose, provider, system/software versions, interactions, hardware, interface, product form and instructions.', 'Explain development methods and any pretrained components, design logic and choices, architecture and computing resources, dataset provenance/preparation, oversight, predetermined changes, signed/dated test reports and security measures. An index makes these retrievable; it does not replace them.'],
['Also include monitoring, group performance and limitations, foreseeable risks, relevant inputs and oversight, metric appropriateness, the risk-management system and lifecycle changes.', 'Annex IV further includes applied Official Journal standards or alternative solutions, the conformity declaration, and the post-market evaluation plan. Standards are technical specifications; a declaration states conformity. Their procedures are later-course handoffs, not assumed complete because this index lists them.'],
['An **integrated product file** for Annex I Section A contains both Article 11 information and the sector-law information in one set. Article 8 also permits appropriate integration of testing, reporting and procedures to avoid duplication.', 'Small firms may provide Annex IV elements in a simplified manner using the Commission’s designated form if they choose that route. Verify the form’s availability and version before relying on it. Simplification does not mean omitting the required elements.'],
['Northbridge’s file should identify the actual ranking version and locate evidence supporting its specified recruitment purpose. A change to labels, inputs or operation may require an update.', 'If a signed test report describes a different version, mark the evidence gap. A well-formatted index does not establish that the referenced evidence exists or applies.']], [
q([0],[1,5], 'Northbridge has only a brochure and proposes creating the technical documentation after launch. What is wrong?', 'When must the compliance-demonstrating technical file exist?', ('Before supply/service and maintained up to date','Article 11 makes this a prior and continuing requirement.'),('Only after the first authority complaint','The prior requirement is not complaint-triggered.'),('Only if the brochure is poorly designed','Presentation quality does not replace technical evidence.')),
q([1],[2,3,5], 'The index cites a test report for a different version without explaining relevance. What should happen?', 'Does a reference to a mismatched-version report close the evidence requirement?', ('Resolve the version/evidence gap','The records must demonstrate this system’s compliance.'),('Accept any report with a signature','A signature alone does not establish relevance.'),('Remove the version from the index','Hiding the mismatch loses traceability.')),
q([2],[4], 'A Section A product has a sector technical file. What does integration permit?', 'Can a provider reuse a Section A documentation process?', ('One file containing both required information sets','Integration avoids duplication while preserving requirements.'),('Discard the AI information automatically','Integration is not a waiver.'),('Use any self-made simplified form as designated','The opted simplified route requires the Commission form.'))]),
'H14': lesson('Articles 12(1), (2), 19; Articles 3(23), 79(1)', 'Distinguish automatic logging capability from controlled-log custody.', [
['**Logging capability** means the system technically allows automatic recording of events over its lifetime. Logs are event records that support appropriate traceability for its intended purpose.', 'Article 12 connects relevant events to identifying Article 79 risk situations or substantial modification, post-market monitoring and deployer operation monitoring. It does not require storing every event indefinitely.'],
['An **Article 79 risk** includes the specified health/safety or fundamental-rights concerns addressed by that provision. A **substantial modification** is a post-supply change not foreseen or planned in the initial assessment which affects system-requirement compliance or changes the assessed intended purpose.', 'These are triggers to inspect, not labels for every minor edit. Northbridge should be able to record events relevant to unexpected operation and meaningful changes.'],
['**Controlled-log retention** concerns automatically generated logs to the extent under the provider’s control. Article 19 requires a purpose-appropriate period of at least six months unless applicable Union/national law provides otherwise, especially personal-data law.', 'This is a qualified minimum, not a command to collect unlimited personal data. Separate which actor controls which records, the period and the other-law basis.'],
['Financial institutions covered by the specified Union financial-law governance rules maintain these logs as part of the relevant financial documentation. Specialist remote-identification fields are taught in the optional biometric lesson.', 'Case: Northbridge’s feature can log events, but no one can identify where controlled logs are retained. Capability alone does not prove custody. Conversely, a stored launch report does not demonstrate lifetime automatic logging.']], [
q([0],[1,4], 'Northbridge stores a launch report but its system cannot automatically log operational events. What is missing?', 'Does a one-time report establish Article 12’s system capability?', ('Automatic event recording across system lifetime','Capability is separate from static documentation.'),('Only a longer brochure','A brochure does not implement event recording.'),('A rule to retain all events forever','Lifetime capability is not perpetual retention.')),
q([1],[3,4], 'Northbridge says the six-month rule applies only to logs another actor exclusively controls. What should the assessor check?', 'Which logs does the provider custody duty concern?', ('Automatically generated logs to the extent under its control','Control determines this actor’s custody boundary.'),('Only logs exclusively controlled by someone else','That reverses the relevant boundary.'),('Every record globally regardless of control','The statute qualifies the obligation.')),
q([1],[3], 'A retention policy states “six months regardless of any applicable law.” Is that complete?', 'How should the minimum retention period be recorded?', ('Appropriate period, normally at least six months, with other-law qualifications','The statutory rule preserves applicable contrary law.'),('Exactly six months with no exceptions','The minimum and qualifications are different.'),('Indefinitely because logging works for life','Capability and custody periods are distinct.'))]),
'H15': lesson('Article 13(1)–(3)', 'Give deployers usable instructions and enough information to interpret outputs.', [
['**Deployer instructions** accompany the system in an appropriate digital or other format. They must be concise, complete, correct, clear, relevant, accessible and comprehensible.', 'Include provider and representative contact details where applicable. A technical file kept privately by the supplier does not by itself give the employer usable instructions.'],
['Explain purpose, capabilities, limitations, tested/validated accuracy metrics, robustness and cybersecurity, and known or foreseeable circumstances affecting those levels. Include foreseeable risks under intended use and misuse.', 'Where appropriate or applicable, include relevant group performance, input specifications, dataset information, explanation capabilities and information for correct output use. A general “high accuracy” claim is insufficient for these needed details.'],
['**Output interpretation** means understanding what a result does and does not support. System operation must be sufficiently transparent for deployers to interpret outputs and use them appropriately.', 'Northbridge’s rank is advice for the specified recruitment task, not automatic proof of a person’s worth. Explain the basis and limitations needed for the actual intended decision, with relevant interpretation tools.'],
['Instructions also include predetermined changes from the initial assessment, human-oversight measures, computing/hardware needs, expected lifetime, care/maintenance and its frequency, including updates. Where relevant, explain log collection, storage and interpretation mechanisms.', 'Case: the employer gets a score legend but no input limits or maintenance schedule. Request the missing relevant operational information rather than assuming the technical team will somehow supply it later.']], [
q([0],[1,2,4], 'A supplier gives a score legend but omits relevant input limits and maintenance frequency. What needs correction?', 'Does a legend alone supply the specified deployer instructions?', ('Provide the relevant complete operational information','Article 13 includes inputs, maintenance and other particulars.'),('Only change the legend’s colour','Appearance does not supply missing information.'),('Keep all needed instructions inside a private supplier file','The deployer needs usable accompanying instructions.')),
q([1],[2,3], 'An employer treats a ranking as proof that the lowest-ranked person is unqualified. What should the instructions enable?', 'What information helps prevent an unjustified interpretation of a recruitment rank?', ('Interpretation of the output within its purpose and limits','Transparency enables appropriate use rather than overclaiming.'),('Unconditional reliance on every score','That ignores the result’s limitations.'),('Only knowledge of the vendor’s revenue','That does not explain the output.')),
q([0],[4], 'A provider predetermined certain changes at initial assessment. May it omit them from the instructions?', 'Which change information belongs in the accompanying instructions?', ('The predetermined changes and performance changes, if any','Article 13(3)(c) includes them.'),('Only changes the customer discovers independently','Instructions must provide the specified information.'),('Every hypothetical future edit as already approved','Predetermined changes are not blanket approval of unknown changes.'))]),
'H16': lesson('Article 14(1)–(4)', 'Design oversight that a person can effectively exercise.', [
['**Effective human oversight** is the ability of natural persons to oversee operation during use, to prevent or minimise relevant risks from intended use or foreseeable misuse. Measures must fit risk, autonomy and context.', 'The provider may build measures into the system where technically feasible, identify measures for the deployer to implement, or combine both. Adding a person’s name to a form is not evidence of effective oversight.'],
['The system must enable the assigned person, as appropriate and proportionate, to understand capabilities/limitations, monitor operation and detect/address anomalies or unexpected performance.', 'It must support interpretation and decisions not to use it, to disregard, override or reverse outputs, and to intervene or interrupt it into a safe state. A pause button that leaves an unsafe process continuing is not the intended safeguard.'],
['**Automation bias** is the tendency to automatically rely or over-rely on system outputs. It matters especially when AI recommendations inform human decisions.', 'Northbridge’s reviewer should not approve every suggestion solely because it is scored. This is a capacity and workflow problem, not evidence that the human is absent only when there is no mouse click.'],
['Case: the named reviewer cannot see limitations, cannot challenge rankings and is penalised for stopping use. The interface’s “human approved” badge does not establish the needed oversight capabilities.', 'Request demonstrable interpretation, challenge, intervention and safe-stop arrangements. The deployment lesson will address who is assigned and supported; this lesson concerns what the system enables.']], [
q([0],[1,2,4], 'A reviewer is named but cannot interpret, override or safely interrupt the system. Is the oversight design established?', 'Does a named human satisfy Article 14 without effective controls?', ('No; verify proportionate operational capabilities','Oversight must be effective during use.'),('Yes; a name automatically fulfils it','Naming alone does not provide the capabilities.'),('Yes; clicking approve replaces all controls','Approval can coexist with ineffective oversight.')),
q([1],[3,4], 'A reviewer approves rankings because AI scores must be correct. What is the relevant risk?', 'Which tendency is shown by automatic trust in scored recommendations?', ('Automation bias','The tendency is over-reliance on system output.'),('Proof that the recommendation is valid','Confidence is not evidence of validity.'),('Proof that no human participates','The human can participate while over-relying.')),
q([0],[2], 'A stop control freezes the screen but leaves a harmful process operating. What must be examined?', 'What makes interruption useful for the oversight requirement?', ('A procedure bringing operation to a safe state','Safe halt is part of the specified capability.'),('Only whether the button is visible','Visibility does not establish safe intervention.'),('Only whether the score disappears','Hiding output need not stop the harmful operation.'))]),
'H17': lesson('Articles 9(6)–(8), 15(1)–(5)', 'Choose purpose-appropriate performance, fault and attack evidence.', [
['**Purpose-performance metrics** measure what matters for the intended task. Article 15 requires appropriate accuracy, robustness and cybersecurity, with consistent performance through the lifecycle; accuracy levels and relevant metrics belong in the instructions.', 'No single percentage establishes all recruitment compliance. Explain metric choice and test context. The Commission encourages benchmarks and measurement methods; that does not create an invented universal pass number.'],
['**Fault resilience** concerns errors, faults or inconsistencies within the system or operating environment, including interactions with people or other systems. Use technical and organisational measures; redundancy, backup or fail-safe plans can be suitable.', 'For Northbridge, test a broken document input or failed external service and whether the system produces a misleading rank. The examples illustrate evidence selection, not a mandatory architecture.'],
['**AI cybersecurity** addresses unauthorised attempts to change use, outputs or performance through vulnerabilities. Measures must fit relevant circumstances and risks.', 'Data poisoning manipulates training data; model poisoning targets pretrained components; adversarial inputs or evasion seek mistaken outputs. Confidentiality attacks target protected information. Where appropriate, measures must prevent, detect, respond, resolve and control these attacks or model flaws.'],
['Keep performance, fault and attack evidence distinct. A clean network scan does not prove resistance to misleading input or corrupted training labels. A good aggregate accuracy result does not establish safe fallback.', 'Case: Northbridge changes an external dependency. Review whether the previous test conditions and resilience/security evidence remain appropriate to the actual version and context.']], [
q([0],[1], 'A supplier cites one high accuracy percentage as proof of every requirement. What is missing?', 'Can one favourable number establish all purpose-specific performance and security duties?', ('Appropriate metrics, context and separate requirement evidence','Accuracy alone does not establish all required qualities.'),('A universal EU recruitment percentage','No universal percentage is established here.'),('Only a marketing comparison with competitors','A comparison alone is not complete compliance evidence.')),
q([1],[2,4], 'A failed external service causes a confident but unsupported applicant rank. Which evidence needs attention?', 'What should the assessor test about the failed-dependency scenario?', ('Fault response and safe operation or fallback','Interaction faults belong in resilience analysis.'),('Only ordinary successful-input accuracy','That omits the failure condition.'),('Only whether the screen still loads','Loading does not establish a safe result.')),
q([2],[3,4], 'An attacker alters training labels. Does a network scan alone establish protection against that attack?', 'Which AI-specific vulnerability is involved in manipulated training data?', ('Data poisoning requiring appropriate targeted controls','Training-data manipulation is specifically identified.'),('Only a typography issue','The attack can change model behaviour.'),('A problem excluded because training is upstream','Training and pretrained components are included.'))]),
'H18': lesson('Articles 11–15; Annex IV', 'Review a technical deployment package for actual evidence gaps.', [
['Case package: Northbridge supplies a current-version brochure, a test report for an older version, an automatic logging feature with no proven controlled-log custody, and a reviewer who cannot challenge scores.', 'The exercise supplies gaps, not proof of all possible faults. Review what each document actually demonstrates for the assessed version and intended use.'],
['A technical index needs the relevant records and explanations. Match purpose, design, datasets, oversight, test evidence and change history to the version. Listing a file does not establish its applicability.', 'If the old test still supports a claim, explain and evidence why. Otherwise request relevant testing rather than silently carrying the old result forward.'],
['Logging capability and custody are separate findings. Verify relevant automatic event recording and a qualified retention arrangement for logs under the actor’s control.', 'Oversight needs interpretation, anomaly handling, challenge and safe intervention. The supplied inability to challenge scores leaves a material readiness gap.'],
['Check purpose-appropriate accuracy and its declared metrics, fault resilience and appropriate AI-specific cybersecurity evidence. A good ordinary-input result does not answer every failure or attack case.', 'Supported decision: hold this evidence package pending resolved technical gaps and accountable actions. Conformity procedures, other law and actual deployment controls remain separate gates; this module does not grant market authorisation.']], [
q([0],[1,2], 'The package cites older-version testing without a relevance explanation. Which decision follows?', 'How should the assessor handle Northbridge’s mismatched test evidence?', ('Request version-relevant proof or a justified applicability explanation','The file must demonstrate the assessed system’s compliance.'),('Accept the report solely because it exists','Existence does not establish relevance.'),('Erase the version reference','Hiding a gap does not close it.')),
q([0],[3], 'The supplier shows logging capability but no custody policy. What remains unresolved?', 'Does a working event logger alone establish the controlled-log obligation?', ('Which controlled logs are retained and under which qualified period','Capability and custody are separate.'),('Whether the logo is prominent enough','The logo does not establish custody.'),('A statutory rule requiring all data forever','The rule is qualified and purpose-related.')),
q([0],[3,4], 'The reviewer cannot challenge outputs and security testing addresses only ordinary inputs. Is unconditional readiness supported?', 'What conclusion fits the supplied oversight and attack-evidence gaps?', ('Hold pending the material controls and evidence','The stated package lacks required support.'),('Certify because an accuracy claim exists','Accuracy does not cure the other gaps.'),('Declare this course’s completion a release certificate','Course progress is not regulatory authorisation.'))]),
}
