"""Article 50 biometric exposure, deepfakes and publication: original cases."""

from lesson_builder import assessment
from lesson_content_n0 import CODE, GUIDELINES

LESSONS = {
    "T13": {
        "locator": "Articles 3(34), 3(39)-(40), 50(3), 50(5)-(6); Recital 18; Guidelines paragraphs 99-110, 141-144",
        "additional_sources": [GUIDELINES],
        "summary": "Identify biometric exposure, disclose it to affected people and preserve the separate legality assessment.",
        "screens": [
            ["An **emotion recognition system** identifies or infers emotions or intentions of natural persons on the basis of their biometric data. Biometric data are personal data arising from specific technical processing relating to physical, physiological or behavioural characteristics.", "Reading the sentiment of an ordinary written comment is not automatically biometric emotion recognition. Physical states such as pain or fatigue are distinguished from emotions in Recital 18. Check the actual inputs, inference and purpose."],
            ["A **biometric categorisation system** assigns natural persons to specific categories on the basis of their biometric data, subject to the definition's exclusion for ancillary features intrinsically linked to another commercial service and strictly necessary for objective technical reasons.", "Harbour uses a camera-based system to infer visitors' emotional responses. Another system assigns categories from biometric characteristics. Identify each function before deciding which duties and restrictions apply."],
            ["Article 50(3) places the disclosure duty on the **deployer**: inform natural persons exposed to the operation of emotion recognition or biometric categorisation. Paragraph 5 requires clear, distinguishable, accessible information at the latest at first interaction or exposure.", "Disclosure does not make a prohibited use lawful. Separate Article 5 restrictions and, where applicable, Chapter III high-risk requirements still matter. Paragraph 3 also expressly requires processing personal data in accordance with the applicable EU data-protection framework."],
            ["The paragraph 3 exception concerns systems permitted by law to detect, prevent or investigate criminal offences, subject to appropriate safeguards for third parties' rights and freedoms in accordance with Union law. Its list does not include prosecution; do not import that word from another paragraph.", "In an ordinary commercial visitor study, an investigation label is insufficient. Harbour must identify the relevant function, inform exposed people where required, and separately establish lawful use and personal-data processing."],
        ],
        "questions": [
            assessment([0], [1], "Harbour reads the sentiment of ordinary written customer comments without processing biometric data. Is that alone biometric emotion recognition?", "Does inferring sentiment from non-biometric written comments alone meet this emotion-recognition definition?", ("No; the definition requires inference based on biometric data", "The input basis is an express part of the definition."), ("Yes; every sentiment analysis is biometric", "A sentiment output does not establish biometric input processing."), ("Yes; any analysis about a person qualifies", "That ignores the specific definition.")),
            assessment([1], [2], "A system assigns people to categories based on biometric characteristics. Which definition must Harbour examine, including its specific exclusion?", "Which definition addresses assigning natural persons to categories using biometric data?", ("Biometric categorisation system", "Check both the categorisation function and the precise exclusion."), ("Every ordinary text editor", "Text editing does not establish biometric categorisation."), ("Only a system inferring emotions", "Categorisation and emotion inference are distinct functions.")),
            assessment([2], [3, 4], "Harbour deploys a camera-based emotion inference system for visitors. It adds a notice. What does that establish about legality?", "Does informing exposed visitors automatically authorise the biometric use and data processing?", ("Disclosure addresses one duty; legality and data protection remain separate", "Article 50 does not displace prohibitions or applicable data-protection law."), ("The notice authorises every biometric purpose", "Transparency does not supply a universal legal authorisation."), ("The notice removes every high-risk obligation", "Paragraph 6 preserves Chapter III obligations.")),
        ],
    },
    "T14": {
        "locator": "Articles 3(60), 50(4), subparagraph 1; Guidelines paragraphs 113-119",
        "additional_sources": [GUIDELINES],
        "summary": "Evaluate a realistic synthetic depiction in its context rather than relying on intention or an invented harm threshold.",
        "screens": [
            ["A **deepfake** is AI-generated or manipulated image, audio or video content that resembles existing persons, objects, places, entities or events and would falsely appear to a person to be authentic or truthful.", "The Commission's interpretation considers resemblance, an existing or potentially existing subject, the specified kinds of subject and false apparent authenticity or truthfulness. These interpretation aids do not replace the legal definition."],
            ["The decisive **false-authenticity assessment** examines how the content appears in context. A realistic depiction is not classified solely by whether its creator intended to deceive, or whether a separately invented harm threshold is met.", "Harbour publishes a generated photograph of smiling staff on its recruitment page. Presentation as a photograph of its actual staff may falsely suggest an authentic depiction. Calling it harmless or well-intentioned does not settle that question."],
            ["Audio can also qualify. A generated clip presented as a recording of an actual person saying something they did not say creates a different context from an unmistakably fictional performance.", "Do not exempt a realistic synthetic person solely because no specific real individual was copied. The guidance includes potentially existing subjects; examine both resemblance and the audience-facing context."],
            ["For qualifying deepfake content, Article 50(4) requires the deployer to disclose that it has been artificially generated or manipulated. A generator's technical marking duty is a separate analysis.", "A useful decision record preserves the content, presentation, audience context and reason for the conclusion. Where the conclusion is uncertain, identify the missing facts rather than certifying the content from realism alone."],
        ],
        "questions": [
            assessment([0], [1, 3], "Harbour publishes AI-generated audio presented as an authentic recording of an actual person making a statement they never made. Which content rule needs assessment?", "Which rule is relevant to a synthetic voice clip falsely presented as an authentic person's recording?", ("The deepfake definition and deployer disclosure duty", "The medium and false appearance of authenticity engage the analysis."), ("Only the rule for published public-interest text", "The supplied content is audio, not that text category."), ("No rule because audio is excluded", "Audio is expressly included in the deepfake definition.")),
            assessment([1], [2], "A realistic generated staff photo is presented as Harbour's actual team. The creator says there was no intent to deceive. Is that enough to rule out a deepfake?", "Does a benevolent intention settle false authenticity in a realistic recruitment photo?", ("No; assess its appearance and context against the definition", "The definition does not depend solely on the creator's intention."), ("Yes; only malicious creators can make deepfakes", "That adds a condition absent from the definition."), ("Yes; all recruitment photographs are exempt", "There is no blanket recruitment exemption.")),
            assessment([0, 1], [1, 3, 4], "Harbour creates a realistic synthetic person without copying a named individual. Which review is appropriate?", "Does the absence of a copied named person by itself settle a realistic synthetic depiction's classification?", ("Examine resemblance and false apparent authenticity in context", "The guidance includes potentially existing subjects; absence of a named original is not decisive alone."), ("Automatically exempt it because the face is newly generated", "That skips the broader subject and authenticity analysis."), ("Automatically classify every drawing as a deepfake", "The definition still requires the relevant resemblance and false appearance.")),
        ],
    },
    "T15": {
        "locator": "Article 50(4), subparagraph 1, sentences 2-3; Guidelines paragraphs 119-125, 141-144; Code Section 2 Commitments 1 and 3",
        "additional_sources": [GUIDELINES, CODE],
        "summary": "Apply the creative-work accommodation and authorised-law-enforcement exception precisely.",
        "screens": [
            ["For content forming part of an **evidently artistic, creative, satirical, fictional or analogous work or programme**, disclosure is limited to revealing the existence of artificially generated or manipulated content in an appropriate manner that does not hamper display or enjoyment.", "This is an accommodation in the manner of disclosure, not a blanket removal of the disclosure duty. Establish that the work is evidently of the qualifying kind."],
            ["Harbour produces a clearly fictional short film containing realistic synthetic scenes. It chooses an appropriate notice revealing the AI-generated or manipulated content while preserving the film's presentation.", "Article 50(5) still addresses clarity, distinguishability, accessibility and first exposure. The Code provides implementation approaches, including an optional EU icon or an equivalent compliant icon or label; the Act does not mandate one universal icon. Do not assume a hidden notice or a notice delivered only after exposure always suffices."],
            ["A realistic advertisement presented as a factual testimonial does not become an evidently fictional work simply because the creative team made it. Evaluate the audience-facing work and context.", "An ordinary deepfake disclosure and the creative-work accommodation are different decisions. Retain the evidence supporting the selected approach and review it if the presentation changes."],
            ["The separate deepfake exception applies where use is authorised by law to detect, prevent, investigate or prosecute criminal offences. A commercial claim of fraud prevention alone does not establish authorisation.", "Do not combine exceptions casually: a creative-work accommodation concerns how disclosure is made; authorised criminal-law use concerns whether the paragraph's duty applies on the stated legal basis."],
        ],
        "questions": [
            assessment([0], [1, 2], "Harbour's evidently fictional film includes qualifying synthetic scenes. What does the creative-work rule permit?", "How does the accommodation affect disclosure within an evidently fictional work?", ("Reveal the artificial content appropriately without hampering enjoyment", "Disclosure remains, with an accommodated manner of presentation."), ("Remove all disclosure because the work is creative", "The provision limits the manner rather than universally removing the duty."), ("Hide the notice where no viewer can perceive it", "Appropriate disclosure must still reveal the existence of the content.")),
            assessment([0], [3], "A realistic AI testimonial is presented as a factual customer account. Its agency calls all advertising creative. Is that sufficient for the accommodation?", "Does a creative team's involvement alone make a factual-looking testimonial evidently fictional?", ("No; assess the work's evident character and presentation", "The statutory category is not established by the producer's job description."), ("Yes; every advertisement qualifies automatically", "There is no blanket advertising accommodation."), ("Yes; context never matters", "The evident character and presentation are relevant.")),
            assessment([1], [4], "Harbour invokes fraud prevention but identifies no law authorising this use. Can it claim the deepfake criminal-offence exception on that basis alone?", "Is a commercial fraud-prevention purpose alone sufficient for the deepfake exception?", ("No; establish the specified legal authorisation", "The provision expressly requires authorisation by law."), ("Yes; a commercial purpose replaces authorisation", "Purpose and authorisation are distinct."), ("Yes; any creative work creates that authorisation", "The creative-work accommodation is a different provision.")),
        ],
    },
    "T16": {
        "locator": "Article 50(4), subparagraph 2, sentence 1; Guidelines paragraphs 130-132",
        "additional_sources": [GUIDELINES],
        "summary": "Identify publication intended to inform the public on matters of public interest.",
        "screens": [
            ["For AI-generated or manipulated **text**, the paragraph 4 disclosure rule concerns text published with the purpose of informing the public on matters of public interest. These conditions must be examined together.", "A **matter of public interest** concerns issues relevant to public life and collective interests. The guidance discusses fields such as politics, health, security, environmental matters and financial or economic issues. A topic label alone does not establish the whole publication test."],
            ["A private customer-service answer or internal email is not automatically a publication to inform the public. A public safety article assembled from those answers can have a different purpose and audience.", "Harbour uses AI to draft an internal operational email and a website article informing residents about a pollution incident. The public-facing environmental article needs the specified published-text analysis."],
            ["A cookbook or ordinary promotional text is not automatically within this specific duty merely because it is public. Health claims, safety advice or reporting on collective interests can change the analysis.", "Use the actual content, audience, purpose and publication context. Record uncertainty where facts are missing, rather than declaring all public AI text either covered or exempt."],
            ["This lesson identifies the publication trigger; the following lesson examines the human-review/editorial exception. The provider's paragraph 2 machine-readable marking duty is separate and may still apply to generated text outside this particular paragraph 4 trigger.", "Harbour's publication worksheet asks: is it generated or manipulated text, is it published, is its purpose to inform the public, and does the matter involve public interest? A private-to-public reuse requires a new assessment."],
        ],
        "questions": [
            assessment([0], [1, 3], "Harbour publishes an AI-drafted article informing residents about a pollution incident. Which characteristic is relevant to the public-interest assessment?", "Which matter in Harbour's public information article supports a public-interest analysis?", ("The environmental issue affecting the community", "Environmental and collective interests are relevant, alongside purpose and publication."), ("Only the number of characters", "Length does not decide the public-interest condition."), ("Only the software's brand", "The topic and purpose are not established by branding.")),
            assessment([1], [2, 4], "Harbour reuses an internal AI draft as a website safety article for the public. Can it keep the private-email conclusion unchanged?", "What should happen when an internal draft becomes a public information article?", ("Reassess publication, purpose and public interest", "The changed context can engage the public-facing text duty."), ("Keep the conclusion because the first draft was private", "Initial use does not decide the later publication context."), ("Ignore publication because text is always excluded", "The provision expressly covers specified published text.")),
            assessment([0, 1], [1, 3, 4], "Harbour publicly posts ordinary promotional copy with no established public-interest information purpose. Does public availability alone settle this specific text rule?", "Is making AI text publicly available enough by itself to establish every paragraph 4 text condition?", ("No; establish the purpose and matter-of-public-interest conditions", "The conditions operate together; public availability is not the entire test."), ("Yes; every public AI sentence meets the trigger", "That ignores the specified information purpose and subject matter."), ("No; and that automatically removes provider marking duties", "Paragraph 2 has a separate scope and actor.")),
        ],
    },
    "T17": {
        "locator": "Article 50(4), subparagraph 2, sentence 2; Guidelines paragraphs 133-139; Code Section 2 Commitment 4",
        "additional_sources": [GUIDELINES, CODE],
        "summary": "Apply the two-part editorial exception and retain proportionate evidence of actual review and responsibility.",
        "screens": [
            ["The specified text disclosure duty does not apply where the generated content has undergone a process of **human review or editorial control**, and a natural or legal person holds **editorial responsibility** for publication.", "Read the logic precisely: (human review OR editorial control) AND editorial responsibility. Review/control and responsibility are distinct parts of the exception. Naming someone alone does not establish that the process occurred."],
            ["Review or control must be meaningful for the content and publication. Consider checking factual claims, sources, context and suitability, with the ability to correct content and decide what is published.", "Harbour's editor examines an AI-drafted environmental report, corrects unsupported claims and approves the final text. A perfunctory click or an unread approval does not demonstrate the same process."],
            ["Editorial responsibility identifies the natural or legal person accountable for the publication. A reviewer can perform checks while the organisation holds responsibility, if the actual arrangements support that allocation.", "The Code addresses documented policies and processes, assigned roles and resources, and an editorial contact where needed. It does not impose a universal requirement to create a separate record for every publication. Proportionate evidence can make the claimed exception reviewable."],
            ["An **editorial exception record**, used here as a practical worksheet, connects the final version, actual review/control, responsible person or organisation and decision. It is an evidence aid, not a statutory form.", "If AI substantially rewrites the report after review and nobody reviews or controls the final publication, the previous approval cannot simply be assumed to cover it. Assess the final workflow; provider marking remains a separate question."],
            ["The same text subparagraph contains an authorised-law exception for detecting, preventing, investigating or prosecuting criminal offences. Establish that legal basis separately when relevant.", "For Harbour's ordinary environmental report, choose between disclosure and a substantiated editorial exception. Do not treat the exception as permission to publish inaccurate or otherwise unlawful content."],
        ],
        "questions": [
            assessment([0], [1, 2], "Harbour names a publication owner but nobody reads or controls the AI-generated text. Is the editorial exception established?", "Does a named publication owner alone establish both parts of the exception?", ("No; actual human review or editorial control is also required", "The review/control condition and responsibility condition operate together."), ("Yes; a name replaces every review process", "That omits an express condition."), ("Yes; any AI draft is automatically reviewed", "Generation does not establish human review or editorial control.")),
            assessment([1], [1, 3], "A human reviews the report but no natural or legal person holds editorial responsibility for publication. Which condition remains missing?", "What is missing when review occurred but nobody holds editorial responsibility?", ("Editorial responsibility for publication", "Review alone does not meet the second part."), ("A mandatory AI label on every internal email", "That is not the missing condition of this exception."), ("A requirement that the reviewer trained the model", "Model training is not the editorial-responsibility test.")),
            assessment([2], [3, 4], "After approval, AI substantially rewrites the report and Harbour publishes it without further review or control. What should its worksheet flag?", "Can an earlier review be assumed to cover a substantially rewritten final publication?", ("Reassess whether the final content underwent the qualifying process", "The evidence must support the actual published content and workflow."), ("Treat any earlier approval as permanent coverage", "That disconnects the process from the final publication."), ("Claim the Act requires a fixed statutory worksheet template", "This worksheet is an optional evidence aid, not a prescribed legal form.")),
        ],
    },
    "T18": {
        "locator": "Article 50(2)-(7), Articles 5, 26(11), 85, 99, 100; Guidelines paragraphs 99-155; Code Sections 1 and 2",
        "additional_sources": [GUIDELINES, CODE],
        "summary": "Combine output provenance, biometric exposure and publication decisions in one reviewable case.",
        "screens": [
            ["Final case: Harbour operates a public exhibition. It provides an image generator and deploys a biometric visitor-analysis system. It publishes a prerecorded realistic avatar film and an AI-drafted environmental report.", "Treat each activity separately. The avatar is prerecorded, with no interactive conversation in this case. Assess the stated facts instead of assigning one course-wide exemption to every use."],
            ["The generator's preview verifies marking, but final export strips metadata and changes image size. Harbour needs delivered-file evidence for its marking/detection route and the four technical qualities.", "Biometric visitor analysis requires function-specific disclosure to exposed people where paragraph 3 applies. The notice does not decide whether the use is permitted under prohibitions, high-risk rules or data-protection law."],
            ["The film is stipulated to contain a qualifying deepfake and to be an evidently fictional work. Harbour must reveal the artificial content appropriately without hampering enjoyment, with the applicable presentation requirements.", "The environmental report informs the public on a public-interest matter. It has substantive human review of the final version and the organisation holds editorial responsibility. On those stipulated facts, the text editorial exception can apply."],
            ["A defensible decision package identifies the actor and activity, content or exposure, applicable provision, required action or substantiated exception, implementation evidence and person responsible for corrections.", "Code adherence can help demonstrate implementation but does not conclusively prove it. Keep other legal obligations in view. An exception for the report is not an exception for the film, generator or biometric system."],
            ["Before release, Harbour checks the actual outputs, notices, final report and evidence route. Missing export tests remain a gap even where a separate text exception is substantiated.", "This capstone deliberately combines independent duties. It assesses the supplied facts; it does not certify Harbour's complete legal compliance or decide facts left unstated."],
            ["Boundary lookup: Article 5 governs prohibited practices; Article 26(11) concerns a separate notification for specified high-risk decision systems. Article 85 provides a complaint route to the relevant market-surveillance authority.", "For enforcement, check Article 99 and the applicable national arrangements. Article 100 addresses fines on Union institutions, bodies, offices and agencies. These are pointers for further study, not a full complaints or penalties course."],
        ],
        "questions": [
            assessment([0], [1, 2, 5], "In the capstone, Harbour's image preview verifies marking but the final export is untested. Which conclusion is justified?", "Can a successful preview alone settle the final delivered image's marking analysis?", ("The delivered-output evidence remains incomplete", "Later transformations may affect preservation and detection."), ("The report's editorial exception covers image marking", "That exception concerns a separate published-text duty."), ("The supplier's Code signature conclusively proves the export", "Actual implementation still needs verification.")),
            assessment([0], [2, 3, 4], "The report meets the stipulated editorial exception. Does that remove the visitor disclosure and fictional deepfake disclosure?", "Does a substantiated text editorial exception exempt Harbour's other activities?", ("No; assess biometric exposure and the film separately", "Each duty has its own actor, trigger and conditions."), ("Yes; one exception covers the whole exhibition", "The exception does not extend to unrelated activities."), ("Yes; a fictional film can never require disclosure", "The creative accommodation changes the manner of disclosure.")),
            assessment([0], [3, 4, 5], "Which final review package makes Harbour's combined decisions reviewable?", "Which evidence package supports checking the capstone's distinct duties and exception?", ("Activity-specific decisions, actual implementation evidence and correction owners", "This connects legal conditions to the actual outputs, exposure and publication."), ("Only an organisation-wide statement that all AI is compliant", "That hides differing triggers and untested stages."), ("Only a supplier certificate and the first draft", "Those omit actual notices, delivered files and the reviewed final publication.")),
        ],
    },
}
