"""Exceptional authorisations, declarations, CE marking and registration."""

from high_risk_content import lesson, question
from conformity_sources import add_registered_sources

LESSONS = {
    "F25": lesson("Article 46(1)–(7)", "Separate a lawful exceptional authorisation from a commercial deadline.", [
        ["A **conformity derogation authorisation** is exceptional permission from the market surveillance authority following a duly justified request. It concerns public security, protection of life and health, environmental protection or protection of key industrial and infrastructural assets. It is limited to the Member State concerned and a limited period while the conformity procedure is completed without undue delay."],
        ["The authority must conclude that Chapter III Section 2 requirements are met. The derogation changes the ordinary prior procedure; it does not waive those substantive requirements or legalise an Article 5 prohibited practice. A provider's launch deadline or customer contract is not itself an authorisation."],
        ["The **emergency-use boundary** is narrower still: a duly justified urgency concerning exceptional public-security threats, or a specific substantial imminent threat to life or physical safety. Law-enforcement or civil-protection authorities may act before authorisation, but must request it during or after use without undue delay. Refusal requires immediate discontinuation and discarding all results and outputs of that use."],
        ["Authorities notify the Commission and other Member States of the relevant authorisation, excluding sensitive operational data about law-enforcement activities. If no objection is raised within fifteen calendar days after receipt, the authorisation is deemed justified. Following objections and consultation the Commission decides whether it is justified; an unjustified authorisation must be withdrawn. This is oversight, not an automatic provider self-approval after fifteen days."],
        ["The **sector derogation boundary** matters: for Annex I Section A products, Article 46(7) allows only the derogations from conformity assessment provided by the applicable sector law. Harbour cannot substitute this AI Act exceptional route for its sector-law conditions. Identify the actual law, authority, legal basis, territorial/time limits and decision in the evidence record."],
    ], [
        question([0], [1, 2], "A startup needs to ship before a trade fair. Does that itself authorise a conformity derogation?", "Can a commercial delivery deadline replace the Article 46 authority decision?", ("No; an exceptional legal basis and authority authorisation are needed.", "The specified purposes, conditions and authority decision control the route."), ("Yes; a deadline is enough if the provider promises later testing.", "A commercial promise does not establish this exceptional authorisation."), ("Yes; substantive safety requirements can then be ignored.", "Section 2 requirements remain necessary.")),
        question([1], [3, 4], "A civil-protection authority's urgent use is refused authorisation. What follows?", "What is required when the emergency-use authorisation request is refused?", ("Discontinue immediately and discard that use's results and outputs.", "Article 46(2) expressly requires both steps."), ("Continue until the next scheduled release.", "Refusal requires immediate discontinuation."), ("Keep relying on the outputs because they were useful.", "The refusal rule also requires discarding the results and outputs.")),
        question([2], [5], "Harbour's system is an Annex I Section A medical product. Where must its derogation basis come from?", "Which exceptional conformity route governs the stipulated sector product?", ("The applicable sector legislation's derogation provisions.", "Article 46(7) reserves this route to the sector-law provisions."), ("Any provider-created emergency policy.", "An internal policy cannot supply the statutory derogation."), ("Article 46 automatically regardless of sector law.", "The Section A boundary must be applied.")),
    ]),
    "F26": lesson("Article 47(1)–(5); Annex V(1)–(8)", "Prepare a scoped declaration supported by the assessed system evidence.", [
        ["**Provider declaration responsibility:** the provider draws up an EU declaration of conformity for each high-risk system in written, machine-readable, physically or electronically signed form. It keeps it available to national competent authorities for ten years after placing the system on the market or putting it into service. This is the provider's responsibility statement, not a notified body's certificate."],
        ["The declaration states that Chapter III Section 2 requirements are met, remains up to date and is supplied on request. It is translated into a language easily understood by the national competent authorities of the Member States where the system is placed on the market or made available. A file accessible only to the provider's sales team is not the authority-access arrangement."],
        ["**Declaration content check, fields 1–4:** Annex V requires the system name/type and an unambiguous identification/traceability reference; provider or, where applicable, representative names/addresses; a statement that the declaration is under the provider's sole responsibility; and a statement that the system conforms to the AI Act and, where applicable, other relevant Union legislation providing for a declaration."],
        ["**Fields 5–8:** references to relevant harmonised standards or common specifications; where applicable the notified body's name/number, procedure and certificate identification; place/date of issue, signatory name/function and an indication of for whom/on whose behalf it was signed; and, where personal data processing is involved, the Annex V personal-data-law statement. Verify the applicable data-protection framework and supporting evidence; do not invent a claim that every privacy regime applies to every product."],
        ["Where other Union legislation also requires a declaration, one declaration covers all applicable legislation and identifies it. Signing transfers neither responsibility to the model supplier nor proof of every unrelated legal requirement. Keep the declared system/version, applicable laws, assessment evidence, signature and later changes linked in the release record."],
    ], [
        question([0], [1, 2], "Who assumes responsibility by issuing the EU declaration?", "Does a supplier certificate replace the provider's Article 47 declaration?", ("The provider issuing the declaration remains responsible.", "Article 47 assigns the declaration and compliance responsibility to the provider."), ("Only the model supplier, irrespective of the system built.", "The provider's system duties are not transferred by buying a model."), ("Only the graphic designer who formats the document.", "Formatting does not determine the responsible declarant.")),
        question([1], [3, 4], "A declaration says only 'AI compliant' and names no traceable system. What is missing?", "Why is a generic conformity slogan insufficient for Annex V?", ("The required identification, statements, references and signatory details.", "Annex V specifies declaration content for an identifiable system."), ("Only a larger logo.", "A logo does not supply the required declaration fields."), ("Nothing if a certificate exists somewhere.", "A certificate is not a substitute for complete declaration content.")),
        question([0, 1], [1, 5], "A certificate expires after four years. May the provider discard the declaration then?", "Does certificate expiry shorten Article 47's declaration retention period?", ("No; retain it for the specified ten-year period and keep it up to date.", "The declaration's retention obligation is distinct from certificate validity."), ("Yes; all documents share the certificate's expiry.", "That incorrectly merges separate retention and validity rules."), ("Yes; only the supplier needs a copy.", "Article 47 places retention on the provider.")),
    ]),
    "F27": lesson("Article 48(1)–(5); Regulation (EC) 765/2008 Article 30", "Check marking accessibility, applicable laws and the conditional body number.", [
        ["**CE marking accessibility:** Article 48 requires a visible, legible and indelible marking for the high-risk system. If the system's nature makes this impossible or unwarranted, the marking goes on the packaging or accompanying documentation as appropriate. The general principles in Article 30 of Regulation 765/2008 also apply."],
        ["For a digitally provided high-risk system, use an easily accessible digital marking through its access interface or easily accessible machine-readable code or other electronic means. A hidden repository file that users cannot access is not evidence that this access condition has been met. Record the actual delivered marking and its accessibility."],
        ["The **CE notified-body number** follows the marking where applicable, and also appears in promotional material mentioning the system's CE compliance. The body affixes its number, or the provider/representative does so under its instructions. Do not invent a body number for an Annex VI internal-control route with no such body involvement."],
        ["Where other Union legislation also requires CE marking, the marking indicates satisfaction of that other legislation's requirements too. A medical-product release cannot use a mark to suggest the AI requirements are all that matter. Identify the applicable legislation and evidence before making the claim."],
        ["Under Regulation 765/2008 Article 30, affixing CE marking signifies the manufacturer's responsibility for compliance with all applicable requirements providing for it. It is not a general quality award, and it must not be affixed to products for which the relevant Union legislation does not provide it. A correct mark cannot repair an incomplete assessment or declaration."],
    ], [
        question([0], [1, 2], "A digital product's CE file is inaccessible to its users. What should be checked?", "Which evidence supports the digital marking condition?", ("An easily accessible marking via the interface or permitted electronic means.", "Article 48(2) specifies digital accessibility."), ("Only whether a designer created the file.", "Creation alone does not establish access."), ("Only whether marketing uses the word compliant.", "A claim does not supply the required marking.")),
        question([1], [3], "Northbridge uses Annex VI without a notified body. Should it invent an identification number?", "Does every high-risk CE marking necessarily include a notified-body number?", ("No; the number requirement applies where applicable body involvement exists.", "Article 48(4) is conditional, not a universal invented-number requirement."), ("Yes; any four-digit number is acceptable.", "The number identifies the actual applicable body."), ("Yes; use the model supplier's customer account number.", "A customer account is not a notified-body identifier.")),
        question([0, 1], [4, 5], "Harbour's marking ignores another applicable CE law. What is the problem?", "What does CE marking signify when several applicable laws require it?", ("Compliance with all applicable marking legislation must be supported.", "Article 48(5) and the general CE principles prevent an AI-only claim from replacing other requirements."), ("Only the AI Act matters once the AI logo is added.", "Other applicable legislation remains relevant."), ("CE is simply an optional quality prize.", "It is a statutory conformity marking under applicable legislation.")),
    ]),
    "F28": lesson("Article 49(1)–(2); Annex VIII Sections A and B", "Distinguish high-risk registration from the documented Article 6(3) exclusion.", [
        ["The **registration role test** begins with the actor and system. Before placing on the market or putting into service an Annex III high-risk system other than point 2, the provider or, where applicable, representative registers itself and the system in the Article 71 EU database. A private customer is not automatically the provider merely because it buys the system."],
        ["The **high-risk registration record** uses Annex VIII Section A: provider, submitting-person and applicable representative identities; traceable system name/reference; intended purpose; components/functions and information supporting use, including inputs and operating logic; and its market/service/withdrawal/recall status. Do not substitute a model name for the actual system identity."],
        ["The remaining Section A fields include applicable certificate type/number/expiry and body identity; a scanned certificate where applicable; Member States where the system is or has been placed/made available/put into service; declaration copy; electronic instructions (with the specified authority-use exceptions); and an optional additional-information URL. Some fields are conditional. A missing conditional certificate is not the same as an omitted required declaration."],
        ["The **exempt-system registration record** is different: a provider concluding that an Annex III-listed system is not high-risk under Article 6(3) must still register itself and the system before release. Section B requires actor/system identities, intended purpose, a short summary of why it meets the Article 6(3) exclusion conditions, and status. This is not a universal registration duty for every minimal-risk AI product."],
        ["At this retained baseline, Annex VIII Section B points 7 and 9 are deleted; point 8 remains the status field. Do not copy obsolete templates to recreate deleted requirements. The exclusion still needs the Article 6(4) documented assessment and applicable registration. Profiling natural persons in an Annex III system prevents relying on Article 6(3)'s exclusion."],
    ], [
        question([0], [1], "Who registers Northbridge's ordinary Annex III employment system before release?", "Does an ordinary private employer purchase automatically transfer provider registration to the customer?", ("The provider or applicable representative registers itself and the system.", "Article 49(1) assigns this pre-release duty to that actor."), ("Every private employee using it instead of the provider.", "That is not the actor allocation in paragraph 1."), ("Nobody because software has no physical packaging.", "The duty is not limited to physical systems.")),
        question([1], [2, 3], "A registration record identifies only the commercial model. What is missing?", "What identity must the high-risk registration record make traceable?", ("The actual AI system and its required purpose, status and evidence fields.", "Annex VIII Section A concerns the registered system, not only its model."), ("Only the marketing team's preferred colour.", "Colour does not establish the required system record."), ("Nothing if the supplier is well known.", "Supplier fame does not replace required system information.")),
        question([2], [4, 5], "A provider supports an Article 6(3) exclusion for an Annex III-listed system. Is registration automatically waived?", "Which registration branch applies to a supported non-high-risk conclusion under Article 6(3)?", ("Register the provider and system with the Section B record.", "Article 49(2) retains this duty; it is distinct from ordinary minimal risk."), ("No registration or documented assessment is ever needed.", "The exclusion retains documentation and registration duties."), ("Restore deleted Section B fields from an old template.", "The current baseline's deletions must be respected.")),
    ]),
    "F29": lesson("Article 49(3)–(5); Article 71; Annex VIII Section C", "Select the correct database destination and the separate public-deployer duty.", [
        ["A **public-deployer registration** is separate from the provider entry. Public authorities, Union institutions/bodies/offices/agencies, and persons acting on their behalf register themselves, select the system and register its use before use or putting into service an Annex III high-risk system other than point 2. Ordinary private deployers are not all covered by this particular duty."],
        ["Annex VIII Section C records deployer and submitter identities; the provider's database entry URL; a summary of the Article 27 fundamental-rights impact assessment; and, where applicable, the data-protection impact assessment summary. Check the applicability and actual assessment evidence. Registration does not replace either assessment or the provider's entry."],
        ["The **registration destination test** distinguishes the ordinary EU record from a secure non-public section. For Annex III points 1, 6 and 7 in law-enforcement, migration, asylum or border-control contexts, the specified reduced fields go in the secure section, accessible only to the Commission and relevant Article 74(8) national authorities. Neither all biometric records nor all public-sector records are automatically restricted."],
        ["Article 49(4) specifies Section A points 1–10 excluding 6, 8 and 9; Section B points 1–5 and 8–9; Section C points 1–3; and specified Annex IX real-world-test fields. The Annex IX reference is a lookup boundary, not a complete real-world-testing course. Its Section B9 reference persists despite B9's deletion in this baseline: flag interpretation and verify current instructions, rather than invent the deleted field."],
        ["Annex III point 2 critical-infrastructure systems use registration at national level under Article 49(5). Verify the actual national authority, portal and required process for the country; this lesson has not checked individual national portals. For each release/use, record actor, system, context, destination, date and receipt. A provider's public entry cannot prove a public customer's separate use entry."],
    ], [
        question([0], [3, 4, 5], "A lawful point 1 system is used in the specified asylum context. Which destination rule needs checking?", "Does the specified authority-use context change the ordinary EU database destination?", ("The secure non-public section with its specified fields and access limits.", "Article 49(4) defines this restricted branch."), ("Always publish every confidential field on a marketing website.", "That ignores the secure-record and access conditions."), ("Skip every record because the use is sensitive.", "Restricted registration is not the absence of registration.")),
        question([1], [1, 2], "A public authority buys Northbridge's registered system. What separate duty must it check?", "Does the provider's entry necessarily complete the public deployer's record?", ("Its own pre-use registration and applicable assessment summaries.", "Article 49(3) and Annex VIII Section C concern the deployer's use."), ("None; a provider URL replaces every public-deployer obligation.", "The two actor records have distinct purposes."), ("Every private customer must submit identical public-authority records.", "The particular paragraph does not cover every ordinary private deployer.")),
        question([0, 1], [4, 5], "An Annex III point 2 system needs a registration destination. What follows?", "Where does the critical-infrastructure registration branch lead?", ("The national registration process, verified for the relevant country.", "Article 49(5) directs this branch to national level."), ("Automatically the ordinary public EU entry used by recruitment software.", "Point 2 has a different specified destination."), ("An invented deleted B9 field on any website.", "A stale reference does not supply a destination or revive deleted content.")),
    ]),
    "F30": lesson("Articles 5–6, 17, 40–49, 111 and 113; Annexes IV–VIII", "Make a bounded release decision and record its evidence and unresolved conditions.", [
        ["The **market-release case** joins the decisions without claiming an all-law legal clearance. In a dated decision record identify provider/deployer roles, intended purpose, system/version, territory and release action. Complete the Article 5 precheck and Article 6 classification, including any other applicable law. Record which provisions apply at that date; these exercises stipulate a supported temporal interpretation of their chosen procedures."],
        ["Northbridge v1 is stipulated to materially rank recruitment candidates for an ordinary private employer. Its case dossier contains a supported non-prohibited-use analysis, Annex III classification, Section 2 evidence, Article 17 processes, Annex IV technical documentation, recorded Annex VI checks, a complete signed declaration, accessible digital CE marking and the appropriate provider registration. Within these stated checks, a supported readiness conclusion can be recorded, with ongoing obligations and named owners."],
        ["Harbour v1 is stipulated to require sector third-party assessment. Its certificate refers to v0 and the assessor's relevant scope has not been verified. Mark the release **not ready on the stated evidence**: resolve competence/scope and version coverage, and obtain the applicable assessment evidence. A launch promise is not an Article 46 sector derogation. A separate sector-law review remains necessary."],
        ["If Northbridge later changes its intended purpose or makes an unplanned compliance-affecting modification, review classification, provider role and reassessment; do not recycle v1's conclusion automatically. A public-authority customer has its own applicable registration and impact-assessment duties. These are distinct from the private-employer case assumptions."],
        ["Use three outcomes: **ready for the specified checked scope**, **not ready because a required condition is unmet**, or **needs further review because decisive facts or interpretation are unresolved**. Record each conclusion's facts, dated sources, evidence links, conditions, decision owner and next action. Unknowns should remain visible. Passing this lesson demonstrates reasoning practice, not certification of an actual product."],
    ], [
        question([0], [1, 2, 5], "Northbridge's complete stipulated dossier supports all the stated release checks. Which conclusion is proportionate?", "How should a supported readiness decision describe its scope?", ("Ready within the specified checked scope, with continuing duties and owners.", "The conclusion follows the stated evidence without claiming every possible legal clearance."), ("Permanently certified for every future purpose and jurisdiction.", "The evidence concerns a dated system/version and bounded scope."), ("Ready solely because it uses a popular model.", "Model popularity does not establish the dossier's legal conditions.")),
        question([0], [3, 5], "Harbour has an unverified assessor scope and a v0 certificate for v1. Is its stated release ready?", "What outcome follows from missing relevant assessment/version evidence?", ("Not ready on these facts; resolve the identified assessment gaps.", "The stipulated required assessment is not supported for this release."), ("Ready because a certificate exists, whatever its scope.", "Certificate existence does not establish relevant scope or version coverage."), ("Ready because a sales deadline creates a derogation.", "Commercial urgency does not supply an applicable statutory authorisation.")),
        question([0], [1, 4, 5], "The release date's applicability interpretation is unresolved. What is the honest outcome?", "What should happen when a decisive legal-application fact is still unknown?", ("Needs further review, with the unknown, owner and next evidence action recorded.", "Unresolved decisive conditions cannot support a final readiness conclusion."), ("Mark ready and remove the uncertainty from the record.", "That hides a condition on which the decision depends."), ("Assume every public customer's duty is completed by the provider entry.", "Public-deployer duties are distinct and need their own applicability check.")),
    ]),
}

LESSONS = add_registered_sources(LESSONS)
